'\" t
...\" cm_inser.sgm /main/10 1996/09/08 19:50:40 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "dtcm_insert" "user cmd"
.SH "NAME"
\fBdtcm_insert\fP \(em insert appointments into the calendar database
.SH "SYNOPSIS"
.PP
\fBdtcm_insert\fP [-c\0\fIcalendar\fP]  [-d\0\fIdate\fP]  [-s\0\fIstart\fP]  [-e\0\fIend\fP]  [-v\0\fIview\fP]  [-w\0\fIwhat\fP] 
.SH "DESCRIPTION"
.PP
The
\fBdtcm_insert\fP utility is non-GUI interface to the XCDE calendar and appointment services,
used to add new appointments to the calendar
database via the RPC daemon
\fBrpc\&.cmsd\fP(1m)\&. Appointments are added one at a time\&.
Each of the components of an
appointment is specified using one of the command-line options\&.
Once an appointment
is added, the list of appointments for the specified date
(see the
\fB-d\fP and
\fB-v\fP options) is displayed\&.
.SH "OPTIONS"
.PP
The following options are available:
.IP "\fB-c\0\fP\fIcalendar\fP" 10
Specify the name of the target calendar\&.
Calendar names
typically take the form
\fIuser\fP@ \fIhostname\fP, where
\fIuser\fP is a user\&'s login name and
\fIhostname\fP is the host machine name\&.
An example is
\fBfelix@cat\fP\&. If no target calendar is specified,
the calendar defaults to
the current user at the current host machine\&.
.IP "\fB-d\0\fP\fIdate\fP" 10
Specify the date for the appointment(s) to be inserted\&.
The
\fIdate\fP is specified using the form
\fImm\fP/ \fIdd\fP/ \fIyy\fP, where
\fImm\fP, \fIdd\fP and
\fIyy\fP are the two-digit month, day and year modulo 100, respectively\&.
Certain other references such as
``today,\&'\&' ``Tuesday,\&'\&' ``tomorrow,\&'\&' etc\&.
are correctly calculated\&.
If no date is specified,
\fIdate\fP defaults to today\&'s date\&.
.IP "\fB-s\0\fP\fIstart\fP" 10
Specify the starting time for the appointment\&.
The time is specified using the form
\fIhh\fP: \fImm\fP\&. If
\fIhh\fP is greater than 12, 24-hour convention (for example,
\fB15:30\fP instead of
\fB3:30 pm\fP \fB)\fP is assumed\&.
If
\fIhh\fP is 0 to 12,
an optional
\fBam\fP or
\fBpm\fP suffix can be used, with or without
white space separating the suffix from the
\fImm\fP\&. If no suffix is used,
\fBam\fP is assumed\&.
If no starting time is specified,
no time is associated with the inserted appointment\&.
.IP "\fB-e\0\fP\fIend\fP" 10
The ending time for the appointment,
in the same format as
\fB-s\fP\&. Specifying an ending time without a starting time is an error\&.
.IP "\fB-v\0\fP\fIview\fP" 10
Specify the view span of appointments to display\&.
The
\fIview\fP option-argument can be:
.RS
.IP "\fBday\fP" 10
Display all appointments for the given date (see
\fB-d\fP option)\&.
.IP "\fBweek\fP" 10
Display the full week that contains the given date,
starting with Sunday\&.
.IP "\fBmonth\fP" 10
Display the entire month that contains the given date\&.
.RE
.IP "\fB-w\0\fP\fIwhat\fP" 10
Specify the appointment description text\&.
Up to 5 lines of text can be specified by placing \en
(the literal characters \e and n, not
\fB<newline>\fP) between lines\&.
If not specified,
\fIwhat\fP defaults to
\fBAppointment\fP\&.
.SH "OPERANDS"
.PP
None\&.
.SH "STDIN"
.PP
Not used\&.
.SH "INPUT FILES"
.PP
None\&.
.SH "ENVIRONMENT VARIABLES"
.PP
The following environment variables affect the execution of
\fBdtcm_insert\fP:
.IP "\fBLANG\fP" 10
Provide a default value for the internationalization variables
that are unset or null\&.
If
\fBLANG\fP is unset or null, the corresponding value from the
implementation-specific default locale will be used\&.
If any of the internationalization variables contains an invalid setting, the
utility behaves as if none of the variables had been defined\&.
.IP "\fILC_ALL\fP" 10
If set to a non-empty string value,
override the values of all the other internationalization variables\&.
.IP "\fILC_MESSAGES\fP" 10
Determine the locale that is used to affect
the format and contents of diagnostic
messages written to standard error
and informative messages written to standard output\&.
.IP "\fBNLSPATH\fP" 10
Determine the location of message catalogues
for the processing of
\fILC_MESSAGES\fP\&.
.SH "RESOURCES"
.PP
None\&.
.SH "ASYNCHRONOUS EVENTS"
.PP
The
\fBdtcm_insert\fP utility takes the standard action for all signals\&.
.SH "STDOUT"
.PP
The standard output contains the list of appointments
for the specified view span, including the appointment just
inserted\&.
.SH "STDERR"
.PP
Used only for diagnostic messages\&.
.SH "OUTPUT FILES"
.PP
None\&.
.SH "EXTENDED DESCRIPTION"
.PP
None\&.
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.IP "0" 10
Successful completion\&.
.IP ">0" 10
An error occurred\&.
.SH "CONSEQUENCES OF ERRORS"
.PP
Default\&.
.SH "FILES"
.PP
\fB/usr/spool/calendar/callog\&.username\fP,
\fB/usr/dt/bin/rpc\&.cmsd\fP
.SH "APPLICATION USAGE"
.PP
In the
\fB-w\fP option, it may be necessary to
escape the \e character (``\e\en\&'\&') or enclose
the string in quotes
to avoid interpretation by the shell\&.
.SH "EXAMPLES"
.PP
The simplest form of
\fBdtcm_insert\fP has no arguments, where the user is prompted
to enter the appointment, line-by-line:
.PP
.nf
\f(CWdtcm_insert
Please enter the information for the appointment you wish to add\&.
Defaults will be shown in parentheses\&.
Calendar (hlj@poobah):
Date (2/27/1995):
Start (0822): 1200
End (1300):
Repeat (One Time):
What (you may enter up to 5 lines, use ^D to finish):
lunch with the calendar team
at Sparcy\&'s
^D

Appointments for Monday February 27, 1995:
          1) 1200-   1300 lunch with the calendar team
                             at Sparcy\&'s\fR
.fi
.PP
.PP
To insert at a specific time:
.PP
.nf
\f(CWdtcm_insert -s "11:00 am"
Appointments for Tuesday September 25, 1990:
        1) Appointment
        2) 11:00am-12:00pm Appointment\fR
.fi
.PP
.PP
To insert at a specific start and end time:
.PP
.nf
\f(CWdtcm_insert -s "11:00 am" -e 11:28am
Appointments for Tuesday September 25, 1990:
        1) Appointment
        2) 11:00am-11:28am Appointment\fR
.fi
.PP
.PP
To insert at a specific time and date:
.PP
.nf
\f(CWdtcm_insert -s 11:00am -d 09/26/90
Appointments for Wednesday September 26, 1990:
        1) 11:00am-12:00pm Appointment\fR
.fi
.PP
.PP
To insert at a specific time, date, and message:
.PP
.nf
\f(CWdtcm_insert -s "11:00 am" -d 09/26/90 -w "call home"
Appointments for Wednesday September 26, 1990:
        1) 11:00am-12:00pm Appointment
        2) 11:00am-12:00pm call home\fR
.fi
.PP
.PP
To insert a multiple-line appointment:
.PP
.nf
\f(CWdtcm_insert -s 12:00 -w "call dentist\en
                 no thanks\encancel appointment"
Appointments for Tuesday September 25, 1990:
        1) Appointment
        2) 11:00am-12:00pm Appointment
        3) 12:00pm-1:00pm call dentist
                 no thanks
                 cancel appointment\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fBrpc\&.cmsd\fP(1m), \fBdtcm\fP(1), \fBdtcm_delete\fP(1), \fBdtcm_lookup\fP(1)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
