'\" t
...\" helpgen.sgm /main/10 1996/09/08 19:52:43 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "dthelpgen" "user cmd"
.SH "NAME"
\fBdthelpgen\fP \(em generates a top-level help browser volume
.SH "SYNOPSIS"
.PP
\fBdthelpgen\fP [-dir\fIdirectory\fP]  [\fIoptions\fP] 
.SH "DESCRIPTION"
.PP
The
\fBdthelpgen\fP utility searches for all CDE help family files
installed and registered, and generates a help
volume named browser,
which contains hypertext links to all help
families and volumes found\&.
By default, the scope of this search
includes only the local system; however, it can be extended to remote
systems using the environment variables described below\&.
.PP
The
\fBdthelpgen\fP utility only updates the
browser
help volume if new family files or volumes are detected within
the search path directories\&.
In the case where no new family files are present,
\fBdthelpgen\fP exits\&.
If new files are present,
\fBdthelpgen\fP posts an information dialog telling the user that it\&'s updating the
browser
volume\&.
.PP
By viewing the
browser
help volume and traversing its
hypertext links, the user can navigate through all of the registered
online help information\&.
.PP
To view the
browser
volume, select the Help Viewer control from
the desktop\&'s Front Panel\&.
The top level of the
browser
volume lists product
families\&.
The second level, under each family,
lists the volumes that are members of the product family\&.
.PP
CDE users or system administrators typically do not need
to interact directly with the
\fBdthelpgen\fP utility\&.
A
browser
volume is generated (when one does not already exist, or is
out of date) when the user selects the Help Viewer control
from the CDE front panel\&.
A
browser
volume is also generated when the user executes the
\fBReloadApps\fP Action, or runs
\fBdthelpgen\fP directly from a terminal window\&.
In the first two cases, the resulting
browser
volume is placed in the user\&'s
\fB$HOME/\&.dt/help/$DTUSERSESSION\fP directory\&.
When running
\fBdthelpgen\fP from a terminal window, the -dir option must be used to specify
the location to create the resulting
browser
file\&.
.SH "OPTIONS"
.PP
The following options are available:
.IP "\fB-generate\fP" 10
Specifies that
\fBdthelpgen\fP unconditionally regenerate the
browser
volume
without first checking if new families or help volumes are present\&.
.IP "\fB-dir\fP \fIdirectory\fP" 10
Specifies the directory to deposit the generated files\&.
The specification can use substitution values\&.
The \fBENVIRONMENT VARIABLES\fP
heading describes the substitution values allowed and their effect\&.
If the environment variable
\fBLANG\fP is not set or is
\fBNULL\fP, it is forced to
\fBC\fP\&.
.IP "\fB-file\fP \fIbasename\fP" 10
Specifies the base name for the files generated by
\fBdthelpgen\fP\&. The default
name is
browser\&.
Extensions are appended to
\fIbasename\fP to create
the file names for the
help
volume\&.
.IP "\fB-lang\fP \fIlanguage\fP" 10
Specifies which language directories to search for
help
Family files and
help volumes\&.
If this option is not set, the default
\fBLANG\fP value is used\&.
If the
\fB-lang\fP value is set, it takes precedence over the current environment\&'s
\fBLANG\fP setting\&.
.SH "ENVIRONMENT VARIABLES"
.PP
The CDE help system uses two environment variables for locating
help
volumes and Family files within the desktop environment:
.IP "\fIDTHELPSEARCHPATH\fP" 10
\fISystem\fP search path environment variable for locating
help
volumes on local and/or remote nfs mounted systems\&.
.IP "\fIDTHELPUSERSEARCHPATH\fP" 10
Users
search path environment variable for locating user
specific
help
volumes on local and/or remote nfs mounted systems\&.
.PP
The environment variables contain colon-separated lists of directory paths\&.
Each directory path can contain both environment variable names as well as
special field descriptors that are expanded at runtime\&.
.PP
Field descriptors consist of a percentage (\fB%\fP) symbol
followed by a single character\&.
Field descriptors and their substitution values are:
.IP "\fB%H\fP" 10
This value is replaced with the current volume or family name being searched
for\&.
.IP "\fB%L\fP" 10
Replaced with the current value of the
\fBLANG\fP environment variable\&.
.IP "\fB%%\fP" 10
Replaced with a single \fB%\fP\&.
.PP
For example, given:
\fBDTHELPSEARCHPATH\fB="/etc/dt/appconfig/help/%L/%H\&.sdl"\fP\fP
.PP
The
\fBdthelpgen\fP utility looks for files ending with \fB\&.hf\fP
in the directory
\fB/etc/dt/appconfig/$LANG\fP\&. To find the volumes listed in each \fB\&.hf\fP
file,
\fBdthelpgen\fP looks in
\fB/etc/dt/help/appconfig/$LANG/%H\&.sdl\fP with \fB%H\fP
replaced with the name of the volume listed in the Family file\&.
.PP
The
\fBdthelpgen\fP utility uses both
\fIDTHELPUSERSEARCHPATH\fP and
\fIDTHELPSEARCHPATH\fP\&. The default value for
\fIDTHELPUSERSEARCHPATH\fP is:
.PP
\fB$HOME/\&.dt/help/$DTUSERSESSION/%H:
$HOME/\&.dt/help/$DTUSERSESSION/%H\&.sdl:
$HOME/\&.dt/help/$DTUSERSESSION/%H\&.hv:
$HOME/\&.dt/help/%H:
$HOME/\&.dt/help/%H\&.sdl:
$HOME/\&.dt/help/%H\&.hv\fP
.PP
The
\fIDTHELPUSERSEARCH\fP is first searched for the requested volume\&.
If the volume is not found, the
\fIDTHELPSEARCHPATH\fP value is searched\&.
.PP
The default value for
\fIDTHELPSEARCHPATH\fP path is:
\fB/etc/dt/appconfig/help/%L/%H:
/etc/dt/appconfig/help/%L/%H\&.sdl:
/etc/dt/appconfig/help/%L/%H\&.hv:
/etc/dt/appconfig/help/C/%H:
/etc/dt/appconfig/help/C/%H\&.sdl:
/etc/dt/appconfig/help/C/%H\&.hv:
/usr/dt/appconfig/help/%L/%H:
/usr/dt/appconfig/help/%L/%H\&.sdl:
/usr/dt/appconfig/help/%L/%H\&.hv:
/usr/dt/appconfig/help/C/%H:
/usr/dt/appconfig/help/C/%H\&.sdl:
/usr/dt/appconfig/help/C/%H\&.hv\fP
.SH "INPUT FILES"
.PP
The following are input files used by
\fBdthelpgen\fP\&.
.IP "\fB<file>\&.hf\fP" 10
runtime Help Family file, accessed directly by
\fBdthelpgen\fP\&.
.IP "\fB<file>\&.sdl\fP" 10
runtime Help volume file(s), accessed indirectly through explicit
references within the Help Family file\&.
.SH "OUTPUT FILES"
.PP
The following are descriptions of the output files generated by
\fBdthelpgen\fP\&.
.IP "\fBbrowser\&.hv\fP" 10
The master runtime browser Help volume file generated by
\fBdthelpgen\fP\&.
.IP "\fBbrowser00\&.ht & browser01\&.ht\fP" 10
Runtime browser Help topic files generated by
\fBdthelpgen\fP\&.
.SS "Warning Messages"
.IP "\fBZero Volume files found\fP" 10
Indicates that none of the volumes specified in the Family files are
registered in the system\&.
.IP "\fBZero Family files found\fP" 10
Indicates that no Family files are registered in the system\&.
.SS "Error Messages"
.IP "\fBElement of path is not a directory\fP" 10
Indicates that some part of the path is not a directory\&.
.IP "\fBAccess denied for directory path\&.\fP" 10
Try running as super user?"
Indicates that some part of path does not allow the caller read,
access or write permission\&.
.IP "\fBElement of path does not exist\fP" 10
Indicates that some element of path does not exist or is misspelled\&.
.IP "\fBFile system containing path is full\fP" 10
Indicates that the disc containing the path does not contain any space
or inodes\&.
.IP "\fBUnable to access path - error status number value\fP" 10
Indicates that there is an access problem of type
\fIvalue\fP occurred with path\&.
.IP "\fBFile system containing path is read only\fP" 10
Indicates that the disc containing the path is mounted read-only\&.
.IP "\fBRequires root permission to write to path\fP" 10
Indicates that some part of the path does not allow the user write
permission\&.
.IP "\fBWrite to volume invalid\fP" 10
Indicates that volume does not have the correct write permissions
for the caller\&.
.IP "\fBSearch Path empty\fP" 10
Indicates that the environment variables\&.
\fIDTHELPUSERSEARCHPATH\fP and/or
\fIDTHELPSEARCHPATH\fP were declared but no paths were specified in the variables\&.
.IP "\fB`title\&' resource missing\fP" 10
Indicates that the title resource in a Family file is missing\&.
.IP "\fB`abstract\&' resource missing\fP" 10
Indicates that the abstract resource in a Family file is missing\&.
.IP "\fB`volumes\&' resource missing\fP" 10
Indicates that the volumes resource in a Family file is missing\&.
.IP "\fB`character\&' set resource missing\fP" 10
Indicates that the CharSet resource in a Family file is missing\&.
.IP "\fBUnable to access current working directory - error status number value\fP" 10
Indicates that the -dir option was specified with a relative path and that
\fBdthelpgen\fP is unable to get the current working directory\&.
.IP "\fBUnable to allocate memory\fP" 10
System resources are used up, no available memory,
\fBdthelpgen\fP aborts execution\&.
.IP "\fBDestination directory missing\fP" 10
Missing
\fIdirectory\fP value for
\fB-dir\fP option\&.
.IP "\fBInvalid system language specified\fP" 10
Non-supported value used with the
\fB-lang\fP option\&.
.SH "EXAMPLES"
.IP "\fBdthelpgen -dir $HOME/\&.dt/help\fP" 10
Creates, if required, a new
browser
help volume in the users home directory under \fB\&.dt/help/\fP\&.
.IP "\fBdthelpview -dir $HOME/\&.dt/help -generate\fP" 10
Forces the creation of a new
browser
help volume and places it in the users home directory under \fB\&.dt/help/\fP\&.
.SH "SEE ALSO"
.PP
\fBdthelpview\fP(1), \fBdtsearchpath\fP(1), \fBdthffile\fP(4), \fICDE Help System Author\&'s and Programmer\&'s Guide\fP\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
