'\" t
...\" lp.sgm /main/7 1996/09/08 19:54:51 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "dtlp" "user cmd"
.SH "NAME"
\fBdtlp\fP \(em gather lp arguments and print a file
.SH "SYNOPSIS"
.PP
\fBdtlp\fP [-b \fIbanner_title\fP]  [-d \fIlpdest\fP]  [-m \fIprint_command\fP]  [-n \fIcopy_count\fP]  [-o \fIother_options\fP]  [-u \fIuser_filename\fP]  [-a]  [-e]  [-h]  [-r]  [-s]  [-v]  [-w]  [\fIprint_file\fP] 
.SH "DESCRIPTION"
.PP
The
\fBdtlp\fP command line utility is a front-end to the
\fBlp\fP subsystem\&.
The
\fBdtlp\fP utility
gathers
\fBlp\fP print options and prints a specified
file\&.
It operates in two modes:
.IP "\fBGUI mode\fP" 10
By default,
\fBdtlp\fP posts a
\fBPrint\fP dialog that appears with \fBPrint\fP,
\fBCancel\fP, and \fBHelp\fP pushbuttons\&.
.IP "\fBSilent mode\fP" 10
When invoked with the \fIsilent\fP flag,
\fBdtlp\fP does not present the GUI input dialog\&.
It collects input arguments from the command line and environment
variables\&.
.SS "The Print Dialog"
.PP
When invoked normally,
\fBdtlp\fP posts a
\fBPrint\fP dialog that shows:
.IP "\fBFile\fP" 10
The name of the file to print (a read-only text label)\&.
.IP "\fBPrinter\fP" 10
The printer device\&.
The default is the value of the \fBLPDEST\fP environment variable\&.
If
\fBLPDEST\fP is unset, then the properly localized string
\fBDefault\fP
appears in the text field\&.
.IP "\fBCopies\fP" 10
The number of copies to print\&.
The default is 1\&.
.IP "\fBBanner Page Title\fP" 10
The title to appear on the printed banner page,
and if formatted, in the header of each page\&.
.IP "\fBPrint Page Numbers\fP" 10
A checkbox to indicate
whether the file should be printed formatted (run through the
\fBpr -f\fP command) or printed unformatted\&.
.IP "\fBPrint Command Options\fP" 10
Any options to be passed directly to the
\fBlp\fP command\&.
For example, some implementations support the \fB-o2\fP
option to
\fBlp\fP to enable double-page printing\&.
.IP "" 10
When the user presses the \fBPrint\fP button, these settings are
passed onto the
\fBlp\fP subsystem,
along with the values of any other environment settings (see the
\fBENVIRONMENT\fP heading in this man page)\&.
.SH "OPTIONS"
.PP
The
\fBdtlp\fP command accepts a \fIprint_file\fP name specification\&.
If a
\fIprint_file\fP is not specified, standard input is assumed\&.
When used in
this fashion, the \fB-u\fP \fIuser_filename\fP option can be used to
pass a name to
\fBdtlp\fP for display in the
\fBPrint\fP dialog\&.
.SS "Command Line Options and the ENVIRONMENT Setting"
.PP
The
\fBdtlp\fP command
is sensitive to some ENVIRONMENT settings\&.
In the case in which both a command line option and a
complementary environment
setting are
specified, the command line option takes precedence\&.
.SS "Command Line Options"
.IP "-b banner_title" 10
Set the string used in printing the banner on the title page\&.
If the \fB-r\fP option is also specified, then print this same string
on the page headers\&.
.IP "-d lpdest" 10
Set the printer destination for the file\&.
.IP "-m print_command" 10
Use this value as the path name of the
\fBlp\fP print command\&.
The default is
\fBlp\fP\&.
.IP "-n copy_count" 10
Print this many copies\&.
Default is 1\&.
.IP "-o other_options" 10
Pass these options directly through to the
\fBprint_command\fP, without any interpretation\&.
This setting is
intended for users with advanced printing knowledge\&.
.IP "-u user_filename" 10
Use this value as the name of file as it should appear in the
\fBPrint\fP dialog or print output\&.
Default is \fBprint_file\fP\&.
Equivalent to the \fIDTPRINTUSERFILENAME\fP
setting under the \fBENVIRONMENT\fP heading in this man page\&.
.IP "-a" 10
Causes the file to be formatted with the \fBman\fP
command\&.
If set, then other formatting specifications (such
as \fB-r\fP) are ignored\&.
.IP "-e" 10
Remove the file after printing it\&.
This functionality is intended for temporary files generated by
applications that
don\&'t need to persist beyond the act of printing\&.
Equivalent to the \fIDTPRINTFILEREMOVE\fP\&.
.IP "-h" 10
Print out a help message\&.
.IP "-r" 10
Format the file before printing it, by running it through
the \fBpr -f\fP command\&.
.IP "-s" 10
Print the file silently, without posting the
\fBPrint\fP dialog\&.
Equivalent to the \fIDTPRINTSILENT\fP
setting under the \fBENVIRONMENT\fP heading in this man page\&.
.IP "-v" 10
Print out verbose messages during the print process\&.
.IP "-w" 10
Causes output to the printer to be sent raw, with no
interpretation of tabs, backspaces, formfeeds, and
binary characters\&.
Useful for printing \fBPCL\fP and \fBPS\fP files\&.
If set, then other formatting specifications (such
as \fB-r\fP) are ignored; however, the \fB-a\fP option
will take precedence over this setting\&.
.IP "print_file" 10
Print this file\&.
If \fIprint_file\fP
is not supplied, standard input is assumed\&.
.SH "ENVIRONMENT"
.PP
Following are the names and meanings
of the environment values that affect the operation of
\fBdtlp\fP:
.IP "\fBLANG\fP" 10
Use the specified value to determine the locale of the message strings that
appear in the
\fBPrint\fP dialog\&.
.IP "\fBLPDEST\fP" 10
Use the specified value as the printer destination for the file\&.
.IP "\fIDTPRINTCWD\fP" 10
If set to an existing, usable directory, this setting
causes
\fBdtlp\fP to execute the
\fBlp\fP command pipeline from that
directory\&.
By default, uses the current directory
from which
\fBdtlp\fP is invoked\&.
.IP "\fIDTPRINTFILEREMOVE\fP" 10
Equivalent to the \fB-e\fP
command line setting\&.
Value must be \fBTrue\fP
or \fBFalse\fP (case is ignored)\&.
Default is \fBFalse\fP\&.
.IP "\fIDTPRINTSILENT\fP" 10
Equivalent to the \fB-s\fP
command line setting\&.
Value must be \fBTrue\fP
or \fBFalse\fP (case is ignored)\&.
Default is \fBFalse\fP\&.
.IP "\fIDTPRINTUSERFILENAME\fP" 10
Equivalent to the \fB-u\fP
command line setting\&.
.SS "Reconciling Options"
.PP
In the case of conflicting formatting options,
\fBdtlp\fP uses the following decisions to reconcile them:
.IP "   \(bu" 6
If any \fIraw\fP
(as with \fB-w\fP), or \fIman\fP (as with
\fB-a\fP)
options are specified, all
other page formatting and numbering options are turned off;
otherwise, page printing and formatting are allowed\&.
.IP "   \(bu" 6
In a formatted operation:
If a banner title is specified (as with
\fB-b\fP), it will be used
as the page header\&.
.IP "   \(bu" 6
If a user filename is specified (as with
\fB-u\fP or
\fIDTPRINTUSERFILENAME\fP), it will be used as the page
header;
otherwise, the filename itself will be used as the page header\&.
.SH "RETURN VALUES"
.IP "0" 10
Command completed successfully\&.
.IP "-1" 10
The user pressed the \fBCancel\fP button\&.
.IP "2" 10
Usage error\&.
.IP "3" 10
There is no specified file to print\&.
.IP "4" 10
Unable to find the \fBdtksh\fP initialization file,
\fB/usr/dt/scripts/DtFuncs\&.sh\fP\&.
.IP "5" 10
The file is an invalid file (for example, a directory or a device file)\&.
.IP "6" 10
The user has no read permission on the file\&.
.SH "EXAMPLES"
.SS "Command Line"
.PP
The following command line causes
\fBdtlp\fP to post a
\fBPrint\fP dialog
for \fBfile1\fP with a name displayed of
\fBYour File\fP and with the default printer chosen:
\fB/usr/dt/bin/dtlp -u "Your File" file1\fP
The following command line causes
\fBdtlp\fP to silently print two copies of \fBfile2\fP on printer
\fBlaser3\fP:
\fB/usr/dt/bin/dtlp -n 2 -d laser3 -s file2\fP
.SS "Action Definition"
.PP
The following \fBPrint\fP action would cause a \fBPCL\fP file to
be printed using the
\fBdtlp\fP command\&.
.PP
.nf
\f(CWACTION Print
{
        LABEL           Print
        ARG_TYPE        PCL
        TYPE            COMMAND
        WINDOW_TYPE     NO_STDIO
        EXEC_STRING     /usr/dt/bin/dtlp -w %Arg_1%
}\fR
.fi
.PP
.PP
The following \fBPrint\fP action would cause a man page file to
be printed using the
\fBdtlp\fP command\&.
.PP
.nf
\f(CWACTION Print
{
        LABEL           Print
        ARG_TYPE        MAN_PAGE
        TYPE            COMMAND
        WINDOW_TYPE     NO_STDIO
        EXEC_STRING     /usr/dt/bin/dtlp -a %Arg_1%
}\fR
.fi
.PP
.PP
By default,
these actions will post the
\fBPrint\fP dialog\&.
.SH "LOCALES AND CODESETS"
.PP
The strings that appear in the
\fBPrint\fP dialog are localizable\&.
.SH "FILES"
.IP "\fB/usr/dt/appconfig/types/C/print\&.dt\fP" 10
Defines the default system \fBPrint\fP action\&.
.IP "\fB/usr/dt/appconfig/types/C/dt\&.dt\fP" 10
Defines the default \fBPrint\fP actions for
man pages (type \fBMAN\fP), ASCII files (type \fBTEXTFILE\fP),
PCL files (type \fBPCL\fP), and PS files (type \fBPOSTSCRIPT\fP)\&.
.IP "\fB/etc/dt/appconfig/types/C/*\&.dt\fP" 10
The datatype files that implement the per-printer \fBPrint\fP
action; these are created by the \fBdtprintinfo -populate\fP command\&.
.IP "\fB/usr/dt/scripts/DtFuncs\&.sh\fP" 10
The \fBdtksh\fP initialization file that defines a number
of GUI convenience functions, as for creating a dialog box\&.
.SH "BUGS"
.PP
The
\fBdtlp\fP \fBPrint\fP dialog cannot accept quote marks (either \fB\&'\fP or \fB"\fP)
in the \fBBanner Page Title\fP text field\&.
.SH "SEE ALSO"
.PP
\fBdtsearchpath\fP(1), \fBdtprintinfo\fP(1)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
