'\" t
...\" srkdump.sgm /main/6 1996/09/08 19:56:56 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "dtsrkdump" "user cmd"
.SH "NAME"
\fBdtsrkdump\fP \(em Produce reports about DtSearch database keys
.SH "SYNOPSIS"
.PP
\fBdtsrkdump\fP-o  | -w  | -ow  [-v]  [-t\fIthreshold\fP  | -p\fIpercent\fP ] \fIdbname\fP 
.SH "DESCRIPTION"
.PP
\fBdtsrkdump\fP is a convenience utility that traverses the
word/stem, document, or both b-trees for the specified DtSearch database
and prints a summary report about the keys to stdout\&. The
\fB-v\fP option additionally prints a detailed key by
key report\&. \fBdtsrkdump\fP can be used to confirm
integrity of the b-trees, and to count and report currently available
documents and keytypes\&.
.SH "OPTIONS"
.PP
The following options are available:
.PP
.RS
\fBNote:  
.PP
If an option takes a value, the value must be directly appended to
the option name without white space\&.
.RE
.IP "\fB-o\fP" 10
Instructs \fBdtsrkdump\fP to produce a report for unique
document keys\&. You must specify this argument or the \fB-w\fP
or \fB-ow\fP argument\&.
.IP "\fB-w\fP" 10
Instructs \fBdtsrkdump\fP to produce a report for word and
stem keys\&. You must specify this argument or the
\fB-o\fP or \fB-ow\fP argument\&.
.IP "\fB-ow\fP" 10
Instructs \fBdtsrkdump\fP to produce reports for both
unique document keys and word and stem keys\&. You must specify this
argument or the \fB-o\fP or
\fB-w\fP argument\&.
.IP "\fB-v\fP" 10
Specifies verbose mode, which generates a report item for every key in
the database\&. Use this option with caution when working with very large
databases\&.
.IP "\fB-t\fP\fIthreshold\fP" 10
Sets the frequency of occurrence threshold for reporting words to
\fIthreshold\fP\&. \fBdtsrkdump\fP
will output only those words that occure in at least
\fIthreshold\fP records\&. Setting the threshhold to 1
will output all words\&. If neither the \fB-t\fP nor
\fB-p\fP option is specified, the default threshold
is \fB-t100\fP\&.
.IP "\fB-t\fP\fIpercent\fP" 10
Sets the frequency threshold for reporting words to a percentage of all
records\&. \fIpercent\fP is a floating-point
number between 0 and 100, and can include the decimal point\&.
\fBdtsrkdump\fP will output only those words that occur
in at least \fIpercent\fP of all records\&. If
neither the \fB-t\fP nor \fB-p\fP
option is specified, the default threshold is \fB-t100\fP\&.
.SH "OPERAND"
.PP
The \fIdbname\fP argument specifies the name
of the database to be traversed\&. A path prefix is optional\&. The database
name is the 1 to 8 ASCII character string used at creation time
.SH "ENVIRONMENT VARIABLES"
.PP
None\&.
.SH "RESOURCES"
.PP
None\&.
.SH "ACTIONS/MESSAGES"
.PP
None\&.
.SH "RETURN VALUES"
.PP
The return values are as follows:
.IP "0" 10
\fBdtsrkdump\fP completed successfully\&.
.IP "non-zero" 10
\fBdtsrkdump\fP encountered an error\&.
.SH "FILES"
.PP
\fBdtsrkdump\fP opens all database files for
\fIdbname\fP\&.
.SH "EXAMPLES"
.PP
Output a summary report on the objects (documents) in the local database
named \fBmydb\fP\&. The summary report will print the
document count for each keytype in the database\&.
.PP
.nf
\f(CWdtsrkdump -o mydb\fR
.fi
.PP
.PP
Output a summary report on the words and stems in the local database
named \fBmydb\fP\&. The summary report will print the count
of each index term in the database from the three word b-trees\&.
.PP
.nf
\f(CWdtsrkdump -w mydb\fR
.fi
.PP
.PP
Output every document key in database \fBjpndb\fP in
directory \fB/usr/dtsearch\fP, plus a summary report of
the document count for each keytype in the database, plus every word or
stem that occurs in 20 or more documents, plus a summary report of
counts of each term for the word b-trees\&.
.PP
.nf
\f(CWdtsrkdump -ow -v -t20 /usr/dtsearch/jpndb\fR
.fi
.PP
.PP
Output the same as the previous example except that the detail word and
stem will only contain terms that occur in 80\&.5% or more of the
database\&.
.PP
.nf
\f(CWdtsrkdump -ow -v -p80\&.5 /usr/dtsearch/jpndb\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fBdtsrdbfiles\fP(4),
\fBDtSearch\fP(5)
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
