'\" t
...\" tt_typ_c.sgm /main/8 1996/09/08 20:20:59 rws $
...\" tt_typ_c.sgm /main/8 1996/09/08 20:20:59 rws $-->
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "tt_type_comp" "user cmd"
.SH "NAME"
\fBtt_type_comp\fP \(em compile ToolTalk otypes and ptypes
.SH "SYNOPSIS"
.PP
\fBtt_type_comp\fP [-mMs]  [-d\0\fIdb\fP]  [\fIsource_file\fP] 
.PP
\fBtt_type_comp\fP [-r]  [-s]  [-d\0\fIdb\fP]  [\fItype\fP]  [\&.\!\&.\!\&.] 
.PP
\fBtt_type_comp\fP [-p]  [-O]  [-P]  [-sE]  [-d\0\fIdb\fP] 
.PP
\fBtt_type_comp\fP [-p]  [-O]  [-P]  [-s]  [\fIsource_file\fP] 
.PP
\fBtt_type_comp\fP [-x]  [-s]  [-o\0\fIcompiled_file\fP]  [\fIsource_file\fP] 
.PP
\fBtt_type_comp\fP [-hv] 
.SH "DESCRIPTION"
.PP
The
\fBtt_type_comp\fP utility processes otypes and ptypes\&.
The default action of
\fBtt_type_comp\fP is to compile types from source form into compiled form and then
merge the compiled types into the standard ToolTalk types databases\&.
The
\fBtt_type_comp\fP utility preprocesses the source types with
\fBcpp\fP(1), and can optionally write out the compiled types instead of merging
them into the standard databases\&.
The
\fBtt_type_comp\fP utility can also remove types from the standard databases
or write out the contents of these databases\&.
.PP
The
\fBtt_type_comp\fP utility operates in two fundamental modes: XDR and Classing Engine\&.
XDR mode is the default\&.
In XDR mode, the standard databases are
simply serialized ToolTalk data structures,
and the format of
\fBtt_type_comp\fP output files is the same as that of the databases\&.
In Classing Engine mode,
the standard databases are in fact the Classing Engine\&'s
own databases, and the format of
\fBtt_type_comp\fP output files is that expected for input to
\fBce_db_build\fP(1) and
\fBce_db_merge\fP(1)\&. 
.SH "OPTIONS"
.PP
The following options are available:
.IP "\fB-d\0\fP\fIdb\fP" 10
Specify the database to work on, which must be one of
\fBuser\fP, \fBsystem\fP or
\fBnetwork\fP\&. For Classing Engine mode these are defined as:
.RS
.IP "\fBuser\fP" 10
\fB$HOME/\&.cetables/cetables\fP
.IP "\fBsystem\fP" 10
\fB/etc/cetables/cetables\fP
.IP "\fBnetwork\fP" 10
\fB$OPENWINHOME/lib/cetables/cetables\fP
.RE
.IP "" 10
For the XDR format these are defined as:
.RS
.IP "\fBuser\fP" 10
\fB$HOME/\&.tt/types\&.xdr\fP
.IP "\fBsystem\fP" 10
\fB/etc/tt/types\&.xdr\fP
.IP "\fBnetwork\fP" 10
\fB$OPENWINHOME/etc/tt/types\&.xdr\fP
.RE
.IP "" 10
These three databases form a hierarchy in which the definition of a
type in the user database overrides the definition in the system
database, and so on\&.
For the merge and remove options, the default database is
\fBuser\fP\&. For the
\fB-p\fP, \fB-O\fP and
\fB-P\fP options, the default is all three databases\&.
.IP "\fB-E\fP" 10
Use Classing Engine mode, instead of the default XDR mode\&.
.IP "\fB-h\fP" 10
Write a help message for invoking
\fBtt_type_comp\fP and then exit\&.
.IP "\fB-m\fP" 10
Merge types into the specified database, updating any existing type with
the new definition given\&.
This is the default action\&.
This action is not supported for Classing Engine mode\&.
The specified database is the first element from the
\fITTPATH\fP environment variable, or
\fB$HOME/\&.tt/types\&.xdr\fP if
\fITTPATH\fP is
\fBNULL\fP or not set\&.
If
\fITTPATH\fP is
\fBNULL\fP or not set, it is considered to be:
.PP
.nf
\f(CW$HOME/\&.tt/types\&.xdr:\e
/etc/tt/types\&.xdr:\e
/usr/dt/appconfig/tttypes/types\&.xdr\fR
.fi
.PP
.IP "\fB-M\fP" 10
Merge types into the specified database (see
\fB-m\fP), but only if they do not already
exist in that database\&.
This action is not supported for Classing Engine mode\&.
.IP "\fB-O\fP" 10
Write the names of all otypes read\&.
.IP "\fB-p\fP" 10
Write the ToolTalk types read
in a source format suitable for recompilation with
\fBtt_type_comp\fP\&.
.IP "\fB-P\fP" 10
Write the names of all ptypes read\&.
.IP "\fB-o\0\fP\fIcompiled_file\fP" 10
Write the compiled types into the specified file,
or to standard output if
\fIcompiled_file\fP is -\&.
.IP "\fB-r\fP" 10
Remove the given ptypes or otypes
from the specified database, as indicated by the
\fItype\fP operands\&.
.IP "\fB-s\fP" 10
Silent mode\&.
Write nothing to standard output\&.
.IP "\fB-v\fP" 10
Write the version number of
\fBtt_type_comp\fP and then exit\&.
.IP "\fB-x\fP" 10
Compile source types into a compiled types file, instead of merging
them into the standard types databases\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.IP "\fIsource_file\fP" 10
A pathname of a text file containing ToolTalk source code\&.
If
\fIsource_file\fP is -, standard input is used\&.
.IP "\fItype\fP" 10
A name of a type to be removed by the
\fB-r\fP option\&.
.SH "STDIN"
.PP
The standard input is used only if a
\fIsource_file\fP operand is -\&.
.SH "INPUT FILES"
.PP
The input file named by
\fIsource_file\fP is a text file containing ToolTalk source
code\&.
.SH "ENVIRONMENT VARIABLES"
.PP
The following environment variables affect the execution of
\fBtt_type_comp\fP:
.IP "\fICEPATH\fP" 10
In Classing Engine mode, a colon-separated list of directories that
tells the Classing Engine where to find the databases that
contain (among other things) ToolTalk types\&.
See
\fBce_db_build\fP(1)\&.
.IP "\fBLANG\fP" 10
Provide a default value for the internationalization variables
that are unset or null\&.
If
\fBLANG\fP is unset or null, the corresponding value from the
implementation-specific default locale will be used\&.
If any of the internationalization variables contains an invalid setting, the
utility behaves as if none of the variables had been defined\&.
.IP "\fILC_ALL\fP" 10
If set to a non-empty string value,
override the values of all the other internationalization variables\&.
.IP "\fILC_MESSAGES\fP" 10
Determine the locale that is used to affect
the format and contents of diagnostic
messages written to standard error
and informative messages written to standard output\&.
.IP "\fBNLSPATH\fP" 10
Determine the location of message catalogues
for the processing of
\fILC_MESSAGES\fP\&.
.IP "\fITTPATH\fP" 10
In XDR mode, a
colon-separated list of directories that tells the ToolTalk service
where to find the ToolTalk types databases\&.
.IP "" 10
The format of this variable is
.PP
.nf
\f(CW\fIuserDir\fP[:\fIsystemDir\fP[:\fInetworkDir\fP]]\fR
.fi
.PP
.SH "RESOURCES"
.PP
None\&.
.SH "ASYNCHRONOUS EVENTS"
.PP
The
\fBtt_type_comp\fP utility takes the standard action for all signals\&.
.SH "STDOUT"
.PP
When the
\fB-h\fP option is used,
\fBtt_type_comp\fP writes to standard output a help message
in an unspecified format\&.
.PP
When the
\fB-o\fP option is used,
\fBtt_type_comp\fP writes to standard output a listing of all
otypes
read\&.
.PP
When the
\fB-p\fP option is used,
\fBtt_type_comp\fP writes to standard output a listing of
all the ToolTalk types read,
in a source format suitable for recompilation with
\fBtt_type_comp\fP\&.
.PP
When the
\fB-P\fP option is used,
\fBtt_type_comp\fP writes to standard output a listing of all
ptypes
read\&.
.PP
When the
\fB-v\fP option is used,
\fBtt_type_comp\fP writes to standard output a version number
in an unspecified format\&.
.SH "STDERR"
.PP
Used only for diagnostic messages\&.
.SH "OUTPUT FILES"
.PP
When the
\fB-x\fP or
\fB-d\0user\fP option is used,
\fBtt_type_comp\fP writes the compiled types in an unspecified format
into a user-specified file\&.
Otherwise, it writes the compiled types into the
databases described under
\fB-d\fP\&.
.SH "EXTENDED DESCRIPTION"
.PP
None\&.
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.IP "0" 10
Successful completion\&.
.IP "1" 10
Usage;
\fBtt_type_comp\fP was given invalid command line options\&.
.IP "2" 10
A syntax error was found in the source types given to
\fBtt_type_comp\fP\&.
.IP "3" 10
System error;
\fBtt_type_comp\fP was interrupted by
\fBSIGINT\fP, or encountered some system or internal error\&.
.SH "CONSEQUENCES OF ERRORS"
.PP
Default\&.
.SH "FILES"
.IP "\fB$HOME/\&.tt/types\&.xdr\fP" 10
User\&'s ToolTalk types database for XDR mode
.IP "\fB/etc/tt/types\&.xdr\fP" 10
System ToolTalk types database for XDR mode
.IP "\fB/usr/dt/appconfig/tttypes/types\&.xdr\fP" 10
Network ToolTalk types database for XDR mode
.IP "\fB$OPENWINHOME/etc/tt/types\&.xdr\fP" 10
Network ToolTalk types database for XDR mode
.IP "\fB$HOME/\&.cetables/cetables\fP" 10
.IP "\fB/etc/cetables/cetables\fP" 10
.IP "\fB$OPENWINHOME/lib/cetables/cetables\fP" 10
Classing Engine databases containing ToolTalk types for CE mode\&.
See
\fBce_db_build\fP(1)\&.
.SH "APPLICATION USAGE"
.PP
None\&.
.SH "EXAMPLES"
.PP
None\&.
.SH "SEE ALSO"
.PP
\fBttsession\fP(1), \fBce_db_build\fP(1), \fBce_db_merge\fP(1), \fBcpp\fP(1)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
