/* XPM */
static char * admintool2_32_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconGray7	m black	c #424242424242",
"o	s iconColor1	m black	c black",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray1	m white	c #dededededede",
"%	s iconColor3	m black	c red",
"&	s iconColor6	m white	c yellow",
"*	s iconGray8	m black	c #212121212121",
/* pixels */
"                               .",
" ..............................X",
" ..............................X",
" ..............ooooo...........X",
" ..............oO .o...o.......X",
" ..............o+ .o..o o......X",
" ..............oO .o.o..Oo.....X",
" ...............+@o...o#. o....X",
" ......oooo+....+ o....+#. o...X",
" .....o$o@.$O...+ o....Oo..$+..X",
" .....oo$o.. +..+ o...o%.o$. O.X",
" .....o o$o. +..+ o..o%.%ooo.o.X",
" .....o$ o#. +..+o+oo%.oo...+o.X",
" .....o.. .$ +.o & +%*%o....+o.X",
" ......#..O..o.o&O&+o%o......o.X",
" .......++oO. oO&X +oo.........X",
" ..........oO$ o X&+o..........X",
" ...........oO$ oX +...........X",
" ............oO. oo+.O###......X",
" ..+.O##########Oooo##$$@#.....X",
" .+@+#@$$$$$$$$O####$$@@oo.....X",
" +  +O@$$$OXXXXXO.$$@@oo.......X",
" X   +O@$$$$$$$$$$@@oo.........X",
" .X   +o@@@@@@@@@@oo...........X",
" ..X   +*ooooooooo.............X",
" ...X   +o.....................X",
" ....X&% o.....................X",
" .....X o......................X",
" ......o.......................X",
" ..............................X",
" ..............................X",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
