/* XPM */
static char * ereg_32_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 8 1 0 0",
/* colors */
" 	s iconGray1	m white	c #dededededede",
".	s iconGray3	m white	c #adadadadadad",
"X	s iconGray7	m black	c #424242424242",
"o	s iconColor2	m white	c white",
"O	s iconColor8	m black	c magenta",
"+	s iconColor5	m black	c blue",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray6	m black	c #636363636363",
/* pixels */
"                                ",
" ..............................X",
" ..............................X",
" ...........o..................X",
" ..........ooo.oooo    .   .. .X",
" .........ooooo................X",
" ........oooOooo...............X",
" .......oooO+Oooo.oooo    .   .X",
" ......oooO+Oooooo.............X",
" .....oooO+Oooo@ooo............X",
" ....oooO+Oooo@ooooo.oooo   .  X",
" ...oooO+Oooo@ooo@ooo..........X",
" ..oooO+Oooo@ooo@ooooo.........X",
" .oooO+Oooo@ooo@ooo@ooo.oooo  .X",
" oooO+Oooo@ooo@ooo@ooooo.......X",
" #oooOooooooo@ooo@ooo@ooo......X",
" .#ooooooooo@ooo@ooo@ooooo.ooo X",
" ..#ooooooooooo@ooo@ooooo#.....X",
" ...#ooooooooo@ooo@ooooo#......X",
" ....#ooooooooooo@ooooo#.oooo .X",
" .....#ooooooooo@ooooo#........X",
" ......#ooooooooooooo#.........X",
" .......#ooooooooooo#.oooo  .  X",
" ........#ooooooooo#...........X",
" .........#ooooooo#............X",
" ..........#ooooo#.oooo   .   .X",
" ...........#ooo#..............X",
" ............#o#...............X",
" .............#.       .   .. .X",
" ..............................X",
" ..............................X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
