/* XPM */
static char * ereg_48_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s iconGray1	m white	c #dededededede",
".	s iconGray3	m white	c #adadadadadad",
"X	s iconGray7	m black	c #424242424242",
"o	s iconColor2	m white	c white",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconColor8	m black	c magenta",
"@	s iconColor5	m black	c blue",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray6	m black	c #636363636363",
/* pixels */
"                                                ",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" .................o..oooooo      ..     ..   O.X",
" ................ooo...........................X",
" ...............ooooo..........................X",
" ..............ooooooo.........................X",
" .............oooo+oooo..oooooo      ..     O..X",
" ............oooo+@+oooo.......................X",
" ...........oooo+@+@+oooo......................X",
" ..........oooo+@+@+oooooo.....................X",
" .........oooo+@+@+oooooooo..oooooo      .     X",
" ........oooo+@+@+ooooo#oooo...................X",
" .......oooo+@+@+ooooo#Oooooo..................X",
" ......oooo+@+@+ooooo#Oooooooo.................X",
" .....oooo+@+@+ooooo#Ooooo#oooo..oooooo    .. .X",
" ....oooo+@+@+ooooo#Ooooo#Oooooo...............X",
" ...oooo+@+@+ooooo#Ooooo#Oooooooo..............X",
" ..oooo+@+@+ooooo#Ooooo#Ooooo#oooo.............X",
" .oooo+@+@+ooooo#Ooooo#Ooooo#Oooooo..oooooo   .X",
" oooo+@+@+ooooo#Ooooo#Ooooo#Oooooooo...........X",
" $oooo+@+ooooooooooo#Ooooo#Ooooo#oooo..........X",
" .$oooo+ooooooooooo#Ooooo#Ooooo#Oooooo.........X",
" ..$oooooooooooooo#Ooooo#Ooooo#Oooooooo.ooooo .X",
" ...$oooooooooooooooooo#Ooooo#Oooooooo$........X",
" ....$oooooooooooooooo#Ooooo#Oooooooo$.........X",
" .....$oooooooooooooo#Ooooo#Oooooooo$..........X",
" ......$oooooooooooooooooo#Oooooooo$...........X",
" .......$oooooooooooooooo#Oooooooo$..oooooo  ..X",
" ........$oooooooooooooo#Oooooooo$.............X",
" .........$ooooooooooooooooooooo$..............X",
" ..........$ooooooooooooooooooo$...............X",
" ...........$ooooooooooooooooo$..oooooo   .   .X",
" ............$ooooooooooooooo$.................X",
" .............$ooooooooooooo$..................X",
" ..............$ooooooooooo$...................X",
" ...............$ooooooooo$..oooooo     .    O.X",
" ................$ooooooo$.....................X",
" .................$ooooo$......................X",
" ..................$ooo$.......................X",
" ...................$o$..oooooo    ..    ..  O.X",
" ....................$.........................X",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
