'\" t
...\" EdGetSiz.sgm /main/6 1996/09/08 20:03:21 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "DtEditorGetSizeHints" "library call"
.SH "NAME"
\fBDtEditorGetSizeHints\fP \(em retrieve sizing information from a DtEditor widget
.SH "SYNOPSIS"
.PP
.nf
#include <Dt/Editor\&.h>
\fBvoid \fBDtEditorGetSizeHints\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXSizeHints *\fBpHints\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The
\fBDtEditorGetSizeHints\fP function retrieves the current sizing information from
a DtEditor widget, allowing the application to compute appropriate size hints
for the window manager\&.
.PP
The
\fIwidget\fP argument specifies the DtEditor widget ID\&.
.PP
The
\fIpHints\fP argument is a pointer to an
\fBXSizeHints\fR structure into which the current sizing information is placed\&.
The fields in this structure do not have to contain any
values when it is passed in\&.
.PP
Upon successful completion, the
\fBDtEditorGetSizeHints\fP function fills in the following fields of the
\fBXSizeHints\fR structure: minimum width (
\fImin_width\fP) and height (
\fImin_height\fP); width (
\fIwidth_inc\fP) and height (
\fIheight_inc\fP) increment; and base width (
\fIbase_width\fP) and height (
\fIbase_height\fP); otherwise, the structure is unchanged\&.
The Flags field is set to:
.PP
.nf
\f(CWPMinSize | PResizeInc | PBaseSize\fR
.fi
.PP
.SH "RETURN VALUE"
.PP
The
\fBDtEditorGetSizeHints\fP function returns no value\&.
.SH "EXAMPLES"
.PP
The following code segment sets the resize increment and minimum window
size properties for the application\&.
.PP
.nf
\f(CWWidget          editor,
                application_shell;
Display         display;
XSizeHints      size_hints;
long            supplied_return;
XGetWMSizeHints(display, XtWindow(application_shell),
                 &size_hints, &supplied_return, XA_WM_NORMAL_HINTS);
DtEditorGetSizeHints(editor, &size_hints);
XSetWMSizeHints(display, XtWindow(application_shell),
                 &size_hints, XA_WM_NORMAL_HINTS);\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fBDt/Editor\&.h - DtEditor\fP(5), \fBDtEditor\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
