'\" t
...\" MmdbSGDS.sgm /main/5 1996/09/08 20:08:07 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "DtMmdbSectionGetDataSize" "library call"
.SH "NAME"
\fBDtMmdbSectionGetDataSize\fP \(em obtains
the size of a section\&'s data
.SH "SYNOPSIS"
.PP
.nf
#include <DtMmdb\&.h>
\fBint \fBDtMmdbSectionGetDataSize\fP\fR(
\fBDtMmdbInfoRequest* \fBrequest\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The \fBDtMmdbSectionGetDataSize\fP function
returns the number of bytes in the specified section\&'s data\&.
Table lookup is
involved if the section identifier is specified by the
\fIlocator_ptr\fP field\&.
.SH "ARGUMENTS"
.IP "\fIrequest\fP" 10
Specifies the bookcase in the bookcase descriptor field and
either the section\&'s Database Engine identifier (in the
\fIprimary_oid\fP field) or the
section\&'s logical identifier (in the \fIlocator_ptr\fP
field)\&. If both of these fields have a value,
\fBDtMmdbSectionGetDataSize\fP uses the
\fIlocator_ptr\fP value\&.
.SH "RETURN VALUE"
.PP
If \fBDtMmdbSectionGetDataSize\fP completes
successfully, it returns the size of the section\&'s data\&.
If it fails, it returns -1\&.
.SH "EXAMPLE"
.PP
The following shows how a \fBDtMmdbSectionGetDataSize\fP call
might be coded\&.
.PP
.nf
\f(CWDtMmdbInfoRequest request;
/* fill the request here */
l = DtMmdbSectionGetDataSize(&request);\fR
.fi
.PP
.SH "SEE ALSO"
.PP
TO BE SUPPLIED
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
