'\" t
...\" MmdbBkGL.sgm /main/5 1996/08/30 13:05:53 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "DtMmdbBookGetLicense" "library call"
.SH "NAME"
\fBDtMmdbBookGetLicense\fP \(em obtains
a book\&'s license term
.SH "SYNOPSIS"
.PP
.nf
#include <DtMmdb\&.h>
\fBconst char* \fBDtMmdbBookGetLicense\fP\fR(
\fBDtMmdbInfoRequest* \fBrequest\fR\fR,
\fBunsigned int* \fBlength\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The \fBDtMmdbBookGetLicense\fP function
returns the license term of the specified book object\&. Do not use the
\fBfree\fP function on the returned pointer\&. Table lookup is involved
when the identifier is specified by either the
\fIprimary_oid\fP or
\fIsequence_num\fP field\&.
.SH "ARGUMENTS"
.IP "\fIrequest\fP" 10
Specifies the bookcase in the bookcase descriptor field, as well
as a valid value in the \fIprimary_oid\fP, the
\fIsecondary_oid\fP, or the
\fIsequence_num\fP field\&.
The \fIprimary_oid\fP represents the
DtInfo Database object identifier of the TOC section; the
\fIsecondary_oid\fP represents the
object identifier of the book itself; and the
\fIsequence_num\fP represents
the sequence number of the book within the bookcase (0 based)\&.
If more than one of these fields have a valid value, the
order of precedence is:
\fIprimary_oid\fP,
\fIsecondary_oid\fP, and, last,
\fIsequence_num\fP\&.
.IP "\fIlength\fP" 10
Specifies the variable to receive the length of the
returned short title, if the returned pointer to the title is not NULL\&.
.SH "RETURN VALUE"
.PP
If \fBDtMmdbBookGetLicense\fP completes
successfully, it returns a pointer to the book\&'s license term\&.
If it fails, it returns a NULL pointer\&.
.SH "EXAMPLE"
.PP
None\&.
.SH "SEE ALSO"
.PP
TO BE SUPPLIED\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
