'\" t
...\" OpenHieB.sgm /main/9 1996/09/08 21:25:53 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "MrmOpenHierarchyFromBuffer" "library call"
.SH "NAME"
\fBMrmOpenHierarchyFromBuffer\fP \(em Allocates a hierarchy ID and opens a buffer containing a memory image of a UID file
.iX "MrmOpenHierarchyFrom\\%Buffer"
.iX "uil functions" "MrmOpenHierarchyFrom\\%Buffer"
.SH "SYNOPSIS"
.PP
.nf
#include <Mrm/MrmPublic\&.h>
.sp \n(PDu
\fBCardinal \fBMrmOpenHierarchyFromBuffer\fP\fR(
\fBunsigned char \fBuid_buffer\fR\fR,
\fBMrmHierarchy *\fBhierarchy_id\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBMrmOpenHierarchyFromBuffer\fP allows you to specify a buffer
containing information from UID files that MRM searches in subsequent
fetch operations\&.
This function also allocates a hierarchy ID and initializes the
optimized search lists in the hierarchy\&.
.IP "\fIbuffer\fP" 10
Specifies a stream of bytes containing information from UID files
.IP "\fIhierarchy_id\fP" 10
Returns the search hierarchy ID\&.
The search hierarchy ID identifies the buffer that MRM searches when
performing subsequent fetch calls\&.
.SH "RETURN"
.PP
This function returns one of the following status return constants:
.iX "MrmSUCCESS"
.iX "MrmFAILURE"
.IP "\fBMrmSUCCESS\fP" 10
The function executed successfully\&.
.IP "\fBMrmFAILURE\fP" 10
The function failed\&.
.SH "RELATED"
.PP
\fBMrmCloseHierarchy\fP(3) and
\fBMrmOpenHierarchyPerDisplay\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
