'\" t
...\" RegisteA.sgm /main/8 1996/09/08 21:26:08 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "MrmRegisterClass" "library call"
.SH "NAME"
\fBMrmRegisterClass\fP \(em Saves the information needed for MRM to access the widget creation function for user-defined widgets
.iX "MrmRegisterClass"
.iX "uil functions" "MrmRegisterClass"
.SH "SYNOPSIS"
.PP
.nf
#include <Mrm/MrmPublic\&.h>
\fBCardinal \fBMrmRegisterClass\fP\fR(
\fBMrmType \fBclass_code\fR\fR,
\fBString \fBclass_name\fR\fR,
\fBString \fBcreate_name\fR\fR,
\fBWidget (*\fBcreate_proc\fR) ()\fR,
\fBWidgetClass \fBclass_record\fR\fR);
.fi
.iX "MRM function" "MrmRegisterClass"
.iX "MrmRegisterClass" "definition"
.SH "DESCRIPTION"
.PP
The
\fBMrmRegisterClass\fP
function
.iX "MrmRegisterClass" "description"
allows MRM to access user-defined widget classes\&.
This function registers the necessary information for
MRM to create widgets of this class\&.
You must call
\fBMrmRegisterClass\fP
prior to fetching any user-defined class widget\&.
.PP
\fBMrmRegisterClass\fP
saves the information needed to access the widget creation
function and to do type conversion of argument lists by using the
information in MRM databases\&.
.IP "\fIclass_code\fP" 10
This argument is ignored; it is present for compatibility with previous
releases\&.
.IP "\fBclass_name\fP" 10
This argument is ignored; it is present for compatibility with previous
releases\&.
.IP "\fIcreate_name\fP" 10
Specifies the case-sensitive name of the low-level widget creation
function for the class\&.
An example from the Motif Toolkit is
\fBXmCreateLabel\fP\&.
Arguments are
\fIparent_widget\fP,
\fIname\fP,
\fIoverride_arglist\fP,
and
\fIoverride_argcount\fP\&.
.IP "" 10
For user-defined widgets,
\fIcreate_name\fP
is the creation procedure in the UIL that defines this widget\&.
.IP "\fBcreate_proc\fP" 10
Specifies the address of the creation function that you named in
\fIcreate_name\fP\&.
.IP "\fIclass_record\fP" 10
Specifies a pointer to the class record\&.
.SH "RETURN"
.iX "MrmSUCCESS"
.iX "MrmFAILURE"
.PP
This function returns one of the following status return constants:
.IP "\fBMrmSUCCESS\fP" 10
The function executed successfully\&.
.IP "\fBMrmFAILURE\fP" 10
The function failed\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
