'\" t
...\" TopLevel.sgm /main/9 1996/09/08 21:42:33 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "TopLevelShell" "library call"
.SH "NAME"
\fBTopLevelShell\fP \(em The TopLevelShell widget class
.iX "TopLevelShell"
.iX "widget class" "TopLevelShell"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
#include <X11/Shell\&.h>
.fi
.SH "DESCRIPTION"
.PP
TopLevelShell is used for normal top-level windows such as any
additional top-level widgets an application needs\&.
.SS "Classes"
.PP
TopLevelShell inherits behavior and resources from \fBCore\fP,
\fBComposite\fP, \fBShell\fP,
\fBWMShell\fP, and \fBVendorShell\fP\&.
.PP
The class pointer is \fBtopLevelShellWidgetClass\fP\&.
.PP
The class name is \fBTopLevelShell\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBTopLevelShell Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNiconicXmCIconicBooleanFalseCSG
_____
XmNiconNameXmCIconNameStringNULLCSG
_____
XmNiconNameEncodingXmCIconNameEncodingAtomdynamicCSG
_____
.TE
.IP "\fBXmNiconic\fP" 10
If True when the widget is \fIcreated\fP, specifies that the widget
should start as an icon when it is realized\&. A value of False
indicates that the widget is not to be realized as an icon\&. This
resource will only override the \fBXmNinitialState\fP resource when
specified in the call that creates the widget\&.
.IP "\fBXmNiconName\fP" 10
Specifies the short form of the application name to be displayed by the
window manager when the application is iconified\&.
When \fBXtGetValues\fP is called on this resource, the returned value
is a pointer to the actual resource value and
should not be freed\&.
.IP "\fBXmNiconNameEncoding\fP" 10
Specifies a property type that represents the encoding of the
\fBXmNiconName\fP string\&.
If a language procedure has been set, the default is None; otherwise,
the default is \fBXA_STRING\fP\&. When the widget is realized, if the value
is None, the corresponding name is assumed to be in the current locale\&.
The name is passed to \fBXmbTextListToTextProperty\fP with an encoding
style of \fBXStdICCTextStyle\fP\&. The resulting encoding is \fBSTRING\fP
if the name is fully convertible to \fBSTRING\fP, otherwise \fBCOMPOUND_TEXT\fP\&.
The values of the encoding resources are not changed; they remain None\&.
.SS "Inherited Resources"
.PP
TopLevelShell inherits behavior and resources from the following
superclasses\&. For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBVendorShell Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNaudibleWarningXmCAudibleWarningunsigned charXmBELLCSG
_____
XmNbuttonFontListXmCButtonFontListXmFontListdynamicCSG
_____
XmNbuttonRenderTableXmCButtonRenderTableXmRenderTabledynamicCSG
_____
XmNdefaultFontListXmCDefaultFontListXmFontListdynamicCG
_____
XmNdeleteResponseXmCDeleteResponseunsigned charXmDESTROYCSG
_____
XmNinputMethodXmCInputMethodStringNULLCSG
_____
XmNinputPolicyXmCInputPolicyXmInputPolicyXmPER_SHELLCSG
_____
XmNkeyboardFocusPolicyXmCKeyboardFocusPolicyunsigned charXmEXPLICITCSG
_____
XmNlabelFontListXmCLabelFontListXmFontListdynamicCSG
_____
XmNlabelRenderTableXmCLabelRenderTabelXmRenderTabledynamicCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectionXmLEFT_TO_RIGHTCG
_____
XmNmwmDecorationsXmCMwmDecorationsint-1CG
_____
XmNmwmFunctionsXmCMwmFunctionsint-1CG
_____
XmNmwmInputModeXmCMwmInputModeint-1CG
_____
XmNmwmMenuXmCMwmMenuStringNULLCG
_____
XmNpreeditTypeXmCPreeditTypeStringdynamicCSG
_____
XmNshellUnitTypeXmCShellUnitTypeunsigned charXmPIXELSCSG
_____
XmNtextFontListXmCTextFontListXmFontListdynamicCSG
_____
XmNtextRenderTableXmCTextRenderTableXmRenderTabledynamicCSG
_____
XmNunitTypeXmCUnitTypeunsigned charXmPIXELSCSG
_____
XmNuseAsyncGeometryXmCUseAsyncGeometryBooleanFalseCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBWMShell Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbaseHeightXmCBaseHeightintXtUnspecifiedShellIntCSG
_____
XmNbaseWidthXmCBaseWidthintXtUnspecifiedShellIntCSG
_____
XmNheightIncXmCHeightIncintXtUnspecifiedShellIntCSG
_____
XmNiconMaskXmCIconMaskPixmapNULLCSG
_____
XmNiconPixmapXmCIconPixmapPixmapNULLCSG
_____
XmNiconWindowXmCIconWindowWindowNULLCSG
_____
XmNiconXXmCIconXintXtUnspecifiedShellIntCSG
_____
XmNiconYXmCIconYintXtUnspecifiedShellIntCSG
_____
XmNinitialStateXmCInitialStateintNormalStateCSG
_____
XmNinputXmCInputBooleanTrueCSG
_____
XmNmaxAspectXXmCMaxAspectXintXtUnspecifiedShellIntCSG
_____
XmNmaxAspectYXmCMaxAspectYintXtUnspecifiedShellIntCSG
_____
XmNmaxHeightXmCMaxHeightintXtUnspecifiedShellIntCSG
_____
XmNmaxWidthXmCMaxWidthintXtUnspecifiedShellIntCSG
_____
XmNminAspectXXmCMinAspectXintXtUnspecifiedShellIntCSG
_____
XmNminAspectYXmCMinAspectYintXtUnspecifiedShellIntCSG
_____
XmNminHeightXmCMinHeightintXtUnspecifiedShellIntCSG
_____
XmNminWidthXmCMinWidthintXtUnspecifiedShellIntCSG
_____
XmNtitleXmCTitleStringdynamicCSG
_____
XmNtitleEncodingXmCTitleEncodingAtomdynamicCSG
_____
XmNtransientXmCTransientBooleanFalseCSG
_____
XmNwaitForWmXmCWaitForWmBooleanTrueCSG
_____
XmNwidthIncXmCWidthIncintXtUnspecifiedShellIntCSG
_____
XmNwindowGroupXmCWindowGroupWindowdynamicCSG
_____
XmNwinGravityXmCWinGravityintdynamicCSG
_____
XmNwmTimeoutXmCWmTimeoutint5000 msCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBShell Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNallowShellResizeXmCAllowShellResizeBooleanFalseCG
_____
XmNcreatePopupChildProcXmCCreatePopupChildProcXtCreatePopupChildProcNULLCSG
_____
XmNgeometryXmCGeometryStringNULLCSG
_____
XmNoverrideRedirectXmCOverrideRedirectBooleanFalseCSG
_____
XmNpopdownCallbackXmCCallbackXtCallbackListNULLC
_____
XmNpopupCallbackXmCCallbackXtCallbackListNULLC
_____
XmNsaveUnderXmCSaveUnderBooleanFalseCSG
_____
XmNvisualXmCVisualVisual *CopyFromParentCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Translations"
.PP
There are no translations for TopLevelShell\&.
.SH "RELATED"
.PP
\fBComposite\fP(3), \fBCore\fP(3), \fBShell\fP(3), \fBWMShell\fP(3), and
\fBVendorShell\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
