'\" t
...\" def_sess.sgm /main/5 1996/08/30 12:45:02 rws $
...\" def_sess.sgm /main/5 1996/08/30 12:45:02 rws $-->
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "tt_default_session" "library call"
.SH "NAME"
\fBtt_default_session\fP \(em retrieve the current default session identifier
.SH "SYNOPSIS"
.PP
.nf
#include <Tt/tt_c\&.h>
\fBchar \fB*tt_default_session\fP\fR(\fBvoid\fR)
.fi
.SH "DESCRIPTION"
.PP
The
\fBtt_default_session\fP function
retrieves the current default session identifier\&.
.SH "RETURN VALUE"
.PP
Upon successful completion, the
\fBtt_default_session\fP function returns the pointer to the unique identifier for the
current default session\&.
If the pointer is
\fBNULL\fP, no default session is set\&.
The application can use
\fBtt_ptr_error\fP(3) to extract one of the following
\fBTt_status\fR values from the returned pointer:
.IP "TT_OK" 10
The operation completed successfully\&.
.IP "TT_ERR_NOMP" 10
The
\fBttsession\fP(1) process is not running and the ToolTalk service cannot restart it\&.
.IP "TT_ERR_PROCID" 10
The current default process identifier is out of date or invalid\&.
.SH "APPLICATION USAGE"
.PP
A session can have more than one session identifier\&.
This means that the application
cannot compare the result of
\fBtt_default_session\fP with the result of
\fBtt_message_session\fP(3) to verify that the message was sent in the default session\&.
.PP
The application should use
\fBtt_free\fP(3) to free any data stored in the address returned by the
ToolTalk API\&.
.SH "SEE ALSO"
.PP
\fBTt/tt_c\&.h - Tttt_c\fP(5), \fBtt_ptr_error\fP(3), \fBtt_free\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:40
