'\" t
...\" uid.sgm /main/5 1996/08/30 13:45:57 rws $
...\" uid.sgm /main/5 1996/08/30 13:45:57 rws $-->
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "tt_message_uid" "library call"
.SH "NAME"
\fBtt_message_uid\fP \(em retrieve the user identifier attribute from a message
.SH "SYNOPSIS"
.PP
.nf
#include <Tt/tt_c\&.h>
\fBuid_t \fBtt_message_uid\fP\fR(
\fBTt_message \fBm\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The
\fBtt_message_uid\fP function
retrieves the user identifier attribute from the specified message\&.
.PP
The ToolTalk service automatically sets the user identifier of a message with
the user identifier of the process that created the message\&.
.PP
The
\fIm\fP argument is the opaque handle for the message involved in this operation\&.
.SH "RETURN VALUE"
.PP
Upon successful completion, the
\fBtt_message_uid\fP function returns
the user identifier of the message\&.
If the group
\fBnobody\fP is returned, the
message handle is not valid\&.
.SH "SEE ALSO"
.PP
\fBTt/tt_c\&.h - Tttt_c\fP(5), \fBtt_message_gid\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
