'\" t
...\" thr_sess.sgm /main/9 1996/09/08 20:13:36 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "tt_thread_session" "library call"
.SH "NAME"
\fBtt_thread_session\fP \(em retrieve the default session identifier for the currently active thread
.SH "SYNOPSIS"
.PP
.nf
#include <Tt/tt_c\&.h>
\fBchar *\fBtt_thread_session\fP\fR(
\fB\fR);
.fi
.SH "DESCRIPTION"
.PP
The
\fBtt_thread_session\fP function
retrieves the default session
identifier for the currently active thread\&. If there is no default
session set for the currently-active thread, then the process default
session identifier is returned\&.
.PP
A session can have more than one session identifier\&.
This means, for example, that the application cannot compare the
result of \fBtt_thread_session\fP with the result of
\fBtt_message_session\fP to verify that the message was
sent in the default session\&.
.PP
The returned pointer points to the character string name of
the session\&. When no longer needed, it must be
freed with \fBtt_free\fP\&.
.SH "ARGUMENTS"
.PP
None\&.
.SH "RETURN VALUE"
.PP
Upon successful completion, the
\fBtt_thread_session\fP function returns
the pointer to a character string that uniquely identifies the default
session for the currently active thread\&.
.IP "\fBTT_OK\fP" 10
The operation completed successfully\&.
.IP "\fBTT_ERR_NOMP\fP" 10
The \fBttsession\fP process is not running
and the ToolTalk service cannot start it\&.
.IP "\fBTT_ERR_PROCID\fP" 10
The current default process identifier is out of date or invalid\&.
.IP "\fBTT_ERR_UNIMP\fP" 10
The ToolTalk implementation does not support multithreading\&.
.IP "\fBTT_ERR_TOOLATE\fP" 10
The multithreading feature has not been enabled\&.
.SH "APPLICATION USAGE"
.PP
None\&.
.SH "SEE ALSO"
.PP
\fBTt/tt_c\&.h - Tttt_c\fP(5),
\fBtt_free\fP(3),
\fBtt_ptr_error\fP(3)
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
