'\" t
...\" UilDumpS.sgm /main/9 1996/09/08 21:42:57 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "UilDumpSymbolTable" "library call"
.SH "NAME"
\fBUilDumpSymbolTable\fP \(em Dumps the contents of a named UIL symbol table to standard output
.iX "UilDumpSymbolTable"
.iX "uil functions" "UilDumpSymbolTable"
.SH "SYNOPSIS"
.PP
.nf
#include <uil/UilDef\&.h>
.sp \n(PDu
\fBvoid \fBUilDumpSymbolTable\fP\fR(
\fBsym_entry_type *\fBroot_ptr\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The \fBUilDumpSymbolTable\fP function dumps
the contents of a
UIL symbol table pointer to standard output\&.
.IP "\fIroot_ptr\fP" 10
Specifies a pointer to the the symbol table root entry\&.
This value can be taken from the \fBparse_tree_root\fP part of
the \fBUil_compile_desc_type\fP data structure returned by \fBUil\fP\&.
.PP
By following the link from the root entry,
you can traverse the entire parse tree\&.
Symbol table entries are in the following format:
.PP
\fBhex\&.address\fR
\fBsymbol\&.type\fR
\fBsymbol\&.data\fR
\fBprev\&.source\&.position\fR
\fBsource\&.position\fR
\fBmodification\&.record\fR
.PP
where:
.IP "\fBhex\&.address\fR" 10
Specifies the hexadecimal address of this entry in the symbol table\&.
.IP "\fBsymbol\&.type\fR" 10
Specifies the type of this symbol table entry\&. Some possible types
are \fIroot\fP, \fImodule\fP, \fIvalue\fP, \fIprocedure\fP, and \fIwidget\fP\&.
.IP "\fBsymbol\&.data\fR" 10
Specifies data for the symbol table entry\&. The data varies with the
type of the entry\&. Often it contains pointers to other symbol table entries,
or the actual data for the data type\&.
.IP "\fBprev\&.source\&.position\fR" 10
Specifies the end point in the source code for the previous source item\&.
.IP "\fBsource\&.position\fR" 10
Specifies the range of positions in the source code for this symbol\&.
.PP
The exact data structures for each symbol type are defined in the
include file \fBUilSymDef\&.h\fP\&.
Note that this file is automatically included when
an application includes the file \fBUilDef\&.h\fP\&.
.SH "RELATED"
.PP
\fBUil\fP(3)
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
