'\" t
...\" ArrowBuB.sgm /main/11 1996/09/08 20:25:10 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmArrowButtonGadget" "library call"
.SH "NAME"
\fBXmArrowButtonGadget\fP \(em The ArrowButtonGadget widget class
.iX "XmArrowButtonGadget"
.iX "widget class" "ArrowButtonGadget"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ArrowBG\&.h>
.fi
.SH "DESCRIPTION"
.PP
ArrowButtonGadget consists of a directional arrow surrounded by a border shadow\&.
When it is selected, the shadow changes to give the appearance that the
ArrowButtonGadget has been pressed in\&. When it is unselected, the
shadow reverts to give the appearance that the button is released, or out\&.
.PP
ArrowButtonGadget holds the \fBXmQTactivatable\fP trait\&.
.SS "Classes"
.PP
ArrowButtonGadget inherits behavior, resources, and traits
from the \fBObject\fP, \fBRectObj\fP, and \fBXmGadget\fP classes\&.
.PP
The class pointer is \fBxmArrowButtonGadgetClass\fP\&.
.PP
The class name is \fBXmArrowButtonGadget\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmArrowButtonGadget Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNactivateCallbackXmCCallbackXtCallbackListNULLC
_____
XmNarmCallbackXmCCallbackXtCallbackListNULLC
_____
XmNarrowDirectionXmCArrowDirectionunsigned charXmARROW_UPCSG
_____
XmNdetailShadowThicknessXmCDetailShadowThicknessDimension2CSG
_____
XmNdisarmCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmultiClickXmCMultiClickunsigned chardynamicCSG
_____
.TE
.IP "\fBXmNactivateCallback\fP" 10
Specifies a list of callbacks that is called
when the ArrowButtonGadget is activated\&.
To activate the button, press and release
\fBBSelect\fP while the pointer is inside
the ArrowButtonGadget\&. Activating the ArrowButtonGadget
also disarms it\&.
The reason sent by this callback is \fBXmCR_ACTIVATE\fP\&.
This callback uses the \fBXmQTactivatable\fP trait\&.
.IP "\fBXmNarmCallback\fP" 10
Specifies a list of callbacks that is called
when the ArrowButtonGadget is armed\&.
To arm this widget, press \fBBSelect\fP
while the pointer is inside the ArrowButtonGadget\&.
The reason sent by this callback is \fBXmCR_ARM\fP\&.
.IP "\fBXmNarrowDirection\fP" 10
Sets the arrow direction\&.
The values for this resource are
.RS
.IP "   \(bu" 6
\fBXmARROW_UP\fP
.IP "   \(bu" 6
\fBXmARROW_DOWN\fP
.IP "   \(bu" 6
\fBXmARROW_LEFT\fP
.IP "   \(bu" 6
\fBXmARROW_RIGHT\fP
.RE
.IP "\fBXmNdetailShadowThickness\fP" 10
Specifies the thickness of the inside arrow shadows\&. The default thickness
is 2 pixels\&.
.IP "\fBXmNdisarmCallback\fP" 10
Specifies a list of callbacks that is called
when the ArrowButtonGadget is disarmed\&.
To disarm this widget, press and release \fBBSelect\fP
while the pointer is inside the ArrowButtonGadget\&.
The reason sent by this callback is \fBXmCR_DISARM\fP\&.
.IP "\fBXmNmultiClick\fP" 10
If a button click is followed by another button click within the time
span specified by the display\&'s multiclick time and this resource is
set to \fBXmMULTICLICK_DISCARD\fP, the second click is not processed\&.
If this resource is set to \fBXmMULTICLICK_KEEP\fP, the event
is processed and \fIclick_count\fP is incremented in the callback structure\&.
When the ArrowButtonGadget is not in a menu, the default value is
\fBXmMULTICLICK_KEEP\fP\&.
.SS "Inherited Resources"
.PP
\fBXmArrowButtonGadget\fP inherits behavior and resources from the
superclasses described in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmGadget Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapdynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightOnEnterXmCHighlightOnEnterBooleanFalseCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimension2CSG
_____
XmNlayoutDirectionXmNCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmNONECSG
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBRectObj Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNborderWidthXmCBorderWidthDimension0N/A
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBObject Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
        int \fIclick_count\fP;
} XmArrowButtonCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
.IP "\fIclick_count\fP" 10
This value is valid only when the reason is \fBXmCR_ACTIVATE\fP\&.
It contains the number of clicks in the last multiclick sequence
if the \fBXmNmultiClick\fP resource is set to \fBXmMULTICLICK_KEEP\fP,
otherwise it contains 1\&.
The activate callback is invoked for each click if \fBXmNmultiClick\fP
is set to \fBXmMULTICLICK_KEEP\fP\&.
.SS "Behavior"
.PP
\fBXmArrowButtonGadget\fP includes behavior from \fBXmGadget\fP\&.
The following list describes additional
XmArrowButtonGadget behavior:
.IP "\fB<Btn1Down>\fP:" 10
Draws the shadow in the selected state and
calls the callbacks for \fBXmNarmCallback\fP\&.
.IP "\fB<Btn1Down>\fP\fB\ or\ \fP\fB<Btn1Up>\fP:" 10
Draws the shadow in the unselected state\&.
If the pointer is within the ArrowButtonGadget,
calls the callbacks for \fBXmNactivateCallback\fP\&.
Calls the callbacks for \fBXmNdisarmCallback\fP\&.
.IP "\fB<Btn1Down>\fP\fB(2+)\fP:" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_DISCARD\fP, this action does
nothing\&.
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_KEEP\fP, this action
draws the shadow in the selected state and calls the callbacks for
\fBXmNarmCallback\fP\&.
.IP "\fB<Btn1Up>\fP\fB(2+)\fP:" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_DISCARD\fP, this action does
nothing\&.
.IP "" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_KEEP\fP, this action
increments \fIclick_count\fP in the callback structure and
draws the shadow in the unselected state\&.
If the pointer is within the ArrowButtonGadget, this action calls the
callbacks for \fBXmNactivateCallback\fP and \fBXmNdisarmCallback\fP\&.
.IP "\fB<Key>\fP\fB<osfSelect>\fP:" 10
Draws the shadow in the selected state and
calls the callbacks for \fBXmNarmCallback\fP\&.
Arranges for the shadow to be drawn in the unselected state and
the callbacks for \fBXmNactivateCallback\fP and \fBXmNdisarmCallback\fP
to be called, either immediately or at a later time\&.
.IP "\fB<Key>\fP\fB<osfHelp>\fP:" 10
Calls the callbacks for \fBXmNhelpCallback\fP if any exist\&.
If there are no help callbacks for this widget, this action calls the help
callbacks for the nearest ancestor that has them\&.
.IP "\fB<Enter>\fP:" 10
Draws the ArrowButtonGadget shadow in its selected state if the
pointer leaves and re-enters the gadget while <Btn1> is pressed\&.
.IP "\fB<Leave>\fP:" 10
Draws the ArrowButtonGadget shadow in its unselected state
if the pointer leaves the gadget while <Btn1> is pressed\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBObject\fP(3), \fBRectObj\fP(3),
\fBXmCreateArrowButtonGadget\fP(3), and
\fBXmGadget\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
