'\" t
...\" CascBB.sgm /main/11 1996/09/08 20:25:59 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmCascadeButtonGadget" "library call"
.SH "NAME"
\fBXmCascadeButtonGadget\fP \(em The CascadeButtonGadget widget class
.iX "XmCascadeButtonGadget"
.iX "widget class" "CascadeButtonGadget"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/CascadeBG\&.h>
.fi
.SH "DESCRIPTION"
.PP
CascadeButtonGadget links two menu panes, a MenuBar to a menu pane, or an
OptionMenu to a menu pane\&.
.PP
It is used in menu systems and must have a RowColumn parent
with its \fBXmNrowColumnType\fP resource set to \fBXmMENU_BAR\fP,
\fBXmMENU_POPUP\fP, \fBXmMENU_PULLDOWN\fP, or \fBXmMENU_OPTION\fP\&.
.PP
It is the only gadget that can have a Pulldown menu pane attached to it as
a submenu\&. The submenu is displayed when this gadget is activated within
a PopupMenu, a PulldownMenu, or an OptionMenu\&. Its visuals can
include a label or pixmap and a cascading indicator when it is in a
Popup or Pulldown menu pane; or it can include only a label or a pixmap
when it is in an OptionMenu\&.
The positioning of the PulldownMenu with respect to the CascadeButton
depends on the \fBXmNlayoutDirection\fP resource of the MenuShell\&.
.PP
The default behavior associated with a CascadeButtonGadget depends on the type
of menu system in which it resides\&.
By default, \fBBSelect\fP controls the behavior of the CascadeButtonGadget\&.
In addition, \fBBMenu\fP controls the behavior of the CascadeButtonGadget if
it resides in a PopupMenu system\&.
The actual mouse button used is determined by its RowColumn parent\&.
\fBBMenu\fP also performs the \fBBSelect\fP actions in all
types of menu systems\&.
.PP
A CascadeButtonGadget\&'s visuals differ from most other button gadgets\&. When
the button
becomes armed, its visuals change from a 2-D to a 3-D look, and it displays
the submenu that has been attached
to it\&. If no submenu is attached, it simply changes its visuals\&.
.PP
When a CascadeButtonGadget
within a Pulldown or Popup menu pane is armed as the result of the user
moving the mouse pointer into the gadget, it does not immediately display its
submenu\&. Instead, it waits a short time to see if the arming
was temporary (that is, the user was simply passing through the gadget), or
the user really wanted the submenu posted\&. This delay is
configurable using \fBXmNmappingDelay\fP\&.
.PP
CascadeButtonGadget provides a single mechanism for
activating the gadget from the keyboard\&. This mechanism is referred to as
a keyboard mnemonic\&.
If a mnemonic has been
specified for the gadget, the user may activate it
by simply typing the mnemonic while the CascadeButtonGadget is visible\&.
If the CascadeButtonGadget is in a MenuBar and the MenuBar does not have
focus, the \fBMAlt\fP modifier must be
pressed with the mnemonic\&.
Mnemonics are typically used to interact with a menu
using the keyboard\&.
.PP
If a CascadeButtonGadget is in a Pulldown or Popup menu pane and there is a submenu attached, the
\fBXmNmarginBottom\fP, \fBXmNmarginLeft\fP, \fBXmNmarginRight\fP, and
\fBXmNmarginTop\fP
resources may enlarge to accommodate \fBXmNcascadePixmap\fP\&.
\fBXmNmarginWidth\fP defaults
to 6 if this
resource is in a MenuBar; otherwise, it takes LabelGadget\&'s default, which
is 2\&.
.PP
CascadeButtonGadget uses the \fBXmQTmenuSystem\fP and
\fBXmQTspecifyRenderTable\fP traits\&.
.SS "Classes"
.PP
CascadeButtonGadget inherits behavior, resources, and traits
from the \fBObject\fP, \fBRectObj\fP, \fBXmGadget\fP,
and \fBXmLabelGadget\fP classes\&.
.PP
The class pointer is \fBxmCascadeButtonGadgetClass\fP\&.
.PP
The class name is \fBXmCascadeButtonGadget\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file,
remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmCascadeButtonGadget\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNactivateCallbackXmCCallbackXtCallbackListNULLC
_____
XmNcascadePixmapXmCPixmapPixmapdynamicCSG
_____
XmNcascadingCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmappingDelayXmCMappingDelayint180 msCSG
_____
XmNsubMenuIdXmCMenuWidgetWidgetNULLCSG
_____
.TE
.IP "\fBXmNactivateCallback\fP" 10
Specifies the list of callbacks that is
called when the user activates the CascadeButtonGadget,
and there is no submenu attached to pop up\&. The activation occurs
when a mouse button is released
or when the mnemonic associated with the gadget is typed\&. The specific mouse
button depends on information in the RowColumn parent\&. The reason
sent by the callback is \fBXmCR_ACTIVATE\fP\&.
.IP "\fBXmNcascadePixmap\fP" 10
Specifies the cascade pixmap displayed on one end of the gadget when
a CascadeButtonGadget is used within a Popup or Pulldown menu pane
and a submenu is attached\&.
The LabelGadget class resources \fBXmNmarginBottom\fP,
\fBXmNmarginLeft\fP, \fBXmNmarginRight\fP, and
\fBXmNmarginTop\fP may be modified to
ensure that room is left for the cascade pixmap\&.
The default cascade pixmap in menus other than option menus is an arrow
pointing to the side of the menu where the submenu will appear\&.
The default for the CascadeButtonGadget in an option menu is
\fBXmUNSPECIFIED_PIXMAP\fP\&.
.IP "" 10
The positioning of the cascade pixmap
to either the left of right of the widget, and the direction of the
arrow, depend on the \fBXmNlayoutDirection\fP resource of the MenuShell\&.
.IP "\fBXmNcascadingCallback\fP" 10
Specifies the list of callbacks that is
called just prior to the mapping of the submenu
associated with the
CascadeButtonGadget\&. The reason sent by the callback is \fBXmCR_CASCADING\fP\&.
.IP "\fBXmNmappingDelay\fP" 10
Specifies the amount of time, in milliseconds, between when a
CascadeButtonGadget
becomes armed and when it maps its submenu\&. This delay is used only when the
gadget is within a Popup or Pulldown menu pane\&.
The value must not be negative\&.
.IP "\fBXmNsubMenuId\fP" 10
Specifies the widget ID for the Pulldown menu pane to be
associated with this CascadeButtonGadget\&. The specified menu pane is
displayed when the CascadeButtonGadget becomes armed\&. The menu pane must
have been created with the appropriate parentage depending on the type
of menu used\&. See \fBXmCreatePulldownMenu\fP(3),
\fBXmCreatePopupMenu\fP(3), and \fBXmCreateOptionMenu\fP(3) for
more information on the menu systems\&.
.SS "Inherited Resources"
.PP
CascadeButtonGadget inherits behavior and resources from the
superclasses described in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmLabelGadget Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorXmCAcceleratorStringNULLN/A
_____
XmNacceleratorTextXmCAcceleratorTextXmStringNULLN/A
_____
XmNalignmentXmCAlignmentunsigned chardynamicCSG
_____
XmNfontListXmCFontListXmFontListdynamicCSG
_____
XmNlabelInsensitivePixmapXmCLabelInsensitivePixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNlabelPixmapXmCLabelPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNlabelStringXmCXmStringXmStringdynamicCSG
_____
XmNlabelTypeXmCLabelTypeunsigned charXmSTRINGCSG
_____
XmNmarginBottomXmCMarginBottomDimensiondynamicCSG
_____
XmNmarginHeightXmCMarginHeightDimension2CSG
_____
XmNmarginLeftXmCMarginLeftDimension0CSG
_____
XmNmarginRightXmCMarginRightDimensiondynamicCSG
_____
XmNmarginTopXmCMarginTopDimensiondynamicCSG
_____
XmNmarginWidthXmCMarginWidthDimensiondynamicCSG
_____
XmNmnemonicXmCMnemonicKeySymNULLCSG
_____
XmNmnemonicCharSetXmCMnemonicCharSetStringdynamicCSG
_____
XmNrecomputeSizeXmCRecomputeSizeBooleanTrueCSG
_____
XmNrenderTableXmCRenderTableXmRenderTabledynamicCSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmGadget Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapdynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightOnEnterXmCHighlightOnEnterBooleanFalseCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimension0CSG
_____
XmNlayoutDirectionXmNCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmNONECSG
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBRectObj Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNborderWidthXmCBorderWidthDimension0N/A
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBObject Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
} XmAnyCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback or is NULL if this
callback was not triggered by an \fBXEvent\fP
.SS "Behavior"
.PP
\fBXmCascadeButtonGadget\fP includes behavior from \fBXmGadget\fP\&.
\fBXmCascadeButton\fP includes the menu traversal behavior from \fBXmLabel\fP\&.
Additional \fBXmCascadeButtonGadget\fP behavior is described in
the following list (in a Popup
menu system, \fB<Btn3>\fP also performs the \fB<Btn1>\fP actions)\&.
.IP "\fB<Btn1Down>\fP:" 10
Unposts any menus posted by the parent menu\&.
Arms the CascadeButtonGadget,
posts the associated submenu,
enables mouse traversal,
and, in a MenuBar, arms the MenuBar\&.
If the menu is already active, this event
disables keyboard traversal for the menu and returns
the menu to mouse traversal mode\&.
.IP "\fB<Btn1Up>\fP:" 10
Calls the callbacks in \fBXmNcascadingCallback\fP,
posts the submenu attached to the CascadeButtonGadget and
enables keyboard traversal within the menu\&.
If the CascadeButtonGadget does not have a submenu attached,
this action calls the callbacks in \fBXmNactivateCallback\fP,
activates the CascadeButtonGadget, and unposts
all posted menus in the cascade\&.
.IP "\fB<Key>\fP\fB<osfActivate>\fP:" 10
Calls the callbacks in \fBXmNcascadingCallback\fP,
and
posts the submenu attached to the CascadeButtonGadget if keyboard
traversal is enabled in the menu\&.
If the CascadeButtonGadget does not have a submenu attached,
this action calls the callbacks in \fBXmNactivateCallback\fP,
activates the CascadeButtonGadget, and unposts
all posted menus in the cascade\&.
This action applies only to gadgets in MenuBars, PulldownMenus, and
PopupMenus\&. For a CascadeButtonGadget in an OptionMenu, if the parent
is a manager, this action passes the event to the parent\&.
.IP "\fB<Key>\fP\fB<osfSelect>\fP:" 10
Calls the callbacks in \fBXmNcascadingCallback\fP,
and
posts the submenu attached to the CascadeButtonGadget if keyboard
traversal is enabled in the menu\&.
If the CascadeButtonGadget does not have a submenu attached,
this action calls the callbacks in \fBXmNactivateCallback\fP,
activates the CascadeButtonGadget, and unposts all posted
menus in the cascade\&.
.IP "\fB<Key>\fP\fB<osfHelp>\fP:" 10
Unposts all menus in the menu hierarchy and,
when the shell\&'s keyboard focus policy is
\fBXmEXPLICIT\fP,
restores keyboard focus to
the widget that had the focus before the menu system was entered\&.
Calls the callbacks for \fBXmNhelpCallback\fP if any exist\&.
If there are no help callbacks for this widget, this action calls the
help callbacks for the nearest ancestor that has them\&.
.IP "\fB<Key>\fP\fB<osfCancel>\fP:" 10
In a MenuBar, disarms the CascadeButtonGadget and the menu and,
when the shell\&'s keyboard focus policy is
\fBXmEXPLICIT\fP,
restores
keyboard focus to the widget that had the focus before the menu was
entered\&.
For a CascadeButtonGadget in an OptionMenu, if the parent is a manager, this
action passes the event to the parent\&.
.IP "" 10
In a toplevel Pulldown MenuPane from a MenuBar, unposts the menu,
disarms the MenuBar CascadeButton and the MenuBar, and,
when the shell\&'s keyboard focus policy is
\fBXmEXPLICIT\fP,
restores keyboard
focus to the widget that had the focus before the MenuBar was
entered\&.
In other Pulldown MenuPanes, unposts the menu\&.
.IP "" 10
In a Popup MenuPane, unposts the menu and restores keyboard focus to the
widget from which the menu was posted\&.
.IP "\fB<Enter>\fP:" 10
If keyboard traversal is enabled does nothing\&.
Otherwise, in a MenuBar,
unposts any MenuPanes associated with another MenuBar entry,
arms the CascadeButtonGadget, and posts the associated submenu\&.
In other menus,
arms the CascadeButtonGadget and posts the associated submenu after
the delay specified by \fBXmNmappingDelay\fP\&.
.IP "\fB<Leave>\fP:" 10
If keyboard traversal is enabled does nothing\&.
Otherwise, in a MenuBar,
disarms the CascadeButtonGadget
if the submenu associated with the CascadeButtonGadget is not currently
posted or if there is no submenu associated with the CascadeButtonGadget\&.
.IP "" 10
In other menus, if the pointer moves anywhere except into a submenu
associated with the CascadeButtonGadget, the CascadeButtonGadget is
disarmed and its submenu is unposted\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBObject\fP(3), \fBRectObj\fP(3),
\fBXmCascadeButtonHighlight\fP(3),
\fBXmCreateCascadeButtonGadget\fP(3),
\fBXmCreatePulldownMenu\fP(3),
\fBXmCreatePopupMenu\fP(3),
\fBXmCreateOptionMenu\fP(3),
\fBXmGadget\fP(3), \fBXmLabelGadget\fP(3),
and \fBXmRowColumn\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
