'\" t
...\" ClipbF.sgm /main/11 1996/09/25 10:24:13 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmClipboardInquireCount" "library call"
.SH "NAME"
\fBXmClipboardInquireCount\fP \(em A clipboard function that returns the number of data item formats
.iX "XmClipboardInquireCount"
.iX "clipboard functions" "XmClipboardInquireCount"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/CutPaste\&.h>
int XmClipboardInquireCount (\fIdisplay, window, count,
        max_format_name_length\fP)
        Display \fI* display\fP;
        Window  \fIwindow\fP;
        int     \fI* count\fP;
        unsigned long   \fI* max_format_name_length\fP;
\fB\fR(\fBvoid\fR)
.fi
.SH "DESCRIPTION"
.PP
\fBXmClipboardInquireCount\fP returns the number of data item formats available
for the data item in the clipboard\&. This function also returns the
maximum name-length for all formats in which the data item is
stored\&.
.IP "\fIdisplay\fP" 10
Specifies a pointer to the \fBDisplay\fR structure that was returned in a
previous call to \fBXOpenDisplay\fP or \fBXtDisplay\fP\&.
.IP "\fIwindow\fP" 10
Specifies the window ID of a widget that relates the application window to the
clipboard\&. The widget\&'s window ID can be obtained through
\fBXtWindow\fP\&.
The same application instance should pass the same window ID to each of the
clipboard functions that it calls\&.
.IP "\fIcount\fP" 10
Returns the number of data item formats available for the data item in
the clipboard\&. If no formats are available, this argument equals 0
(zero)\&. The count includes the formats that were passed by name\&.
.IP "\fImax_format_name_length\fP" 10
Specifies the maximum length of all format names for the data item in
the clipboard\&.
.SH "RETURN"
.IP "\fBXmClipboardSuccess\fP" 10
The function was successful\&.
.IP "\fBXmClipboardLocked\fP" 10
The function failed because the clipboard was locked by another
application\&. The application can continue to call the function again with
the same parameters until the lock goes away\&. This gives the application
the opportunity to ask if the user wants to keep trying or to give up
on the operation\&.
.IP "\fBXmClipboardNoData\fP" 10
The function could not find data on the clipboard corresponding to the
format requested\&. This could occur because the clipboard is empty;
there is data on the clipboard, but not in the requested format; or
the data in the requested format was passed by name and is no longer
available\&.
.SH "RELATED"
.PP
\fBXmClipboardStartCopy\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
