'\" t
...\" ClipbP.sgm /main/10 1996/09/25 10:25:27 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmClipboardUnlock" "library call"
.SH "NAME"
\fBXmClipboardUnlock\fP \(em A clipboard function that unlocks the clipboard
.iX "XmClipboardUnlock"
.iX "clipboard functions" "XmClipboardUnlock"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/CutPaste\&.h>
int XmClipboardUnlock (\fIdisplay, window, remove_all_locks\fP)
        Display \fI* display\fP;
        Window  \fIwindow\fP;
        Boolean \fIremove_all_locks\fP;
\fB\fR(\fBvoid\fR)
.fi
.SH "DESCRIPTION"
.PP
\fBXmClipboardUnlock\fP unlocks the clipboard,
enabling it to be accessed by other applications\&.
.PP
If multiple calls to \fBXmClipboardLock\fP have occurred, the same
number of calls to \fBXmClipboardUnlock\fP is necessary to unlock the
clipboard, unless \fIremove_all_locks\fP is set to True\&.
.IP "\fIdisplay\fP" 10
Specifies a pointer to the \fBDisplay\fR structure that was returned in a
previous call to \fBXOpenDisplay\fP or \fBXtDisplay\fP\&.
.IP "\fIwindow\fP" 10
Specifies the window ID of a widget that relates the application window to the
clipboard\&. The widget\&'s window ID can be obtained through
\fBXtWindow\fP\&.
The same application instance should pass the same window ID to each of the
clipboard functions that it calls\&.
.IP "\fIremove_all_locks\fP" 10
When True, indicates that all nested locks should be removed\&. When False,
indicates that only one level of lock should be removed\&.
.SH "RETURN"
.IP "\fBXmClipboardSuccess\fP" 10
The function was successful\&.
.IP "\fBXmClipboardFail\fP" 10
The function failed because the clipboard was not locked or was locked
by another application\&.
.SH "RELATED"
.PP
\fBXmClipboardCancelCopy\fP(3), \fBXmClipboardCopy\fP(3),
\fBXmClipboardEndCopy\fP(3), \fBXmClipboardEndRetrieve\fP(3),
\fBXmClipboardInquireCount\fP(3), \fBXmClipboardInquireFormat\fP(3),
\fBXmClipboardInquireLength\fP(3), \fBXmClipboardInquirePendingItems\fP(3),
\fBXmClipboardLock\fP(3), \fBXmClipboardRegisterFormat\fP(3),
\fBXmClipboardRetrieve\fP(3), \fBXmClipboardStartCopy\fP(3),
\fBXmClipboardStartRetrieve\fP(3), \fBXmClipboardUndoCopy\fP(3),
and \fBXmClipboardWithdrawFormat\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
