'\" t
...\" ComboBox.sgm /main/16 1996/10/29 16:07:27 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmComboBox" "library call"
.SH "NAME"
\fBXmComboBox\fP \(em The ComboBox widget class
.iX "XmComboBox"
.iX "widget class" "ComboBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ComboBox\&.h>
.fi
.SH "DESCRIPTION"
.PP
\fBXmComboBox\fP combines the capabilities of a single-line
TextField widget
and a List widget\&. It allows users to perform opoerations like
typing and pasting information, and it also
provides a list of possible choices that the user
can select from to complete
the TextField entry field\&. The list can either be displayed at all
times or can be dropped down by the user\&. When the list portion of the
ComboBox is hidden, users are given a visual cue (a
downward-pointing arrow)
next to the TextField field\&. The position of the arrow relative to the
TextField field depends on the \fBXmNlayoutDirection\fP resource of the
widget\&. This
version of the
ComboBox is called
the "drop-down" ComboBox\&. Drop-down ComboBoxes are useful
when screen space is limited, or when users will
complete the text entry field more often by typing text than by
selecting the entry field text from the list\&.
The user can access the drop-down ComboBox in either one of two ways:
.IP "   \(bu" 6
By clicking and releasing \fB<Btn1>\fP on the downward-pointing arrow,
which
pops the list up, and the list stays up\&. A later selection of an item
in the list will cause the item to appear in the text entry field, and
the list will unpost itself\&.
.IP "   \(bu" 6
By pressing \fB<Btn1>\fP on the downward-pointing arrow, dragging
it to a list item, and then releasing it there, which selects that
item\&. The list
disappears, and the selected item appears in the text entry field\&.
.PP
The application provides an array of strings that fill the list\&. At
creation time, string items can be passed to the ComboBox via an
arglist\&.
Each string becomes an item in the list, with the first string becoming
the item in position 1, the second string becoming the item in position 2,
and so on\&. The size of the list is
set by specifying the number of items that are visible in the list
(\fBXmNvisibleItemCount\fP)\&. If the number of items in the list exceeds the
number of items that are visible, a vertical scroll bar will
automatically appear that allows the user to scroll through a
large number of items\&.
.PP
ComboBox creates two child widgets: a TextField widget for entering
text and a ScrolledWindow containing a List for the list of items\&.
The name of the items list itself is \fBList\fP, and the name of the
TextField is \fBText\fP\&.
The application or user can specify resource values for these widgets in
a resource file, and the application can use \fBXtNameToWidget\fP
(specifying \fB"*List"\fP for the items list or \fB"*Text"\fP for the
TextField widget) to obtain the widget IDs of the
descendant widgets\&.
At creation time, ComboBox passes appropriate resource values in the
creation arglist, including \fBXmNitems\fP, to the items list\&.
Note that the result of providing the \fBXmNdestroyCallback\fP
resource in the creation \fIarglist\fP is unspecified\&. The
application should use the \fBXtAddCallback\fP function to add
callbacks to the appropriate widget (TextField or List) after
creating it\&.
.PP
ComboBox forces the following resource values
on its List child:
.IP "   \(bu" 6
If \fBXmNcomboBoxType\fP is \fBXmCOMBO_BOX\fP,
\fBXmNtraversalOn\fP is forced to False\&.
.IP "   \(bu" 6
\fBXmNhighlightThickness\fP is forced to 2 in a drop-down ComboBox and
to 0 in other types of ComboBoxes\&.
.IP "   \(bu" 6
\fBXmNborderWidth\fP is forced to 0\&.
.IP "   \(bu" 6
\fBXmNnavigationType\fP is forced to \fBXmNONE\fP\&.
.IP "   \(bu" 6
\fBXmNselectionPolicy\fP is forced to \fBXmBROWSE_SELECT\fP\&.
.IP "   \(bu" 6
\fBXmNlistSizePolicy\fP is forced to \fBXmVARIABLE\fP\&.
.IP "   \(bu" 6
\fBXmNspacing\fP is forced to 0\&.
.IP "   \(bu" 6
\fBXmNvisualPolicy\fP is forced to \fBXmVARIABLE\fP\&.
.IP "   \(bu" 6
\fBXmNselectedPositions\fP is forced to NULL\&.
.IP "   \(bu" 6
\fBXmNselectedPositionsCount\fP is forced to 0\&.
.PP
When \fBXmNcomboBoxType\fP is \fBXmDROP_DOWN_LIST\fP,
ComboBox forces the following resource values on
its TextField child:
.IP "   \(bu" 6
\fBXmNeditable\fP is forced to False\&.
.IP "   \(bu" 6
\fBXmNcursorPositionVisible\fP is forced to False\&.
.IP "   \(bu" 6
\fBXmNshadowThickness\fP is forced to 0\&.
.PP
By contrast, when \fBXmNcomboBoxType\fP is \fBXmCOMBO_BOX\fP or
\fBXmDROP_DOWN_COMBO_BOX\fP, ComboBox forces the following
resource values on its TextField child:
.IP "   \(bu" 6
\fBXmNeditable\fP is forced to True\&.
.IP "   \(bu" 6
\fBXmNcursorPositionVisible\fP is forced to True\&.
.IP "   \(bu" 6
\fBXmNeditMode\fP is forced to \fBXmSINGLE_LINE_EDIT\fP\&.
.PP
ComboBox always forces the values of the following resources on
the TextField:
.IP "   \(bu" 6
\fBXmNnavigationType\fP is forced to \fBXmNONE\fP\&.
.IP "   \(bu" 6
\fBXmNhighlightThickness\fP is forced to 0\&.
.IP "   \(bu" 6
\fBXmNborderWidth\fP is forced to 0\&.
.PP
ComboBox allows a single item to be selected in two ways: by
selecting the desired item from the List or by entering text
into the TextField\&.
ComboBox does not automatically select a list item if the user types
that string into the TextField\&. It selects the item when the user
presses \fBKActivate\fP or moves the focus\&.
ComboBox supports the Browse
Select selection model of List (see the \fBXmList\fP reference page
for a description of this model), so selections are mutually
exclusive\&. Selecting an item from the list causes
that item to be displayed in the TextField portion of the
ComboBox\&.
If an application sets the \fBXmNvalue\fP resource of TextField,
that string is shown in the TextField\&.
If the application has not provided any list items,
or if there is no current selection, the TextField
is empty\&.
.PP
The TextField in the ComboBox widget
can be either editable or noneditable, depending on the value of
the \fBXmNcomboBoxType\fP resource\&.
.PP
If the TextField is editable, the user can type into it\&.
When the user presses the Return key, the ComboBox will
compare the typed entry to the items in the List\&.
If there is an exact match, then the matched List item is
selected\&.
If the application wishes to validate the entered text (for example, to
ensure that the typed selection is a valid one), it can do so by
setting \fBXmNmodifyVerifyCallback\fP on the TextField widget\&.
.PP
If the TextField is noneditable, typing text may invoke a matching
algorithm that will attempt to match the entered text with items in
the list\&. The specific matching algorithm applied, which may be none,
is determined by the value of the \fBXmNmatchBehavior\fP resource in
ComboBox, which can be either \fBXmNONE\fP or
\fBXmQUICK_NAVIGATE\fP\&. A value
of \fBXmNONE\fP indicates that no matching algorithm will occur\&. A value of
\fBXmQUICK_NAVIGATE\fP indicates that when the List widget has focus,
one-character navigation is supported\&. In this algorithm, if the typed
character is the initial character of some item in the List, this
algorithm causes that item to be navigated to and selected, and the
item is displayed in the TextField\&. Subsequently typing the same
character will cycle among the items with the same first character\&.
.PP
Regardless of the selection mechanism used (either selected directly
from the List or typed into the TextField), when an item in the
List is selected, that item is highlighted in the List\&.
In addition, the selected item is displayed in the
TextField of the ComboBox\&. If the user performs an action
that would move focus away from ComboBox, or selects a List item,
the \fBXmNselectionCallback\fP callbacks are invoked to notify
the application of the current contents of the TextField (or choice)\&. The
application then takes whatever action is required based on those
contents (or choice)\&.
.PP
ComboBox uses the \fBXmQTspecifyRenderTable\fP trait and holds the
\fBXmQTaccessTextual\fP trait\&.
.SS "Classes"
.PP
\fBXmComboBox\fP inherits behavior, resources, and traits from \fBCore\fP,
\fBComposite\fP,
and \fBXmManager\fP classes\&.
.PP
The class pointer is \fBxmComboBoxWidgetClass\fP\&.
.PP
The class name is \fBXmComboBox\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by
the programmer to specify data\&. The programmer can also set the
resource values for the inherited classes to set attributes for
this widget\&. To reference a resource by name or by class in
a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or \fBXmC\fP prefix and
use the
remaining letters\&. To specify one of the defined values for a
resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use the
remaining letters (in either lowercase or uppercase, but
include any underscores between words)\&. The codes in the
access column indicate if the given resource can be at
creation time (C), set by using \fBXtSetValues\fP (S), retrieved by
using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmComboBox Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNarrowSizeXmCArrowSizeDimensiondynamicCSG
_____
XmNarrowSpacingXmCArrowSpacingDimensiondynamicCSG
_____
XmNcolumnsXmCColumnshortdynamicCSG
_____
XmNcomboBoxTypeXmCComboBoxTypeunsigned charXmCOMBO_BOXCG
_____
XmNfontListXmCFontListXmFontListNULLCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimension2CSG
_____
XmNitemCountXmCItemCountintdynamicCSG
_____
XmNitemsXmCItemsXmStringTabledynamicCSG
_____
XmNlistXmCListWidgetdynamicG
_____
XmNmarginHeightXmCMarginHeightDimension2CSG
_____
XmNmarginWidthXmCMarginWidthDimension2CSG
_____
XmNmatchBehaviorXmCMatchBehaviorunsigned chardynamicCSG
_____
XmNpositionModeXmCPositionModeXtEnumXmZERO_BASEDCG
_____
XmNrenderTableXmCRenderTableXmRenderTabledynamicCSG
_____
XmNselectedItemXmCSelectedItemXmStringNULLCSG
_____
XmNselectedPositionXmCSelectedPositionintdynamicCSG
_____
XmNselectionCallbackXmCCallbackXmCallbackListNULLC
_____
XmtextFieldXmCTextFieldWidgetdynamicG
_____
XmNvisibleItemCountXmCVisibleItemCountint10CSG
_____
.TE
.IP "\fBXmNarrowSize\fP" 10
Specifies the width of the arrow\&. The default size
depends on the size of the text, as well as
the size of the ComboBox\&.
.IP "\fBXmNarrowSpacing\fP" 10
Specifies the space between the text and arrow visual in pixels\&. The
default value is obtained from the \fBXmNmarginWidth\fP resource\&.
.IP "\fBXmNcolumns\fP" 10
Specifies the number of columns in the text field\&. If unset,
the text field\&'s value is used\&. Refer to the \fBXmTextField\fP man page
for more detailed information\&.
.IP "\fBXmNcomboBoxType\fP" 10
Specifies the type of ComboBox to be created\&. This can be one of
the following:
.RS
.IP "\fBXmCOMBO_BOX\fP" 10
Generates a ComboBox where the list is always displayed, and the text
entry field is editable\&.
.IP "\fBXmDROP_DOWN_COMBO_BOX\fP" 10
Generates a ComboBox where the list is hidden unless specifically
requested, and the text entry field is editable\&.
.IP "\fBXmDROP_DOWN_LIST\fP" 10
Generates a ComboBox where the list is hidden unless specifically
requested, and the text entry field is noneditable\&.
.RE
.IP "\fBXmNfontList\fP" 10
Specifies the fontlist associated with \fBXmComboBox\fP\&. The fontlist
is an obsolete construct, and has been superseded by the render table\&.
It is included for compatibility with earlier versions of Motif, and
for applications that do not easily support render tables\&. The
default fontlist is derived from the default render table, and if
both a fontlist and a render table are specified, the render table
takes precedence\&.
.IP "\fBXmNhighlightThickness\fP" 10
Specifies the thickness of the highlighting rectangle\&.
.IP "\fBXmNitemCount\fP" 10
Specifies the number of items in the list\&. If unset,
the lists\&'s value is used\&.
Refer to the \fBXmList\fP man page for more detailed information\&.
.IP "\fBXmNitems\fP" 10
Specifies the items in the list\&. If unset,
the lists\&'s value is used\&. Refer to the \fBXmList\fP man page for more detailed information\&.
.IP "\fBXmNlist\fP" 10
The list widget\&.
.IP "\fBXmNmarginWidth\fP" 10
Specifies the horizontal spacing between the child widgets and the boundary
of the ComboBox\&.
.IP "\fBXmNmarginHeight\fP" 10
Specifies the vertical spacing between the child widgets and the boundary
of the ComboBox\&.
.IP "\fBXmNmatchBehavior\fP" 10
Defines the matching algorithm applied to match the text
typed by the user in the TextField field with items in the list\&.
The current values are \fBXmNONE\fP and \fBXmQUICK_NAVIGATE\fP, as follows:
.RS
.IP "\fBXmNONE\fP" 10
Indicates that there is no assigned matching algorithm\&.
.IP "\fBXmQUICK_NAVIGATE\fP" 10
Is only valid for noneditable ComboBoxes (\fBXmNcomboBoxType\fP resource value
\fBXmDROP_DOWN_LIST\fP)\&. This algorithm supports 1-character navigation
when the List widget has focus\&. If the typed character is the
initial character of some item in the List, this algorithm causes
that item to be navigated to and selected\&. Subsequently typing the
same character will cycle among the items with the same first character\&.
.RE
.IP "\fBXmNpositionMode\fP" 10
Specifies how the value of the
\fBXmNselectedPosition\fP
resource and the \fBitem_position\fP field
of the callback structure are to be interpreted\&. Note that
the convenience functions \fBXmComboBoxDeletePos\fP and \fBXmComboBoxAddItem\fP
are not affected by this resource, and (like \fBXmList\fP) always use
1-based positions\&. Valid values for this resource are:
.RS
.IP "\fBXmZERO_BASED\fP" 10
(DtComboBox compatibility mode: default) \fBXmNselectedPosition\fP
is in \fB[0,itemcount-1]\fP\&.
The \fBitem_position\fP in the \fBXmComboBoxCallbackStruct\fP
is 0 if the first element in the list
was selected\&. Note that 0 is also returned if no element in the list
was selected (that is, a new item was entered in the text field)\&.
.IP "\fBXmONE_BASED\fP" 10
(Motif mode) Both the resource value and the callback fields
are 1-based\&. This is consistent with other Motif widgets\&.
.RE
.IP "\fBXmNrenderTable\fP" 10
Specifies the render table associated with ComboBox\&.
This render table is used in both the TextField field and the
List in the ComboBox\&. This is used in conjunction with the
\fBXmNvisibleItemCount\fP resource of the List to determine the height
of the ComboBox widget\&.
.IP "" 10
If this value is NULL at initialization, and if the widget parent is
\fBXmBulletinBoard\fP or its subclasses,
\fBVendorShell\fP or its subclasses, or \fBXmMenuShell\fP, then the
widget parent provides the default render table associated with
the widget\&.
If both a render table and a fontlist are specified, the render table
will take precedence\&.
.IP "\fBXmNselectedItem\fP" 10
Specifies a compound string that represents the current selection of
the ComboBox\&. The selected item is the content of the
ComboBox text entry field\&.
.IP "\fBXmNselectedPosition\fP" 10
If the selection in the ComboBox is an item in the list, this is
the index of the selected item in the list\&. If no item in
the list is selected, this is 0\&.
.IP "\fBXmNselectionCallback\fP" 10
Specifies the list of callbacks called when an item is selected\&.
The reason field in the \fBXmComboBoxCallbackStruct\fR is
\fBXmCR_SELECT\fP\&.
.IP "\fBXmNtextField\fP" 10
The text field widget\&.
.IP "\fBXmNvisibleItemCount\fP" 10
Specifies the number of visible items in the list\&. This will override any
value specified for the list\&.
Refer to the \fBXmList\fP man page for more detailed information\&.
.SS "Inherited Resources"
.PP
ComboBox inherits behavior and resources from superclasses described
in the following tables\&. For a complete description of each
resource, refer to the reference page for that superclass\&.
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetNULLCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmSTICKY_TAG_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback\&.
The callback structure is defined as follows:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent *\fIevent\fP;
        XmString \fIitem_or_text\fP;
        int \fIitem_position\fP;
} XmComboBoxCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&. It can be NULL\&.
.IP "\fIitem_or_text\fP" 10
The contents of the text field at the time the event caused the
callback\&. The \fIitem_or_text\fP parameter points to a temporary
storage space that is
reused after the callback is finished\&. If an application needs to save
the item, it should copy \fIitem_or_text\fP into its own data space\&.
.IP "\fIitem_position\fP" 10
The position of item in the list\&'s \fBXmNitems\fP 1-based array\&. If this
is 0, it means that the \fIitem_or_text\fP was not selected from the
List\&.
.SS "Translations"
.PP
The ComboBox translations are listed below\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.PP
.RS
\fBNote:  
.PP
The KPageUp and KPageDown translations do not take effect unless the
\fBList\fP child widget is posted\&.
.RE
.IP "\fB<Btn1Down>\fP:" 10
CBArmAndDropDownList()
.IP "\fB<Btn1Up>\fP:" 10
CBDisarm()
.PP
The following lists the List translations in the drop-down list\&. When
ComboBox \fBXmNcomboBoxType\fP is
\fBXmDROP_DOWN_LIST\fP,
\fB<osfActivate>\fP, \fB<osfCancel>\fP, and
\fBReturn\fP are overriden by ComboBox actions\&.
.IP "\fB:c\fP <Key>\fB<osfDown>\fP:" 10
CBDropDownList()
.IP "\fB:c\fP <Key>\fB<osfUp>\fP:" 10
CBDropDownList()
.IP "\fB:\fP<Key>\fB<osfCancel>\fP:" 10
CBCancel()
.IP "\fB:\fP<Key>\fB<osfActivate>\fP:" 10
CBActivate()
.IP "\fB\(aps \(apm \(apa\fP<Key>\fBReturn\fP:" 10
CBActivate()
.SS "Accelerators"
.PP
The following accelerators are added to ComboBox and its children\&.
The accelerators may not directly correspond to a translation table\&.
If the translation is not listed below, it may depend on the context
of the event\&.
.IP "\fB:c\fP <Key>\fB<osfUp>\fP:" 10
CBDropDownList()
.IP "\fB:\fP<Key>\fB<osfUp>\fP:" 10
CBListAction(\fBUp\fP)
.IP "\fB:c\fP <Key>\fB<osfDown>\fP:" 10
CBDropDownList()
.IP "\fB:\fP<Key>\fB<osfDown>\fP:" 10
CBListAction(\fBDown\fP)
.IP "\fB:c\fP <Key>\fB<osfBeginLine>\fP:" 10
CBListAction(\fBListBeginData\fP)
.IP "\fB:c\fP <Key>\fB<osfEndLine>\fP:" 10
CBListAction(\fBListEndData\fP)
.IP "\fB:\fP<Key>\fB<osfPageUp>\fP:" 10
CBListAction(\fBListPrevPage\fP)
.IP "\fB:\fP<Key>\fB<osfPageDown>\fP:" 10
CBListAction(\fBListNextPage\fP)
.PP
A drop-down ComboBox also adds accelerators to its List child\&.
Aside from the accelerators that are already listed in this section,
those accelerators are the default TextField key translations\&.
.SS "Action Routines"
.PP
The \fBXmComboBox\fP action routines are as follows:
.IP "CBActivate():" 10
Calls the \fBXmNselectionCallback\fP callbacks\&. If the
\fBXmNcomboBoxType\fP is
\fBXmDROP_DOWN_COMBO_BOX\fP or \fBXmDROP_DOWN_LIST\fP, it unposts the
list\&. If the
parent is a manager, passes the event to the parent\&.
.IP "CBArmAndDropDownList():" 10
If the pointer is within the down arrow, draws the shadow of the arrow
in the selected state, and then posts the list\&.
.IP "CBCancel():" 10
If the \fBXmNcomboBoxType\fP is \fBXmDROP_DOWN_COMBO_BOX\fP or
\fBXmDROP_DOWN_LIST\fP, pops down
the list\&. If the parent is a manager, passes the event to the parent\&.
.IP "CBDisarm():" 10
Redraws the arrow in an unselected state\&.
.IP "CBDropDownList():" 10
If \fBXmNcomboBoxType\fP is \fBXmDROP_DOWN\fP or \fBXmDROP_DOWN_LIST\fP, and
list is not
displayed, posts the list\&. If list is displayed, it unposts the list\&.
.IP "CBListAction(\fBListBeginData\fP):" 10
Moves the location cursor to the first item in the list\&.
In Normal Mode, this also deselects any current selection,
selects the first item in the list, and calls the
\fBXmNbrowseSelectionCallback\fP selection callback\&.
.IP "CBListAction(\fBListEndData\fP):" 10
Moves the location cursor to the last item in the list\&.
In Normal Mode, this also deselects any current selection,
selects the last item in the list, and calls the
\fBXmNbrowseSelectionCallback\fP selection callback\&.
.IP "CBListAction(\fBListPrevPage\fP):" 10
Scrolls the list to the previous page, moving the location cursor to a
new item\&.
This action also selects the new item, deselects any current
selection, and calls the \fBXmNbrowseSelectionCallback\fP callbacks\&.
If the ComboBox is not a drop-down type, then this action does
nothing\&.
.IP "CBListAction(\fBListNextPage\fP):" 10
Scrolls the list to the next page, moving the location cursor to a new
item\&.
This action also selects the new item, deselects any current
selection, and calls the \fBXmNbrowseSelectionCallback\fP callbacks\&.
If the ComboBox is not a drop-down type, then this action does
nothing\&.
.IP "CBListAction(\fBUp\fP):" 10
Moves the location cursor to the previous item in the list\&.
This action also selects the previous item, deselects any current
selection, and calls the \fBXmNbrowseSelectionCallback\fP callbacks\&.
Note that, unlike the List \fBListPrevItem\fP action, this action wraps
around\&.
.IP "CBListAction(\fBDown\fP):" 10
Moves the location cursor to the next item in the list\&.
This action also selects the next item, deselects any current
selection, and calls the \fBXmNbrowseSelectionCallback\fP callbacks\&.
Note that, unlike the List \fBListNextItem\fP action, this action wraps
around\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&. For information
about bindings for virtual buttons and keys, see
\fBVirtualBindings\fP(3)\&.
.SH "ERRORS/WARNINGS"
.PP
The toolkit will display a warning if the application tries to
set the value of \fBXmNlist\fP
or the \fBXmNtextField\fP resource, which are read-only (marked G in the resource
table)\&.
.SH "RELATED"
.PP
\fBComposite\fP(3),
\fBCore\fP(3),
\fBXmCreateComboBox\fP(3),
\fBXmList\fP(3),
\fBXmManager\fP(3), and
\fBXmTextField\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
