'\" t
...\" ComboSel.sgm /main/5 1996/08/30 14:17:37 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmComboBoxSelectItem" "library call"
.SH "NAME"
\fBXmComboBoxSelectItem\fP \(em select a XmComboBox item
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ComboBox\&.h>
\fBvoid \fBXmComboBoxSelectItem\fP\fR(
\fBWidget \fBw\fR\fR,
\fBXmString \fBitem\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The
\fBXmComboBoxSelectItem\fP function selects an item in the XmList of the XmComboBox
widget\&.
.PP
The
\fIw\fP argument specifies the XmComboBox widget ID\&.
.PP
The
\fIitem\fP argument specifies the
\fBXmString\fR of the item to be selected\&.
If the
\fIitem\fP is not found on the list,
\fBXmComboBoxSelectItem\fP notifies the user via the
\fBXtWarning\fP function\&.
.SH "RETURN VALUE"
.PP
The
\fBXmComboBoxSelectItem\fP function returns no value\&.
.SH "SEE ALSO"
.PP
\fBXmComboBoxAddItem\fP(3), \fBXmComboBoxDeletePos\fP(3), \fBXmComboBoxSetItem\fP(3); \fBXtWarning\fP(3)\&. in the  CAE Specification,  Window Management: X Toolkit Intrinsics\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
