'\" t
...\" ComboBU.sgm /main/8 1996/09/08 20:30:27 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmComboBoxUpdate" "library call"
.SH "NAME"
\fBXmComboBoxUpdate\fP \(em A ComboBox function that resynchronizes data
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ComboBox\&.h>
\fBvoid \fBXmComboBoxUpdate\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmComboBoxUpdate\fP resynchronizes the internal data structures of a
specified ComboBox widget\&. This function is useful when an
application manipulates ComboBox\&'s child widgets, possibly changing
data structures\&. For example, you might want to use the
\fBXmComboBoxUpdate\fP function after a ComboBox List child selection
has been changed without notification\&.
.IP "\fIwidget\fP" 10
Specifies the ComboBox widget ID\&.
.SH "RELATED INFORMATION"
.PP
\fBXmComboBox\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
