'\" t
...\" ContainI.sgm /main/7 1996/08/30 14:26:29 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmContainerReorder" "library call"
.SH "NAME"
\fBXmContainerReorder\fP \(em Container widget function to reorder children
.iX "XmContainerReorder"
.iX "XmContainer"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Container\&.h>
\fBvoid \fBXmContainerReorder\fP\fR(
\fBWidget \fBcontainer\fR\fR,
\fBWidgetList \fBwidgets\fR\fR,
\fBint \fBnum_widgets\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmContainerReorder\fP obtains the \fBXmNpositionIndex\fP constraint
resources of each widget specified in \fIwidgets\fP, sorts them in
ascending order, and inserts the \fBXmNpositionIndex\fP constraint
resources in the new order into each widget\&.
If the \fBXmNlayoutType\fP resource of Container is \fBXmOUTLINE\fP or
\fBXmDETAIL\fP, \fBXmContainerReorder\fP will force a layout of all
items\&.
.IP "\fIcontainer\fP" 10
Specifies the Container widget ID\&.
.IP "\fIwidgets\fP" 10
Specifies an array of widget children of \fIcontainer\fP\&.
.IP "\fInum_widgets\fP" 10
Specifies the number of items in the \fIwidgets\fP array\&.
.PP
For a complete definition of Container and its associated resources, see
\fBXmContainer\fP(3)\&.
.SH "RELATED"
.PP
\fBXmContainer\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
