'\" t
...\" CreMeC.sgm /main/8 1996/09/08 20:33:44 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmCreateMessageBox" "library call"
.SH "NAME"
\fBXmCreateMessageBox\fP \(em The MessageBox widget creation function
.iX "XmCreateMessageBox"
.iX "creation functions" "XmCreateMessageBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MessageB\&.h>
\fBWidget \fBXmCreateMessageBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCreateMessageBox\fP creates an unmanaged MessageBox\&.
A MessageBox is used for common interaction tasks, which include giving
information, asking questions, and reporting errors\&.
It includes an optional symbol, a message, and three buttons\&.
.PP
By default, there is no symbol\&. The default button labels are \fBOK\fP,
\fBCancel\fP, and \fBHelp\fP\&.
.PP
If the parent of the MessageBox is a DialogShell, use \fBXtManageChild\fP to
pop up the MessageBox (passing the MessageBox as the widget parameter); use
\fBXtUnmanageChild\fP to pop it down\&.
.IP "\fIparent\fP" 10
Specifies the parent widget ID
.IP "\fIname\fP" 10
Specifies the name of the created widget
.IP "\fIarglist\fP" 10
Specifies the argument list
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)
.PP
For a complete definition of MessageBox and its associated resources, see
\fBXmMessageBox\fP(3)\&.
.SH "RETURN"
.PP
Returns the MessageBox widget ID\&.
.SH "RELATED"
.PP
\fBXmMessageBox\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
