'\" t
...\" CvtXmStA.sgm /main/9 1996/09/08 20:38:14 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmCvtXmStringTableToTextProperty" "library call"
.SH "NAME"
\fBXmCvtXmStringTableToTextProperty\fP \(em A function that converts from XmStringTable to an XTextProperty Structure
.iX "XmCvtXmStringTableToTextProperty"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
int XmCvtXmStringTableToTextProperty (\fIdisplay, string_table, count, style, text_prop_return\fP)
        Display *\fIdisplay\fP;
        XmStringTable   \fIstring_table\fP;
        int     \fIcount\fP;
        XmICCEncodingStyle      \fIstyle\fP;
        XTextProperty   *\fItext_prop_return\fP;
\fB\fR(\fBvoid\fR)
.fi
.SH "DESCRIPTION"
.PP
\fBXmCvtXmStringTableToTextProperty\fP converts the \fBXmString\fRs
in the specified \fBXmStringTable\fR into an
\fBXTextProperty\fP structure\&.
.PP
The function sets the encoding member of \fItext_prop_return\fP to an
\fBAtom\fP for the specified display naming the encoding determined by
the specified style, and it converts the first \fIcount\fP compound
strings in the specified \fBXmStringTable\fR to this encoding for
storage in the \fItext_prop_return\fP value member\&. Following are the
possible encoding styles:
.IP "\fBXmSTYLE_COMPOUND_STRING\fP" 10
The encoding is \fB_MOTIF_COMPOUND_STRING\fP\&. The function converts
each specified \fBXmString\fR to a compound string in Byte Stream
format\&.
.IP "\fBXmSTYLE_COMPOUND_TEXT\fP" 10
The encoding is \fBCOMPOUND_TEXT\fP\&. The function converts each
specified \fBXmString\fR to compound text\&.
.IP "\fBXmSTYLE_LOCALE\fP" 10
The encoding is the encoding of the current locale\&. The function
converts each specified \fBXmString\fR to the encoding of the current
locale\&.
.IP "\fBXmSTYLE_STRING\fP" 10
The encoding is \fBSTRING\fP (plain C strings encoded in ISO8859-1), and
the function converts each specified
\fBXmString\fR to \fBSTRING\fP\&.
.IP "\fBXmSTYLE_TEXT\fP" 10
If all specified \fBXmString\fRs are fully convertible to the
encoding of the current locale, the encoding is the encoding of the
current locale, and the function converts each specified
\fBXmString\fR to the encoding of the current locale\&. Otherwise, the
encoding is \fBCOMPOUND_TEXT\fP, and the function converts each
specified compound
string to compound text\&.
.IP "\fBXmSTYLE_STANDARD_ICC_TEXT\fP" 10
If all specified \fBXmString\fRs are fully convertible to \fBSTRING\fP, the
encoding is \fBSTRING\fP, and the function converts each specified
\fBXmString\fR
to \fBSTRING\fP\&. Otherwise, the encoding is \fBCOMPOUND_TEXT\fP, and the
function converts each specified \fBXmString\fR to compound text\&.
.IP "\fIdisplay\fP" 10
Specifies the connection to the X server\&.
.IP "\fIstring_table\fP" 10
Specifies a set of \fBXmString\fRs\&.
.IP "\fIcount\fP" 10
Specifies the number of \fBXmString\fRs to be
converted in \fIstring_table\fP\&.
.IP "\fIstyle\fP" 10
Specifies the manner in which the property is encoded\&.
.IP "\fItext_prop_return\fP" 10
Returns the \fBXTextProperty\fP structure\&.
.PP
To free the storage for the value member of the \fBXTextProperty\fP, use
\fBXtFree\fP\&.
.SH "RETURN VALUES"
.PP
If conversion depends on the locale and the
current locale is not supported, the function returns
\fBXLocaleNotSupported\fP\&. In both of these cases, the function does not set
\fItext_prop_return\fP\&.
.PP
To determine whether the function is guaranteed not to return
\fBXLocaleNotSupported\fP, use \fBXSupportsLocale\fP\&.
.SH "RELATED INFORMATION"
.PP
\fBXmCvtXmStringToByteStream\fP(3),
\fBXmCvtTextPropertyToXmStringTable\fP(3), and
\fBXmStringTable\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
