'\" t
...\" CvtByteS.sgm /main/7 1996/08/30 14:59:48 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmCvtByteStreamToXmString" "library call"
.SH "NAME"
\fBXmCvtByteStreamToXmString\fP \(em A compound string function that converts from a compound string in Byte Stream format to a compound string
.iX "XmCvtByteStreamToXmString"
.iX "compound string functions" "XmCvtByteStreamToXmString"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmString \fBXmCvtByteStreamToXmString\fP\fR(
\fBunsigned char *\fBproperty\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCvtByteStreamToXmString\fP converts a stream of bytes representing a
compound string in Byte Stream format to a compound string\&.
This routine is typically used by the destination of a data transfer
operation to produce a compound string from a transferred Byte Stream
representation\&.
.IP "\fIproperty\fP" 10
Specifies a compound string representation in Byte Stream format\&.
.SH "RETURN"
.PP
Returns a compound string\&.
The function allocates space to hold the returned compound string\&.
The application is responsible for managing this allocated space\&.
The application can recover this allocated space by calling \fBXmStringFree\fP\&.
.SH "RELATED"
.PP
\fBXmString\fP(3),
\fBXmCvtXmStringToByteStream\fP(3), and
\fBXmStringFree\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
