'\" t
...\" DragIcon.sgm /main/9 1996/09/08 20:39:59 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmDragIcon" "library call"
.SH "NAME"
\fBXmDragIcon\fP \(em The DragIcon widget class
.iX "XmDragIcon"
.iX "widget class" "DragIcon"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DragDrop\&.h>
.fi
.SH "DESCRIPTION"
.PP
A DragIcon is a component of the visual used to represent the source
data in a drag and drop transaction\&. During a drag operation, a real
or simulated X cursor provides drag-over visuals consisting of a
static portion that represents the object being dragged, and dynamic
cues that provide visual feedback during the drag operation\&. The
visual is attained by blending together various \fBXmDragIcons\fP
specified in the \fBXmDragContext\fP associated with the drag
operation\&.
.PP
The static portion of the drag-over visual is the graphic
representation that identifies the drag source\&. For example,
when a user drags several items within a list, a DragIcon depicting a
list might be supplied as the visual\&. The \fBXmDragContext\fP
resources, \fBXmNsourceCursorIcon\fP or \fBXmNsourcePixmapIcon\fP,
specify a DragIcon to use for the static portion of the visual\&.
.PP
A drag-over visual incorporates dynamic cues in order to provide
visual feedback in response to the user\&'s actions\&. For instance,
the drag-over visual might use different indicators to identify
the type of operation (copy, link, or move) being performed\&. Dynamic
cues could also alert the user that a drop site is valid or invalid
as the pointer traverses the drop site\&. The \fBXmNoperationCursorIcon\fP
and \fBXmNstateCursorIcon\fP resources of \fBXmDragContext\fP specify
DragIcons for dynamic cues\&.
.PP
A drag-over visual typically consists of a source, operation and
state DragIcon\&. The \fBXmNblendModel\fP resource of \fBXmDragContext\fP
offers several options that determine which icons are blended
to produce the drag-over visual\&. DragIcon resources control
the relative position of the operation and state icons (if used)\&.
If a particular DragIcon is not specified, the toolkit uses the
\fBXmScreen\fP default DragIcons\&.
.PP
An application initializes a DragIcon with the function
\fBXmCreateDragIcon\fP or through entries in the resource
database\&. If a pixmap and its mask (optional) are specified
in the resource database, the toolkit converts the
values in the X11 Bitmap file format and assigns values to
the corresponding resources\&.
.SS "Classes"
.PP
DragIcon inherits behavior and a resource from \fBObject\fP\&.
.PP
The class pointer is \fBxmDragIconObjectClass\fP\&.
.PP
The class name is \fBXmDragIcon\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the
programmer to specify data\&. The programmer can also set the
resource values for the inherited classes to set attributes for
this widget\&. To reference a resource by name or by class in
a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or \fBXmC\fP prefix and use
the remaining letters\&. To specify one of the defined values for a
resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include
any underscores between words)\&. The codes in the access column
indicate if the given resource can be set at creation time (C),
set by using \fBXtSetValues\fP (S), retrieved by using
\fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmDragIcon Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNattachmentXmCAttachmentunsigned charXmATTACH_NORTH_WESTCSG
_____
XmNdepthXmCDepthint1CSG
_____
XmNheightXmCHeightDimension0CSG
_____
XmNhotXXmCHotPosition0CSG
_____
XmNhotYXmCHotPosition0CSG
_____
XmNmaskXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNoffsetXXmCOffsetPosition0CSG
_____
XmNoffsetYXmCOffsetPosition0CSG
_____
XmNpixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNwidthXmCWidthDimension0CSG
_____
.TE
.IP "\fBXmNattachment\fP" 10
Specifies a relative location on the source icon for the attachment of
the state or operation icon\&. The origin of the state and operation
icons is aligned with the specified compass point on the source icon\&.
The \fBXmNoffsetX\fP and \fBXmNoffsetY\fP resources can be used to further
refine the icon positions\&. The possible values are
.RS
.IP "\fBXmATTACH_NORTH_WEST\fP" 10
Attaches the origin of the state or operation icon to the northwest
point on the source icon\&.
.IP "\fBXmATTACH_NORTH\fP" 10
Attaches the origin of the state or operation icon to the north
point on the source icon\&.
.IP "\fBXmATTACH_NORTH_EAST\fP" 10
Attaches the origin of the state or operation icon to the northeast
point on the source icon\&.
.IP "\fBXmATTACH_EAST\fP" 10
Attaches the origin of the state or operation icon to the east
point on the source icon\&.
.IP "\fBXmATTACH_SOUTH_EAST\fP" 10
Attaches the origin of the state or operation icon to the southeast
point on the source icon\&.
.IP "\fBXmATTACH_SOUTH\fP" 10
Attaches the origin of the state or operation icon to the south
point on the source icon\&.
.IP "\fBXmATTACH_SOUTH_WEST\fP" 10
Attaches the origin of the state or operation icon to the southwest
point on the source icon\&.
.IP "\fBXmATTACH_WEST\fP" 10
Attaches the origin of the state or operation icon to the west
point on the source icon\&.
.IP "\fBXmATTACH_CENTER\fP" 10
Attaches the origin of the state or operation icon to the
center of the source icon\&. The \fBXmNoffsetX\fP and \fBXmNoffsetY\fP
resources may be used to center the attached icon\&.
.IP "\fBXmATTACH_HOT\fP" 10
Attaches the hotspot coordinates of a state or operation DragIcon to
an x,y position on the source icon\&. The x,y coordinate
is taken from the event passed to the \fBXmDragStart\fP function,
and made relative to the widget passed as an argument to the same
function\&.
.RE
.IP "\fBXmNdepth\fP" 10
Specifies the depth of the pixmap\&.
.IP "\fBXmNheight\fP" 10
Specifies the height of the pixmap\&.
.IP "\fBXmNhotX\fP" 10
Specifies the x-coordinate of the hotspot of a cursor DragIcon
in relation to the origin of the pixmap bounding box\&.
.IP "\fBXmNhotY\fP" 10
Specifies the y-coordinate of the hotspot of a cursor DragIcon
in relation to the origin of the pixmap bounding box\&.
.IP "\fBXmNmask\fP" 10
Specifies a pixmap of depth 1 to use as the DragIcon mask
pixmap\&.
.IP "\fBXmNoffsetX\fP" 10
Specifies a horizontal offset (in pixels) of the origin of the state
or operation icon relative to the attachment point on the source icon\&.
A positive offset value moves the origin to the right; a negative value
moves the origin to the left\&.
.IP "\fBXmNoffsetY\fP" 10
Specifies a vertical offset (in pixels) of the origin of the state or
operation icon relative to the attachment point on the source icon\&. A
positive offset value moves the origin down; a negative value moves the
origin up\&.
.IP "\fBXmNpixmap\fP" 10
Specifies a pixmap to use as the DragIcon pixmap\&.
.IP "\fBXmNwidth\fP" 10
Specifies the width of the pixmap\&.
.SS "Inherited Resources"
.PP
DragIcon inherits behavior and a resource from \fBObject\fP\&.
For a complete description of this resource, refer to the
\fBObject\fP reference page\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBObject Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.SH "RELATED INFORMATION"
.PP
\fBObject\fP(3),
\fBXmCreateDragIcon\fP(3),
\fBXmDisplay\fP(3),
\fBXmDragContext\fP(3),
\fBXmDropSite\fP(3),
\fBXmDropTransfer\fP(3), and
\fBXmScreen\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
