'\" t
...\" FontList.sgm /main/8 1996/09/08 20:43:12 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmFontList" "library call"
.SH "NAME"
\fBXmFontList\fR \(em Data type for a font list
.iX "XmFontList"
.iX "data types" "XmFontList"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
.fi
.SH "DESCRIPTION"
.PP
\fBXmFontList\fR is the data type for a font list\&. A font list
consists of font list entries\&. Each entry contains a font or a
font set (a group of fonts) and is identified with a tag,
which is optional\&. If this tag is
NULL, the tag
is set to \fBXmFONTLIST_DEFAULT_TAG\fP\&.
.PP
The value of
\fBXmFONTLIST_DEFAULT_TAG\fP is \fBXmFONTLIST_DEFAULT_TAG_STRING\fP\&.
.PP
When a compound string is displayed, the font list element tag of the
compound string segment is matched with a font list entry tag in
the font list and the matching font list entry is used to display
the compound string\&. A font list entry is chosen as follows:
.IP "   \(bu" 6
The first font list entry whose tag matches the tag of the compound
string segment is used\&.
.IP "   \(bu" 6
If no match has been found and if the tag of the compound string
segment is \fBXmFONTLIST_DEFAULT_TAG\fP, the first font list
entry whose tag matches the tag that would result from creating
an entry with \fBXmSTRING_DEFAULT_CHARSET\fP is used\&.
For example, if creating an entry with \fBXmSTRING_DEFAULT_CHARSET\fP
would result in the tag \fBISO8859-1\fP, the compound string segment
tag \fBXmFONTLIST_DEFAULT_TAG\fP matches the font list entry tag
\fBISO8859-1\fP\&.
.IP "   \(bu" 6
If no match has been found and if the tag of the compound string
segment matches the tag that would result from creating a segment
with \fBXmSTRING_DEFAULT_CHARSET\fP, the first font list entry
whose tag is \fBXmFONTLIST_DEFAULT_TAG\fP is used\&.
.IP "   \(bu" 6
If no match has been found, the first entry in the font list is
used\&.
.PP
The font list interface consists of the routines listed
in \fBRelated Information\fP\&.
.PP
Font lists are specified in resource files with the following syntax:
.PP
.nf
\fIresource_spec\fP\fB:\fP  \fIfont_entry\fP [, \fIfont_entry\fP ]+
.fi
.PP
The resource value string consists of one or more font list entries
separated by commas\&. Each \fIfont_entry\fP identifies a font or
font set and an optional font list entry tag\&. A tag specified for a
single font follows the font name and is separated
by = (equals sign); otherwise,
in a font set the tag is separated by a colon\&. The colon is required
whether a tag is specified or not\&. A font entry uses the following
syntax to specify a single font:
.PP
.nf
\fIfont_name\fP [ \&'=\&' \fItag\fP ]
.fi
.PP
For example, the following entry specifies a 10 point Times Italic font
without a font list entry tag;
.PP
.nf
\f(CW*fontList:  -Adobe-Times-Medium-I-Normal--10*\fR
.fi
.PP
.PP
A font entry containing a font set is similar, except a semicolon
separates multiple font names and the specification ends with
a colon followed by an optional tag:
.PP
.nf
\fIfont_name\fP [ \&';\&' \fIfont_name\fP ]+ \&':\&' [ \fItag\fP ]
.fi
.PP
A \fIfont_name\fP is an X Logical Font Description (XLFD) string
and \fItag\fP is any set of characters from ISO646IRV except
space, comma, colon, equal sign and semicolon\&. Following is an example of a font
set entry\&. It consists of three fonts (except for charsets),
and an explicit font list entry tag\&.
.PP
.nf
\f(CW*fontList: -Adobe-Courier-Bold-R-Normal--25-180-100-100-M-150;\
-JIS-Fixed-Medium-R-Normal--26-180-100-100-C-240;\
-JIS-Fixed-Medium-R-Normal--26-180-100-100-C-120:MY_TAG\fR
.fi
.PP
.PP
Note that the \fBXmRenderTable\fR is another data type that can be
used for font lists\&. Refer to the \fBXmRenderTable\fP(3) for details\&.
.SH "RELATED"
.PP
\fBXmFontListAdd\fP(3),
\fBXmFontListAppendEntry\fP(3),
\fBXmFontListCopy\fP(3),
\fBXmFontListCreate\fP(3),
\fBXmFontListEntryCreate\fP(3),
\fBXmFontListEntryFree\fP(3),
\fBXmFontListEntryGetFont\fP(3),
\fBXmFontListEntryGetTag\fP(3),
\fBXmFontListEntryLoad\fP(3),
\fBXmFontListFree\fP(3),
\fBXmFontListFreeFontContext\fP(3),
\fBXmFontListGetNextFont\fP(3),
\fBXmFontListInitFontContext\fP(3),
\fBXmFontListNextEntry\fP(3),
\fBXmFontListRemoveEntry\fP(3),
\fBXmRenderTable\fP(3),
and
\fBXmString\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
