'\" t
...\" FontLstW.sgm /main/9 1996/09/08 20:44:51 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmFontListRemoveEntry" "library call"
.SH "NAME"
\fBXmFontListRemoveEntry\fP \(em A font list function that removes a font list entry from a font list
.iX "XmFontListRemoveEntry"
.iX "font list functions" "XmFontListRemoveEntry"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmFontList \fBXmFontListRemoveEntry\fP\fR(
\fBXmFontList \fBoldlist\fR\fR,
\fBXmFontListEntry \fBentry\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmFontListRemoveEntry\fP creates a new font list
that contains the contents of \fIoldlist\fP
minus those entries specified in \fIentry\fP\&.
The routine removes any entries from \fIoldlist\fP
that match the components (tag, type font/font set)
of the specified entry\&. The function deallocates the
original font list after extracting the required
information\&. The caller uses \fBXmFontListEntryFree\fP
to recover memory allocated for the specified entry\&. This
routine does not free the \fBXFontSet\fP or \fBXFontStruct\fP associated
with the font list entry that is removed\&.
.IP "\fIoldlist\fP" 10
Specifies the font list
.IP "\fIentry\fP" 10
Specifies the font list entry to be removed
.SH "RETURN"
.PP
If \fIoldlist\fP is NULL, the function returns NULL\&. If
\fIentry\fP is NULL or no entries are removed, the function
returns \fIoldlist\fP\&. Otherwise, it returns a new font list\&.
If the function returns a new font list, the function allocates
space to hold the new font list\&. The application is responsible
for managing the allocated space\&. The application can recover the
allocated space by calling \fBXmFontListFree\fP\&.
.SH "RELATED"
.PP
\fBXmFontList\fP(3),
\fBXmFontListAppendEntry\fP(3),
\fBXmFontListEntryCreate\fP(3),
\fBXmFontListEntryFree\fP(3),
\fBXmFontListEntryLoad\fP(3), and
\fBXmFontListFree\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
