'\" t
...\" FontLstP.sgm /main/8 1996/09/08 20:44:16 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmFontListEntryLoad" "library call"
.SH "NAME"
\fBXmFontListEntryLoad\fP \(em A font list function that loads
a font or creates a font set and creates an accompanying font list entry
.iX "XmFontListEntryLoad"
.iX "font list functions" "XmFontListEntryLoad"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmFontListEntry \fBXmFontListEntryLoad\fP\fR(
\fBDisplay *\fBdisplay\fR\fR,
\fBchar *\fBfont_name\fR\fR,
\fBXmFontType \fBtype\fR\fR,
\fBchar *\fBtag\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmFontListEntryLoad\fP loads a font or creates a font set
based on the value of the \fItype\fP argument\&. It creates and returns
a font list entry that contains the font or font set and the
specified tag\&.
.PP
If the value of \fItype\fP is \fBXmFONT_IS_FONT\fP, the function uses
the \fBXtCvtStringToFontStruct\fP routine to convert the value of
\fIfont_name\fP to a font struct\&.
If the value of \fItype\fP is \fBXmFONT_IS_FONTSET\fP, the function uses
the \fBXtCvtStringToFontSet\fP converter to create a font set in the
current locale\&.
\fBXmFontListEntryLoad\fP creates a font list entry that contains the
font or font set derived from the converter\&.
For more information about \fBXtCvtStringToFontStruct\fP and
\fBXtCvtStringToFontSet\fP, see \fIX Toolkit Intrinsics\(emC Language
Interface\&.\fP
.PP
.IP "\fIdisplay\fP" 10
Specifies the display where the font list will be used\&.
.IP "\fIfont_name\fP" 10
Specifies an X Logical Font Description (XLFD) string,
which is interpreted either as a font name or as a base font name
list\&.
A base font name list is a comma-separated and NULL-terminated string\&.
.IP "\fItype\fP" 10
Specifies whether the \fIfont_name\fP argument refers to a font name or
to a base font name list\&.
Valid values are \fBXmFONT_IS_FONT\fP and \fBXmFONT_IS_FONTSET\fP\&.
.IP "\fItag\fP" 10
Specifies the tag of the font list entry to be created\&.
The tag may be specified as \fBXmFONTLIST_DEFAULT_TAG\fP,
which is used to identify the default font list
element in a font list when specified as part of a resource\&.
.SH "RETURN"
.PP
If the specified font is not found, or if the specified font
set cannot be created, then either an implementation-defined font will
be opened or a font set will be created, and a warning messge will be
generated\&. If no suitable font can be found or a font set cannot be created,
then another message will be generated and the function will return
NULL; otherwise the function returns a font list entry\&.
If the function returns a font list entry, the function allocates space
to hold the font list entry\&. The application is responsible for managing
the allocated space\&. The application can recover the allocated space by
calling \fBXmFontListEntryFree\fP\&.
.SH "RELATED"
.PP
\fBXmFontList\fP(3),
\fBXmFontListAppendEntry\fP(3),
\fBXmFontListEntryCreate\fP(3),
\fBXmFontListEntryFree\fP(3),
\fBXmFontListEntryGetFont\fP(3),
\fBXmFontListEntryGetTag\fP(3), and
\fBXmFontListRemoveEntry\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
