'\" t
...\" Form.sgm /main/9 1996/09/08 20:45:00 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmForm" "library call"
.SH "NAME"
\fBXmForm\fP \(em The Form widget class
.iX "XmForm"
.iX "widget class" "Form"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Form\&.h>
.fi
.SH "DESCRIPTION"
.PP
Form is a container widget with no input semantics of its own\&.
Constraints are placed on children of the Form to define attachments
for each of the child\&'s four sides\&.
These attachments can be to the Form, to another child widget or gadget,
to a relative position within the Form, or to the initial position of
the child\&.
The attachments determine the layout behavior of the Form when resizing
occurs\&.
.PP
The default value for \fBXmNinitialFocus\fP is the value of
\fBXmNdefaultButton\fP\&.
.PP
Following are some important considerations in using a Form:
.IP "   \(bu" 6
Every child must have an attachment on either the left or the right\&.
If initialization or \fBXtSetValues\fP leaves a widget without
such an attachment, the result depends upon the value of
\fBXmNrubberPositioning\fP\&.
.IP "" 10
If \fBXmNrubberPositioning\fP is False, the child is given an
\fBXmNleftAttachment\fP of \fBXmATTACH_FORM\fP and an
\fBXmNleftOffset\fP equal to its current \fIx\fP value\&.
.IP "" 10
If \fBXmNrubberPositioning\fP is True, the child is given an
\fBXmNleftAttachment\fP of \fBXmATTACH_POSITION\fP and an
\fBXmNleftPosition\fP proportional to the current \fIx\fP value divided
by the width of the Form\&.
.IP "" 10
In either case, if the child has not been previously given an \fIx\fP
value, its \fIx\fP value is taken to be 0 (zero), which places the child at the
left side of the Form\&.
.IP "   \(bu" 6
If you want to create a child without any attachments, and then
later (for example, after creating and managing it, but before realizing it)
give it a right attachment through \fBXtSetValues\fP, you must set its
\fBXmNleftAttachment\fP to \fBXmATTACH_NONE\fP at the same time\&.
.IP "   \(bu" 6
The \fBXmNresizable\fP resource controls only whether a geometry request
by the child will be granted\&.
It has no effect on whether the child\&'s size can be changed because of
changes in geometry of the Form or of other children\&.
.IP "   \(bu" 6
Every child has a preferred width, based on geometry requests it
makes (whether they are granted or not)\&.
.IP "   \(bu" 6
If a child has attachments on both the left and the right sides,
its size is completely controlled by the Form\&.
It can be shrunk below its preferred width or enlarged above it, if
necessary, due to other constraints\&.
In addition, the child\&'s geometry requests to change its own width may
be refused\&.
.IP "   \(bu" 6
If a child has attachments on only its left or right side, it will
always be at its preferred width (if resizable, otherwise at is current
width)\&.
This may cause it to be clipped by the Form or by other children\&.
.IP "   \(bu" 6
If a child\&'s left (or right) attachment is set to \fBXmATTACH_SELF\fP, its
corresponding left (or right) offset is forced to 0 (zero)\&.
The attachment is then changed to \fBXmATTACH_POSITION\fP, with a
position that corresponds to the \fIx\fP value of the child\&'s left (or
right) edge\&.
To fix the position of a side at a specific \fIx\fP value, use
\fBXmATTACH_FORM\fP or \fBXmATTACH_OPPOSITE_FORM\fP with the \fIx\fP
value as the left (or right) offset\&.
.IP "   \(bu" 6
Unmapping a child has no effect on the Form except that the child
is not mapped\&.
.IP "   \(bu" 6
Unmanaging a child unmaps it\&.
If no other child is attached to it, or if all children attached to it
and all children recursively attached to them are also all unmanaged,
all of those children are treated as if they did not exist in
determining the size of the Form\&.
.IP "   \(bu" 6
When using \fBXtSetValues\fP to change the \fBXmNx\fP resource of a
child, you must simultaneously set its left attachment to either
\fBXmATTACH_SELF\fP or \fBXmATTACH_NONE\fP\&.
Otherwise, the request is not granted\&.
If \fBXmNresizable\fP is False, the request is granted only if the
child\&'s size can remain the same\&.
.IP "   \(bu" 6
A left (or right) attachment of \fBXmATTACH_WIDGET\fP, where
\fBXmNleftWidget\fP (or \fBXmNrightWidget\fP) is NULL, acts like an
attachment of \fBXmATTACH_FORM\fP\&.
.IP "   \(bu" 6
If an attachment is made to a widget that is not a child of the
Form, but an ancestor of the widget is a child of the Form, the
attachment is made to the ancestor\&.
.PP
All these considerations are true of top and bottom attachments as well,
with top acting like left, bottom acting like right, \fIy\fP acting like
\fIx\fP, and height acting like width\&.
.SS "Classes"
.PP
Form inherits behavior, resources, and traits from \fBCore\fP,
\fBComposite\fP, \fBConstraint\fP,
\fBXmManager\fP, and \fBXmBulletinBoard\fP\&.
.PP
The class pointer is \fBxmFormWidgetClass\fP\&.
.PP
The class name is \fBXmForm\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the
programmer to specify data\&. The programmer can also set the resource
values for the inherited classes to set attributes for this widget\&.
To reference a resource by name or by class in a \fB\&.Xdefaults\fP file,
remove the \fBXmN\fP or \fBXmC\fP prefix and use the remaining letters\&.
To specify one of the defined values for a resource in a \fB\&.Xdefaults\fP
file, remove the \fBXm\fP prefix and use the remaining letters (in
either lowercase or uppercase, but include any underscores between
words)\&. The codes in the access column indicate if the given resource
can be set at creation time (C), set by using \fBXtSetValues\fP
(S), retrieved by using \fBXtGetValues\fP (G), or is not
applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmForm Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNfractionBaseXmCMaxValueint100CSG
_____
XmNhorizontalSpacingXmCSpacingDimension0CSG
_____
XmNrubberPositioningXmCRubberPositioningBooleanFalseCSG
_____
XmNverticalSpacingXmCSpacingDimension0CSG
_____
.TE
.IP "\fBXmNfractionBase\fP" 10
Specifies the denominator used in calculating the relative position of
a child widget using \fBXmATTACH_POSITION\fP constraints\&.
The value must not be 0 (zero)\&.
.IP "" 10
If the value of a child\&'s \fBXmNleftAttachment\fP (or
\fBXmNrightAttachment\fP) is \fBXmATTACH_POSITION\fP, the position of
the left (or right) side of the child is relative to the left
side of the Form and is a fraction of the width of the Form\&.
This fraction is the value of the child\&'s \fBXmNleftPosition\fP (or
\fBXmNrightPosition\fP) resource divided by the value of the Form\&'s
\fBXmNfractionBase\fP\&.
.IP "" 10
If the value of a child\&'s \fBXmNtopAttachment\fP (or
\fBXmNbottomAttachment\fP) is \fBXmATTACH_POSITION\fP, the position of
the top (or bottom) side of the child is relative to the top
side
of the Form and is a fraction of the height of the Form\&.
This fraction is the value of the child\&'s \fBXmNtopPosition\fP (or
\fBXmNbottomPosition\fP) resource divided by the value of the Form\&'s
\fBXmNfractionBase\fP\&.
.IP "\fBXmNhorizontalSpacing\fP" 10
Specifies the offset for right and left attachments\&. This resource is
only used if no offset resource is specified (when attaching to a
widget), or if no margin resource is specified (when attaching
to the Form)\&.
.IP "\fBXmNrubberPositioning\fP" 10
Indicates the default near (left) and top attachments for a child of the
Form\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP\&.)
.IP "" 10
The default left attachment is applied whenever initialization or
\fBXtSetValues\fP leaves the child without either a left or right
attachment\&.
The default top attachment is applied whenever initialization or
\fBXtSetValues\fP leaves the child without either a top or bottom
attachment\&.
.IP "" 10
If this Boolean resource is set to False, \fBXmNleftAttachment\fP and
\fBXmNtopAttachment\fP default to \fBXmATTACH_FORM\fP,
\fBXmNleftOffset\fP defaults to the current \fIx\fP value of the left
side of the child,
and \fBXmNtopOffset\fP defaults to the current
\fIy\fP value of the child\&.
The effect is to position the child according to its absolute distance
from the left or top side of the Form\&.
.IP "" 10
If this resource is set to True, \fBXmNleftAttachment\fP and
\fBXmNtopAttachment\fP default to \fBXmATTACH_POSITION\fP,
\fBXmNleftPosition\fP defaults to a value proportional to the current
\fIx\fP value of the left side of the child divided by the width of the
Form, and \fBXmNtopPosition\fP defaults to a value proportional to the
current \fIy\fP value of the child divided by the height of the Form\&.
The effect is to position the child relative to the left or top
side of the Form and in proportion to the width or height of the Form\&.
.IP "\fBXmNverticalSpacing\fP" 10
Specifies the offset for top and bottom attachments\&. This resource is
only used if no offset resource is specified (when attaching to a
widget), or if no margin resource is specified (when attaching
to the Form)\&.
.IP "" 10
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmForm Constraint Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomAttachmentXmCAttachmentunsigned charXmATTACH_NONECSG
_____
XmNbottomOffsetXmCOffsetint0CSG
_____
XmNbottomPositionXmCPositionint0CSG
_____
XmNbottomWidgetXmCWidgetWidgetNULLCSG
_____
XmNleftAttachmentXmCAttachmentunsigned charXmATTACH_NONECSG
_____
XmNleftOffsetXmCOffsetint0CSG
_____
XmNleftPositionXmCPositionint0CSG
_____
XmNleftWidgetXmCWidgetWidgetNULLCSG
_____
XmNresizableXmCBooleanBooleanTrueCSG
_____
XmNrightAttachmentXmCAttachmentunsigned charXmATTACH_NONECSG
_____
XmNrightOffsetXmCOffsetint0CSG
_____
XmNrightPositionXmCPositionint0CSG
_____
XmNrightWidgetXmCWidgetWidgetNULLCSG
_____
XmNtopAttachmentXmCAttachmentunsigned charXmATTACH_NONECSG
_____
XmNtopOffsetXmCOffsetint0CSG
_____
XmNtopPositionXmCPositionint0CSG
_____
XmNtopWidgetXmCWidgetWidgetNULLCSG
_____
.TE
.IP "\fBXmNbottomAttachment\fP" 10
Specifies attachment of the bottom side of the child\&. It can have the
following values:
.RS
.IP "\fBXmATTACH_NONE\fP" 10
Do not attach the bottom side of the child\&.
.IP "\fBXmATTACH_FORM\fP" 10
Attach the bottom side of the child to the bottom
side of the Form\&.
.IP "\fBXmATTACH_OPPOSITE_FORM\fP" 10
Attach the bottom side of the child to
the top side of the Form\&.
\fBXmNbottomOffset\fP can be used to determine the visibility of the
child\&.
.IP "\fBXmATTACH_WIDGET\fP" 10
Attach the bottom side of the child to the top
side of the widget or
gadget specified in the \fBXmNbottomWidget\fP resource\&.
If \fBXmNbottomWidget\fP is NULL, \fBXmATTACH_WIDGET\fP is replaced by
\fBXmATTACH_FORM\fP, and the child is attached to the bottom side of the
Form\&.
.IP "\fBXmATTACH_OPPOSITE_WIDGET\fP" 10
Attach the bottom side of the child to
the bottom side of the widget or
gadget specified in the \fBXmNbottomWidget\fP resource\&.
.IP "\fBXmATTACH_POSITION\fP" 10
Attach the bottom side of the child to a
position that is relative to
the top side of the Form and in proportion to the height of the Form\&.
This position is determined by the \fBXmNbottomPosition\fP and
\fBXmNfractionBase\fP resources\&.
.IP "\fBXmATTACH_SELF\fP" 10
Attach the bottom side of the child to a position
that is proportional
to the current \fIy\fP value of the bottom of the child divided by the
height of the Form\&.
This position is determined by the \fBXmNbottomPosition\fP and
\fBXmNfractionBase\fP resources\&.
\fBXmNbottomPosition\fP is set to a value proportional to the current
\fIy\fP value of the bottom of the child divided by the height of the
Form\&.
.RE
.IP "\fBXmNbottomOffset\fP" 10
Specifies the constant offset between the bottom side of the
child and the object to which it is
attached\&.
The relationship established remains, regardless of any resizing operations
that occur\&.
When this resource is explicitly set, the value of \fBXmNverticalSpacing\fP
is ignored\&.
.IP "\fBXmNbottomPosition\fP" 10
This resource is used to determine the position of the bottom side of
the child when the child\&'s \fBXmNbottomAttachment\fP is set to
\fBXmATTACH_POSITION\fP\&.
In this case the position of the bottom side of the child is relative to
the top side of the Form and is a fraction of the height of the Form\&.
This fraction is the value of the child\&'s \fBXmNbottomPosition\fP
resource divided by the value of the Form\&'s \fBXmNfractionBase\fP\&.
For example, if the child\&'s \fBXmNbottomPosition\fP is 50, the Form\&'s
\fBXmNfractionBase\fP is 100, and the Form\&'s height is 200, the position
of the bottom side of the child is 100\&.
.IP "\fBXmNbottomWidget\fP" 10
Specifies the widget or gadget to which
the bottom side of the child is attached\&.
This resource is used if the \fBXmNbottomAttachment\fP resource
is set to either \fBXmATTACH_WIDGET\fP
or \fBXmATTACH_OPPOSITE_WIDGET\fP\&.
.IP "" 10
A string-to-widget resource converter is automatically installed for use
with this resource\&.
With this converter, the widget that is to be the value of the resource
must exist at the time the widget that has the resource is created\&.
.IP "\fBXmNleftAttachment\fP" 10
Specifies attachment of the near (left) side of the child\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
It can have the following values:
.RS
.IP "\fBXmATTACH_NONE\fP" 10
Do not attach the left side of the child\&.
If \fBXmNrightAttachment\fP is also \fBXmATTACH_NONE\fP, this value is
ignored and the child is given a default left attachment\&.
.IP "\fBXmATTACH_FORM\fP" 10
Attach the left side of the child to the left
side of the Form\&.
.IP "\fBXmATTACH_OPPOSITE_FORM\fP" 10
Attach the left side of the child to the
right side of the Form\&.
\fBXmNleftOffset\fP can be used to determine the visibility of the
child\&.
.IP "\fBXmATTACH_WIDGET\fP" 10
Attach the left side of the child to the right
side of the widget or
gadget specified in the \fBXmNleftWidget\fP resource\&.
If \fBXmNleftWidget\fP is NULL, \fBXmATTACH_WIDGET\fP is replaced by
\fBXmATTACH_FORM\fP, and the child is attached to the left side of the
Form\&.
.IP "\fBXmATTACH_OPPOSITE_WIDGET\fP" 10
Attach the left side of the child to
the left side of the widget or
gadget specified in the \fBXmNleftWidget\fP resource\&.
.IP "\fBXmATTACH_POSITION\fP" 10
Attach the left side of the child to a
position that is relative to
the left side of the Form and in proportion to the width of the Form\&.
This position is determined by the \fBXmNleftPosition\fP and
\fBXmNfractionBase\fP resources\&.
.IP "\fBXmATTACH_SELF\fP" 10
Attach the left side of the child to a position
that is proportional to
the current \fIx\fP value of the left side of the child divided by the
width of the Form\&.
This position is determined by the \fBXmNleftPosition\fP and
\fBXmNfractionBase\fP resources\&.
\fBXmNleftPosition\fP is set to a value proportional to the current
\fIx\fP value of the left side of the child divided by the width of the
Form\&.
.RE
.IP "\fBXmNleftOffset\fP" 10
Specifies the constant offset between the near (left) side of the
child and the object to which it is attached\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
The relationship established remains, regardless of any resizing operations
that occur\&.
When this resource is explicitly set, the value of \fBXmNhorizontalSpacing\fP
is ignored\&.
.IP "\fBXmNleftPosition\fP" 10
This resource is used to determine the position of the near (left) side
of the child when the child\&'s \fBXmNleftAttachment\fP is set to
\fBXmATTACH_POSITION\fP\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
.IP "" 10
In this case, the position of the left side of the child is relative to
the left side of the Form and is a fraction of the width of the Form\&.
This fraction is the value of the child\&'s \fBXmNleftPosition\fP resource
divided by the value of the Form\&'s \fBXmNfractionBase\fP\&.
For example, if the child\&'s \fBXmNleftPosition\fP is 50, the Form\&'s
\fBXmNfractionBase\fP is 100, and the Form\&'s width is 200, the position
of the left side of the child is 100\&.
.IP "\fBXmNleftWidget\fP" 10
Specifies the widget or gadget to which the near (left) side of the
child is attached\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
The \fBXmNleftWidget\fP resource is used if the \fBXmNleftAttachment\fP
resource is set to either \fBXmATTACH_WIDGET\fP
or \fBXmATTACH_OPPOSITE_WIDGET\fP\&.
.IP "" 10
A string-to-widget resource converter is automatically installed for use
with this resource\&.
With this converter, the widget that is to be the value of the resource
must exist at the time the widget that has the resource is created\&.
.IP "\fBXmNresizable\fP" 10
This Boolean resource specifies whether or not a child\&'s request for a
new size is (conditionally) granted by the Form\&.
If this resource is set to True the request is granted if possible\&.
If this resource is set to False the request is always refused\&.
.IP "" 10
If a child has both left and right attachments, its width is completely
controlled by the Form, regardless of the value of the child\&'s
\fBXmNresizable\fP resource\&.
If a child has a left or right attachment but not both, the child\&'s
\fBXmNwidth\fP is used in setting its width if the value of the child\&'s
\fBXmNresizable\fP resource is True\&.
These conditions are also true for top and bottom attachments, with
height acting like width\&.
.IP "\fBXmNrightAttachment\fP" 10
Specifies attachment of the far (right) side of the child\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
It can have the following values:
.RS
.IP "\fBXmATTACH_NONE\fP" 10
Do not attach the right side of the child\&.
.IP "\fBXmATTACH_FORM\fP" 10
Attach the right side of the child to the right
side of the Form\&.
.IP "\fBXmATTACH_OPPOSITE_FORM\fP" 10
Attach the right side of the child to
the left side of the Form\&.
\fBXmNrightOffset\fP can be used to determine the visibility of the
child\&.
.IP "\fBXmATTACH_WIDGET\fP" 10
Attach the right side of the child to the left
side of the widget or
gadget specified in the \fBXmNrightWidget\fP resource\&.
If \fBXmNrightWidget\fP is NULL, \fBXmATTACH_WIDGET\fP is replaced by
\fBXmATTACH_FORM\fP, and the child is attached to the right side of the
Form\&.
.IP "\fBXmATTACH_OPPOSITE_WIDGET\fP" 10
Attach the right side of the child to
the right side of the widget or
gadget specified in the \fBXmNrightWidget\fP resource\&.
.IP "\fBXmATTACH_POSITION\fP" 10
Attach the right side of the child to a
position that is relative to
the left side of the Form and in proportion to the width of the Form\&.
This position is determined by the \fBXmNrightPosition\fP and
\fBXmNfractionBase\fP resources\&.
.IP "\fBXmATTACH_SELF\fP" 10
Attach the right side of the child to a position
that is proportional to
the current \fIx\fP value of the right side of the child divided by the
width of the Form\&.
This position is determined by the \fBXmNrightPosition\fP and
\fBXmNfractionBase\fP resources\&.
\fBXmNrightPosition\fP is set to a value proportional to the current
\fIx\fP value of the right side of the child divided by the width of the
Form\&.
.RE
.IP "\fBXmNrightOffset\fP" 10
Specifies the constant offset between the far (right) side of the
child and the object to which it is attached\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
The relationship established remains, regardless of any resizing operations
that occur\&.
When this resource is explicitly set, the value of \fBXmNhorizontalSpacing\fP
is ignored\&.
.IP "\fBXmNrightPosition\fP" 10
This resource is used to determine the position of the far (right) side
of the child when the child\&'s \fBXmNrightAttachment\fP is set to
\fBXmATTACH_POSITION\fP\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
.IP "" 10
In this case the position of the right side of the child is relative to
the left side of the Form and is a fraction of the width of the Form\&.
This fraction is the value of the child\&'s \fBXmNrightPosition\fP resource
divided by
the value of the Form\&'s \fBXmNfractionBase\fP\&.
For example, if the child\&'s \fBXmNrightPosition\fP is 50, the Form\&'s
\fBXmNfractionBase\fP is 100, and the Form\&'s width is 200, the position
of the right side of the child is 100\&.
.IP "\fBXmNrightWidget\fP" 10
Specifies the widget or gadget
to which the far (right) side of the child is attached\&.
(Note that whether this resource actually applies to the left or
right side of the child and its attachment
depends on the value of
the \fBXmNlayoutDirection\fP resource\&.)
The \fBXmNrightWidget\fP resource is used if the
\fBXmNrightAttachment\fP resource
is set to either \fBXmATTACH_WIDGET\fP
or \fBXmATTACH_OPPOSITE_WIDGET\fP\&.
.IP "" 10
A string-to-widget resource converter is automatically installed for use
with this resource\&.
With this converter, the widget that is to be the value of the resource
must exist at the time the widget that has the resource is created\&.
.IP "\fBXmNtopAttachment\fP" 10
Specifies attachment of the top side of the child\&. It can have
following values:
.RS
.IP "\fBXmATTACH_NONE\fP" 10
Do not attach the top side of the child\&.
If the \fBXmNbottomAttachment\fP resource
is also \fBXmATTACH_NONE\fP, this value is
ignored and the child is given a default top attachment\&.
.IP "\fBXmATTACH_FORM\fP" 10
Attach the top side of the child to the top side
of the Form\&.
.IP "\fBXmATTACH_OPPOSITE_FORM\fP" 10
Attach the top side of the child to the
bottom side of the Form\&.
\fBXmNtopOffset\fP can be used to determine the visibility of the
child\&.
.IP "\fBXmATTACH_WIDGET\fP" 10
Attach the top side of the child to the bottom
side of the widget or
gadget specified in the \fBXmNtopWidget\fP resource\&.
If \fBXmNtopWidget\fP is NULL, \fBXmATTACH_WIDGET\fP is replaced by
\fBXmATTACH_FORM\fP and the child is attached to the top side of the
Form\&.
.IP "\fBXmATTACH_OPPOSITE_WIDGET\fP" 10
Attach the top side of the child to
the top side of the widget or
gadget specified in the \fBXmNtopWidget\fP resource\&.
.IP "\fBXmATTACH_POSITION\fP" 10
Attach the top side of the child to a
position that is relative to
the top side of the Form and in proportion to the height of the Form\&.
This position is determined by the \fBXmNtopPosition\fP and
\fBXmNfractionBase\fP resources\&.
.IP "\fBXmATTACH_SELF\fP" 10
Attach the top side of the child to a position
that is proportional to
the current \fIy\fP value of the child divided by the height of the
Form\&.
This position is determined by the \fBXmNtopPosition\fP and
\fBXmNfractionBase\fP resources\&.
\fBXmNtopPosition\fP is set to a value proportional to the current
\fIy\fP value of the child divided by the height of the Form\&.
.RE
.IP "\fBXmNtopOffset\fP" 10
Specifies the constant offset between the top side of the
child and the object to which it is
attached\&.
The relationship established remains, regardless of any resizing operations
that occur\&.
When this resource is explicitly set, the value of \fBXmNverticalSpacing\fP
is ignored\&.
.IP "\fBXmNtopPosition\fP" 10
This resource is used to determine the position of the top side of
the child when the child\&'s \fBXmNtopAttachment\fP is set to
\fBXmATTACH_POSITION\fP\&.
In this case, the position of the top side of the child is relative to
the top side of the Form and is a fraction of the height of the Form\&.
This fraction is the value of the child\&'s \fBXmNtopPosition\fP
resource divided by the value of the Form\&'s \fBXmNfractionBase\fP\&.
For example, if the child\&'s \fBXmNtopPosition\fP is 50, the Form\&'s
\fBXmNfractionBase\fP is 100, and the Form\&'s height is 200, the position
of the top side of the child is 100\&.
.IP "\fBXmNtopWidget\fP" 10
Specifies the widget or gadget to which the top
side of the child is attached\&.
This resource is used if \fBXmNtopAttachment\fP is
set to a value of either \fBXmATTACH_WIDGET\fP
or \fBXmATTACH_OPPOSITE_WIDGET\fP\&.
.IP "" 10
A string-to-widget resource converter is automatically installed for use
with this resource\&.
With this converter, the widget that is to be the value of the resource
must exist at the time the widget that has the resource is created\&.
.SS "Inherited Resources"
.PP
Form inherits behavior and resources from the
superclasses described in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmBulletinBoard Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNallowOverlapXmCAllowOverlapBooleanTrueCSG
_____
XmNautoUnmanageXmCAutoUnmanageBooleanTrueCG
_____
XmNbuttonFontListXmCButtonFontListXmFontListdynamicCSG
_____
XmNbuttonRenderTableXmCButtonRenderTableXmRenderTabledynamicCSG
_____
XmNcancelButtonXmCWidgetWidgetNULLSG
_____
XmNdefaultButtonXmCWidgetWidgetNULLSG
_____
XmNdefaultPositionXmCDefaultPositionBooleanTrueCSG
_____
XmNdialogStyleXmCDialogStyleunsigned chardynamicCSG
_____
XmNdialogTitleXmCDialogTitleXmStringNULLCSG
_____
XmNfocusCallbackXmCCallbackXtCallbackListNULLC
_____
XmNlabelFontListXmCLabelFontListXmFontListdynamicCSG
_____
XmNlabelRenderTableXmCLabelRenderTableXmRenderTabledynamicCSG
_____
XmNmapCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmarginHeightXmCMarginHeightDimension0CSG
_____
XmNmarginWidthXmCMarginWidthDimension0CSG
_____
XmNnoResizeXmCNoResizeBooleanFalseCSG
_____
XmNresizePolicyXmCResizePolicyunsigned charXmRESIZE_ANYCSG
_____
XmNshadowTypeXmCShadowTypeunsigned charXmSHADOW_OUTCSG
_____
XmNtextFontListXmCTextFontListXmFontListdynamicCSG
_____
XmNtextRenderTableXmCTextRenderTableXmRenderTabledynamicCSG
_____
XmNtextTranslationsXmCTranslationsXtTranslationsNULLC
_____
XmNunmapCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetdynamicCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmTAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimensiondynamicCSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicN/A
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Translations"
.PP
XmForm inherits translations from XmBulletinBoard\&.
.SH "RELATED"
.PP
\fBComposite\fP(3), \fBConstraint\fP(3), \fBCore\fP(3),
\fBXmBulletinBoard\fP(3),
\fBXmCreateForm\fP, \fBXmCreateFormDialog\fP(3), and
\fBXmManager\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
