'\" t
...\" Frame.sgm /main/9 1996/09/08 20:45:11 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmFrame" "library call"
.SH "NAME"
\fBXmFrame\fP \(em The Frame widget class
.iX "XmFrame"
.iX "widget class" "Frame"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Frame\&.h>
.fi
.SH "DESCRIPTION"
.PP
Frame is a very simple manager used to enclose a single work
area child in a border drawn by Frame\&.
It uses the Manager class resources for border drawing and performs
geometry management so that its size always matches its child\&'s outer size
plus the Frame\&'s margins and shadow thickness\&.
.PP
Frame is most often used to enclose other managers when the
application developer wants the manager to have the same border
appearance as the primitive widgets\&. Frame can also be
used to enclose primitive widgets that do not support the same
type of border drawing\&. This gives visual consistency when
you develop applications using diverse widget sets\&.
Constraint resources are used to designate a child as the Frame title,
align its text, and control its vertical alignment in relation to
Frame\&'s top shadow\&. The title appears only at the top of the Frame\&.
.PP
If the Frame\&'s parent is a Shell widget,
the \fBXmNshadowType\fP resource defaults to \fBXmSHADOW_OUT\fP, and
the Manager\&'s \fBXmNshadowThickness\fP resource defaults to 1\&.
.PP
If the Frame\&'s parent is not a Shell widget,
the \fBXmNshadowType\fP resouce defaults to \fBXmSHADOW_ETCHED_IN\fP, and
the Manager\&'s \fBXmNshadowThickness\fP resource defaults to 2\&.
.SS "Classes"
.PP
Frame inherits behavior and
resources from the \fBCore\fP, \fBComposite\fP,
\fBConstraint\fP, and \fBXmManager\fP classes\&.
.PP
The class pointer is \fBxmFrameWidgetClass\fP\&.
.PP
The class name is \fBXmFrame\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file,
remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmFrame Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNmarginWidthXmCMarginWidthDimension0CSG
_____
XmNmarginHeightXmCMarginHeightDimension0CSG
_____
XmNshadowTypeXmCShadowTypeunsigned chardynamicCSG
_____
.TE
.IP "\fBXmNmarginWidth\fP" 10
Specifies the padding space on the left and right
sides between Frame\&'s child and Frame\&'s shadow drawing\&.
.IP "\fBXmNmarginHeight\fP" 10
Specifies the padding space on the top and bottom
sides between Frame\&'s child and Frame\&'s shadow drawing\&.
When a title is present, the top margin equals the value
specified by this resource plus the distance (if any) that the
title extends below the top shadow\&.
.IP "\fBXmNshadowType\fP" 10
Describes the drawing style for Frame\&. This resource can have the
following values:
.RS
.IP "\fBXmSHADOW_IN\fP" 10
Draws Frame so that it appears inset\&.
This means that the bottom shadow visuals and top shadow visuals
are reversed\&.
.IP "\fBXmSHADOW_OUT\fP" 10
Draws Frame so that it appears outset\&.
This is the default if Frame\&'s parent is a Shell widget\&.
.IP "\fBXmSHADOW_ETCHED_IN\fP" 10
Draws Frame using a double line giving the
effect of a line etched into the window\&. The thickness of the double
line is equal to the value of \fBXmNshadowThickness\fP\&.
This is the default when Frame\&'s parent is not a Shell widget\&.
.IP "\fBXmSHADOW_ETCHED_OUT\fP" 10
Draws Frame using a double line giving the
effect of a line coming out of the window\&. The thickness of the double
line is equal to the value of \fBXmNshadowThickness\fP\&.
.RE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmFrame Constraint Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildTypeXmCChildTypeunsigned charXmFRAME_WORKAREA_CHILDCSG
_____
XmNchildHorizontalAlignmentXmCChildHorizontalAlignmentunsigned charXmALIGNMENT_BEGINNINGCSG
_____
XmNchildHorizontalSpacingXmCChildHorizontalSpacingDimensiondynamicCSG
_____
XmNchildVerticalAlignmentXmCChildVerticalAlignmentunsigned charXmALIGNMENT_CENTERCSG
_____
XmNframeChildTypeXmCFrameChildTypeunsigned charXmFRAME_WORKAREA_CHILDCSG
_____
.TE
.IP "\fBXmNchildType\fP" 10
Refer to the \fBXmNframeChildType\fP resource description\&. The
\fBXmNchildType\fP resource is obsoleted by \fBXmNframeChildType\fP,
but is kept here for backward compatibility\&.
.IP "\fBXmNchildHorizontalAlignment\fP" 10
Specifies the alignment of the title\&. This resource has the
following values:
.RS
.IP "   \(bu" 6
\fBXmALIGNMENT_BEGINNING\fP
.IP "   \(bu" 6
\fBXmALIGNMENT_CENTER\fP
.IP "   \(bu" 6
\fBXmALIGNMENT_END\fP
.RE
.IP "" 10
See the description of \fBXmNalignment\fP in the \fBXmLabel\fP
reference page for an explanation of these values\&.
.IP "\fBXmNchildHorizontalSpacing\fP" 10
Specifies the minimum distance between either edge of the title text
and the inner edge of the Frame shadow\&. Clipping of the title
text occurs in order to maintain this spacing\&. The default value
is the margin width of the Frame\&.
.IP "\fBXmNchildVerticalAlignment\fP" 10
Specifies the vertical alignment of the title text, or the title
area in relation to the top shadow of the Frame\&.
.RS
.IP "\fBXmALIGNMENT_BASELINE_BOTTOM\fP" 10
Causes the baseline of the
title to align vertically with the
top shadow of the Frame\&. In the case of a multi-line title,
the baseline of the last line of text aligns vertically with
the top shadow of the Frame\&.
.IP "\fBXmALIGNMENT_BASELINE_TOP\fP" 10
Causes the baseline of the first
line of the title to align vertically with the top shadow
of the Frame\&.
.IP "\fBXmALIGNMENT_CHILD_TOP\fP" 10
Causes the top edge of the title
area to align vertically with the top shadow of the Frame\&.
.IP "\fBXmALIGNMENT_CENTER\fP" 10
Causes the center of the title
area to align vertically with the top shadow of the Frame\&.
.IP "\fBXmALIGNMENT_CHILD_BOTTOM\fP" 10
Causes the bottom edge of the title
area to align vertically with the top shadow of the Frame\&.
.RE
.IP "\fBXmNframeChildType\fP" 10
Specifies whether a child is a title or work area\&. Frame supports
a single title and/or work area child\&. The possible
values are
.RS
.IP "   \(bu" 6
\fBXmFRAME_TITLE_CHILD\fP
.IP "   \(bu" 6
\fBXmFRAME_WORKAREA_CHILD\fP
.IP "   \(bu" 6
\fBXmFRAME_GENERIC_CHILD\fP
.RE
.IP "" 10
The Frame geometry manager ignores any child of type
\fBXmFRAME_GENERIC_CHILD\fP\&.
This resource replaces
\fBXmNchildType\fP\&.
.SS "Inherited Resources"
.PP
Frame inherits behavior and resources from the following
superclasses\&. For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetNULLCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmTAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimensiondynamicCSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Translations"
.PP
XmFrame inherits translations from XmManager\&.
.SH "RELATED"
.PP
\fBComposite\fP(3),
\fBConstraint\fP(3),
\fBCore\fP(3),
\fBXmCreateFrame\fP(3), and
\fBXmManager\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
