'\" t
...\" ImSetVal.sgm /main/13 1996/09/08 20:48:16 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmImSetValues" "library call"
.SH "NAME"
\fBXmImSetValues\fP \(em An input manager function that updates attributes of
an input context
.iX "XmImSetValues"
.iX "input manager functions" "XmImSetValues"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/XmIm\&.h>
\fBvoid \fBXmImSetValues\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR,
\fB\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmImSetValues\fP updates attributes of the input context associated with
the specified widget\&. The \fIarglist\fP argument is a list of
attribute/value pairs for the input context\&. This function passes the
attributes and values to \fBXICSetValues\fP\&. The initial call to
this routine should pass in all of the input context attributes\&.
Thereafter, the application programmer calls \fBXmImSetValues\fP, for
an XIC,
only if a value has changed\&.
.PP
If the previous parameters for the widget\&'s XIC do not allow
the previously registered XIC to be reused, that XIC will be
unregistered, and a new one will be created and registered with the
widget\&. Note that sharing of data is preserved\&.
.PP
Note that the Text and TextField widgets call the
\fBXmImSetValues\fP function when they receive focus\&. Therefore,
further calls to the \fBXmImSetValues\fP function for these
widgets are unnecessary\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the widget registered with the input manager
.IP "\fIarglist\fP" 10
Specifies the list of attribute/value pairs to be passed to \fBXICSetValues\fP;
the following attributes are accepted:
\fBXmNpreeditStartCallback\fP
\fBXmNpreeditDoneCallback\fP
\fBXmNpreeditDrawCallback\fP
and
\fBXmNpreeditCaretCallback\fP\&. These attributes accept an accompanying
value of type pointer
to structure of type \fBXIMCallback\fP\&.
.IP "" 10
These callbacks are used only when the \fBXmNpreeditType\fP
resource of the relevant \fBVendorShell\fP has the "onthespot" value,
and that the XIM supports \fBXIMPreeditCallbacks\fP input style\&. These
values are ignored if the condition is not met\&.
.IP "" 10
For each of these callbacks, if the callback value is not set by this
function, no action will be taken when the Input Method tries to call this callback\&.
Refer to the "Xlib - C Language X Interface, X Version 11, Release 6,"
Chapter 13 for the detail of these callbacks\&.
.IP "\fIargcount\fP" 10
Specifies the number of attribute/values pairs in the argument
list (\fIarglist)\fP
.PP
Resources that can be set for the input context include:
.IP "\fBXmNbackground\fP" 10
Specifies the pixel value for the background color\&.
.IP "\fBXmNbackgroundPixmap\fP" 10
Specifies a pixmap for tiling the background\&.
.IP "\fBXmNfontList\fP" 10
Specifies the font list used by the widget\&. The input method
uses the first occurrence of a font set tagged with
\fBXmFONTLIST_DEFAULT_TAG\fP\&. If no such instance is
found, the first font set in the font list is used\&. If
the font list does not contain a font set, a value is not
passed to \fBXICSetValues\fP\&.
.IP "\fBXmNforeground\fP" 10
Specifies the pixel value for the foreground color\&.
.IP "\fBXmNlineSpace\fP" 10
Specifies the line spacing used in the pre-edit window\&.
.IP "\fBXmNrenderTable\fP" 10
Specifies the render table used by the widget\&.
.IP "\fBXmNspotLocation\fP" 10
Specifies the \fIx\fP and \fIy\fP coordinates of the position
where text will be inserted in the widget handling
input, whose input method style is \fB"OverTheSpot"\fP\&. The \fIy\fP
coordinate is the position of the baseline used by the current text line\&.
.PP
The caller may also pass any other vendor-defined resources to this
function\&. For additional information on the internationalization
interface, see the Xlib documentation\&.
.SH "RELATED"
.PP
\fBXmImSetFocusValues\fP(3),
\fBXmImVaSetFocusValues\fP(3), and
\fBXmImVaSetValues\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
