'\" t
...\" IsTraver.sgm /main/8 1996/09/08 20:49:25 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmIsTraversable" "library call"
.SH "NAME"
\fBXmIsTraversable\fP \(em A function that identifies whether a widget can
be traversed
.iX "XmIsTraversable"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBBoolean \fBXmIsTraversable\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmIsTraversable\fP determines whether the specified widget is
eligible to receive focus through keyboard traversal\&.
In general, a widget is eligible to receive focus when all of the
following conditions are true:
.IP "   \(bu" 6
The widget and its ancestors are not being destroyed, are sensitive, and
have a value of True for \fBXmNtraversalOn\fP\&.
.IP "   \(bu" 6
The widget and its ancestors are realized, managed, and (except for
gadgets) mapped\&.
If an application unmaps a \fIwidget\fP that has its
\fBXmNmappedWhenManaged\fP resource set to True, the return value
is undefined\&.
.IP "   \(bu" 6
Some part of the widget\&'s rectangular area is unobscured by the widget\&'s
ancestors, or some part of the widget\&'s rectangular area is inside the
work window (but possibly outside the clip window) of a ScrolledWindow
whose \fBXmNscrollingPolicy\fP is \fBXmAUTOMATIC\fP and whose
\fBXmNtraverseObscuredCallback\fP is not NULL\&.
.PP
Some widgets may not be eligible to receive focus even if they meet all
these conditions\&.
For example, most managers cannot receive focus through keyboard traversal\&.
Some widgets may be eligible to receive focus under particular
conditions\&.
For example, a DrawingArea is eligible to receive focus if it meets the
conditions above and has no child whose \fBXmNtraversalOn\fP resource is
True\&.
.PP
Note that when all widgets in a shell hierarchy have been made
untraversable, they are considered to have lost focus\&. When a
widget in this hierarchy is made traversable again, it regains focus\&.
.PP
\fBXmIsTraversable\fP may return unexpected results when \fIwidget\fP
or its ancestors are overlapped by their siblings\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the widget
.SH "RETURN"
.PP
Returns True if the widget is eligible to receive focus through keyboard
traversal; otherwise, returns False\&.
.SH "RELATED"
.PP
\fBXmGetVisibility\fP(3) and \fBXmProcessTraversal\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
