'\" t
...\" LstSeleB.sgm /main/8 1996/09/08 20:52:08 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmListSelectPos" "library call"
.SH "NAME"
\fBXmListSelectPos\fP \(em A List function that selects an item at a specified position in the list
.iX "XmListSelectPos"
.iX "List functions" "XmListSelectPos"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/List\&.h>
\fBvoid \fBXmListSelectPos\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBint \fBposition\fR\fR,
\fBBoolean \fBnotify\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmListSelectPos\fP highlights a List item at the specified position
and adds it to the list of selected items\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the List widget\&.
.IP "\fIposition\fP" 10
Specifies the position of the item to be selected\&.
A value of 1 indicates that the first item in the list is selected; a
value of 2 indicates that the second item is selected; and so on\&.
A value of 0 (zero) indicates that the last item in the list is selected\&.
.IP "\fInotify\fP" 10
Specifies a Boolean value that when TRUE invokes the selection callback
for the current mode\&. From an application interface view, calling this
function with \fInotify\fP True is indistinguishable from a user-initiated
selection action\&.
When \fInotify\fP is FALSE, no callbacks are called\&.
.PP
For a complete definition of List and its associated resources, see
\fBXmList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmList\fP(3) and
\fBXmListSelectItem\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
