'\" t
...\" LstItemP.sgm /main/8 1996/09/08 20:50:50 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmListItemPos" "library call"
.SH "NAME"
\fBXmListItemPos\fP \(em A List function that returns the position of an item in the list
.iX "XmListItemPos"
.iX "List functions" "XmListItemPos"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/List\&.h>
\fBint \fBXmListItemPos\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmString \fBitem\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmListItemPos\fP returns the position of the first
instance of the specified item in a list\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the List widget
.IP "\fIitem\fP" 10
Specifies the item whose position is returned
.PP
For a complete definition of List and its associated resources, see
\fBXmList\fP(3)\&.
.SH "RETURN"
.PP
Returns the position in the list of the first instance of the specified
item\&.
The position of the first item in the list is 1; the position of the
second item is 2; and so on\&.
This function returns 0 (zero) if the item is not found\&.
.SH "RELATED"
.PP
\fBXmList\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
