'\" t
...\" LstSetIt.sgm /main/7 1996/08/30 15:47:18 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmListSetItem" "library call"
.SH "NAME"
\fBXmListSetItem\fP \(em A List function that makes an existing item the first visible item in the list
.iX "XmListSetItem"
.iX "List functions" "XmListSetItem"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/List\&.h>
\fBvoid \fBXmListSetItem\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmString \fBitem\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmListSetItem\fP makes the first item in the list that matches
\fIitem\fP the first visible item in the list\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the List widget from whose list an item is made the
first visible
.IP "\fIitem\fP" 10
Specifies the item
.PP
For a complete definition of List and its associated resources, see
\fBXmList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmList\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
