'\" t
...\" MainWinA.sgm /main/9 1996/09/08 20:52:59 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmMainWindow" "library call"
.SH "NAME"
\fBXmMainWindow\fP \(em The MainWindow widget class
.iX "XmMainWindow"
.iX "widget class" "MainWindow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MainW\&.h>
.fi
.SH "DESCRIPTION"
.PP
MainWindow provides a standard layout for the primary window of an
application\&. This layout includes a MenuBar, a CommandWindow, a work
region, a MessageWindow, and ScrollBars\&. Any or all of these areas are optional\&. The
work region and ScrollBars in the MainWindow behave identically to the work
region and ScrollBars in the ScrolledWindow widget\&. The user can think of
the MainWindow as an extended ScrolledWindow with an optional MenuBar and
optional CommandWindow and MessageWindow\&.
.PP
In a fully loaded MainWindow, the MenuBar spans the top of the window
horizontally\&. The CommandWindow spans the MainWindow horizontally just below
the MenuBar, and the work region lies below the CommandWindow\&.
The MessageWindow is below the work region\&.
Any space remaining below the
MessageWindow is managed in a manner identical to ScrolledWindow\&.
The behavior of ScrolledWindow can be controlled by the ScrolledWindow
resources\&.
To create a MainWindow, first create the
work region elements, a MenuBar, a CommandWindow, a MessageWindow, a
horizontal
ScrollBar, and a vertical ScrollBar widget, and then
call \fBXmMainWindowSetAreas\fP with those widget IDs\&.
.PP
MainWindow
can also create three Separator widgets that provide a visual separation of
MainWindow\&'s four components\&.
The user can specify resources in a resource file for the automatically
created gadgets that contain the MainWindow separators\&. The name of the
first separator gadget is \fBSeparator1\fP; the second is \fBSeparator2\fP;
and the third is \fBSeparator3\fP\&.
.PP
MainWindow also provides the following three child types for layout at
creation time:
.IP "   \(bu" 6
\fBXmMENU_BAR\fP
.IP "   \(bu" 6
\fBXmCOMMAND_WINDOW\fP
.IP "   \(bu" 6
\fBXmMESSAGE_WINDOW\fP
.PP
MainWindow can use these child types
at creation time instead of their associated resource values\&.
MainWindow uses the \fBXmQTmenuSystem\fP trait\&.
.SS "Descendants"
.PP
MainWindow automatically creates the descendants shown in the
following table\&.
An application can use \fBXtNameToWidget\fP to gain access
to the named descendant\&. In addition, a user or an application
can use the named descendant when specifying resource values\&.
.TS
tab() box;
l| l| l.
\fBNamed Descendant\fP\fBClass\fP\fBIdentity\fP
___
=
___
\fBHorScrollBar\fP\fBXmScrollBar\fPhorizontal scroll bar
___
\fBSeparator1\fP\fBXmSeparatorGadget\fPoptional first separator
___
\fBSeparator2\fP\fBXmSeparatorGadget\fPoptional second separator
___
\fBSeparator3\fP\fBXmSeparatorGadget\fPoptional third separator
___
\fBVertScrollBar\fP\fBXmScrollBar\fPvertical scroll bar
___
.TE
.SS "Classes"
.PP
MainWindow inherits behavior and resources from \fBCore\fP,
\fBComposite\fP, \fBConstraint\fP, \fBXmManager\fP,
and
\fBXmScrolledWindow\fP\&.
.PP
The class pointer is \fBxmMainWindowWidgetClass\fP\&.
.PP
The class name is \fBXmMainWindow\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove
the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmMainWindow Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNcommandWindowXmCCommandWindowWidgetNULLCSG
_____
XmNcommandWindowLocationXmCCommandWindowLocationunsigned charABOVE (SeeDesc\&.)CG
_____
XmNmainWindowMarginHeightXmCMainWindowMarginHeightDimension0CSG
_____
XmNmainWindowMarginWidthXmCMainWindowMarginWidthDimension0CSG
_____
XmNmenuBarXmCMenuBarWidgetNULLCSG
_____
XmNmessageWindowXmCMessageWindowWidgetNULLCSG
_____
XmNshowSeparatorXmCShowSeparatorBooleanFalseCSG
_____
.TE
.IP "\fBXmNcommandWindow\fP" 10
Specifies the widget to be laid out as the CommandWindow\&. This widget
must have been previously created and managed as a child of MainWindow\&.
.IP "\fBXmNcommandWindowLocation\fP" 10
Controls the position of the command window\&. \fBXmCOMMAND_ABOVE_WORKSPACE\fP
locates the command window between the menu bar and the work window\&.
\fBXmCOMMAND_BELOW_WORKSPACE\fP locates the command window between the
work window and the message window\&.
.IP "\fBXmNmainWindowMarginHeight\fP" 10
Specifies the margin height on the top and bottom of MainWindow\&. This
resource overrides any setting of the
ScrolledWindow resource
\fBXmNscrolledWindowMarginHeight\fP\&.
.IP "\fBXmNmainWindowMarginWidth\fP" 10
Specifies the margin width on the right and left sides of MainWindow\&. This
resource overrides any setting of the ScrolledWindow resource
\fBXmNscrolledWindowMarginWidth\fP\&.
.IP "\fBXmNmenuBar\fP" 10
Specifies the widget to be laid out as the MenuBar\&. This widget must
have been previously created and managed as a child of MainWindow\&.
.IP "\fBXmNmessageWindow\fP" 10
Specifies the widget to be laid out as the MessageWindow\&. This widget
must have been previously created and managed as a child of MainWindow\&.
The MessageWindow is positioned at the bottom of the MainWindow\&.
If this value is NULL, no message window is included in the MainWindow\&.
.IP "\fBXmNshowSeparator\fP" 10
Displays separators between the components of the MainWindow when set
to True\&. If set to False, no separators are displayed\&.
.SS "Inherited Resources"
.PP
MainWindow inherits behavior and resources from the
superclasses described in the following table\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmScrolledWindow Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNautoDragModelXmCAutoDragModelXtEnumXmAUTO_DRAG_ENABLEDCSG
_____
XmNclipWindowXmCClipWindowWidgetdynamicG
_____
XmNhorizontalScrollBarXmCHorizontalScrollBarWidgetdynamicCSG
_____
XmNscrollBarDisplayPolicyXmCScrollBarDisplayPolicyunsigned chardynamicCSG
_____
XmNscrollBarPlacementXmCScrollBarPlacementunsigned charXmBOTTOM_RIGHTCSG
_____
XmNscrolledWindowMarginHeightXmCScrolledWindowMarginHeightDimension0N/A
_____
XmNscrolledWindowMarginWidthXmCScrolledWindowMarginWidthDimension0N/A
_____
XmNscrollingPolicyXmCScrollingPolicyunsigned charXmAPPLICATION_DEFINEDCG
_____
XmNspacingXmCSpacingDimension4CSG
_____
XmNtraverseObscuredCallbackXmCCallbackXtCallbackListNULLCSG
_____
XmNverticalScrollBarXmCVerticalScrollBarWidgetdynamicCSG
_____
XmNvisualPolicyXmCVisualPolicyunsigned chardynamicG
_____
XmNworkWindowXmCWorkWindowWidgetNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetNULLCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmTAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension0CSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Translations"
.PP
MainWindow inherits translations from ScrolledWindow\&.
.SH "RELATED"
.PP
\fBComposite\fP(3), \fBConstraint\fP(3), \fBCore\fP(3),
\fBXmCreateMainWindow\fP(3),
\fBXmMainWindowSep1\fP(3), \fBXmMainWindowSep2\fP(3),
\fBXmMainWindowSep3\fP(3),
\fBXmMainWindowSetAreas\fP(3),
\fBXmManager\fP(3), and \fBXmScrolledWindow\fP(3)
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
