'\" t
...\" NotebG.sgm /main/7 1996/08/30 15:51:06 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmNotebookGetPageInfo" "library call"
.SH "NAME"
\fBXmNotebookGetPageInfo\fP \(em A Notebook function that returns page information
.iX "XmNotebookGetPageInfo"
.iX "Notebook functions" "XmNotebookGetPageInfo"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Notebook\&.h>
\fBXmNotebookPageStatus \fBXmNotebookGetPageInfo\fP\fR(
\fBWidget \fBnotebook\fR\fR,
\fBint \fBpage_number\fR\fR,
\fBXmNotebookPageInfo \fB*page_info\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmNotebookGetPageInfo\fP returns status information for the specified
Notebook page\&.
.IP "\fInotebook\fP" 10
Specifies the Notebook widget\&.
.IP "\fIpage_number\fP" 10
Specifies the page number to be queried\&.
.IP "\fIpage_info\fP" 10
Points to the structure containing the page information\&. The structure
has the following form:
.PP
.nf
typedef struct
{
        int     \fIpage_number\fP;
        Widget  \fIpage_widget\fP;
        Widget  \fIstatus_area_widget\fP;
        Widget  \fImajor_tab_widget\fP;
        Widget  \fIminor_tab_widget\fP;
} XmNotebookPageInfo;
\fB\fR(\fBvoid\fR)
.fi
.RS
.IP "\fIpage_number\fP" 10
Specifies the \fIpage_number\fP passed to the function\&.
.IP "\fIpage_widget\fP" 10
Specifies a child widget of the Notebook with a \fBXmNchildType\fP of
\fBXmPAGE\fP and a \fBXmNpageNumber\fP equal to \fIpage_number\fP if one
exists; otherwise set to NULL\&.
.IP "\fIstatus_area_widget\fP" 10
Specifies a child widget of the Notebook with a \fBXmNchildType\fP of
\fBXmSTATUS_AREA\fP and a \fBXmNpageNumber\fP equal to \fIpage_number\fP if one
exists; otherwise set to NULL\&.
.IP "\fImajor_tab_widget\fP" 10
Specifies a child widget of the Notebook with a \fBXmNchildType\fP of
\fBXmMAJOR_TAB\fP and the nearest \fBXmNpageNumber\fP
equal to or less than \fIpage_number\fP if one
exists; otherwise set to NULL\&.
.IP "\fIminor_tab_widget\fP" 10
Specifies a child widget of the Notebook with a \fBXmNchildType\fP of
\fBXmMINOR_TAB\fP and the nearest \fBXmNpageNumber\fP
equal to or less than \fIpage_number\fP if one
exists; otherwise set to NULL\&.
.RE
.PP
For a complete definition of Notebook and its associated resources, see
\fBXmNotebook\fP(3)\&.
.SH "RETURN"
.PP
Returns one of the following page status values:
.IP "\fBXmPAGE_FOUND\fP" 10
The specified page was found\&.
.IP "\fBXmPAGE_INVALID\fP" 10
The specified page number is out of the page number range\&.
.IP "\fBXmPAGE_EMPTY\fP" 10
The specified page does not have a page widget\&.
.IP "\fBXmPAGE_DUPLICATED\fP" 10
There is more than one page widget with the specified page number\&. The
more recently managed page widget is used for the page information structure\&.
.SH "RELATED"
.PP
\fBXmNotebook\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
