'\" t
...\" Notebook.sgm /main/11 1996/09/08 20:54:37 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmNotebook" "library call"
.SH "NAME"
\fBXmNotebook\fP \(em The Notebook widget class
.iX "XmNotebook"
.iX "widget class" "Notebook"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Notebook\&.h>
.fi
.SH "DESCRIPTION"
.PP
Notebook is a manager widget that
organizes its children into pages, tabs, status areas, and page scrollers to
simulate a real notebook\&. It stacks its page children so that all page
children occupy the same area like real book pages\&.
Notebook displays visuals that look like the binding of a book and the
edges of other pages around the page that is shown\&.
Tab children simulate
notebook tabs\&. Major tabs divide Notebook into several sections,
and minor tabs subdivide these sections\&. Status area children provide additional
information about pages such as page numbers\&. The page scroller child allows
the user to move from page to page\&. Notebook also provides tab scrollers
for scrolling major and minor tabs if it cannot display all tabs within its
edges\&.
.PP
The application creates pages, tabs, status areas, and page scroller
as children of the Notebook widget\&. Notebook creates tab scrollers
when the Notebook is created\&.
.PP
The \fBXmNnotebookChildType\fP constraint resource
of Notebook determines whether a child widget is a page, tab, status area,
or page scroller\&. Any Motif widget can be a page of the Notebook\&.
When the application creates a child of the Notebook widget without setting
the child type constraint, the child becomes a page by default, unless it has
the \fBXmQTactivatable\fP,
\fBXmQTaccessTextual\fP, or \fBXmQTnavigator\fP trait\&.
Children with the \fBXmQTactivatable\fP,
\fBXmQTaccessTextual\fP, or \fBXmQTnavigator\fP trait become
major tabs, status areas, and page scrollers, respectively\&.
.PP
Notebook uses the \fBXmQTaccessTextual\fP, \fBXmQTactivatable\fP,
\fBXmQTjoinSide\fP, and
\fBXmQTnavigator\fP traits, and installs the \fBXmQTscrollFrame\fP trait\&.
.PP
The application attaches a tab to a page by creating a tab child of the
Notebook and setting the \fBXmNpageNumber\fP constraint to the page number of
the targeted page\&. By the same method, a status area widget can be attached to
a page\&. The page scroller child, on the other hand, is associated with the
Notebook, not with a specific page\&. Therefore, there is only one valid page
scroller for each Notebook\&.
.SS "Pages"
.PP
Only one child of type \fBXmPAGE\fP is displayed at a time by Notebook\&.
Other page children are hidden off-screen\&. When Notebook displays a particular
page, it positions the previously-displayed page off-screen and puts the new
page in its place\&. The page is resized to fit into the dimensions that
Notebook has allocated to display pages\&.
.SS "Page Numbers"
.PP
Notebook uses the \fBXmNcurrentPageNumber\fP, \fBXmNfirstPageNumber\fP,
and \fBXmNlastPageNumber\fP resources to determine the current page and
available page number range\&. Only those pages whose page numbers are within
the range can be displayed\&. Other pages cannot be displayed until the range
between \fBXmNfirstPageNumber\fP and \fBXmNlastPageNumber\fP is
changed to include them or their page numbers are changed to a number within
the range\&.
.PP
If \fBXmNfirstPageNumber\fP and \fBXmNlastPageNumber\fP are not set explicitly
by the application, they are set to 1 by default; Notebook
sets \fBXmNlastPageNumber\fP
to the largest page number assigned by the application thereafter by
default\&. However, once \fBXmNlastPageNumber\fP is set by the application,
Notebook no longer changes it
even when a page with a higher page number is managed\&.
.PP
The \fBXmNpageNumber\fP constraint resource is used for specifying the page
number of a page widget\&. It can be set to any integer\&. For tab and status area
children, the resource is used for linking the child widget to a page\&.
For the page scroller child, the resource has no meaning and is ignored by
the Notebook\&.
.PP
When a page without a page number is managed, Notebook assigns it
the smallest unallocated page number that is not less than
the first page number and greater than the last allocated page number\&. When
a tab or a status area without a page number is managed, the newly managed
widget is assigned
the page number of the most recently managed page, unless the page already has
the same type of child\&. If the page does have the same type of child,
Notebook assigns the newly managed widget
a page number one greater than the most recently managed page;
this new page number is now occupied\&.
Notebook may generate a
default page number greater than \fBXmNlastPageNumber\fP, making
those pages inaccessible to the user\&.
.SS "Duplicate and Empty Pages"
.PP
Since an application can create or change page numbers, it is possible
to have duplicate page numbers and empty pages\&. When two pages with the
same page number are managed, only the more recently managed page can be
displayed\&. Inserting a page with an existing page number
does not cause a warning\&. The old page widget cannot be displayed
until the new page widget is removed from the Notebook or until the page number
of the old page widget is changed to some other number\&.
.PP
An empty page is a page
slot where no page is inserted\&. Empty pages occur when a tab or status area
is associated with a page number that has no matching page widget\&.
Empty pages display the blank Notebook
background unless the application provides visual information to this
empty area while processing \fBXmNpageChangedCallback\fP\&.
.SS "Notebook Visuals"
.PP
Notebook draws lines around two sides of the top page
to simulate the edges of other pages that are behind the top page\&.
The \fBXmNbackPagePlacement\fP and \fBXmNorientation\fP resources determine
which two sides have the lines drawn around them\&. By default, they are drawn
on the bottom and right sides of the top page\&. The application can set
resources to control how many lines are drawn and how wide the area that they
are drawn in is\&. Applications can also choose from three styles of binding
visual that simulates the binding of a Notebook\&. Solid or spiral bindings
can be drawn by Notebook, or the application can supply a pixmap that is
tiled into the binding\&.
.SS "Tabs"
.PP
A major or minor tab is a Motif widget with the \fBXmQTactivatable\fP trait\&.
If a widget without the trait is created
for a tab, Notebook does not provide the page activation callback\&.
As a result, even though the tab is displayed, it cannot automatically move the
associated page to the top\&.
.PP
Major tabs divide the Notebook pages into sections\&. Minor tabs
subdivide these sections\&.
Only minor tabs associated with the current
section are displayed, where a section consists of the group of pages
between the current major tab and the next major tab, including the
current major tab but not including the page containing the next major tab\&.
The exception to this is when there is no preceding major tab, in
which case the section starts from the \fBXmNfirstPageNumber\fP value\&.
A user in one major tab section does not see
the minor tabs in other sections\&.
However, all tabs are used in computing
the size of the Notebook\&.
.PP
Unlike regular notebook tabs, tabs in the
Notebook are not attached to a physical page (a widget)\&. They are, instead,
attached to a logical page (a page number)\&. Therefore, it is possible to have
a tab with an empty page\&. When a page with a tab is removed from the Notebook,
the tab is not removed because it is still bound to a logical page\&.
Destroying or unmanaging
a page widget only erases the page and leaves an empty page\&.
It does not tear the page out of the Notebook\&. To remove the tab, the
application must explicitly destroy or unmanage it\&.
.PP
Notebook supports the \fBXmQTjoinSide\fP trait\&. A widget that has the
\fBXmQTjoinSide\fP trait can be added to the Notebook as a Major or Minor
tab and will appear to be attached to its associated page with no margins or
shadows between them\&.
.SS "Status Areas"
.PP
A status area is any widget that is used for describing
the associated page\&. For example, the Label widget as a status area child
can hold a simple string or a pixmap that describes a page\&. A status area
widget is also attached to a page by the page number constraint resource\&.
Therefore, it is possible to have multiple status area widgets for one page\&.
Only the most recently managed status area widget for that page can be
displayed\&. All others for that page are not unmanaged, but their sizes are
used for computing the size of the Notebook\&. If no status area widget
is provided, the Notebook displays its blank background in the status area\&'s
reserved space\&. Notebook does not create any default status area widget\&.
.SS "Page Scrollers"
.PP
The page scroller of the Notebook is any widget that the application
creates for scrolling pages\&. If the application does not create one when
the Notebook is realized, Notebook creates a SpinBox widget as the
default page scroller\&.
If the application creates a new page scroller, the default page scroller is
destroyed\&. If the application creates multiple page scrollers, only the
most recently managed one can be displayed and used\&. All others are
unmanaged\&.
.PP
The default SpinBox page scroller grays out one of the arrow visuals
if the current page is a boundary page\&.
If the current page is the first page, the previous arrow of the SpinBox
is grayed\&. If the current page is the last page, the next arrow of the
SpinBox is grayed\&.
.SS "Tab Scrollers"
.PP
Tab scrollers are created by the Notebook for scrolling major tabs and minor
tabs\&. When Notebook is initialized, it creates four ArrowButtonGadgets
for scrolling to the next major tab, the previous major tab, the next
minor tab, and the previous minor tab\&.
The application cannot replace these tab scrollers\&.
The application can change all resources
of these widgets except the position and the arrow direction\&. Tab scrollers
are only visible and enabled when there is not enough space to display all the
major or minor tabs appropriate to the page\&. Tab scrollers are also
grayed out when scrolling is inappropriate\&. The following lists the
tab scrollers that are created:
.TS
tab() box;
c s s
l| l| l.
T{
\fBChild Widgets that XmNotebook Creates\fP
T}
\fBChild\fP\fBName\fP\fBWidget Class\fP
___
Page ScrollerPageScrollerXmSpinBox
___
Next Major Tab ScrollerMajorTabScrollerNextXmArrowButtonGadget
___
Previous Major Tab ScrollerMajorTabScrollerPreviousXmArrowButtonGadget
___
Next Minor Tab ScrollerMinorTabScrollerNextXmArrowButtonGadget
___
Previous Minor Tab ScrollerMinorTabScrollerPreviousXmArrowButtonGadget
___
.TE
.PP
When the user selects the page scroller, a major tab, or a minor tab, the value
of \fBXmNcurrentPageNumber\fP is changed to the selected page number and
\fBXmNpageChangedCallback\fP is invoked\&. After the application returns from
the callback, the Notebook displays the last page child whose page number is
equal to the current page number\&. It also displays the last matched status
area child\&. All other pages and status areas are automatically hidden\&. Major
tabs and minor tabs that can fit into the Notebook\&'s edges are displayed and
positioned appropriately\&. All other tabs are also hidden\&. The application
can also cause a page change by calling \fBXtSetValues\fP on
\fBXmNcurrentPageNumber\fP and then calling \fBXtCallCallbacks\fP on
\fBXmNpageChangedCallback\fP\&.
.SS "Orientation"
.PP
The Notebook has eight different visual configurations, depending on
the value of \fBXmNbackPagePlacement\fP and \fBXmNorientation\fP\&. These two
resources determine the placement of back pages, the binding, major tabs,
minor tabs, the status area, and the page scroller\&. The location of the binding
is determined by \fBXmNorientation\fP\&.
Major tabs are always placed on the back page side opposite to the binding;
Minor tabs are placed on the
back page display area that is visually connected to the binding\&.
Both Major and Minor tabs are ordered so that the page numbers they access
increase as they get closer to the corner where the back pages meet\&.
The status area and the page scroller are always located on the bottom
of the Notebook, inside the frame\&. The page scroller is always placed adjacent
to a back page side\&. The following table shows the possible configurations
and the locations of each Notebook component within the configuration\&.
The default back page value
and the default orientation
are based upon \fBXmNlayoutDirection\fP\&.
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBNotebook Configurations\fP
\fBXmNbackPagePlacement\fP\fBXmNorientation\fP\fBMajor Tabs\fP\fBStatus Area\fP\fBBinding\fP
_____
\fBMinor Tabs\fP\fBPage Scroller\fP
_____
XmBOTTOM_RIGHTXmHORIZONTALRIGHTBOTTOM LEFTLEFT
_____
BOTTOMBOTTOM RIGHT
_____
XmBOTTOM_RIGHTXmVERTICALBOTTOMBOTTOM LEFTTOP
_____
RIGHTBOTTOM RIGHT
_____
XmBOTTOM_LEFTXmHORIZONTALLEFTBOTTOM RIGHTRIGHT
_____
BOTTOMBOTTOM LEFT
_____
XmBOTTOM_LEFTXmVERTICALBOTTOMBOTTOM RIGHTTOP
_____
LEFTBOTTOM LEFT
_____
XmTOP_RIGHTXmHORIZONTALRIGHTBOTTOM LEFTLEFT
_____
TOPBOTTOM RIGHT
_____
XmTOP_RIGHTXmVERTICALTOPBOTTOM LEFTBOTTOM
_____
RIGHTBOTTOM RIGHT
_____
XmTOP_LEFTXmHORIZONTALLEFTBOTTOM RIGHTRIGHT
_____
TOPBOTTOM LEFT
_____
XmTOP_LEFTXmVERTICALTOPBOTTOM RIGHTBOTTOM
_____
LEFTBOTTOM LEFT
_____
.TE
.PP
There are three tab groups for tab group traversal
inside the Notebook: major tabs, minor tabs,
and the page scroller\&.
The application can also create additional types of tab groups
within the Notebook; for example, each page added by the application is
treated as a separate tab group by the traversal actions\&.
.SS "Classes"
.PP
Notebook inherits behavior, resources, and traits from \fBCore\fP,
\fBComposite\fP, \fBConstraint\fP, and \fBXmManager\fP classes\&.
.PP
The class pointer is \fBxmNotebookWidgetClass\fP\&.
.PP
The class name is \fBXmNotebook\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the
programmer to specify data\&. The programmer can also set the resource
values for the inherited classes to set attributes for this widget\&.
To reference a resource by name or by class in a \fB\&.Xdefaults\fP file,
remove the \fBXmN\fP or \fBXmC\fP prefix and use the remaining letters\&.
To specify one of the defined values for a resource in a \fB\&.Xdefaults\fP
file, remove the \fBXm\fP prefix and use the remaining letters (in
either lowercase or uppercase, but include any underscores between
words)\&. The codes in the access column indicate if the given resource
can be set at creation time (C), set by using \fBXtSetValues\fP
(S), retrieved by using \fBXtGetValues\fP (G), or is not
applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmNotebook Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbackPageBackgroundXmCBackPageBackgroundPixeldynamicCSG
_____
XmNbackPageForegroundXmCBackPageForegroundPixeldynamicCSG
_____
XmNbackPageNumberXmCBackPageNumberCardinal2CSG
_____
XmNbackPagePlacementXmCBackPagePlacementunsigned chardynamicCSG
_____
XmNbackPageSizeXmCBackPageSizeDimension8CSG
_____
XmNbindingPixmapXmCBindingPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNbindingTypeXmCBindingTypeunsigned charXmSPIRALCSG
_____
XmNbindingWidthXmCBindingWidthDimension25CSG
_____
XmNcurrentPageNumberXmCCurrentPageNumberintdynamicCSG
_____
XmNfirstPageNumberXmCFirstPageNumberint1CSG
_____
XmNframeBackgroundXmCFrameBackgroundPixeldynamicCSG
_____
XmNframeShadowThicknessXmCShadowThicknessDimension0CSG
_____
XmNinnerMarginHeightXmCInnerMarginHeightDimension0CSG
_____
XmNinnerMarginWidthXmCInnerMarginWidthDimension0CSG
_____
XmNlastPageNumberXmCLastPageNumberintdynamicCSG
_____
XmNminorTabSpacingXmCMinorTabSpacingDimension3CSG
_____
XmNmajorTabSpacingXmCMajorTabSpacingDimension3CSG
_____
XmNorientationXmCOrientationunsigned charXmHORIZONTALCSG
_____
XmNpageChangedCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.IP "\fBXmNbackPageBackground\fP" 10
Specifies the background color for drawing back pages\&.
The default is a lower-intensity version of \fBXmNframeBackground\fP\&.
.IP "\fBXmNbackPageForeground\fP" 10
Specifies the forground color for drawing back pages\&. The default is
taken from the application\&'s default foreground color\&.
.IP "\fBXmNbackPageNumber\fP" 10
Specifies the number of lines to draw for back pages\&. The minimum value is
1, and the maximum value is (\fBXmNbackPageSize\fP / 2)\&.
.IP "\fBXmNbackPagePlacement\fP" 10
Specifies where to place the back pages\&.
The default is dependent on the \fBXmNlayoutDirection\fP resource
of the Notebook\&'s instance parents\&.
It can have one of the following
values:
.RS
.IP "\fBXmBOTTOM_RIGHT\fP" 10
Displays back pages on the Notebook\&'s bottom and
right sides\&.
.IP "\fBXmBOTTOM_LEFT\fP" 10
Displays back pages on the Notebook\&'s bottom and
left sides\&.
.IP "\fBXmTOP_RIGHT\fP" 10
Displays back pages on the Notebook\&'s top and right
sides\&.
.IP "\fBXmTOP_LEFT\fP" 10
Displays back pages on the Notebook\&'s top and left sides\&.
.RE
.IP "\fBXmNbackPageSize\fP" 10
Specifies the thickness of the back page rendering\&.
.IP "\fBXmNbindingPixmap\fP" 10
Specifies the pixmap or bitmap for stippling or tiling the binding when
\fBXmNbindingType\fP is \fBXmPIXMAP\fP or \fBXmPIXMAP_OVERLAP_ONLY\fP\&.
.IP "\fBXmNbindingType\fP" 10
Specifies the binding type\&. It can have one of the following values:
.RS
.IP "\fBXmNONE\fP" 10
Displays no binding\&.
.IP "\fBXmSOLID\fP" 10
Displays a solid binding in the foreground color of the
Notebook within the binding area specified by \fBXmNbindingWidth\fP\&.
.IP "\fBXmSPIRAL\fP" 10
Displays a spiral binding in the foreground color of the
Notebook within the area specified by \fBXmNbindingWidth\fP
and within the area outside of the frame equal to
the area specified by \fBXmNbindingWidth\fP\&.
.IP "\fBXmPIXMAP\fP" 10
Displays the binding with the pixmap or bitmap specified by
\fBXmNbindingPixmap\fP as a stipple or tile\&. It uses the foreground color of
the Notebook for stippling\&. The binding width is decided by the larger value
of \fBXmNbindingWidth\fP and the width of the pixmap or bitmap\&.
.IP "\fBXmPIXMAP_OVERLAP_ONLY\fP" 10
Displays the binding with the pixmap or bitmap
specified by \fBXmNbindingPixmap\fP as a stipple or tile\&. It uses the
foreground color of the Notebook for stippling\&. The binding is displayed only
within the binding area specified by \fBXmNbindingWidth\fP\&.
.RE
.IP "\fBXmNbindingWidth\fP" 10
Specifies the width of the Notebook binding\&. If \fBXmNbindingType\fP is
\fBXmPIXMAP\fP and the width of the pixmap specified in
\fBXmNbindingPixmap\fP is greater than \fBXmNbindingWidth\fP, then this
resource is ignored and the
width of the pixmap is used as the width of the Notebook binding
instead\&.
.IP "\fBXmNcurrentPageNumber\fP" 10
Specifies the page number of the currently displayed page\&. Initially, it is set
to \fBXmNfirstPageNumber\fP\&. If it is set to less than
\fBXmNfirstPageNumber\fP,
then it is set to \fBXmNfirstPageNumber\fP\&.
If it is set to \fBXmNlastPageNumber\fP,
then it is set to \fBXmNlastPageNumber\fP\&.
.IP "\fBXmNfirstPageNumber\fP" 10
Specifies the page number for the first page of the Notebook\&.
The Notebook does not scroll to any page numbers below this value\&.
.IP "\fBXmNframeBackground\fP" 10
Specifies the background color for drawing the Notebook\&'s frame\&.
.IP "\fBXmNframeShadowThickness\fP" 10
Specifies the shadow thickness around the Notebook\&'s frame\&.
.IP "\fBXmNinnerMarginHeight\fP" 10
Specifies the margin on the top and bottom sides of the page, status
area, and page scroller widgets\&.
.IP "\fBXmNinnerMarginWidth\fP" 10
Specifies the margin on the left and right sides of the page, status
area, and page scroller widgets\&.
.IP "\fBXmNlastPageNumber\fP" 10
Specifies the page number for the last page of the Notebook\&.
The Notebook does not scroll to any page numbers above this value\&.
The default page number is the largest page number of managed page,
major tab, or minor tab widgets\&.
If this is set to a value that is less than \fBXmNfirstPageNumber\fP, the
behavior of the Notebook is undefined\&.
.IP "\fBXmNmajorTabSpacing\fP" 10
Specifies the spacing distance between major tabs\&.
If \fBXmNframeShadowThickness\fP is greater than \fBXmNmajorTabSpacing\fP, then
this resource is ignored and the size of \fBXmNframeShadowThickness\fP is
used as the spacing distance between major tabs\&.
.IP "\fBXmNminorTabSpacing\fP" 10
Specifies the spacing distance between minor tabs\&. If
\fBXmNframeShadowThickness\fP is greater than \fBXmNminorTabSpacing\fP, then
this resource is ignored and the size of \fBXmNframeShadowThickness\fP is
used as the spacing distance between minor tabs\&.
.IP "\fBXmNorientation\fP" 10
Specifies the orientation of the Notebook\&. It can have one of the following
values:
.RS
.IP "\fBXmHORIZONTAL\fP" 10
Places the binding beside the pages, in the left or
right side of the frame\&.
.IP "\fBXmVERTICAL\fP" 10
Places the binding above or below the pages, in the top
or the bottom of the frame\&.
.RE
.IP "\fBXmNpageChangedCallback\fP" 10
Specifies the list of callbacks to call whenever the
\fBXmNcurrentPageNumber\fP, representing the current page number, is
changed\&. This includes the point when the widget is realized and the
page number is initialized\&.
The callback structure is \fBXmNotebookCallbackStruct\fR\&.
The reason is \fBXmCR_MAJOR_TAB\fP, \fBXmCR_MINOR_TAB\fP,
\fBXmCR_PAGE_SCROLLER_INCREMENT\fP,
\fBXmCR_PAGE_SCROLLER_DECREMENT\fP, or \fBXmCR_NONE\fP, depending
upon what action caused the Notebook to display a new page\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmNotebook Constraint Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNnotebookChildTypeXmCNotebookChildTypeunsigned chardynamicCG
_____
XmNpageNumberXmCPageNumberintdynamicCSG
_____
XmNresizableXmCResizableBooleanTrueCSG
_____
.TE
.IP "\fBXmNnotebookChildType\fP" 10
Specifies the child type of the Notebook\&. It can be one of the following types:
.RS
.IP "\fBXmPAGE\fP" 10
The child is a page of the Notebook\&. This is the default
when the child does not have
the \fBXmQTactivatable\fP,
\fBXmQTaccessTextual\fP, or \fBXmQTnavigator\fP trait\&.
.IP "\fBXmMAJOR_TAB\fP" 10
The child is a major tab\&. This is the default when
the child has the \fBXmQTactivatable\fP trait\&.
.IP "\fBXmMINOR_TAB\fP" 10
The child is a minor tab\&.
.IP "\fBXmSTATUS_AREA\fP" 10
The child is a status area\&. This is the default when
the child has the \fBXmQTaccessTextual\fP trait and does not have
the \fBXmQTactivatable\fP trait\&.
.IP "\fBXmPAGE_SCROLLER\fP" 10
The child is the page scroller\&. The default page
scroller is destroyed, if it exists\&. Any previously created page
scrollers are unmanaged\&. This is the default when the child
has the \fBXmQTnavigator\fP trait and does have the
\fBXmQTactivatable\fP trait or the \fBXmQTaccessTextual\fP trait\&.
.RE
.IP "\fBXmNpageNumber\fP" 10
Specifies the page number associated with the widget\&.
If the widget is a page, the number specifies the page number of the widget\&.
If the widget is not a page, the number specifies the page number of the
associated page\&. If none is supplied by the application, Notebook
generates the smallest unallocated page number when the child is managed\&.
This resource is ignored for the page scroller\&.
.IP "\fBXmNresizable\fP" 10
Specifies whether this child can request a resize\&.
.SS "Inherited Resources"
.PP
Notebook inherits behavior and resources from the
superclasses described in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetNULLCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmTAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension0CSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback"
.PP
A pointer to the following structure is passed to callbacks for
\fBXmNpageChangedCallback\fP\&.
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI*event\fP;
        int \fIpage_number\fP;
        Widget \fIpage_widget\fP;
        int \fIprev_page_number\fP;
        Widget \fIprev_page_widget\fP;
} XmNotebookCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Specifies the reason for the callback\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&. It can be NULL\&.
.IP "\fIpage_number\fP" 10
Indicates the page number to be displayed\&.
.IP "\fIpage_widget\fP" 10
Indicates the page widget that has the new page number\&.
It is NULL if no page widget with the page number is found\&.
.IP "\fIprev_page_number\fP" 10
Indicates the page number of the currently displayed page\&. If the
callback procedure is being called at widget initialization, this page
number will be returned as \fBXmUNSPECIFIED_PAGE_NUMBER\fP\&.
.IP "\fIprev_page_widget\fP" 10
Indicates the currently displayed page widget\&. If the callback
procedure is being called at widget initialization, NULL will be
returned\&.
.SS "Translations"
.PP
Notebook inherits translations from Manager\&.
.SS "Accelerators"
.PP
Notebook accelerators are added to all major tab and minor tab
children of XmNotebook\&.
Notebook accelerators are listed below\&.
These accelerators might not directly correspond to a
translation table\&.
.IP "\fB<osfBeginLine>\fP\fB:\fP" 10
TraverseTab(\fBHome\fP)
.IP "\fB<osfEndLine>\fP\fB:\fP" 10
TraverseTab(\fBEnd\fP)
.IP "\fB<osfLeft>\fP\fB:\fP" 10
TraverseTab(\fBPrevious\fP)
.IP "\fB<osfRight>\fP\fB:\fP" 10
TraverseTab(\fBNext\fP)
.IP "\fB<osfUp>\fP\fB:\fP" 10
TraverseTab(\fBPrevious\fP)
.IP "\fB<osfDown>\fP\fB:\fP" 10
TraverseTab(\fBNext\fP)
.SS "Action Routines"
.PP
Notebook action routines are described below:
.IP "TraverseTab(\fBHome|End|Next|Previous\fP)" 10
Moves the focus on major or minor tabs\&.
.SS "Additional Behavior"
.PP
The Notebook widget has the additional behavior described below:
.IP "\fB<Tab>\fP" 10
Notebook intercepts tab group traversal when traversal is entering or
leaving major or minor tabs\&. It does this to support major tabs and minor
tabs as two separate tab groups when they are actually treated as one
by traversal\&. If a minor tab has keyboard focus and a user or program
action specifies \fBXmTRAVERSE_PREV_TAB_GROUP\fP, keyboard focus will
go to a major tab\&. If a major tab has keyboard focus and a user or program
action specifies \fBXmTRAVERSE_NEXT_TAB_GROUP\fP, keyboard focus will
go to a minor tab\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see
\fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBComposite\fP(3),
\fBConstraint\fP(3),
\fBCore\fP(3),
\fBXmCreateNotebook\fP(3),
\fBXmManager\fP(3), and
\fBXmNotebookGetPageInfo\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
