'\" t
...\" ParMapC.sgm /main/7 1996/08/30 15:52:34 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmParseMappingFree" "library call"
.SH "NAME"
\fBXmParseMappingFree\fP \(em A compound string function to free a parse mapping
.iX "XmParseMappingFree"
.iX "compound string functions" "XmParseMappingFree"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBvoid \fBXmParseMappingFree\fP\fR(
\fBXmParseMapping \fBparse_mapping\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmParseMappingFree\fP recovers memory used by an
\fBXmParseMapping\fR\&.
.IP "\fIparse_mapping\fP" 10
Specifies the parse mapping to be freed
.SH "RELATED"
.PP
\fBXmParseMapping\fP(3),
\fBXmParseMappingCreate\fP(3),
\fBXmParseMappingGetValues\fP(3),
\fBXmParseMappingSetValues\fP(3),
\fBXmParseTable\fP(3), and
\fBXmString\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
