'\" t
...\" Primitiv.sgm /main/12 1996/09/08 20:55:32 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmPrimitive" "library call"
.SH "NAME"
\fBXmPrimitive\fP \(em The Primitive widget class
.iX "XmPrimitive"
.iX "widget class" "Primitive"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
.fi
.SH "DESCRIPTION"
.PP
Primitive is a widget class used as a supporting superclass
for other widget classes\&. It handles border drawing and highlighting,
traversal activation and deactivation, and various callback lists needed by
Primitive widgets\&.
Primitive and all its subclasses hold the \fBXmQTcareParentVisual\fP trait\&.
.SS "Data Transfer Behavior"
.PP
Primitive has no widget class conversion or destination procedure\&.
Subclasses and the \fBXmNconvertCallback\fP procedures are responsible
for any conversion of selections\&.
Subclasses and the subclass \fBXmNdestinationCallback\fP procedures are
responsible for any data transfers to the widget\&.
.SS "Classes"
.PP
Primitive inherits behavior, resources, and traits from \fBCore\fP\&.
.PP
The class pointer is \fBxmPrimitiveWidgetClass\fP\&.
.PP
The class name is \fBXmPrimitive\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmPrimitive Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNconvertCallbackXmCCallbackXtCallbackListNULLC
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightOnEnterXmCHighlightOnEnterBooleanFalseCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimension2CSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmNONECSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.IP "\fBXmNbottomShadowColor\fP" 10
Specifies the color to use to draw the bottom and right sides of the
border shadow\&.
This color is used if the \fBXmNtopShadowPixmap\fP resource is
unspecified\&.
.IP "\fBXmNbottomShadowPixmap\fP" 10
Specifies the pixmap to use to draw the bottom and right sides of the
border shadow\&.
.IP "\fBXmNconvertCallback\fP" 10
Specifies a list of callbacks called when the widget is asked to convert
a selection\&.
The type of the structure whose address is passed to these callbacks is
\fBXmConvertCallbackStruct\fR\&.
The reason is \fBXmCR_OK\fP\&.
.IP "\fBXmNforeground\fP" 10
Specifies the foreground drawing color used by Primitive widgets\&.
.IP "\fBXmNhelpCallback\fP" 10
Specifies the list of callbacks that is called when the help key
is pressed\&. The reason sent by the callback is \fBXmCR_HELP\fP\&.
.IP "\fBXmNhighlightColor\fP" 10
Specifies the color of the highlighting rectangle\&.
This color is used if the highlight pixmap resource is
\fBXmUNSPECIFIED_PIXMAP\fP\&.
.IP "\fBXmNhighlightOnEnter\fP" 10
Specifies if the highlighting rectangle is drawn when the cursor moves
into the widget\&.
If the shell\&'s focus policy is \fBXmEXPLICIT\fP, this resource is
ignored, and the widget is highlighted when it has the focus\&.
If the shell\&'s focus policy is \fBXmPOINTER\fP and if this resource is
True, the highlighting rectangle is drawn when the cursor moves into
the widget\&.
If the shell\&'s focus policy is \fBXmPOINTER\fP and if this resource is
False, the highlighting rectangle is not drawn when the the cursor moves
into the widget\&.
The default is False\&.
.IP "\fBXmNhighlightPixmap\fP" 10
Specifies the pixmap used to draw the highlighting rectangle\&.
.IP "\fBXmNhighlightThickness\fP" 10
Specifies the thickness of the highlighting rectangle\&.
.IP "\fBXmNlayoutDirection\fP" 10
Specifies the direction in which components of the primitive (including
strings) are laid out\&. The values are of type \fBXmDirection\fR\&. If
the widget\&'s parent is a primitive or shell, the value is inherited from
the widget\&'s parent\&. Otherwise, it is inherited from the closest
ancestor vendor or menu shell\&. Refer to the \fBXmDirection\fP(3)
reference page for the possible direction values\&.
.IP "\fBXmNnavigationType\fP" 10
Determines whether the widget is a tab group\&.
.RS
.IP "\fBXmNONE\fP" 10
Indicates that the widget is not a tab group\&.
.IP "\fBXmTAB_GROUP\fP" 10
Indicates that the widget is a tab group, unless
the \fBXmNnavigationType\fP of another widget in the hierarchy is
\fBXmEXCLUSIVE_TAB_GROUP\fP\&.
.IP "\fBXmSTICKY_TAB_GROUP\fP" 10
Indicates that the widget is a tab group, even
if the \fBXmNnavigationType\fP of another widget in the hierarchy is
\fBXmEXCLUSIVE_TAB_GROUP\fP\&.
.IP "\fBXmEXCLUSIVE_TAB_GROUP\fP" 10
Indicates that the widget is a tab group and
that widgets in the hierarchy whose \fBXmNnavigationType\fP is
\fBXmTAB_GROUP\fP are not tab groups\&.
.IP "" 10
When a parent widget has an \fBXmNnavigationType\fP of
\fBXmEXCLUSIVE_TAB_GROUP\fP, traversal of non-tab-group widgets within
the group is based on the order of those widgets in their parent\&'s
\fBXmNchildren\fP list\&.
.IP "" 10
When the \fBXmNnavigationType\fP of any widget in a hierarchy is
\fBXmEXCLUSIVE_TAB_GROUP\fP, traversal of tab groups in the hierarchy
proceeds to widgets in the order in which their \fBXmNnavigationType\fP
resources were specified as \fBXmEXCLUSIVE_TAB_GROUP\fP or
\fBXmSTICKY_TAB_GROUP\fP, whether by creating the widgets with that value,
by calling \fBXtSetValues\fP, or by calling \fBXmAddTabGroup\fP\&.
.RE
.IP "\fBXmNpopupHandlerCallback\fP" 10
Allows the application to control which popup menu will be
automatically posted\&. The reason can either be \fBXmCR_POST\fP or
\fBXmCR_REPOST:\fP
.RS
.IP "\fBXmCR_POST\fP" 10
Indicates that this is a regular posting request\&.
.IP "\fBXmCR_REPOST\fP" 10
Indicates that the menu was just unposted and that this callback was
invoked on a replay\&.
.RE
.IP "" 10
This callback
uses the \fBXmPopupHandlerCallbackStruct\fR
structure to pass information\&.
.IP "\fBXmNshadowThickness\fP" 10
Specifies the size of the drawn border shadow\&.
.IP "\fBXmNtopShadowColor\fP" 10
Specifies the color to use to draw the top and left sides of the border
shadow\&.
This color is used if the \fBXmNtopShadowPixmap\fP resource is
unspecified\&.
If a default top shadow pixmap exists, it will need to be removed for
the \fBXmNtopShadowColor\fP to take effect\&.
.IP "\fBXmNtopShadowPixmap\fP" 10
Specifies the pixmap to use to draw the top and left sides of the border
shadow\&.
A Primitive top shadow pixmap is created in two situations\&. In either
of these situations, a default 50-foreground top shadow
pixmap is created\&.
.RS
.IP "   \(bu" 6
If the Primitive top shadow color is the same as the
Core background pixel color\&.
.IP "   \(bu" 6
If the depth of the screen is only one\&.
.RE
.IP "" 10
For example, if a widget with the same top shadow and background color
is created, a default shadow pixmap is generated\&. Such a pixmap
needs to be removed for the \fBXmNtopShadowColor\fP resource to take
effect\&.
.IP "\fBXmNtraversalOn\fP" 10
Specifies if traversal is activated for this widget\&. In CascadeButton
and CascadeButtonGadget, this resource is forced to True unless the parent
is an OptionMenu\&.
.IP "\fBXmNunitType\fP" 10
Provides the basic support for resolution independence\&.
It defines the type of units a widget uses with sizing and
positioning resources\&.
If the widget\&'s parent is a subclass of \fBXmManager\fP and if the
\fBXmNunitType\fP resource is not explicitly set, it defaults to the
unit type of the parent widget\&.
If the widget\&'s parent is not a subclass of \fBXmManager\fP, the
resource has a default unit type of \fBXmPIXELS\fP\&.
.IP "" 10
The unit type can also be specified in resource files, with the
following format:
.PP
.nf
\f(CW\fI<floating value><unit>\fP\fR
.fi
.PP
.IP "" 10
where:
.RS
.IP "\fIunit\fP" 10
is <" ", pixels, inches, centimeters, millimeters, points, font units>
.IP "\fIpixels\fP" 10
is <\fIpix\fP, \fIpixel\fP, \fIpixels\fP>
.IP "\fIinches\fP" 10
is <\fIin\fP, \fIinch\fP, \fIinches\fP>
.IP "\fIcentimeter\fP" 10
is <\fIcm\fP, \fIcentimeter\fP, \fIcentimeters\fP>
.IP "\fImillimeters\fP" 10
is <\fImm\fP, \fImillimeter\fP, \fImillimeters\fP>
.IP "\fBpoints\fP" 10
is <\fIpt\fP, \fIpoint\fP, \fIpoints\fP>
.IP "\fBfont units\fP" 10
is <\fIfu\fP, \fBfont_unit\fP, \fBfont_units\fP>
.IP "\fIfloat\fP" 10
is {"+"|"-"}{{<"0"-"9">*}\&.}<"0"-"9">*
.IP "" 10
Note that the type Dimension must always be positive\&.
.RE
.IP "" 10
For example,
.PP
.nf
\f(CWxmfonts*XmMainWindow\&.height: 10\&.4cm
*PostIn\&.width: 3inches\fR
.fi
.PP
.IP "" 10
\fBXmNunitType\fP can have the following values:
.RS
.IP "\fBXmPIXELS\fP" 10
All values provided to the widget are treated as normal
pixel values\&.
.IP "\fBXmMILLIMETERS\fP" 10
All values provided to the widget are treated as normal millimeter
values\&.
.IP "\fBXm100TH_MILLIMETERS\fP" 10
All values provided to the widget are treated
as 1/100 of a millimeter\&.
.IP "\fBXmCENTIMETERS\fP" 10
All values provided to the widget are treated as normal centimeter
values\&.
.IP "\fBXmINCHES\fP" 10
All values provided to the widget are treated as normal inch
values\&.
.IP "\fBXm1000TH_INCHES\fP" 10
All values provided to the widget are treated as
1/1000 of an inch\&.
.IP "\fBXmPOINTS\fP" 10
All values provided to the widget are treated as normal point
values\&. A point is a unit used in text processing
applications and is defined as 1/72 of an inch\&.
.IP "\fBXm100TH_POINTS\fP" 10
All values provided to the widget are treated as
1/100 of a point\&. A point is a unit used in text processing
applications and is defined as 1/72 of an inch\&.
.IP "\fBXmFONT_UNITS\fP" 10
All values provided to the widget are treated as normal font
units\&. A font unit has horizontal and vertical components\&.
These are the values of the XmScreen resources \fBXmNhorizontalFontUnit\fP
and \fBXmNverticalFontUnit\fP\&.
.IP "\fBXm100TH_FONT_UNITS\fP" 10
All values provided to the widget are
treated as 1/100 of a font unit\&.
A font unit has horizontal and vertical components\&.
These are the values of the \fBXmScreen\fP resources \fBXmNhorizontalFontUnit\fP
and \fBXmNverticalFontUnit\fP\&.
.RE
.IP "\fBXmNuserData\fP" 10
Allows the application to attach any necessary specific data to the widget\&.
It is an internally unused resource\&.
.SS "Dynamic Color Defaults"
.PP
The foreground, background, top shadow, bottom shadow, and
highlight color resources are dynamically defaulted\&.
If no color data is specified, the colors are
automatically generated\&. On a single-plane system, a black and white color
scheme is generated\&. Otherwise, four colors are
generated, which display the correct shading for the 3-D visuals\&.
If the background is the only color specified for a widget, the top
shadow and bottom shadow colors are generated to give the 3-D appearance\&.
Foreground and highlight colors are generated to provide sufficient
contrast with the background color\&.
.PP
Colors are generated only at creation\&. Resetting the background through
\fBXtSetValues\fP does not regenerate the other colors\&.
\fBXmChangeColor\fP can be used to recalculate all associated colors
based on a new background color\&.
.SS "Inherited Resources"
.PP
Primitive inherits behavior and resources from the
superclass described in the following table\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback for
\fBXmNhelpCallback\fP:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
} XmAnyCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
For this callback, \fIreason\fP is set to \fBXmCR_HELP\fP\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
.PP
A pointer to the following callback structure is passed to the
\fBXmNconvertCallback\fP procedures:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent *\fIevent\fP;
        Atom \fIselection\fP;
        Atom \fItarget\fP;
        XtPointer \fIsource_data\fP;
        XtPointer location_data;
        int \fIflags\fP;
        XtPointer \fIparm\fP;
        int \fIparm_format\fP;
        unsigned long \fIparm_length\fP;
        Atom \fIparm_type\fP;
        int \fIstatus\fP;
        XtPointer \fIvalue\fP;
        Atom \fItype\fP;
        int \fIformat\fP;
        unsigned long \fIlength\fP;
} XmConvertCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
It can be NULL\&.
.IP "\fIselection\fP" 10
Indicates the selection for which conversion is being requested\&.
Possible values are \fBCLIPBOARD\fP, \fBPRIMARY\fP, \fBSECONDARY\fP,
and \fB_MOTIF_DROP\fP\&.
.IP "\fItarget\fP" 10
Indicates the conversion target\&.
.IP "\fIsource_data\fP" 10
Contains information about the selection source\&.
When the selection is \fB_MOTIF_DROP\fP, \fIsource_data\fP is the
DragContext\&.
Otherwise, it is NULL\&.
.IP "\fBlocation_data\fP" 10
Contains information about the location of data to be converted\&.
If the value is NULL, the data to be transferred consists of the
widget\&'s current selection\&.
Otherwise, the type and interpretation of the value are specific to the
widget class\&.
.IP "\fIflags\fP" 10
Indicates the status of the conversion\&. Following are the possible
values:
.RS
.IP "\fBXmCONVERTING_NONE\fP" 10
This flag is currently unused\&.
.IP "\fBXmCONVERTING_PARTIAL\fP" 10
The target widget was able to be converted, but some data was lost\&.
.IP "\fBXmCONVERTING_SAME\fP" 10
The conversion target is the source of the data to be transferred\&.
.IP "\fBXmCONVERTING_TRANSACT\fP" 10
This flag is currently unused\&.
.RE
.IP "\fIparm\fP" 10
Contains parameter data for this target\&.
If no parameter data exists, the value is NULL\&.
.IP "" 10
When \fIselection\fP is \fBCLIPBOARD\fP and \fItarget\fP is
\fB_MOTIF_CLIPBOARD_TARGETS\fP or
\fB_MOTIF_DEFERRED_CLIPBOARD_TARGETS\fP, the value is the requested
operation (\fBXmCOPY\fP, \fBXmMOVE\fP, or \fBXmLINK\fP)\&.
.IP "\fIparm_format\fP" 10
Specifies whether the data in \fIparm\fP should be viewed
as a list of \fIchar\fP, \fIshort\fP, or \fIlong\fP quantities\&.
Possible values are 0 (when \fIparm\fP is NULL),
8 (when the data in \fIparm\fP should be viewed as a list of \fIchar\fPs),
16 (when the data in \fIparm\fP should be viewed as a list of \fIshort\fPs),
or 32 (when the data in \fIparm\fP should be viewed as a list of \fIlong\fPs)\&.
Note that \fIparm_format\fP symbolizes a data type, not the number of bits
in each list element\&.
For example, on some machines, a \fIparm_format\fP of 32 means that
the data in \fIparm\fP should be viewed as a list of 64-bit quantities,
not 32-bit quantities\&.
.IP "\fIparm_length\fP" 10
Specifies the number of elements of data in \fIparm\fP, where each
element has the size specified by \fIparm_format\fP\&.
When \fIparm\fP is NULL, the value is 0\&.
.IP "\fIparm_type\fP" 10
Specifies the parameter type of \fIparm\fP\&.
.IP "\fIstatus\fP" 10
An IN/OUT member that specifies the status of the conversion\&.
The initial value is \fBXmCONVERT_DEFAULT\fP\&.
The callback procedure can set this member to one of the following
values:
.RS
.IP "\fBXmCONVERT_DEFAULT\fP" 10
This value means that the widget class conversion procedure, if any, is
called after the callback procedures return\&.
If the widget class conversion procedure produces any data, it
overwrites the data provided by the callback procedures in the \fIvalue\fP
member\&.
.IP "\fBXmCONVERT_MERGE\fP" 10
This value means that the widget class conversion procedure, if any, is
called after the callback procedures return\&.
If the widget class conversion procedure produces any data, it appends
its data to the data provided by the callback procedures in the
\fIvalue\fP member\&.
This value is intended for use with targets that result in lists of
data, such as \fBTARGETS\fP\&.
.IP "\fBXmCONVERT_DONE\fP" 10
This value means that the callback procedure has successfully finished
the conversion\&.
The widget class conversion procedure, if any, is not called after the
callback procedures return\&.
.IP "\fBXmCONVERT_REFUSE\fP" 10
This value means that the callback procedure has terminated the
conversion process without completing the requested conversion\&.
The widget class conversion procedure, if any, is not called after the
callback procedures return\&.
.RE
.IP "\fIvalue\fP" 10
An IN/OUT parameter that contains any data that the callback procedure
produces as a result of the conversion\&.
The initial value is NULL\&.
If the callback procedure sets this member, it must ensure that the
\fItype\fP, \fIformat\fP, and \fIlength\fP members correspond
to the data in \fIvalue\fP\&.
The callback procedure is responsible for allocating memory when it sets
this member\&.
The toolkit frees this memory when it is no longer needed\&.
.IP "\fItype\fP" 10
An IN/OUT parameter that indicates the type of the data in the
\fIvalue\fP member\&.
The initial value is \fBINTEGER\fP\&.
.IP "\fIformat\fP" 10
An IN/OUT parameter that specifies whether the data in \fIvalue\fP should
be viewed as a list of \fIchar\fP, \fIshort\fP, or \fIlong\fP quantities\&.
The initial value is 8\&.
The callback procedure can set this member to 8 (for a list of \fIchar\fP),
16 (for a list of \fIshort\fP), or 32 (for a list of \fIlong\fP)\&.
.IP "\fIlength\fP" 10
An IN/OUT member that specifies the number of elements of data in
\fIvalue\fP, where each element has the size symbolized by \fIformat\fP\&.
The initial value is 0\&.
.PP
A pointer to the following structure is passed to each callback for
\fBXmNpopupHandlerCallback\fP:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* xevent\fP;
        Widget \fImenuToPost\fP;
        Boolean \fIpostIt\fP;
        Widget \fItarget\fP;
} XmPopupHandlerCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIxevent\fP" 10
Points to the \fBXEvent\fP that triggered the handler\&.
.IP "\fImenuToPost\fP" 10
Specifies the popup menu that the menu system believes should be
posted\&. The application may modify this field\&.
.IP "\fIpostIt\fP" 10
Indicates whether the posting process should continue\&. The
application may modify this field\&.
.IP "\fItarget\fP" 10
Specifies the most specific widget or gadget that the menu sytem found
from the event that matches the event\&.
.SS "Translations"
.PP
The \fBXmPrimitive\fP translations are listed below\&.
.PP
Note that for buttons in menus, altering translations in \fB#override\fP
or \fB#augment\fP mode is undefined\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fB:\fP\fB<Key>\fP\fB<osfActivate>\fP:" 10
PrimitiveParentActivate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCancel>\fP:" 10
PrimitiveParentCancel()
.IP "\fB:\fP\fB<Key>\fP\fB<osfBeginLine>\fP:" 10
PrimitiveTraverseHome()
.IP "\fB:\fP\fB<Key>\fP\fB<osfUp>\fP:" 10
PrimitiveTraverseUp()
.IP "\fB:\fP\fB<Key>\fP\fB<osfDown>\fP:" 10
PrimitiveTraverseDown()
.IP "\fB:\fP\fB<Key>\fP\fB<osfLeft>\fP:" 10
PrimitiveTraverseLeft()
.IP "\fB:\fP\fB<Key>\fP\fB<osfRight>\fP:" 10
PrimitiveTraverseRight()
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBReturn\fP:" 10
PrimitiveParentActivate()
.IP "\fBs \(apm \(apa\fP \fB<Key>\fP\fBTab\fP:" 10
PrimitivePrevTabGroup()
.IP "\fB\(apm \(apa\fP \fB<Key>\fP\fBTab\fP:" 10
PrimitiveNextTabGroup()
.IP "\fB<Key>\fP\fB<osfHelp>\fP:" 10
PrimitiveHelp()
.SS "Action Routines"
.PP
The \fBXmPrimitive\fP action routines are
.IP "PrimitiveHelp():" 10
Calls the callbacks for \fBXmNhelpCallback\fP if any exist\&. If there are no help
callbacks for this widget, this action calls the help callbacks
for the nearest ancestor that has them\&.
.IP "PrimitiveNextTabGroup():" 10
This action depends on the value of the Display resource
\fBXmNenableButtonTab\fP\&. When \fBXmNenableButtonTab\fP is False
(default), this action traverses to the first item in the next tab
group\&. If the current tab group is the last entry in the tab group
list, it wraps to the beginning of the tab group list\&.
.IP "" 10
When \fBXmNenableButtonTab\fP is True, this action moves to the next
item within the current tab group, unless it is the last item in the
tab group\&. When the item is the last in the group, the action
traverses to the first item in the next tab group\&. The
\fBXmNenableButtonTab\fP behavior applies only to PushButton, ArrowButton,
and DrawnArrow\&.
.IP "PrimitiveParentActivate():" 10
If the parent is a manager,
passes the \fBKActivate\fP event received by the widget
to the parent\&.
.IP "PrimitiveParentCancel():" 10
If the parent is a manager,
passes the \fBKCancel\fP event received by the widget
to the parent\&.
.IP "PrimitivePrevTabGroup():" 10
This action depends on the value of the Display resource
\fBXmNenableButtonTab\fP\&. When \fBXmNenableButtonTab\fP is False
(default), this action traverses to the first item in the previous tab
group\&. If the beginning of the tab group list is reached, it wraps to
the end of the tab group list\&.
.IP "" 10
When \fBXmNenableButtonTab\fP is True, this action moves to the
previous item within the current tab group unless it is the first item
in the tab group\&. When the item is the first in the group, the action
traverses to the first item in the previous tab group\&. The
\fBXmNenableButtonTab\fP behavior applies only PushButton, ArrowButton, and
DrawnButton\&.
.IP "PrimitiveTraverseDown():" 10
Traverses to the next item below the current widget in the current tab
group, wrapping if necessary\&.
The wrapping direction depends on the layout direction of the
widget tab group\&.
.IP "PrimitiveTraverseHome():" 10
Traverses to the first widget or gadget in the current tab group\&.
.IP "PrimitiveTraverseLeft():" 10
Traverses to the next item to the left of the current widget in the
current tab group, wrapping if necessary\&.
The wrapping direction depends on the layout direction of the
widget tab group\&.
.IP "PrimitiveTraverseNext():" 10
Traverses to the next item in the current tab group, wrapping if
necessary\&.
The wrapping direction depends on the layout direction of the
widget tab group\&.
.IP "PrimitiveTraversePrev():" 10
Traverses to the previous item in the current tab group, wrapping if
necessary\&.
The wrapping direction depends on the layout direction of the
widget tab group\&.
.IP "PrimitiveTraverseRight():" 10
Traverses to the next item to the right of the current gadget in the
current tab group, wrapping if necessary\&.
The wrapping direction depends on the layout direction of the
widget tab group\&.
.IP "PrimitiveTraverseUp():" 10
Traverses to the next item above the current gadget in the current tab
group, wrapping if necessary\&.
The wrapping direction depends on the layout direction of the
widget tab group\&.
.SS "Additional Behavior"
.PP
This widget has the following additional behavior:
.IP "\fB<FocusIn>\fP:" 10
If the shell\&'s keyboard focus policy is \fBXmEXPLICIT\fP, highlights the
widget and gives it the focus
.IP "\fB<FocusOut>\fP:" 10
If the shell\&'s keyboard focus policy is \fBXmEXPLICIT\fP, unhighlights
the widget and removes the focus
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBCore\fP(3),
\fBXmDirection\fP(3),
\fBXmChangeColor\fP(3), and
\fBXmScreen\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
