'\" t
...\" ProcessT.sgm /main/8 1996/09/08 20:55:42 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmProcessTraversal" "library call"
.SH "NAME"
\fBXmProcessTraversal\fP \(em A function that determines which component receives keyboard events when a widget has the focus
.iX "XmProcessTraversal"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBBoolean \fBXmProcessTraversal\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmTraversalDirection \fBdirection\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmProcessTraversal\fP determines which component of a hierarchy
receives keyboard events when the hierarchy that contains the given
widget has keyboard focus\&.
.PP
\fBXmProcessTraversal\fP changes focus only when the keyboard focus
policy of the widget hierarchy is explicit\&.
If the \fBXmNkeyboardFocusPolicy\fP of the nearest shell ancestor of the
given widget is not \fBXmEXPLICIT\fP, \fBXmProcessTraversal\fP
returns False without making any focus changes\&.
.IP "\fIwidget\fP" 10
Specifies the widget ID of the widget whose hierarchy is to be
traversed
.IP "\fIdirection\fP" 10
Specifies the direction of traversal
.SS "DEFINITIONS"
.PP
In order to be eligible to receive keyboard focus when the shell\&'s
\fBXmNkeyboardFocusPolicy\fP is \fBXmEXPLICIT\fP, a widget or gadget
must meet the following conditions:
.IP "   \(bu" 6
The widget and its ancestors are not in the process of being destroyed\&.
.IP "   \(bu" 6
The widget and its ancestors are \fIsensitive\fP\&.
A widget is sensitive when its \fBXmNsensitive\fP and
\fBXmNancestorSensitive\fP resources are both True\&.
.IP "   \(bu" 6
The \fBXmNtraversalOn\fP resource for the widget and its ancestors is
True\&.
.IP "   \(bu" 6
The widget is viewable\&.
This means that the widget and its ancestors are managed, realized, and
(except for gadgets) mapped\&.
Furthermore, in general, some part of the widget\&'s rectangular area must
be unobscured by the widget\&'s ancestors\&. If an application unmaps a
widget that has its \fBXmNmappedWhenManaged\fP resource set to True, the
result is undefined\&.
.IP "" 10
In a ScrolledWindow with an \fBXmNscrollingPolicy\fP of
\fBXmAUTOMATIC\fP, a widget that is obscured because it is not within
the clip window may be able to receive focus if some part of the widget
is within the work area and if an \fBXmNtraverseObscuredCallback\fP
routine can make the widget at least partially visible by scrolling the
window\&.
.PP
In general only primitives, gadgets, and Drawing Area are eligible to
receive focus\&.
Most managers cannot receive focus even if they meet all these
conditions\&.
.PP
The \fIdirection\fP argument identifies the kind of traversal action to
take\&.
The descriptions of these actions below refer to traversable
non-tab-group widgets and traversable tab groups\&.
.IP "   \(bu" 6
A traversable non-tab-group widget is a widget that is not a tab group
and that meets all the conditions for receiving focus described above\&.
.IP "   \(bu" 6
A traversable tab group widget is a tab group widget that meets the same
conditions, except that a manager that is a tab group and meets the
other conditions is also eligible for traversal as long as it contains a
descendant that can receive focus\&.
.PP
A tab group is a widget whose \fBXmNnavigationType\fP is:
.IP "   \(bu" 6
\fBXmTAB_GROUP\fP or \fBXmSTICKY_TAB_GROUP\fP, if the hierarchy (up to
the nearest shell ancestor) that contains the widget has no widget whose
\fBXmNnavigationType\fP is \fBXmEXCLUSIVE_TAB_GROUP\fP
.IP "   \(bu" 6
\fBXmEXCLUSIVE_TAB_GROUP\fP or \fBXmSTICKY_TAB_GROUP\fP, if the
hierarchy (up to the nearest shell ancestor) that contains the widget
has any widget whose \fBXmNnavigationType\fP is
\fBXmEXCLUSIVE_TAB_GROUP\fP
.SS "TRAVERSAL ACTIONS"
.PP
The hierarchy to be traversed is that containing the \fIwidget\fP
argument\&.
This hierarchy is traversed only up to the nearest shell;
\fBXmProcessTraversal\fP does not move focus from one shell to another\&.
If the shell containing \fIwidget\fP does not currently have the focus,
any change that \fBXmProcessTraversal\fP makes to the element with focus
within that shell does not take effect until the next time the shell
receives focus\&.
.PP
\fBXmProcessTraversal\fP begins the traversal action from the widget in
the hierarchy that currently has keyboard focus or that last had focus
when the user traversed away from the shell hierarchy\&.
.PP
The value of the \fIdirection\fP argument determines which of three
kinds of traversal action to take:
.IP "   \(bu" 6
Traversal to a non-tab-group widget\&.
This kind of traversal is possible only when the widget that currently
has focus is not a tab group; otherwise, \fBXmProcessTraversal\fP
returns False for these actions\&.
.IP "" 10
These actions do not move focus from one tab group to another\&.
The actions first determine the containing tab group\&.
This is the tab group containing the widget that currently has focus\&.
The actions traverse only to a non-tab-group widget within the
containing tab group\&.
.IP "" 10
A non-tab-group widget is eligible for this kind of traversal if the
widget is traversable and has no tab group ancestors up to the
containing tab group\&.
If the tab group contains no traversable non-tab-group widgets,
\fBXmProcessTraversal\fP returns False\&.
.IP "" 10
Following are the possible values of the \fIdirection\fP argument\&.
Note that when actions wrap, wrapping occurs in the traversal
direction\&. The following describes what happens in a left
to right environment:
.RS
.IP "   \(bu" 6
\fBXmTRAVERSE_RIGHT\fP\(emIf the \fBXmNnavigationType\fP of the
containing tab group is not \fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to
the next traversable non-tab-group widget to the right of the widget
that currently has focus\&.
In a left to right environment, at the right side of the tab group
this action wraps to the
non-tab-group widget at the left side and next toward the bottom\&.
At the rightmost widget in the bottom row of the tab group this action
wraps to the
non-tab-group widget at the leftmost widget in the upper row\&.
.IP "" 10
In a right to left environment, at the right side of the tab group,
this action wraps to the non-tab-group widget at the left side and
next toward the top\&. At the rightmost widget in the upper row of the
tab group this action wraps to the non-tab-group widget at the
leftmost widget in the bottom row\&.
.IP "" 10
If the \fBXmNnavigationType\fP of the containing tab group is
\fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the next traversable
non-tab-group widget in the tab group, proceeding in the order in which
the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
After the last widget in the tab group, this action wraps to the first
non-tab-group widget\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_LEFT\fP\(emIf the \fBXmNnavigationType\fP of the
containing tab group is not \fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to
the next traversable non-tab-group widget to the left of the widget that
currently has focus\&.
In a left to right environment, at the left side of the tab group this
action wraps to the non-tab-group
widget at the right side and next toward the top\&.
At the leftmost widget in the upper row of the tab group this action
wraps to the non-tab-group widget at the rightmost widget in the
bottom row\&.
.IP "" 10
In a right to left environment, at the left side of the tab group this
action wraps to the non-tab-group widget at the right side and next
toward the bottom\&. At the leftmost widget in the bottom row of the
tab group this
action wraps to the non-tab-group widget at the rightmost widget in
the upper row\&.
.IP "" 10
If the \fBXmNnavigationType\fP of the containing tab group is
\fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the previous traversable
non-tab-group widget in the tab group, proceeding in the reverse order
in which the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
After the first widget in the tab group, this action wraps to the last
non-tab-group widget\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_DOWN\fP\(emIf the \fBXmNnavigationType\fP of the
containing tab group is not \fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to
the next traversable non-tab-group widget below the widget that
currently has focus\&.
In a left to right environment, at the bottom of the tab group this
action wraps to the non-tab-group
widget at the top and next toward the right\&.
At the bottom widget in the rightmost column of the tab group this action
wraps to the
non-tab-group widget at the top widget in the leftmost column\&.
.IP "" 10
In a right to left environment, at the bottom of the tab group this
action wraps to the non-tab-group widget at the top and next toward
the left\&. At the bottom widget of the leftmost widget of the tab
group this action wraps
to the non-tab-group widget at the top widget of the rightmost column\&.
.IP "" 10
If the \fBXmNnavigationType\fP of the containing tab group is
\fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the next traversable
non-tab-group widget in the tab group, proceeding in the order in which
the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
After the last widget in the tab group, this action wraps to the first
non-tab-group widget\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_UP\fP\(emIf the \fBXmNnavigationType\fP of the containing
tab group is not \fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the next
traversable non-tab-group widget above the widget that currently has
focus\&.
In a left to right environment, at the top of the tab group this
action wraps to the non-tab-group
widget at the bottom and next toward the left\&.
At the top widget of the leftmost column of the tab group this action
wraps to the
non-tab-group widget at the bottom widget of the rightmost column\&.
.IP "" 10
In a right to left environment, at the top of the tab group this
action wraps to the non-tab-group widget at the bottom and next toward
the right\&. At the top widget of the right most column of the tab
group this action
wraps to the non-tab-group widget at the bottom widget of the leftmost
column\&.
.IP "" 10
If the \fBXmNnavigationType\fP of the containing tab group is
\fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the previous traversable
non-tab-group widget in the tab group, proceeding in the reverse order
in which the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
After the first widget in the tab group, this action wraps to the last
non-tab-group widget\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_NEXT\fP\(emFocus moves to the next traversable
non-tab-group widget in the tab group, proceeding in the order in which
the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
After the last widget in the tab group, this action wraps to the first
non-tab-group widget\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_PREV\fP\(emFocus moves to the previous traversable
non-tab-group widget in the tab group, proceeding in the reverse order
in which the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
After the first widget in the tab group, this action wraps to the last
non-tab-group widget\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_HOME\fP\(emIf the \fBXmNnavigationType\fP of the containing
tab group is not \fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the first
traversable non-tab-group widget at the initial focus of the tab
group\&.
.IP "" 10
If the \fBXmNnavigationType\fP of the containing tab group is
\fBXmEXCLUSIVE_TAB_GROUP\fP, focus moves to the first traversable
non-tab-group widget in the tab group, according to the order in which
the widgets appear in their parents\&' \fBXmNchildren\fP lists\&.
.RE
.IP "   \(bu" 6
Traversal to a tab group\&.
These actions first determine the current widget hierarchy and the
containing tab group\&.
The current widget hierarchy is the widget hierarchy whose root is the
nearest shell ancestor of the widget that currently has focus\&.
The containing tab group is is the tab group containing the widget that
currently has focus\&.
If the current widget hierarchy contains no traversable tab groups,
\fBXmProcessTraversal\fP returns False\&.
.IP "" 10
Following are the possible values of the \fIdirection\fP argument\&. If
any tab group in the current widget hierarchy has an
\fBXmNnavigationType\fP of \fBXmEXCLUSIVE_TAB_GROUP\fP, traversal of
tab groups in the hierarchy proceeds to widgets in the order in which
their \fBXmNnavigationType\fP resources were specified as
\fBXmEXCLUSIVE_TAB_GROUP\fP or \fBXmSTICKY_TAB_GROUP\fP\&.:
.RS
.IP "   \(bu" 6
\fBXmTRAVERSE_NEXT_TAB_GROUP\fP\(emFinds the hierarchy that contains
\fIwidget\fP,
finds the active tab group (if any), and makes the next tab group the
active tab group in the hierarchy\&.
.IP "   \(bu" 6
\fBXmTRAVERSE_PREV_TAB_GROUP\fP\(emFinds the hierarchy that contains
\fIwidget\fP,
finds the active tab group (if any), and makes the previous tab group the
active tab group in the hierarchy\&.
.RE
.IP "   \(bu" 6
Traversal to any widget\&.
In this case the \fIwidget\fP argument is the widget to which
\fBXmProcessTraversal\fP tries to give focus\&.
If the widget is not traversable, \fBXmProcessTraversal\fP returns
False\&.
.IP "" 10
Following are the possible values of the \fIdirection\fP argument:
.RS
.IP "   \(bu" 6
\fBXmTRAVERSE_CURRENT\fP\(emFinds the hierarchy and the tab group that
contain \fIwidget\fP\&.
If this tab group is not the active tab group, this action
makes it the active tab group\&.
If \fIwidget\fP is an item in the active tab group, this action
makes it the active item\&.
If \fIwidget\fP is the active tab group, this action
makes the first traversable
item in the tab group the active item\&.
.RE
.SS "CAUTIONS"
.PP
Using \fBXmProcessTraversal\fP to traverse to MenuBars,
Pulldown menu panes, or Popup menu panes is not supported\&.
.PP
\fBXmProcessTraversal\fP cannot be called recursively\&.
In particular, an application cannot call this routine from an
\fBXmNfocusCallback\fP or \fBXmNlosingFocusCallback\fP procedure\&.
.SH "RETURN"
.PP
Returns True if the traversal action succeeded\&.
Returns False if the \fBXmNkeyboardFocusPolicy\fP of the nearest shell
ancestor of \fIwidget\fP is not \fBXmEXPLICIT\fP, if the traversal
action finds no traversable widget to receive focus, or if the call to
the routine has invalid arguments\&.
.SH "RELATED"
.PP
\fBXmGetVisibility\fP(3) and
\fBXmIsTraversable\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
