'\" t
...\" PushButA.sgm /main/12 1996/09/08 20:56:00 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmPushButton" "library call"
.SH "NAME"
\fBXmPushButton\fP \(em The PushButton widget class
.iX "XmPushButton"
.iX "widget class" "PushButton"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/PushB\&.h>
.fi
.SH "DESCRIPTION"
.PP
PushButton issues commands within an application\&.
It consists of a text label or pixmap surrounded
by a border shadow\&.
When a PushButton is selected, the shadow changes to give the appearance
that it has been pressed in\&. When a PushButton is
unselected, the shadow changes to give the appearance that it is out\&.
.PP
The default behavior associated with a PushButton in a menu depends on
the type of menu system in which it resides\&.
By default, \fB<Btn1>\fP controls the behavior of the PushButton\&.
In addition, \fB<Btn3>\fP controls the behavior of the PushButton if
it resides in a PopupMenu system\&.
The actual mouse button used is determined by its RowColumn parent\&.
.PP
Thickness for a second shadow, used when the PushButton is the default
button, may be specified with the
\fBXmNshowAsDefault\fP resource\&. If it has a nonzero value, the Label\&'s
resources \fBXmNmarginLeft\fP, \fBXmNmarginRight\fP, \fBXmNmarginTop\fP, and
\fBXmNmarginBottom\fP may be modified to accommodate the second shadow\&.
.PP
If an initial value is specified for \fBXmNarmPixmap\fP but not for
\fBXmNlabelPixmap\fP, the \fBXmNarmPixmap\fP value is used for
\fBXmNlabelPixmap\fP\&.
.PP
PushButton uses the \fBXmQTmenuSystem\fP and
\fBXmQTspecifyRenderTable\fP traits, and
holds the \fBXmQactivatable\fP, \fBXmQTmenuSavvy\fP, and
\fBXmQTtakesDefault\fP traits\&.
.SS "Classes"
.PP
PushButton inherits behavior, resources, and traits from \fBCore\fP,
\fBXmPrimitive\fP,
and \fBXmLabel\fP\&.
.PP
The class pointer is \fBxmPushButtonWidgetClass\fP\&.
.PP
The class name is \fBXmPushButton\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmPushButton Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNactivateCallbackXmCCallbackXtCallbackListNULLC
_____
XmNarmCallbackXmCCallbackXtCallbackListNULLC
_____
XmNarmColorXmCArmColorPixeldynamicCSG
_____
XmNarmPixmapXmCArmPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNdefaultButtonShadowThicknessXmCDefaultButtonShadowThicknessDimensiondynamicCSG
_____
XmNdisarmCallbackXmCCallbackXtCallbackListNULLC
_____
XmNfillOnArmXmCFillOnArmBooleanTrueCSG
_____
XmNmultiClickXmCMultiClickunsigned chardynamicCSG
_____
XmNshowAsDefaultXmCShowAsDefaultDimension0CSG
_____
.TE
.IP "\fBXmNactivateCallback\fP" 10
Specifies the list of callbacks that is called when PushButton is activated\&.
PushButton is activated when the user presses
and releases the active mouse button
while the pointer is inside that widget\&. Activating the PushButton
also disarms it\&.
For this callback, the reason is \fBXmCR_ACTIVATE\fP\&.
This callback uses the \fBXmQTactivatable\fP trait\&.
.IP "\fBXmNarmCallback\fP" 10
Specifies the list of callbacks that is called when PushButton is armed\&.
PushButton is armed when the user presses
the active mouse button while the pointer is inside that
widget\&.
For this callback, the reason is \fBXmCR_ARM\fP\&.
.IP "\fBXmNarmColor\fP" 10
Specifies the color with which to fill the armed button\&.
\fBXmNfillOnArm\fP must be set to True for this resource to have an effect\&.
The default for a color display is a color between the background and the
bottom shadow color\&. For a monochrome display, the default is set to the
foreground color, and any text in the label appears in the background
color when the button is armed\&.
.IP "" 10
This resource is also used when the button is armed in a menu
and the \fBXmNenableEtchedInMenu\fP resource is \fBTrue\fP\&.
.IP "\fBXmNarmPixmap\fP" 10
Specifies the pixmap to be used as the button face if \fBXmNlabelType\fP is
\fBXmPIXMAP\fP and PushButton is armed\&. This resource is disabled when the
PushButton is in a menu\&.
.IP "\fBXmNdefaultButtonShadowThickness\fP" 10
This resource specifies the width of the default button indicator shadow\&.
If this resource is 0 (zero), the width of the shadow comes from the value of
the \fBXmNshowAsDefault\fP resource\&. If this resource is greater than
0, the \fBXmNshowAsDefault\fP resource is only used to specify whether
this button is the default\&.
The default value is the initial value of \fBXmNshowAsDefault\fP\&.
.IP "\fBXmNdisarmCallback\fP" 10
Specifies the list of callbacks
that is called when PushButton is disarmed\&. PushButton is disarmed when
the user presses and releases the active mouse button
while the pointer is inside that widget\&. For this callback, the reason is
\fBXmCR_DISARM\fP\&.
.IP "\fBXmNfillOnArm\fP" 10
Forces the PushButton to fill the background of the button with the
color specified by \fBXmNarmColor\fP when the button is armed and when this
resource is set to True\&. If False, only the top and bottom
shadow colors are switched\&.
When the PushButton is in a menu, this resource is ignored and assumed to be
False\&.
.IP "\fBXmNmultiClick\fP" 10
If a button click is followed by another button click within the time
span specified by the display\&'s multiclick time, and this resource is
set to \fBXmMULTICLICK_DISCARD\fP, do not process the second click\&.
If this resource is set to \fBXmMULTICLICK_KEEP\fP, process the event
and increment \fIclick_count\fP in the callback structure\&.
When the button is in a menu, the default is \fBXmMULTICLICK_DISCARD\fP;
otherwise, for a button not in a menu, \fBXmMULTICLICK_KEEP\fP is
the default value\&.
.IP "\fBXmNshowAsDefault\fP" 10
If \fBXmNdefaultButtonShadowThickness\fP is greater than 0 (zero), a value
greater than 0 in this resource
specifies to mark this button as the default button\&.
If \fBXmNdefaultButtonShadowThickness\fP is 0, a value greater than
0 in this resource specifies to mark this button as the default
button with the shadow thickness specified by this resource\&.
When the Display resource \fBXmNdefaultButtonEmphasis\fP has a value of
\fBXmEXTERNAL_HIGHLIGHT\fP (the default), PushButton draws the
location cursor outside of the outer shadow\&. When this resource has a
value of \fBXmINTERNAL_HIGHLIGHT\fP, the highlight is drawn between
the inner and outer shadows\&.
The space between
the shadow and the default shadow is equal to the sum of both shadows\&.
The default value is 0\&. When this value is not 0, the Label
resources \fBXmNmarginLeft\fP, \fBXmNmarginRight\fP, \fBXmNmarginTop\fP, and
\fBXmNmarginBottom\fP may be modified to accommodate the second shadow\&.
This resource is disabled when the PushButton is in a menu\&.
.SS "Inherited Resources"
.PP
PushButton inherits behavior and resources from the
superclasses described the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmLabel Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorXmCAcceleratorStringNULLCSG
_____
XmNacceleratorTextXmCAcceleratorTextXmStringNULLCSG
_____
XmNalignmentXmCAlignmentunsigned chardynamicCSG
_____
XmNfontListXmCFontListXmFontListdynamicCSG
_____
XmNlabelInsensitivePixmapXmCLabelInsensitivePixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNlabelPixmapXmCLabelPixmapPixmapdynamicCSG
_____
XmNlabelStringXmCXmStringXmStringdynamicCSG
_____
XmNlabelTypeXmCLabelTypeunsigned charXmSTRINGCSG
_____
XmNmarginBottomXmCMarginBottomDimensiondynamicCSG
_____
XmNmarginHeightXmCMarginHeightDimension2CSG
_____
XmNmarginLeftXmCMarginLeftDimensiondynamicCSG
_____
XmNmarginRightXmCMarginRightDimensiondynamicCSG
_____
XmNmarginTopXmCMarginTopDimensiondynamicCSG
_____
XmNmarginWidthXmCMarginWidthDimension2CSG
_____
XmNmnemonicXmCMnemonicKeySymNULLCSG
_____
XmNmnemonicCharSetXmCMnemonicCharSetStringXmFONTLIST_DEFAULT_TAGCSG
_____
XmNrecomputeSizeXmCRecomputeSizeBooleanTrueCSG
_____
XmNrenderTableXmCRenderTableXmRenderTabledynamicCSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmPrimitive Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNconvertCallbackXmCCallbackXtCallbackListNULLC
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightOnEnterXmCHighlightOnEnterBooleanFalseCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimension2CSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmNONECSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
        int \fIclick_count\fP;
} XmPushButtonCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
.IP "\fIclick_count\fP" 10
This value is valid only when the reason is \fBXmCR_ACTIVATE\fP\&.
It contains the number of clicks in the last multiclick sequence
if the \fBXmNmultiClick\fP resource is set to \fBXmMULTICLICK_KEEP\fP,
otherwise it contains 1\&.
The activate callback is invoked for each click if \fBXmNmultiClick\fP
is set to \fBXmMULTICLICK_KEEP\fP\&.
.SS "Translations"
.PP
\fBXmPushButton\fP includes translations from \fIPrimitive\fP\&.
.PP
Note that altering translations in \fB#override\fP
or \fB#augment\fP mode is undefined\&.
.PP
Additional \fBXmPushButton\fP translations for \fBXmPushButtons\fP not in a
menu system are described in the following list\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fBc<Btn1Down>\fP:" 10
ButtonTakeFocus()
.IP "\fB\(apc\fP\fB<Btn1Down>\fP:" 10
Arm()
.IP "\fB\(apc\fP\fB<Btn1Down>\fP\fB,\(apc\fP\fB<Btn1Up>\fP:" 10
Activate() Disarm()
.IP "\fB\(apc\fP\fB<Btn1Down>\fP\fB(2+)\fP:" 10
MultiArm()
.IP "\fB\(apc\fP\fB<Btn1Up>\fP\fB(2+)\fP:" 10
MultiActivate()
.IP "\fB\(apc\fP\fB<Btn1Up>\fP:" 10
Activate() Disarm()
.IP "\fB\(apc\fP\fB<Btn2Down>\fP:" 10
ProcessDrag()
.IP "\fB:\fP\fB<Key>\fP\fB<osfActivate>\fP:" 10
PrimitiveParentActivate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCancel>\fP:" 10
PrimitiveParentCancel()
.IP "\fB:\fP\fB<Key>\fP\fB<osfSelect>\fP:" 10
ArmAndActivate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfHelp>\fP:" 10
Help()
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBReturn\fP:" 10
PrimitiveParentActivate()
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBspace\fP:" 10
ArmAndActivate()
.PP
\fBXmPushButton\fP inherits menu traversal translations
from \fBXmLabel\fP\&.
Additional XmPushButton translations for PushButtons in a
menu system are described in the following list\&.
In a Popup menu system, \fB<Btn3>\fP also performs the \fB<Btn1>\fP
actions\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fB<Btn2Down>\fP:" 10
ProcessDrag()
.IP "\fBc<Btn1Down>\fP:" 10
MenuButtonTakeFocus()
.IP "\fBc<Btn1Up>\fP:" 10
MenuButtonTakeFocusUp()
.IP "\fB\(apc\fP\fB<BtnDown>\fP:" 10
BtnDown()
.IP "\fB\(apc\fP\fB<BtnUp>\fP:" 10
BtnUp()
.IP "\fB:\fP\fB<Key>\fP\fB<osfSelect>\fP:" 10
ArmAndActivate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfActivate>\fP:" 10
ArmAndActivate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCancel>\fP:" 10
MenuEscape()
.IP "\fB:\fP\fB<Key>\fP\fB<osfHelp>\fP:" 10
Help()
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBReturn\fP:" 10
ArmAndActivate()
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBspace\fP:" 10
ArmAndActivate()
.SS "Action Routines"
.PP
The \fBXmPushButton\fP action routines are
.IP "Activate():" 10
This action draws the shadow in the unarmed
state\&.
If the button is not in a menu and if \fBXmNfillOnArm\fP is set to True,
the background color reverts to the unarmed color\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, \fBXmNlabelPixmap\fP is
used for the button face\&.
If the pointer is still within the button,
this action calls the callbacks for \fBXmNactivateCallback\fP\&.
.IP "Arm():" 10
This action arms the PushButton\&.
It draws the shadow in the armed state\&.
If the button is not in a menu and if \fBXmNfillOnArm\fP is set
to True, it fills the button with the color specified by
\fBXmNarmColor\fP\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, the \fBXmNarmPixmap\fP is
used for the button face\&.
It calls the \fBXmNarmCallback\fP callbacks\&.
.IP "ArmAndActivate():" 10
In a menu, unposts all menus in the menu hierarchy and,
unless the button is already armed,
calls the \fBXmNarmCallback\fP callbacks\&.
This action calls the \fBXmNactivateCallback\fP and
\fBXmNdisarmCallback\fP callbacks\&.
.IP "" 10
Outside a menu, draws the shadow in the armed state and, if
\fBXmNfillOnArm\fP is set to True, fills the button with the color
specified by \fBXmNarmColor\fP\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, \fBXmNarmPixmap\fP is
used for the button face\&.
This action calls the \fBXmNarmCallback\fP callbacks\&.
.IP "" 10
Outside a menu, this action also arranges for the following to happen,
either immediately or at a later time:
the shadow is drawn in the unarmed state and, if \fBXmNfillOnArm\fP is set
to True, the background color reverts to the unarmed color\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, \fBXmNlabelPixmap\fP is
used for the button face\&.
The \fBXmNactivateCallback\fP and \fBXmNdisarmCallback\fP callbacks are
called\&.
.IP "BtnDown():" 10
This action unposts any menus posted by the PushButton\&'s parent menu,
disables keyboard traversal for the menu, and enables mouse traversal
for the menu\&.
It draws the shadow in the armed state
and, unless the button is already armed, calls the \fBXmNarmCallback\fP
callbacks\&.
.IP "BtnUp():" 10
This action unposts all menus in the menu hierarchy and activates the
PushButton\&.
It calls the \fBXmNactivateCallback\fP callbacks and then the
\fBXmNdisarmCallback\fP callbacks\&.
.IP "ButtonTakeFocus():" 10
Causes the PushButton to take keyboard focus
when \fBCtrl<Btn1Down>\fP is pressed, without activating the widget\&.
.IP "Disarm():" 10
Calls the callbacks for \fBXmNdisarmCallback\fP\&.
.IP "Help():" 10
In a Pulldown or Popup MenuPane, unposts all menus in the menu hierarchy
and,
when the shell\&'s keyboard focus policy is
\fBXmEXPLICIT\fP,
restores keyboard focus to the widget that had the focus before
the menu system was entered\&.
This action calls the callbacks for \fBXmNhelpCallback\fP if any exist\&.
If there are no help
callbacks for this widget, this action calls the help callbacks
for the nearest ancestor that has them\&.
.IP "MenuShellPopdownOne():" 10
In a top-level Pulldown MenuPane from a MenuBar, unposts the menu,
disarms the MenuBar CascadeButton and the MenuBar; and,
when the shell\&'s keyboard focus policy is
\fBXmEXPLICIT\fP,
restores keyboard
focus to the widget that had the focus before the MenuBar was
entered\&.
In other Pulldown MenuPanes, it unposts the menu\&.
.IP "" 10
In a Popup MenuPane, this action
unposts the menu and restores keyboard focus to the
widget from which the menu was posted\&.
.IP "MultiActivate():" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_DISCARD\fP, this action does
nothing\&.
.IP "" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_KEEP\fP, this action
increments \fIclick_count\fP in the callback structure and
draws the shadow in the unarmed state\&.
If the button is not in a menu and if \fBXmNfillOnArm\fP is set to True,
the background color reverts to the unarmed color\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, the \fBXmNlabelPixmap\fP is
used for the button face\&.
If the pointer is within the PushButton, calls the
callbacks for \fBXmNactivateCallback\fP
and \fBXmNdisarmCallback\fP\&.
.IP "MultiArm():" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_DISCARD\fP, this action does
nothing\&.
.IP "" 10
If \fBXmNmultiClick\fP is \fBXmMULTICLICK_KEEP\fP, this action
draws the shadow in the armed state\&.
If the button is not in a menu and if \fBXmNfillOnArm\fP is set
to True, this action fills the button with the color specified by
\fBXmNarmColor\fP\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, the \fBXmNarmPixmap\fP is
used for the button face\&.
This action calls the \fBXmNarmCallback\fP callbacks\&.
.IP "ProcessDrag():" 10
Drags the contents of a PushButton label, identified when
\fBBTransfer\fP is pressed\&.
This action sets the \fBXmNconvertProc\fP of the DragContext to a
function that calls the \fBXmNconvertCallback\fP procedures, possibly
multiple times, for the \fB_MOTIF_DROP\fP selection\&.
This action is undefined for PushButtons used in a menu system\&.
.SS "Additional Behavior"
.PP
This widget has the following additional behavior:
.IP "\fB<EnterWindow>\fP:" 10
In a menu, if keyboard traversal is enabled, this action does nothing\&.
Otherwise, it draws the shadow in the armed state and calls the
\fBXmNarmCallback\fP callbacks\&.
.IP "" 10
If the PushButton is not in a menu and the cursor leaves and then
reenters the PushButton\&'s window while the button is pressed, this
action draws the shadow in the armed state\&.
If \fBXmNfillOnArm\fP is set to True, it also fills the button with the
color specified by \fBXmNarmColor\fP\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, \fBXmNarmPixmap\fP is
used for the button face\&.
.IP "\fB<LeaveWindow>\fP:" 10
In a menu, if keyboard traversal is enabled, this action does nothing\&.
Otherwise, it draws the shadow in the unarmed state and calls the
\fBXmNdisarmCallback\fP callbacks\&.
.IP "" 10
If the PushButton is not in a menu and the cursor leaves the
PushButton\&'s window while the button is pressed, this action draws the
shadow in the unarmed state\&.
If \fBXmNfillOnArm\fP is set to True, the background color reverts to
the unarmed color\&.
If \fBXmNlabelType\fP is \fBXmPIXMAP\fP, the \fBXmNlabelPixmap\fP is
used for the button face\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBCore\fP(3),
\fBXmCreatePushButton\fP(3), \fBXmLabel\fP(3),
\fBXmPrimitive\fP(3), and \fBXmRowColumn\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
