'\" t
...\" RepTypGC.sgm /main/8 1996/09/08 20:58:34 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRepTypeGetRecord" "library call"
.SH "NAME"
\fBXmRepTypeGetRecord\fP \(em A representation type manager function that
returns information about a representation type
.iX "XmRepTypeGetRecord"
.iX "representation type manager functions" "XmRepTypeGetRecord"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/RepType\&.h>
\fBXmRepTypeEntry \fBXmRepTypeGetRecord\fP\fR(
\fBXmRepTypeId \fBrep_type_id\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmRepTypeGetRecord\fP retrieves information about
a particular representation type that is registered with
the representation type manager\&. This routine allocates
memory for the returned data\&. The application must free
this memory using \fBXtFree\fP\&.
.IP "\fIrep_type_id\fP" 10
The identification number of the representation type
.PP
The representation type entry structure contains the following
information:
.PP
.nf
typedef struct
{
        String  \fIrep_type_name\fP;
        String  *\fIvalue_names\fP;
        unsigned char   *\fIvalues\fP;
        unsigned char   \fInum_values\fP;
        Boolean \fIreverse_installed\fP;
        XmRepTypeId     \fIrep_type_id\fP;
} XmRepTypeEntryRec, *XmRepTypeEntry;
\fB\fR(\fBvoid\fR)
.fi
.IP "\fIrep_type_name\fP" 10
The name of the representation type
.IP "\fIvalue_names\fP" 10
An array of representation type value names
.IP "\fIvalues\fP" 10
An array of representation type numerical values
.IP "\fInum_values\fP" 10
The number of values associated with the representation type
.IP "\fIreverse_installed\fP" 10
A flag that indicates whether or not the reverse converter is
installed
.IP "\fIrep_type_id\fP" 10
The identification number of the representation type
.SH "RETURN"
.PP
Returns a pointer to the representation type entry structure that
describes the representation type\&.
.SH "RELATED"
.PP
\fBXmRepTypeGetId\fP(3),
\fBXmRepTypeGetRegistered\fP(3), and
\fBXmRepTypeRegister\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
