'\" t
...\" RemFro.sgm /main/9 1996/09/08 20:56:37 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRemoveFromPostFromList" "library call"
.SH "NAME"
\fBXmRemoveFromPostFromList\fP \(em a RowColumn function that disables a menu for a particular widget
.iX "XmRemoveFromPostFromList"
.iX "RowColumn functions" "XmRemoveFromPostFromList"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/RowColumn\&.h>
.sp \n(PDu
\fBvoid \fBXmRemoveFromPostFromList\fP\fR(
\fBWidget \fBmenu\fR\fR,
\fBWidget \fBpost_from_widget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmRemoveFromPostFromList\fP makes a Popup or Pulldown menu no
longer accessible from a widget\&. This function does not destroy a
menu, or deallocate the memory associated with it\&. It simply removes
the widget from the menu\&'s list of widgets permitted to post that
menu\&.
.PP
If the \fImenu\fP argument refers to a Popup menu, the event handlers
are removed from the \fIpost_from_widget\fP widget\&. If the argument
refers to a Pulldown menu, its ID is removed from the
\fBXmNsubMenuId\fP of the specified \fIpost_from_widget\fP\&. Also, if
the menu is a Pulldown menu, the \fIpost_from_widget\fP widget must be
either a CascadeButton or a CascadeButtonGadget\&.
.IP "\fImenu\fP" 10
Specifies the widget ID of a the Popup or Pulldown menu to be
made inaccessible from the \fIpost_from_widget\fP widget\&.
.IP "\fIpost_from_widget\fP" 10
Specifies the widget ID of the widget which can no longer post the
menu referred to by the \fImenu\fP argument\&.\&.
.PP
For a complete definition of RowColumn and its associated resources, see
\fBXmRowColumn\fP(3)\&.
.SH "RELATED"
.PP
\fBXmAddToPostFromList\fP(3),
\fBXmGetPostedFromWidget\fP(3), and
\fBXmRowColumn\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
