'\" t
...\" RegistS.sgm /main/8 1996/09/08 20:56:29 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRegisterSegmentEncoding" "library call"
.SH "NAME"
\fBXmRegisterSegmentEncoding\fP \(em A compound string function that registers
a compound text encoding format for a specified font list element tag
.iX "XmRegisterSegment\\%Encoding"
.iX "compound string functions" "XmRegisterSegment\\%Encoding"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBchar * \fBXmRegisterSegmentEncoding\fP\fR(
\fBchar *\fBfontlist_tag\fR\fR,
\fBchar *\fBct_encoding\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmRegisterSegmentEncoding\fP registers a compound text encoding format
with the specified font list element tag\&. The \fBXmCvtXmStringToCT\fP
function uses this registry to map the font list tags of compound string
segments to compound text encoding formats\&. Registering
a font list tag that already exists in the registry overwrites the original
entry\&. You can unregister a font list tag by passing a NULL value for the
\fIct_encoding\fP parameter\&.
.IP "\fIfontlist_tag\fP" 10
Specifies the font list element tag to be registered\&. The
tag must be a NULL-terminated ISO8859-1 string\&.
.IP "\fIct_encoding\fP" 10
Specifies the compound text character set to be used for segments
with the font list tag\&. The value must be a NULL-terminated ISO8859-1 string\&.
A value of \fBXmFONTLIST_DEFAULT_TAG\fP maps the specified font list tag to
the code set of the locale\&.
.SH "RETURN"
.PP
Returns NULL for a new font list tag or the old \fIct_encoding\fP
value for an already registered font list tag\&. The
application is responsible for freeing the
storage associated with the returned data (if any) by
calling \fBXtFree\fP\&.
.SH "RELATED"
.PP
\fBXmCvtXmStringToCT\fP(3),
\fBXmFontList\fP(3),
\fBXmMapSegmentEncoding\fP(3), and
\fBXmString\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
