'\" t
...\" RendTaC.sgm /main/8 1996/09/08 20:57:28 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRenderTableCopy" "library call"
.SH "NAME"
\fBXmRenderTableCopy\fP \(em A render table function that copies renditions
.iX "XmRenderTableCopy"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmRenderTable \fBXmRenderTableCopy\fP\fR(
\fBXmRenderTable \fBtable\fR\fR,
\fBXmStringTag \fB*tags\fR\fR,
\fBint \fBtag_count\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmRenderTableCopy\fP creates a new render table
which will contain
the renditions of the \fItable\fP whose tags match those in \fItags\fP\&.
.IP "\fItable\fP" 10
Specifies the table containing the renditions to be copied\&.
.IP "\fItags\fP" 10
Specifies an array of tags, whose corresponding renditions are to be
copied\&. NULL indicates that the complete table should be copied\&.
.IP "\fItag_count\fP" 10
Specifies the number of tags in \fItags\fP\&.
.SH "RETURN"
.PP
Returns NULL if \fItable\fP is NULL\&. Otherwise, this function returns
the new render table\&.
This function allocates space to hold the new render table\&.
The application is responsible for managing this allocated space\&.
The application can recover this allocated space by calling \fBXmRenderTableFree\fP\&.
.SH "RELATED"
.PP
\fBXmRendition\fP(3) and
\fBXmRenderTableFree\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
