'\" t
...\" RepTypGA.sgm /main/8 1996/09/08 20:58:17 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRepTypeGetId" "library call"
.SH "NAME"
\fBXmRepTypeGetId\fP \(em A representation type manager function that
retrieves the identification number of a representation type
.iX "XmRepTypeGetId"
.iX "representation type manager functions" "XmRepTypeGetId"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/RepType\&.h>
\fBXmRepTypeId \fBXmRepTypeGetId\fP\fR(
\fBString \fBrep_type\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmRepTypeGetId\fP searches the registration list
for the specified representation type and returns the
associated identification number\&.
.IP "\fIrep_type\fP" 10
Specifies the representation type for which an identification
number is requested
.SH "RETURN"
.PP
Returns the identification number of the specified
representation type\&. If the representation type is not
registered, the function returns \fBXmREP_TYPE_INVALID\fP\&.
.SH "RELATED"
.PP
\fBXmRepTypeGetRegistered\fP(3) and
\fBXmRepTypeRegister\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
