'\" t
...\" RepTypGB.sgm /main/8 1996/09/08 20:58:26 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRepTypeGetNameList" "library call"
.SH "NAME"
\fBXmRepTypeGetNameList\fP \(em A representation type manager function that
generates a list of values for a representation type
.iX "XmRepTypeGetNameList"
.iX "representation type manager functions" "XmRepTypeGetNameList"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/RepType\&.h>
\fBString * \fBXmRepTypeGetNameList\fP\fR(
\fBXmRepTypeId \fBrep_type_id\fR\fR,
\fBBoolean \fBuse_uppercase_format\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmRepTypeGetNameList\fP generates a NULL-terminated list of
the value names associated with the specified representation type\&.
Each value name is a NULL-terminated string\&. This routine allocates
memory for the returned data\&. The application must free
this memory using \fBXtFree\fP\&.
.IP "\fIrep_type_id\fP" 10
Specifies the identification number of the representation type\&.
.IP "\fIuse_uppercase_format\fP" 10
Specifies a Boolean value that controls the format of the name
list\&. If the value is True, each value name is in uppercase characters prefixed
by \fBXm\fP; if it is False, the names are in lowercase characters\&.
.SH "RETURN"
.PP
Returns a pointer to an array of the value names\&.
.SH "RELATED"
.PP
\fBXmRepTypeGetId\fP(3),
\fBXmRepTypeGetRegistered\fP(3), and
\fBXmRepTypeRegister\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
