'\" t
...\" RowCol.sgm /main/11 1996/09/08 20:59:24 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmRowColumn" "library call"
.SH "NAME"
\fBXmRowColumn\fP \(em The RowColumn widget class
.iX "XmRowColumn"
.iX "widget class" "RowColumn"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/RowColumn\&.h>
.fi
.SH "DESCRIPTION"
.PP
The RowColumn widget is a general purpose RowColumn manager capable
of containing any widget type as a child\&.
In general, it requires no special
knowledge about how its children function and provides nothing
beyond support for several different layout styles\&. However, it can be
configured as a menu, in which case, it expects only certain children, and
it configures to a particular layout\&. The menus supported are MenuBar,
Pulldown or Popup menu panes, and OptionMenu\&.
RowColumn uses the \fBXmQTmenuSavvy\fP trait and holds the
\fBXmQTmenuSystem\fP trait\&.
.PP
The type of layout performed is controlled by how the application has set
the various layout resources\&.
It can be configured to lay out its children in either rows or
columns\&. In addition, the application can specify how the children are
laid out, as follows:
.IP "   \(bu" 6
The children are packed tightly together into either rows or columns
.IP "   \(bu" 6
Each child is placed in an identically sized
box (producing a symmetrical look)
.IP "   \(bu" 6
A specific layout (the current \fIx\fP and \fIy\fP positions of the children
control their location)
.PP
In addition, the application has control over both the spacing that
occurs between each row and column and the margin spacing
present between the edges of the RowColumn widget and any children
that are placed against it\&.
.PP
The default \fBXmNinsertPosition\fP procedure for the RowColumn
returns the value of \fBXmNpositionIndex\fP if one has been specified
for the child\&. Otherwise, this procedure returns the number of
children in the RowColumn\&'s \fBXmNnumChildren\fP list\&.
In a MenuBar, Pulldown menu pane, or Popup menu pane the default for the
\fBXmNshadowThickness\fP resource is 2\&.
In an OptionMenu or a WorkArea, (such as a RadioBox or CheckBox) this
resource is not applicable and its use is undefined\&.
If an application wishes to place a 3-D shadow around an OptionMenu or
WorkArea, it can create the RowColumn as a child of a Frame widget\&.
.PP
In a MenuBar, Pulldown menu pane, or Popup menu pane the
\fBXmNnavigationType\fP resource is not applicable and its use is
undefined\&.
In a WorkArea, the default for \fBXmNnavigationType\fP is
\fBXmTAB_GROUP\fP\&.
In an OptionMenu the default for \fBXmNnavigationType\fP is
\fBXmNONE\fP\&.
.PP
In a MenuBar, Pulldown menu pane, or Popup menu pane the
\fBXmNtraversalOn\fP resource is not applicable and its use is
undefined\&.
In an OptionMenu or WorkArea, the default for \fBXmNtraversalOn\fP is
True\&.
.PP
If the parent of the RowColumn is a MenuShell, the
\fBXmNmappedWhenManaged\fP resource is forced to False when the widget
is realized\&.
.PP
The user can specify resources in a resource file for the automatically
created widgets and gadgets of an OptionMenu\&. The following list
identifies the names of these widgets (or gadgets) and the associated
OptionMenu areas\&.
.IP "Option Menu Label Gadget" 10
\fBOptionLabel\fP
.IP "Option Menu Cascade Button" 10
\fBOptionButton\fP
.PP
For the Popup and Pulldown Menupanes, popup and pulldown menus have
particular behaviors when the
\fB<Btn1>\fP button is pressed outside the menus\&. These behaviors
are summarized here\&.
.PP
When there is already a popped up menu, a user can either press
\fB<Btn1>\fP in the same area as the
popped up menu, or can press \fB<Btn1>\fP in another area that should
have a menu popped up\&. When \fB<Btn1>\fP is pressed in the same
area as the already popped up menu, that menu is unposted\&.
If \fB<Btn1>\fP is pressed in a different area,
the associated popup menu is posted for the new area\&. Note, however,
that if the
\fBXmNpopupHandlerCallback\fP of either \fBXmManager\fP or
\fBXmPrimitive\fP is available, then the callback may override these
default behaviors\&.
.PP
For pulldown menus, a user can press \fB<Btn1>\fP on the
Cascade button to post the pulldown menu, then click on it again\&. Upon the
second click, the pulldown menu is unposted\&.
.PP
Popup menus are not allowed to have NULL parents\&.
.SS "Tear-off Menus"
.PP
Pulldown and Popup menu panes support tear-off menus, which enable the
user to retain a menu pane on the display to facilitate subsequent
menu selections\&. A menu pane that can be torn-off is identified by
a tear-off button that spans the width of the menu pane and displays
a dashed line\&. A torn-off menu pane contains a window manager system
menu icon and a title bar\&. The window title displays the label of the
cascade button that initiated the action when the label type is
\fBXmSTRING\fP\&. If the label contains a pixmap the window title is
empty\&. A tear-off menu from a Popup menu pane also displays
an empty title\&.
Tear-off menus should not be shared\&.
.PP
The user can tear off a menu pane using the mouse or keyboard\&.
Clicking \fB<Btn1>\fP or pressing \fB<osfActivate>\fP (or \fB<osfSelect>\fP)
on the tear-off button, tears off the menu pane at the current
position\&. Pressing \fB<Btn2>\fP on the tear-off button tears off the
menu pane and allows the user to drag the torn-off menu to a new
position designated by releasing the mouse button\&. Tearing off a
menu pane unposts the current active menu\&. Only one tear-off copy
for each menu pane is allowed\&. Subsequent tear-off actions of a
torn menu pane unpost the existing copy first\&.
.PP
The name of the tear-off button of a torn-off menu pane is
\fBTearOffControl\fP\&. The name can be used to set resources in a resource
file\&. An application can also obtain the tear-off button itself using
\fBXmGetTearOffControl\fP and then set resource values by calling
\fBXtSetValues\fP\&.
.PP
The tear-off button has Separator-like behavior\&. Its appearance can be
specified with the following tear-off button resources:
\fBXmNbackground\fP, \fBXmNbackgroundPixmap\fP,
\fBXmNbottomShadowColor\fP, \fBXmNforeground\fP, \fBXmNheight\fP,
\fBXmNmargin\fP, \fBXmNseparatorType\fP, \fBXmNshadowThickness\fP, and
\fBXmNtopShadowColor\fP\&. Refer to the \fBXmSeparator\fP reference
page for a complete description of each of these resources\&.
.PP
The \fBXmNtearOffModel\fP, \fBXmNtearOffMenuActivateCallback\fP, and
\fBXmNtearOffMenuDeactivateCallback\fP
are RowColumn resources that affect tear-off menu behavior\&.
The \fBXmNtearOffTitle\fP resource enables the application to specify
the tear-off menu\&'s title if the menu is torn off\&.
.PP
By default, menus do not tear off\&. Setting the
\fBXmNtearOffModel\fP resource to \fBXmTEAR_OFF_ENABLED\fP
enables tear-off functionality\&.
There is no resource converter
preregistered for \fBXmNtearOffModel\fP\&. To allow tear-off
functionality to be enabled through the resource database, call the
function \fBXmRepTypeInstallTearOffModelConverter\fP\&.
.PP
Tear-off menu focus policy follows standard window
manager policy\&. It is recommended that the
\fBstartupKeyFocus\fP and \fBautoKeyFocus\fP
\fBmwm\fP resources be set to True\&.
.SS "Descendants"
.PP
RowColumn automatically creates the descendants shown in the
following table\&.
An application can use \fBXtNameToWidget\fP to gain access
to the named descendant\&. In addition, a user or an application
can use the named descendant when specifying resource values\&.
.TS
tab() box;
l| l| l.
\fBNamed Descendant\fP\fBClass\fP\fBIdentity\fP
___
=
___
\fBOptionButton\fP\fBXmCascadeButtonGadget\fPoption menu button
___
\fBOptionLabel\fP\fBXmLabelGadget\fPoption menu label
___
\fBTearOffControl\fPsubclass of \fBXmPrimitive\fPT{
tear-off button of torn-off menu pane
T}
___
.TE
.SS "Classes"
.PP
RowColumn inherits behavior, resources, and traits from \fBCore\fP,
\fBComposite\fP,
\fBConstraint\fP, and \fBXmManager\fP classes\&.
.PP
The class pointer is \fBxmRowColumnWidgetClass\fP\&.
.PP
The class name is \fBXmRowColumn\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmRowColumn Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNadjustLastXmCAdjustLastBooleanTrueCSG
_____
XmNadjustMarginXmCAdjustMarginBooleanTrueCSG
_____
XmNentryAlignmentXmCAlignmentunsigned charXmALIGNMENT_BEGINNINGCSG
_____
XmNentryBorderXmCEntryBorderDimension0CSG
_____
XmNentryCallbackXmCCallbackXtCallbackListNULLC
_____
XmNentryClassXmCEntryClassWidgetClassdynamicCSG
_____
XmNentryVerticalAlignmentXmCVerticalAlignmentunsigned charXmALIGNMENT_CENTERCSG
_____
XmNisAlignedXmCIsAlignedBooleanTrueCSG
_____
XmNisHomogeneousXmCIsHomogeneousBooleandynamicCG
_____
XmNlabelStringXmCXmStringXmStringNULLC
_____
XmNmapCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmarginHeightXmCMarginHeightDimensiondynamicCSG
_____
XmNmarginWidthXmCMarginWidthDimensiondynamicCSG
_____
XmNmenuAcceleratorXmCAcceleratorsStringdynamicCSG
_____
XmNmenuHelpWidgetXmCMenuWidgetWidgetNULLCSG
_____
XmNmenuHistoryXmCMenuWidgetWidgetNULLCSG
_____
XmNmenuPostXmCMenuPostStringNULLCSG
_____
XmNmnemonicXmCMnemonicKeySymNULLCSG
_____
XmNmnemonicCharSetXmCMnemonicCharSetStringXmFONTLIST_DEFAULT_TAGCSG
_____
XmNnumColumnsXmCNumColumnsshort1CSG
_____
XmNorientationXmCOrientationunsigned chardynamicCSG
_____
XmNpackingXmCPackingunsigned chardynamicCSG
_____
XmNpopupEnabledXmCPopupEnabledintXmPOPUP_KEYBOARDCSG
_____
XmNradioAlwaysOneXmCRadioAlwaysOneBooleanTrueCSG
_____
XmNradioBehaviorXmCRadioBehaviorBooleanFalseCSG
_____
XmNresizeHeightXmCResizeHeightBooleanTrueCSG
_____
XmNresizeWidthXmCResizeWidthBooleanTrueCSG
_____
XmNrowColumnTypeXmCRowColumnTypeunsigned charXmWORK_AREACG
_____
XmNspacingXmCSpacingDimensiondynamicCSG
_____
XmNsubMenuIdXmCMenuWidgetWidgetNULLCSG
_____
XmNtearOffMenuActivateCallbackXmCCallbackXtCallbackListNULLC
_____
XmNtearOffMenuDeactivateCallbackXmCCallbackXtCallbackListNULLC
_____
XmNtearOffModelXmCTearOffModelunsigned charXmTEAR_OFF_DISABLEDCSG
_____
XmNtearOffTitleXmCTearOffTitleXmStringNULLCSG
_____
XmNunmapCallbackXmCCallbackXtCallbackListNULLC
_____
XmNwhichButtonXmCWhichButtonunsigned intdynamicCSG
_____
.TE
.IP "\fBXmNadjustLast\fP" 10
Extends the last row of children to the bottom edge of RowColumn (when
\fBXmNorientation\fP is \fBXmHORIZONTAL\fP) or extends the last column to the
right edge of RowColumn (when \fBXmNorientation\fP is \fBXmVERTICAL\fP)\&.
Setting \fBXmNadjustLast\fP to False disables this feature\&.
.IP "\fBXmNadjustMargin\fP" 10
Specifies whether the inner minor margins of all
items contained within the RowColumn widget are
forced to the same value\&. The inner minor margin
corresponds to the \fBXmNmarginLeft\fP, \fBXmNmarginRight\fP,
\fBXmNmarginTop\fP,
and \fBXmNmarginBottom\fP resources supported by \fBXmLabel\fP and
\fBXmLabelGadget\fP\&.
.IP "" 10
A horizontal orientation causes \fBXmNmarginTop\fP and
\fBXmNmarginBottom\fP for all items in a particular row to be forced to the
same value; the value is the largest margin specified
for one of the Label items\&.
.IP "" 10
A vertical orientation causes
\fBXmNmarginLeft\fP and \fBXmNmarginRight\fP for all items in a particular
column to be forced to the same value; the value is the largest
margin specified for one of the Label items\&.
.IP "" 10
This keeps all text within each row or column
lined up with all other text in its row or column\&.
If \fBXmNrowColumnType\fP is either \fBXmMENU_POPUP\fP or
\fBXmMENU_PULLDOWN\fP and this resource is True, only button children
have their margins adjusted\&.
.IP "\fBXmNentryAlignment\fP" 10
Specifies the alignment type for children that are subclasses of
\fBXmLabel\fP or \fBXmLabelGadget\fP when \fBXmNisAligned\fP is enabled\&.
The following are textual alignment types:
.RS
.IP "   \(bu" 6
\fBXmALIGNMENT_BEGINNING\fP (default)
.IP "   \(bu" 6
\fBXmALIGNMENT_CENTER\fP
.IP "   \(bu" 6
\fBXmALIGNMENT_END\fP
.RE
.IP "" 10
See the description of \fBXmNalignment\fP in the \fBXmLabel\fP(3)
reference page for an explanation of these actions\&.
.IP "\fBXmNentryBorder\fP" 10
Imposes a uniform border width upon all RowColumn\&'s children\&.
The default value is 0 (zero), which disables the feature\&.
.IP "\fBXmNentryCallback\fP" 10
Disables the \fBXmNactivateCallback\fP and \fBXmNvalueChangedCallback\fP
callbacks for all CascadeButton, DrawnButton, PushButton, and
ToggleButton widgets and gadgets contained within the RowColumn widget\&.
If the application supplies this resource, the \fBXmNactivateCallback\fP
and \fBXmNvalueChangedCallback\fP callbacks are then revectored to the
\fBXmNentryCallback\fP callbacks\&.
This allows an application to supply a single callback routine for
handling all items contained in a RowColumn widget\&.
The callback reason is \fBXmCR_ACTIVATE\fP\&.
If the application does not supply this resource, the
\fBXmNactivateCallback\fP and \fBXmNvalueChangedCallback\fP
callbacks for each item in the RowColumn widget work as normal\&.
.IP "" 10
The application must supply this resource when this widget is created\&.
Changing this resource using the \fBXtSetValues\fP is not
supported\&.
.IP "\fBXmNentryClass\fP" 10
Specifies the only widget class that can be added
to the RowColumn widget; this resource is meaningful only when the
\fBXmNisHomogeneous\fP resource is set to True\&.
Both widget and gadget variants of the specified class may be added to
the widget\&.
.IP "" 10
When \fBXmCreateRadioBox\fP is called or when \fBXmNrowColumnType\fP is
set to \fBXmWORK_AREA\fP and \fBXmNradioBehavior\fP is True, the default
value of \fBXmNentryClass\fP is
\fBxmToggleButtonGadgetClass\fP\&.
When \fBXmNrowColumnType\fP is set to \fBXmMENU_BAR\fP, the value of
\fBXmNentryClass\fP is forced to \fBxmCascadeButtonWidgetClass\fP\&.
.IP "\fBXmNentryVerticalAlignment\fP" 10
Specifies the type of vertical alignment for children that are
subclasses of \fBXmLabel\fP, \fBXmLabelGadget, and\fP \fBXmText\fP\&.
This resource is invalid if \fBXmNorientation\fP is \fBXmVERTICAL\fP
and \fBXmNpacking\fP is \fBXmPACK_TIGHT\fP, because this layout
preserves variable heights among the children\&. The vertical alignment
types include:
.RS
.IP "\fBXmALIGNMENT_BASELINE_BOTTOM\fP" 10
Causes the bottom baseline of all
children in a row to be aligned\&.
This resource is applicable only when all children in a row
contain textual data\&.
.IP "\fBXmALIGNMENT_BASELINE_TOP\fP" 10
Causes the top baseline of all
children in a row to be aligned\&.
This resource is applicable only when all children in a
row contain textual data\&.
.IP "\fBXmALIGNMENT_CONTENTS_BOTTOM\fP" 10
Causes the bottom of the
contents (text or
pixmap) of all children in a row to be aligned\&.
.IP "\fBXmALIGNMENT_CENTER\fP" 10
Causes the center of all children in a row to be
aligned\&.
.IP "\fBXmALIGNMENT_CONTENTS_TOP\fP" 10
Causes the top of the contents (text or
pixmap) of all children in a row to be aligned\&.
.RE
.IP "\fBXmNisAligned\fP" 10
Specifies text alignment for each item within the RowColumn widget;
this applies only to items that are subclasses of
\fBXmLabel\fP or \fBXmLabelGadget\fP\&.
However, if the item is a Label widget or gadget and its parent is either
a Popup menu pane or a Pulldown menu pane, alignment is not
performed; the Label is treated as the
title within the
menu pane, and the alignment
set by the application is not overridden\&.
\fBXmNentryAlignment\fP controls the type of textual alignment\&.
.IP "\fBXmNisHomogeneous\fP" 10
Indicates whether the RowColumn
widget should enforce exact homogeneity among the items
it contains; if this resource is set to True, only the widgets that are
of the class indicated by \fBXmNentryClass\fP
are allowed as children of the RowColumn widget\&.
This is most often used when creating a MenuBar\&.
Attempting to insert a child that is not a member of the
specified class generates a warning message\&.
.IP "" 10
In a MenuBar, the value of \fBXmNisHomogeneous\fP is forced to True\&.
In an OptionMenu, the value is forced to False\&.
When \fBXmCreateRadioBox\fP is called the default value is True\&.
Otherwise, the default value is False\&.
.IP "\fBXmNlabelString\fP" 10
When \fBXmNrowColumnType\fP is set to \fBXmMENU_OPTION\fP,
this resource points to a text string that displays the label with
respect to the selection area\&. The positioning of the label relative to the
selection area depends on the layout
direction in the horizontal orientation\&.
This resource is not meaningful for all other RowColumn types\&.
If the application wishes to change the label after creation, it must get the
LabelGadget ID (\fBXmOptionLabelGadget\fP) and call \fBXtSetValues\fP on the
LabelGadget directly\&. The default value is no label\&.
.IP "\fBXmNmapCallback\fP" 10
Specifies a widget-specific callback function that is
invoked when the window associated with the RowColumn widget
is about to be mapped\&. The callback reason is \fBXmCR_MAP\fP\&.
.IP "\fBXmNmarginHeight\fP" 10
Specifies the amount of blank space between the top
edge of the RowColumn widget and the first item in each column,
and the bottom edge of the RowColumn widget and the last item
in each column\&.
The default value is 0 (zero) for Pulldown and Popup menu panes, and 3
pixels for other RowColumn types\&.
.IP "\fBXmNmarginWidth\fP" 10
Specifies the amount of blank space between the left
edge of the RowColumn widget and the first item in each row,
and the right edge of the RowColumn widget and the last item in
each row\&.
The default value is 0 (zero) for Pulldown and Popup menu panes, and 3
pixels for other RowColumn types\&.
.IP "\fBXmNmenuAccelerator\fP" 10
This resource is useful only when the RowColumn widget has been configured
to operate as a Popup menu pane or a MenuBar\&.
The format of this resource is similar to the left side specification
of a translation string, with the limitation that it must specify a key
event\&.
For a Popup menu pane, when the accelerator is typed by the user, the Popup
menu pane is posted\&.
For a MenuBar, when the accelerator is typed by the user, the first item
in the MenuBar is highlighted, and traversal is enabled in the
MenuBar\&.
The default for a Popup menu pane is \fB<osfMenu>\fP\&.
The default for a MenuBar is \fB<osfMenuBar>\fP\&.
Setting the \fBXmNpopupEnabled\fP resource to False disables
the accelerator\&.
.IP "\fBXmNmenuHelpWidget\fP" 10
Specifies the widget ID for the CascadeButton, which is treated as
the Help widget if \fBXmNrowColumnType\fP is set to \fBXmMENU_BAR\fP\&.
Which corner of the MenuBar the Help widget is placed at depends on
the \fBXmNlayoutDirection\fP resource of the widget\&.
If the RowColumn widget is any type other than \fBXmMENU_BAR\fP,
this resource is not meaningful\&.
.IP "\fBXmNmenuHistory\fP" 10
Specifies the widget ID of the last menu entry to be activated\&. It is
also useful for specifying the current selection for an OptionMenu\&. If
\fBXmNrowColumnType\fP is set to \fBXmMENU_OPTION\fP, the specified
menu item is positioned under the cursor when the menu is displayed\&.
.IP "" 10
If the RowColumn widget has the \fBXmNradioBehavior\fP resource set to
True,
the widget field associated with this resource
contains the widget ID of the last ToggleButton or ToggleButtonGadget
to change from unselected to selected\&.
The default value is the widget ID of the first child in
the widget\&.
.IP "\fBXmNmenuPost\fP" 10
Specifies an X event description indicating a button event that posts a menu
system\&.
The default for \fBXmMENU_POPUP\fP is \fBBMenu Press\fP\&.
The default for \fBXmMENU_OPTION\fP, \fBXmMENU_BAR\fP, and
\fBXmWORK_AREA\fP is \fB<Btn1>\fP \fBPress\fP\&.
The \fBXmNmenuPost\fP resource for pulldowns should be consistent with that of
the top-level parent menu (although the event type is ignored)\&.
Setting this resource to \fBBTransfer Press\fP will conflict with drag and drop
operations, which use \fBBTransfer Press\fP as a default button binding\&.
Therefore, this resource cannot be \fBBTransfer Press\fP\&.
.IP "\fBXmNmnemonic\fP" 10
This resource is useful only when \fBXmNrowColumnType\fP is
set to \fBXmMENU_OPTION\fP\&.
It specifies a keysym for a key that, when pressed by the user along with
the \fBMAlt\fP modifier, posts
the associated Pulldown menu pane\&.
The first character in the OptionMenu label string that exactly matches
the mnemonic in the character set specified in \fBXmNmnemonicCharSet\fP
is underlined\&.
The user can post the menu by pressing either the shifted or the
unshifted mnemonic key\&.
The default is no mnemonic\&.
.IP "\fBXmNmnemonicCharSet\fP" 10
Specifies the character set of the mnemonic for an OptionMenu\&.
The default is \fBXmFONTLIST_DEFAULT_TAG\fP\&.
If the RowColumn widget is any type other than \fBXmMENU_OPTION\fP,
this resource is not meaningful\&.
.IP "\fBXmNnumColumns\fP" 10
Specifies the number of minor dimension extensions
that are made to accommodate the entries; this
attribute is meaningful only when \fBXmNpacking\fP is set to
\fBXmPACK_COLUMN\fP\&.
.IP "" 10
For vertically oriented RowColumn widgets, this attribute
indicates how many columns are built; the number of
entries per column is adjusted to maintain this
number of columns, if possible\&.
.IP "" 10
For horizontally oriented RowColumn widgets, this attribute
indicates how many rows are built\&.
.IP "" 10
The default value is 1\&.
In an OptionMenu the value is forced to 1\&.
The value must be greater than 0 (zero)\&.
.IP "\fBXmNorientation\fP" 10
Determines whether RowColumn layouts are row-major or column-major\&.
In a column-major layout, the children of the RowColumn
are laid out in
columns within the widget\&. In a row-major layout the children of
the RowColumn are laid out in rows\&. The direction of the horizontal
layout in the row-major layout (from left or right), and the wrapping in
the column-major layout (vertical), depend on the
\fBXmNlayoutDirection\fP resource of the widget\&.
The \fBXmVERTICAL\fP resource value
selects a column-major layout\&.
\fBXmHORIZONTAL\fP selects a row-major layout\&.
.IP "" 10
When creating a MenuBar or an OptionMenu, the default is
\fBXmHORIZONTAL\fP\&.
Otherwise, the default value is \fBXmVERTICAL\fP\&.
The results of specifying a value of \fBXmVERTICAL\fP for a MenuBar are
undefined\&.
.IP "\fBXmNpacking\fP" 10
Specifies how to pack the items contained within a
RowColumn widget\&. This can be set to \fBXmPACK_TIGHT, XmPACK_COLUMN\fP or \fBXmPACK_NONE\fP\&. When a RowColumn widget
packs the items it contains, it determines its major
dimension using the value of the \fBXmNorientation\fP resource\&.
.IP "" 10
\fBXmPACK_TIGHT\fP indicates that given the current major
dimension (for example, vertical if \fBXmNorientation\fP is \fBXmVERTICAL\fP), entries
are placed one after the other until
the RowColumn widget must wrap\&. RowColumn wraps when there is no room left
for a complete child in that dimension\&.
Wrapping occurs
by beginning a new row or column in the next available
space\&. Wrapping continues, as often as necessary, until
all of the children are laid out\&.
In the vertical dimension (columns), boxes are set to the same width; in the
horizontal dimension (rows), boxes are set to the same depth\&.
Each
entry\&'s position in the major dimension is left unaltered (for example,
\fBXmNy\fP is left unchanged when \fBXmNorientation\fP is \fBXmVERTICAL\fP); its
position in the minor
dimension is set to the same value as the greatest entry
in that particular row or column\&. The position in the minor
dimension of any particular row or column is independent
of all other rows or columns\&.
.IP "" 10
\fBXmPACK_COLUMN\fP indicates that all entries are placed in
identically sized boxes\&. The boxes are based on the largest height
and width values of all the children widgets\&.
The value of the \fBXmNnumColumns\fP
resource determines how many boxes are placed in the
major dimension, before extending in the minor dimension\&.
.IP "" 10
\fBXmPACK_NONE\fP indicates that no packing is performed\&.
The \fIx\fP and \fIy\fP attributes of each entry are left alone, and
the RowColumn widget attempts to become large enough to enclose all
entries\&.
.IP "" 10
When \fBXmCreateRadioBox\fP is called or when \fBXmNrowColumnType\fP
is set to \fBXmWORK_AREA\fP and \fBXmNradioBehavior\fP is True, the
default value of \fBXmNpacking\fP is \fBXmPACK_COLUMN\fP\&.
In an OptionMenu the value is initialized to \fBXmPACK_TIGHT\fP\&.
Otherwise, the value defaults to \fBXmPACK_TIGHT\fP\&.
.IP "\fBXmNpopupEnabled\fP" 10
Allows the menu system
to enable keyboard input (accelerators and mnemonics) defined for the Popup
menu pane and any of its submenus\&.
The Popup menu pane needs to be informed whenever its accessibility to the user
changes because posting of the Popup menu pane is controlled by the
application\&.
This resource can take four values, including:
.RS
.IP "\fBXmPOPUP_KEYBOARD\fP" 10
Specifies that the keyboard
input\(emaccelerators and mnemonics\(emdefined for the Popup menu pane
and any of its submenus is enabled\&. This is the default\&.
.IP "\fBXmPOPUP_DISABLED\fP" 10
Specifies that the keyboard input is disabled\&.
.IP "\fBXmPOPUP_AUTOMATIC\fP" 10
Specifies that the keyboard is enabled for automatic popup menus\&.
.IP "\fBXmPOPUP_AUTOMATIC_RECURSIVE\fP" 10
Specifies that the keyboard is enabled for recursive automatic popup menus\&.
.RE
.IP "\fBXmNradioAlwaysOne\fP" 10
If True, forces the active ToggleButton or ToggleButtonGadget
to be automatically selected after having
been unselected (if no other toggle was activated)\&.
If False, the active toggle may be unselected\&.
The default value is True\&. This resource is important only when
\fBXmNradioBehavior\fP is True\&.
.IP "" 10
The application can always add and subtract toggles from
RowColumn regardless of the selected/unselected state of the toggle\&. The
application can also manage and unmanage toggle
children of RowColumn at any time regardless of state\&. Therefore,
the application can sometimes
create a RowColumn that has \fBXmNradioAlwaysOne\fP set to
True and none
of the toggle children selected\&.
The result is undefined if the value of this resource is True and the
application sets more than one ToggleButton at a time\&.
.IP "\fBXmNradioBehavior\fP" 10
Specifies a Boolean value that when True, indicates
that the RowColumn widget should enforce a RadioBox-type behavior
on all of its children that are ToggleButtons or
ToggleButtonGadgets\&.
.IP "" 10
When the value of this resource is True,
\fBXmNindicatorType\fP defaults to \fBXmONE_OF_MANY\fP
for ToggleButton and ToggleButtonGadget children\&.
.IP "" 10
RadioBox
behavior dictates that when one toggle is selected and the user selects another
toggle, the first toggle is unselected
automatically\&.
The RowColumn usually does not enforce this behavior if the application,
rather than the user, changes the state of a toggle\&.
The RowColumn does enforce this behavior if a toggle child is selected
with \fBXmToggleButtonSetState\fP or \fBXmToggleButtonGadgetSetState\fP
with a \fInotify\fP argument of True\&.
.IP "" 10
When \fBXmCreateRadioBox\fP is called, the default value of
\fBXmNradioBehavior\fP is True\&.
Otherwise, the default value is False\&.
.IP "\fBXmNresizeHeight\fP" 10
Requests a new height if necessary, when set to True\&. When this
resource is set to
False, the widget does not request a new height regardless of any
changes to the widget or its children\&.
.IP "\fBXmNresizeWidth\fP" 10
Requests a new width if necessary, when set to True\&. When set to
False, the widget does not request a new width regardless of any
changes to the widget or its children\&.
.IP "\fBXmNrowColumnType\fP" 10
Specifies the type of RowColumn widget
to be created\&.
It is a nonstandard resource that cannot be changed after it is set\&.
If an application uses any of the
convenience routines, except \fBXmCreateRowColumn\fP,
this resource is automatically forced to the appropriate
value by the convenience routine\&. If an application uses
the Xt Intrinsics API to create its RowColumn widgets,
it must specify this resource itself\&. The set
of possible settings for this resource are
.RS
.IP "   \(bu" 6
\fBXmWORK_AREA\fP (default)
.IP "   \(bu" 6
\fBXmMENU_BAR\fP
.IP "   \(bu" 6
\fBXmMENU_PULLDOWN\fP
.IP "   \(bu" 6
\fBXmMENU_POPUP\fP
.IP "   \(bu" 6
\fBXmMENU_OPTION\fP
.RE
.IP "" 10
This resource cannot be changed after the RowColumn widget
is created\&. Any changes attempted through \fBXtSetValues\fP
are ignored\&.
.IP "" 10
The value of this resource is used to determine the value of a number
of other resources\&. The descriptions of RowColumn resources explain
this when it is the case\&. The resource \fBXmNnavigationType\fP,
inherited from \fBXmManager\fP, is changed to \fBXmNONE\fP if
\fBXmNrowColumnType\fP is \fBXmMENU_OPTION\fP\&.
.IP "\fBXmNspacing\fP" 10
Specifies the horizontal and vertical spacing between
items contained within the RowColumn widget\&.
The default value is 3 pixels for \fBXmOPTION_MENU\fP and
\fBXmWORK_AREA\fP and 0 (zero) for other RowColumn types\&.
.IP "\fBXmNsubMenuId\fP" 10
Specifies the widget ID for the Pulldown menu pane to be associated with
an OptionMenu\&. This resource is useful only when \fBXmNrowColumnType\fP is
set to \fBXmMENU_OPTION\fP\&.
The default value is NULL\&.
.IP "\fBXmNtearOffMenuActivateCallback\fP" 10
Specifies the callback list that notifies the application when
the tear-off menu pane is about to be activated\&. It precedes the tear-off\&'s
map callback\&.
.IP "" 10
Use this resource when your application has shared menu panes and when
the torn-off menu can have two or
more parents that can have opposing sensitivity states for the same
menu item\&.
This resource enables
the application to track
whether a menu item is sensitive or insensitive and to set the state to the
original parent\&'s menu item state when the torn-off menu is reposted\&.
The application can use \fBXmGetPostedFromWidget\fP to determine from which
parent the menu was torn\&. The callback reason is \fBXmCR_TEAR_OFF_ACTIVATE\fP\&.
The default is NULL\&.
.IP "\fBXmNtearOffMenuDeactivateCallback\fP" 10
Specifies the callback list that notifies the application when
the tear-off menu pane is about to be deactivated\&. It follows the tear-off\&'s
unmap callback\&.
.IP "" 10
Use this resource when your application has shared menu panes and when
the torn-off menu can have two or
more parents that can have opposing sensitivity states for the same
menu item\&.
This resource enables
the application to track
whether a menu item is sensitive or insensitive and to set the state to the
original parent\&'s menu item state when the torn-off menu is reposted\&.
The application can use \fBXmGetPostedFromWidget\fP to determine from which
parent the menu was torn\&.
The callback reason is \fBXmCR_TEAR_OFF_DEACTIVATE\fP\&. The default is NULL\&.
.IP "\fBXmNtearOffModel\fP" 10
Indicates whether tear-off functionality is enabled or disabled
when \fBXmNrowColumnType\fP is set to \fBXmMENU_PULLDOWN\fP or
\fBXmMENU_POPUP\fP\&. The values are \fBXmTEAR_OFF_ENABLED\fP or
\fBXmTEAR_OFF_DISABLED\fP (default value)\&. This resource is
invalid for type \fBXmMENU_OPTION\fP; however, it does affect
any pulldown
submenus within an OptionMenu\&.
The function \fBXmRepTypeInstallTearOffModelConverter\fP installs
a resource converter for this resource\&.
.IP "\fBXmNtearoffTitle\fP" 10
Used by the TearOff shell to set the title for the window manager to
display\&.
.IP "\fBXmNunmapCallback\fP" 10
Specifies a list of callbacks that is called
after the window associated with the RowColumn
widget has been unmapped\&. The callback reason is \fBXmCR_UNMAP\fP\&.
The default value is NULL\&.
.IP "\fBXmNwhichButton\fP" 10
This resource is obsolete; it has been replaced by \fBXmNmenuPost\fP and
is present for compatibility with older releases of Motif\&.
This resource cannot be 2\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmRowColumn Constraint Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNpositionIndexXmCPositionIndexshortXmLAST_POSITIONCSG
_____
.TE
.IP "\fBXmNpositionIndex\fP" 10
Specifies the position of the widget in its parent\&'s list of
children (the value of the \fBXmNchildren\fP resource)\&. The value
is an integer that is no less than 0 (zero) and no greater than
the number of children in the list at the time the value is
specified\&. A value of 0 (zero) means that the child is placed at the
beginning of the list\&. The value can also be specified as
\fBXmLAST_POSITION\fP (the default), which means that the child
is placed at the end of the list\&. Any other value is ignored\&.
\fBXtGetValues\fP returns the position of the widget in its parent\&'s
child list at the time of the call to \fBXtGetValues\fP\&.
.IP "" 10
When a widget is inserted into its parent\&'s child list, the positions
of any existing children that are greater than or equal to the
specified widget\&'s \fBXmNpositionIndex\fP are increased by 1\&.
The effect of a call to \fBXtSetValues\fP for \fBXmNpositionIndex\fP
is to remove the specified widget from its parent\&'s child list, decrease
by 1 the positions of any existing children that are greater than
the specified widget\&'s former position in the list, and then insert
the specified widget into its parent\&'s child list as described in the
preceding sentence\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBSimple Menu Creation Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbuttonAcceleratorsXmCButtonAcceleratorsStringTableNULLC
_____
XmNbuttonAcceleratorTextXmCButtonAcceleratorTextXmStringTableNULLC
_____
XmNbuttonCountXmCButtonCountint0C
_____
XmNbuttonMnemonicCharSetsXmCButtonMnemonicCharSetsXmStringCharSetTableNULLC
_____
XmNbuttonMnemonicsXmCButtonMnemonicsXmKeySymTableNULLC
_____
XmNbuttonsXmCButtonsXmStringTableNULLC
_____
XmNbuttonSetXmCButtonSetint-1C
_____
XmNbuttonTypeXmCButtonTypeXmButtonTypeTableNULLC
_____
XmNoptionLabelXmCOptionLabelXmStringNULLC
_____
XmNoptionMnemonicXmCOptionMnemonicKeySymNULLC
_____
XmNpostFromButtonXmCPostFromButtonint-1C
_____
XmNsimpleCallbackXmCCallbackXtCallbackProcNULLC
_____
.TE
.IP "\fBXmNbuttonAccelerators\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a list of accelerators for the buttons created\&.
The list contains one element for each button, separator, and title
created\&.
.IP "\fBXmNbuttonAcceleratorText\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a list of compound strings to display for the accelerators for
the buttons created\&.
The list contains one element for each button, separator, and title
created\&.
.IP "\fBXmNbuttonCount\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies the total number of menu buttons, separators, and titles to
create\&.
The value must not be negative\&.
.IP "\fBXmNbuttonMnemonicCharSets\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a list of character sets with which button mnemonics are to be
displayed\&.
The list contains one element for each button, separator, and title
created\&.
The default is determined dynamically depending on the locale of the
widget\&.
.IP "\fBXmNbuttonMnemonics\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a list of mnemonics for the buttons created\&.
The list contains one element for each button, separator, and title
created\&.
.IP "\fBXmNbuttons\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a list of compound strings to use as labels for the buttons
created\&.
The list contains one element for each button, separator, and title
created\&.
.IP "\fBXmNbuttonSet\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies which button of a RadioBox or OptionMenu Pulldown submenu
is initially set\&.
The value is an integer \fIn\fP indicating the \fIn\fPth
ToggleButtonGadget specified for a RadioBox or the \fIn\fPth
PushButtonGadget specified for an OptionMenu Pulldown submenu\&.
The first button specified is number 0\&.
The value must not be negative\&.
.IP "\fBXmNbuttonType\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a list of button types associated with the buttons to be
created\&.
The list contains one element for each button, separator, and title
created\&.
If this resource is not specified, each button in a MenuBar is a
CascadeButtonGadget, each button in a RadioBox or CheckBox is a
ToggleButtonGadget, and
each button in any other type
of RowColumn widget is a PushButtonGadget\&.
Each button type is of type \fBXmButtonType\fR, an enumeration with the
following possible values:
.RS
.IP "\fBXmCASCADEBUTTON\fP" 10
Specifies a CascadeButtonGadget for a MenuBar,
Popup menu pane, or Pulldown menu pane\&.
.IP "\fBXmCHECKBUTTON\fP" 10
Specifies a ToggleButtonGadget for a CheckBox,
Popup menu pane, or Pulldown menu pane\&.
.IP "\fBXmDOUBLE_SEPARATOR\fP" 10
Specifies a SeparatorGadget for a Popup
menu pane, Pulldown menu pane, or OptionMenu Pulldown submenu\&.
The separator type is \fBXmDOUBLE_LINE\fP\&.
.IP "\fBXmPUSHBUTTON\fP" 10
Specifies a PushButtonGadget for a Popup menu pane,
Pulldown menu pane, or OptionMenu Pulldown submenu\&.
.IP "\fBXmRADIOBUTTON\fP" 10
Specifies a ToggleButtonGadget for a RadioBox,
Popup menu pane, or Pulldown menu pane\&.
.IP "\fBXmSEPARATOR\fP" 10
Specifies a SeparatorGadget for a Popup menu pane,
Pulldown menu pane, or OptionMenu Pulldown submenu\&.
.IP "\fBXmTITLE\fP" 10
Specifies a LabelGadget used as a title for a Popup
menu pane or Pulldown menu pane\&.
.RE
.IP "\fBXmNoptionLabel\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a compound string for the label string to be used on the left
side of an OptionMenu\&.
.IP "\fBXmNoptionMnemonic\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a keysym for a key that, when pressed by the user along
with the \fBMAlt\fP modifier, posts
the associated Pulldown menu pane for an OptionMenu\&.
.IP "\fBXmNpostFromButton\fP" 10
This resource is for use with the simple menu creation routines\&.
For a Pulldown menu pane, it specifies the button in the parent to which
the submenu is attached\&.
The menu is then posted from this button\&.
The value is an integer \fIn\fP indicating the \fIn\fPth
CascadeButton or CascadeButtonGadget specified for the parent of the
Pulldown menu pane\&.
The first button specified is number 0\&.
The value must not be negative\&.
.IP "\fBXmNsimpleCallback\fP" 10
This resource is for use with the simple menu creation routines\&.
It specifies a callback procedure to be called when a button is
activated or when its value changes\&.
This callback function is added to each button after creation\&.
For a CascadeButtonGadget or a PushButtonGadget, the callback is added
as the button\&'s \fBXmNactivateCallback\fP, and it is called when the
button is activated\&.
For a ToggleButtonGadget, the callback is added as the button\&'s
\fBXmNvalueChangedCallback\fP, and it is called when the button\&'s value
changes\&.
The button number is passed in the \fIclient_data\fP field\&.
.SS "Inherited Resources"
.PP
RowColumn inherits behavior and resources from the
superclasses described in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetNULLCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypedynamicCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimensiondynamicCSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleandynamicCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcdefault procedureCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
        Widget \fIwidget\fP;
        char \fI* data\fP;
        char \fI* callbackstruct\fP;
} XmRowColumnCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback
.PP
The following fields apply only when the callback reason is \fBXmCR_ACTIVATE\fP;
for all other callback reasons, these fields are set to NULL\&.
The \fBXmCR_ACTIVATE\fP callback reason is generated only when the application
has supplied an entry callback, which overrides any activation callbacks
registered with the individual RowColumn items\&.
.IP "\fIwidget\fP" 10
Is set to the widget ID of the RowColumn item that has been activated
.IP "\fIdata\fP" 10
Contains the client-data value supplied by the
application when the RowColumn item\&'s activation callback was registered
.IP "\fIcallbackstruct\fP" 10
Points to the callback structure
generated by the RowColumn item\&'s activation callback
.SS "Translations"
.PP
\fBXmRowColumn\fP translations depend on the value of
the \fBXmNrowColumnType\fP resource\&.
.PP
If \fBXmNrowColumnType\fP is set to \fBXmWORK_AREA\fP,
\fBXmRowColumn\fP inherits translations from \fBXmManager\fP\&.
.PP
If \fBXmNrowColumnType\fP is set to \fBXmMENU_OPTION\fP,
\fBXmRowColumn\fP inherits traversal, \fB<osfActivate>\fP, and \fB<osfCancel>\fP
translations from \fBXmManager\fP
and has the following additional translations\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fB<Btn2Down>\fP:" 10
MenuGadgetDrag()
.IP "\fBc<Btn1Down>\fP:" 10
MenuGadgetTraverseCurrent()
.IP "\fBc<Btn1Up>\fP:" 10
MenuGadgetTraverseCurrentUp()
.IP "\fB\(apc\fP\fB<BtnDown>\fP:" 10
MenuBtnDown()
.IP "\fB\(apc\fP\fB<BtnUp>\fP:" 10
MenuBtnUp()
.IP "\fB:\fP\fB<Key>\fP\fB<osfHelp>\fP:" 10
MenuHelp()
.PP
The translations for \fBXmRowColumn\fP if
\fBXmNrowColumnType\fP is set to \fBXmMENU_BAR\fP
\fBXmMENU_PULLDOWN\fP, or \fBXmMENU_POPUP\fP
are described in the following list\&.
In a Popup menu system, \fB<Btn3>\fP also performs the \fB<Btn1>\fP
actions\&.
.IP "\fB:\fP\fB<Key>\fP\fB<osfHelp>\fP:" 10
MenuHelp()
.IP "\fB:\fP\fB<Key>\fP\fB<osfLeft>\fP:" 10
MenuGadgetTraverseLeft()
.IP "\fB:\fP\fB<Key>\fP\fB<osfRight>\fP:" 10
MenuGadgetTraverseRight()
.IP "\fB:\fP\fB<Key>\fP\fB<osfUp>\fP:" 10
MenuGadgetTraverseUp()
.IP "\fB:\fP\fB<Key>\fP\fB<osfDown>\fP:" 10
MenuGadgetTraverseDown()
.SS "Action Routines"
.PP
The \fBXmRowColumn\fP action routines are
.IP "Help():" 10
Calls the callbacks for \fBXmNhelpCallback\fP if any exist\&. If there are no help
callbacks for this widget, this action calls the help callbacks
for the nearest ancestor that has them\&.
.IP "ManagerGadgetSelect():" 10
When a gadget child of the menu has the focus, invokes the gadget
child\&'s behavior associated with \fB<osfSelect>\fP\&.
This generally has the effect of unposting the menu hierarchy and arming
and activating the gadget, except that, for a CascadeButtonGadget with a
submenu, it posts the submenu\&.
.IP "MenuBtnDown():" 10
When a gadget child of the menu has focus, invokes the gadget
child\&'s behavior associated with \fB<Btn1Down>\fP\&.
This generally has the effect of unposting any menus posted by the
parent menu, enabling mouse traversal in the menu, and arming the
gadget\&.
For a CascadeButtonGadget with a submenu, it also posts the associated
submenu\&.
.IP "MenuBtnUp():" 10
When a gadget child of the menu has focus, invokes the gadget
child\&'s behavior associated with \fB<Btn1Up>\fP\&.
This generally has the effect of unposting the menu hierarchy and
activating the gadget,
except that for a CascadeButtonGadget with a
submenu, it posts the submenu and enables keyboard traversal in the
menu\&.
.IP "MenuGadgetEscape():" 10
In a top-level Pulldown MenuPane from a MenuBar, unposts the menu,
disarms the MenuBar CascadeButton and the MenuBar, and, when the shell\&'s
keyboard focus policy is \fBXmEXPLICIT\fP, restores keyboard focus to
the widget that had the focus before the MenuBar was entered\&.
In other Pulldown MenuPanes, unposts the menu\&.
.IP "" 10
In a Popup MenuPane, unposts the menu and, when the shell\&'s keyboard
focus policy is \fBXmEXPLICIT\fP, restores keyboard focus to the widget
from which the menu was posted\&.
In a TearOff MenuPane that has no submenus posted, dismisses the
menu; otherwise, if one or more submenus are posted, unposts the last
menu pane\&.
.IP "MenuGadgetTraverseDown():" 10
If the current menu item has a submenu and is in a MenuBar, then this
action posts the submenu, disarms the current menu item, and arms
the submenu\&'s first traversable menu item\&.
.IP "" 10
If the current menu item is in a MenuPane, then this action disarms the
current menu item and arms the item below it\&. This action wraps within the
MenuPane\&. The direction of the wrapping depends on the
\fBXmNlayoutDirection\fP resource\&.
.IP "MenuGadgetTraverseLeft():" 10
When the current menu item is in a MenuBar, this action disarms the
current item and arms the MenuBar item to the left\&.
This action wraps within the MenuBar\&.
.IP "" 10
In MenuPanes, if the current menu item is not at the left edge of a MenuPane,
this action disarms the current item and arms the item to its left\&.
If the current menu item is at the left edge of a submenu attached to a
MenuBar item, then this action unposts the submenu and traverses to the
MenuBar item to the left, wrapping if necessary\&. If that MenuBar item
has a submenu, it posts the submenu and arms the first traversable
item in the submenu\&.
If the current menu item is at the left edge of a submenu not directly
attached to a MenuBar item, then this action unposts the current submenu only\&.
.IP "" 10
In Popup or Torn-off MenuPanes, when the current menu item is at the
left edge, this action wraps within the MenuPane\&. If the current menu
item is at the left edge of the MenuPane and not in the top row, this
action wraps to the rightmost menu item in the row above\&. If the current
menu item is in the upper, leftmost corner, this action wraps
to the tear-off control, if present, or else it wraps to the bottom,
rightmost menu item in the MenuPane\&.
.IP "" 10
The preceding description applies when the \fBXmNlayoutDirection\fP horizontal
direction is \fBXmLEFT_TO_RIGHT\fP\&. If the \fBXmNlayoutDirection\fP horizontal
direction is \fBXmRIGHT_TO_LEFT\fP, then the following applies\&.
.IP "" 10
If the current menu item is in a MenuBar, then this action disarms the
current item and arms the MenuBar item to the left\&.
This action wraps within the MenuBar\&.
.IP "" 10
In MenuPanes, if the current menu item is a CascadeButton, then this
action posts its associated submenu\&.
If the current menu item is not a CascadeButton and is not at the left
edge of a MenuPane, this action disarms the current item and arms the
item to its left, wrapping if necessary\&.
If the current menu item is not a CascadeButton and is at the left edge of a
submenu that is a descendent of a MenuBar, then this action unposts all
submenus and traverses to the MenuBar item to the left\&.
If that MenuBar item has a submenu, it posts the submenu and arms
the submenu\&'s first traversable item\&.
.IP "" 10
In Popup or Torn-off menus, if the current menu item is not a
CascadeButton and is at the left edge of a row (except the
bottom row), this action wraps to the rightmost menu item in the
row below\&. If the current menu item is not a CascadeButton and
is in the bottom, leftmost corner of a Popup or Pulldown MenuPane, this
action wraps to the tear-off control, if present, or else it wraps to
the top, rightmost menu item of the MenuPane\&.
.IP "MenuGadgetTraverseRight():" 10
If the current menu item is in a MenuBar, then this action disarms the
current item and arms the MenuBar item to the right\&.
This action wraps within the MenuBar\&.
.IP "" 10
In MenuPanes, if the current menu item is a CascadeButton, then this
action posts its associated submenu\&.
If the current menu item is not a CascadeButton and is not at the right
edge of a MenuPane, this action disarms the current item and arms the
item to its right, wrapping if necessary\&.
If the current menu item is not a CascadeButton and is at the right edge of a
submenu that is a descendent of a MenuBar, then this action unposts all
submenus and traverses to the MenuBar item to the right\&.
If that MenuBar item has a submenu, it posts the submenu and arms
the submenu\&'s first traversable item\&.
.IP "" 10
In Popup or Torn-off menus, if the current menu item is not a
CascadeButton and is at the right edge of a row (except the
bottom row), this action wraps to the leftmost menu item in the
row below\&. If the current menu item is not a CascadeButton and
is in the bottom, rightmost corner of a Popup or Pulldown MenuPane, this
action wraps to the tear-off control, if present, or else it wraps to
the top, leftmost menu item of the MenuPane\&.
.IP "" 10
The preceding description applies when the \fBXmNlayoutDirection\fP horizontal
direction is \fBXmLEFT_TO_RIGHT\fP\&. If the \fBXmNlayoutDirection\fP horizontal
direction is \fBXmRIGHT_TO_LEFT\fP, then the following applies\&.
When the current menu item is in a MenuBar, this action disarms the
current item and arms the MenuBar item to the left\&.
This action wraps within the MenuBar\&.
.IP "" 10
In MenuPanes, if the current menu item is not at the right edge of a MenuPane,
this action disarms the current item and arms the item to its right\&.
If the current menu item is at the right edge of a submenu attached to a
MenuBar item, then this action unposts the submenu and traverses to the
MenuBar item to the right, wrapping if necessary\&. If that MenuBar item
has a submenu, it posts the submenu and arms the first traversable
item in the submenu\&.
If the current menu item is at the right edge of a submenu not directly
attached to a MenuBar item, then this action unposts the current submenu only\&.
.IP "" 10
In Popup or Torn-off MenuPanes, when the current menu item is at the
right edge, this action wraps within the MenuPane\&. If the current menu
item is at the right edge of the MenuPane and not in the top row, this
action wraps to the leftmost menu item in the row above\&. If the current
menu item is in the upper, rightmost corner, this action wraps
to the tear-off control, if present, or else it wraps to the bottom,
leftmost menu item in the MenuPane\&.
.IP "MenuGadgetTraverseUp():" 10
When the current menu item is in a MenuPane, then
this action disarms the current menu item and arms the item above it\&.
This action wraps within the MenuPane\&. The direction of the wrapping
depends on the \fBXmNlayoutDirection\fP resource\&.
.SS "Related Behavior"
.PP
The following menu functions are available:
.IP "\fB<osfMenuBar>\fP:" 10
In any non-popup descendant of a MenuBar\&'s parent, excluding the MenuBar
itself, this action enables keyboard traversal and moves keyboard focus
to the first item in the MenuBar\&.
In the MenuBar or any menu cascaded from it, this action unposts the
menu hierarchy and, when the shell\&'s keyboard focus policy is
\fBXmEXPLICIT\fP, restores focus to the widget that had the focus
when the menu system was entered\&.
.IP "\fB<osfMenu>\fP:" 10
Pops up the menu associated with the control that has the keyboard focus\&.
Enables keyboard traversal in the menu\&.
In the Popup menu system or any menu cascaded from it, this action
unposts the menu hierarchy and, when the shell\&'s keyboard focus policy
is \fBXmEXPLICIT\fP, restores focus to the widget that had the focus
when the menu system was entered\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBComposite\fP(3),
\fBConstraint\fP(3),
\fBCore\fP(3),
\fBXmCreateMenuBar\fP(3),
\fBXmCreateOptionMenu\fP(3),
\fBXmCreatePopupMenu\fP(3),
\fBXmCreatePulldownMenu\fP(3),
\fBXmCreateRadioBox\fP(3),
\fBXmCreateRowColumn\fP(3),
\fBXmCreateSimpleCheckBox\fP(3),
\fBXmCreateSimpleMenuBar\fP(3),
\fBXmCreateSimpleOptionMenu\fP(3),
\fBXmCreateSimplePopupMenu\fP(3),
\fBXmCreateSimplePulldownMenu\fP(3),
\fBXmCreateSimpleRadioBox\fP(3),
\fBXmCreateWorkArea\fP(3),
\fBXmGetMenuCursor\fP(3),
\fBXmGetPostedFromWidget\fP(3),
\fBXmGetTearOffControl\fP,
\fBXmLabel\fP(3),
\fBXmManager\fP(3),
\fBXmMenuPosition\fP(3),
\fBXmOptionButtonGadget\fP(3),
\fBXmOptionLabelGadget\fP(3),
\fBXmRepTypeInstallTearOffModelConverter\fP,
\fBXmSetMenuCursor\fP(3),
\fBXmUpdateDisplay\fP(3),
\fBXmVaCreateSimpleCheckBox\fP(3),
\fBXmVaCreateSimpleMenuBar\fP(3),
\fBXmVaCreateSimpleOptionMenu\fP(3),
\fBXmVaCreateSimplePopupMenu\fP(3),
\fBXmVaCreateSimplePulldownMenu\fP(3), and
\fBXmVaCreateSimpleRadioBox\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
