'\" t
...\" ScrollBA.sgm /main/13 1996/09/30 13:23:57 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmScrollBar" "library call"
.SH "NAME"
\fBXmScrollBar\fP \(em The ScrollBar widget class
.iX "XmScrollBar"
.iX "widget class" "ScrollBar"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ScrollBar\&.h>
.fi
.SH "DESCRIPTION"
.PP
The ScrollBar widget allows the user to view data that is too large to be
displayed all at once\&. ScrollBars are usually located inside a
ScrolledWindow and adjacent to
the widget that contains the data to be viewed\&. When the user interacts
with the ScrollBar, the data within the other widget scrolls\&.
.PP
A ScrollBar consists of two arrows placed at each end of a rectangle\&. The
rectangle is called the scroll region\&. A smaller rectangle, called the
slider, is placed within the scroll region\&. The data is scrolled by
clicking either arrow, selecting on the scroll region, or dragging the slider\&.
When an arrow is selected, the slider within the scroll region is
moved in the direction of the arrow by an amount supplied by the
application\&. If the mouse button is held down, the slider continues to
move at a constant rate\&.
.PP
The ratio of the slider size to the scroll region size typically
corresponds to the
relationship between the size of the visible data and the total size
of the data\&. For example, if 10 percent of the data is visible, the
slider typically occupies 10 percent of the scroll region\&. This provides the
user with a visual clue to the size of the invisible data\&.
.PP
If the ScrollBar parent is an automatic ScrolledWindow, the
\fBXmNtraversalOn\fP default is True\&. Otherwise, the default is False\&.
.PP
ScrollBar holds the \fBXmQTnavigator\fP traits\&.
.SS "Classes"
.PP
ScrollBar inherits behavior, resources, and traits from the \fBCore\fP and
\fBXmPrimitive\fP classes\&.
.PP
The class pointer is \fBxmScrollBarWidgetClass\fP\&.
.PP
The class name is \fBXmScrollBar\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmScrollBar Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNdecrementCallbackXmCCallbackXtCallbackListNULLC
_____
XmNdragCallbackXmCCallbackXtCallbackListNULLC
_____
XmNeditableXmCEditableBooleanTrueCSG
_____
XmNincrementXmCIncrementint1CSG
_____
XmNincrementCallbackXmCCallbackXtCallbackListNULLC
_____
XmNinitialDelayXmCInitialDelayint250 msCSG
_____
XmNmaximumXmCMaximumint100CSG
_____
XmNminimumXmCMinimumint0CSG
_____
XmNorientationXmCOrientationunsigned charXmVERTICALCSG
_____
XmNpageDecrementCallbackXmCCallbackXtCallbackListNULLC
_____
XmNpageIncrementXmCPageIncrementint10CSG
_____
XmNpageIncrementCallbackXmCCallbackXtCallbackListNULLC
_____
XmNprocessingDirectionXmCProcessingDirectionunsigned chardynamicCSG
_____
XmNrepeatDelayXmCRepeatDelayint50 msCSG
_____
XmNshowArrowsXmCShowArrowsXtEnumXmEACH_SIDECSG
_____
XmNsliderSizeXmCSliderSizeintdynamicCSG
_____
XmNsliderMarkXmCSliderMarkXtEnumdynamicCSG
_____
XmNsliderVisualXmCSliderVisualXtEnumXmSHADOWEDCSG
_____
XmNslidingModeXmCSlidingModeXtEnumXmSLIDERCSG
_____
XmNsnapBackMultipleXmCSnapBackMultipleunsigned shortMaxValueCSG
_____
XmNtoBottomCallbackXmCCallbackXtCallbackListNULLC
_____
XmNtoTopCallbackXmCCallbackXtCallbackListNULLC
_____
XmNtroughColorXmCTroughColorPixeldynamicCSG
_____
XmNvalueXmCValueintdynamicCSG
_____
XmNvalueChangedCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.IP "\fBXmNdecrementCallback\fP" 10
Specifies the list of callbacks that is called when the user takes an
action that moves the ScrollBar by one increment and the value
decreases\&.
The reason passed to the callback is \fBXmCR_DECREMENT\fP\&.
.IP "\fBXmNdragCallback\fP" 10
Specifies the list of callbacks that is called
on each incremental change of position
when the slider is being dragged\&. The reason sent by the
callback is \fBXmCR_DRAG\fP\&.
.IP "\fBXmNeditable\fP" 10
Specifies how ScrollBar will react to user input\&. This
resource can be True or False values, as follows:
.RS
.IP "\fBTrue\fP" 10
Allows the scrollbar to be sensitive to user input\&. This is the
default value\&.
.IP "\fBFalse\fP" 10
Makes the Scale scrollbar insensitive to user input\&. The visual is not
greyed out\&. This value would mostly be used in \fBXmTHERMOMETER\fP
mode\&.
.RE
.IP "" 10
When \fBXmNeditable\fP is used on a widget
it sets the dropsite to \fBXmDROP_SITE_ACTIVE\fP\&.
.IP "\fBXmNincrement\fP" 10
Specifies the amount by which the value increases or decreases when the
user takes an action that moves the slider by one increment\&.
The actual change in value is the lesser of \fBXmNincrement\fP and
(previous \fBXmNvalue\fP\ - \fBXmNminimum\fP) when the slider moves to
the end of the ScrollBar with the minimum value,
and the lesser of \fBXmNincrement\fP
and (\fBXmNmaximum\fP- \fBXmNsliderSize\fP\ -
previous \fBXmNvalue\fP) when the slider moves to the end of the
ScrollBar with the maximum value\&.
The value of this resource must be greater than 0 (zero)\&.
.IP "\fBXmNincrementCallback\fP" 10
Specifies the list of callbacks that is called when the user takes an
action that moves the ScrollBar by one increment and the value
increases\&.
The reason passed to the callback is \fBXmCR_INCREMENT\fP\&.
.IP "\fBXmNinitialDelay\fP" 10
Specifies the amount of time in milliseconds to wait before starting
continuous
slider movement while a button is pressed in an arrow or the scroll region\&.
The value of this resource must be greater than 0 (zero)\&.
.IP "\fBXmNmaximum\fP" 10
Specifies the slider\&'s maximum value\&.
\fBXmNmaximum\fP must be greater than \fBXmNminimum\fP\&.
.IP "\fBXmNminimum\fP" 10
Specifies the slider\&'s minimum value\&.
\fBXmNmaximum\fP must be greater than \fBXmNminimum\fP\&.
.IP "\fBXmNorientation\fP" 10
Specifies whether the ScrollBar is displayed vertically or horizontally\&.
This resource can have values of \fBXmVERTICAL\fP and \fBXmHORIZONTAL\fP\&.
.IP "\fBXmNpageDecrementCallback\fP" 10
Specifies the list of callbacks that is called when the user takes an
action that moves the ScrollBar by one page increment and the value
decreases\&.
The reason passed to the callback is \fBXmCR_PAGE_DECREMENT\fP\&.
.IP "\fBXmNpageIncrement\fP" 10
Specifies the amount by which the value increases or decreases when
the user takes an action that moves the slider by one page increment\&.
The actual change in value is the lesser of \fBXmNpageIncrement\fP and
(previous \fBXmNvalue\fP\ - \fBXmNminimum\fP) when the slider moves to
the end of the ScrollBar with the
minimum value, and the lesser of
\fBXmNpageIncrement\fP and (\fBXmNmaximum\fP- \fBXmNsliderSize\fP\ -
previous \fBXmNvalue\fP) when the slider moves to the end of the
ScrollBar with the maximum value\&.
The value of this resource must be greater than 0 (zero)\&.
.IP "\fBXmNpageIncrementCallback\fP" 10
Specifies the list of callbacks that is called when the user takes an
action that moves the ScrollBar by one page increment and the value
increases\&.
The reason passed to the callback is \fBXmCR_PAGE_INCREMENT\fP\&.
.IP "\fBXmNprocessingDirection\fP" 10
Specifies whether the value for \fBXmNmaximum\fP should be on the right or
left side of \fBXmNminimum\fP for horizontal ScrollBars
or above or below \fBXmNminimum\fP for vertical ScrollBars\&.
This resource can have values of \fBXmMAX_ON_TOP, XmMAX_ON_BOTTOM,
XmMAX_ON_LEFT\fP, and \fBXmMAX_ON_RIGHT\fP\&.
If the ScrollBar is oriented vertically,
the default value is
\fBXmMAX_ON_BOTTOM\fP\&.
If the ScrollBar is oriented horizontally,
the default value
depends on the \fBXmNlayoutDirection\fP resource of the widget\&.
.IP "\fBXmNrepeatDelay\fP" 10
Specifies the amount of time in milliseconds to wait between
subsequent slider movements after the \fBXmNinitialDelay\fP has been processed\&.
The value of this resource must be greater than 0 (zero)\&.
.IP "\fBXmNshowArrows\fP" 10
Specifies whether the arrows are
displayed and how they are to be displayed\&. This resource can take the
following values:
.RS
.IP "\fBXmEACH_SIDE\fP" 10
Indicates that one arrow is displayed on each end of the ScrollBar
slider\&. This corresponds to a value of True in previous releases\&.
.IP "\fBXmMAX_SIDE\fP" 10
Indicates that both arrows are displayed on the \fBXmNmaximum\fP side of
the ScrollBar slider\&.
.IP "\fBXmMIN_SIDE\fP" 10
Indicates that both arrows are displayed on the \fBXmNminimum\fP side of
the ScrollBar slider\&.
.IP "\fBXmNONE\fP" 10
Indicates that no arrows are displayed\&. This corresponds to a value
of False in previous releases\&.
.RE
.IP "" 10
\fBXmEACH_SIDE\fP is the default value\&.
.IP "\fBXmNsliderMark\fP" 10
Specifies the shape the slider is to be displayed in\&. This resource
can take the following values:
.RS
.IP "\fBXmETCHED_LINE\fP" 10
Specifies the slider as an etched line\&.
.IP "\fBXmNONE\fP" 10
Specifies the slider as a foregrounded rectangle\&. This is the default
for a regular slider\&.
.IP "\fBXmROUND_MARK\fP" 10
Specifies the slider as a shadowed circle\&. This is the default when
the slider is a thermometer\&.
.IP "\fBXmTHUMB_MARK\fP" 10
Specifies the slider as a series of three etched lines centered in the
middle of the slider\&.
.RE
.IP "\fBXmNslidingMode\fP" 10
Specifies the mode the slider works in\&. There are two possible modes:
.RS
.IP "\fBXmSLIDER\fP" 10
Allows the slider to move freely between the minimum and maximum ends
of the scale\&. This is the default value\&.
.IP "\fBXmTHERMOMETER\fP" 10
Forces the slider to be anchored to one side of the trough area\&.
.RE
.IP "\fBXmNsliderSize\fP" 10
Specifies the length of the slider between the values of 1 and
(\fBXmNmaximum\fP\ - \fBXmNminimum\fP)\&.
The value is constrained to be within these inclusive bounds\&.
The default value is (\fBXmNmaximum\fP\ - \fBXmNminimum\fP) divided by
10, with a minimum of 1\&.
.IP "\fBXmNsliderVisual\fP" 10
Specifies the color of the slider visual\&. This resource can take
the following values:
.RS
.IP "\fBXmBACKGROUND_COLOR\fP" 10
Specifies that the slider visual is in the background color\&.
.IP "\fBXmFOREGROUND_COLOR\fP" 10
Specifies that the slider visual is in the foreground color\&.
.IP "\fBXmSHADOWED_BACKGROUND\fP" 10
Specifies that the slider visual is in the background color, with a shadow\&.
This is the
default for a regular slider\&.
.IP "\fBXmTROUGH_COLOR\fP" 10
Specifies that the slider visual is in the trough color\&. This is the
default when the slider is a thermometer\&.
.RE
.IP "\fBXmNsnapBackMultiple\fP" 10
Specifies the distance over which the scrollbar slider snaps back to its
original position when the user drags the mouse outside the ScrollBar
edge\&. This distance is defined in terms of multiples of
the width of the slider\&. For example, a multiple of 0 (zero) causes the
slider to snap back as soon as the pointer moves out of the ScrollBar
frame, a multiple of 1 causes the slider to snap back as soon as the
pointer moves beyond 1 ScrollBar width of the ScrollBar edge\&.
Whenever the slider snaps back, the ScrollBar \fBdragCallback\fP is
called if there is one\&.
.IP "" 10
The default value is large enough to prevent unwanted snapBack
activity if the mouse is moved within the boundaries of any reasonable
screen\&. To reset the default, set this resource to a large value,
such as 10000\&.
.IP "\fBXmNtoBottomCallback\fP" 10
Specifies the list of callbacks that is called when the user takes an
action that moves the slider to the end of the ScrollBar with the
maximum value\&.
The reason passed to the callback is \fBXmCR_TO_BOTTOM\fP\&.
.IP "\fBXmNtoTopCallback\fP" 10
Specifies the list of callbacks that is called when the user takes an
action that moves the slider to the end of the ScrollBar with the
minimum value\&.
The reason passed to the callback is \fBXmCR_TO_TOP\fP\&.
.IP "\fBXmNtroughColor\fP" 10
Specifies the color of the slider trough\&.
This color defaults to the color used for selections\&.
.IP "\fBXmNvalue\fP" 10
Specifies the slider\&'s position, between \fBXmNminimum\fP and
(\fBXmNmaximum\fP\ - \fBXmNsliderSize\fP)\&.
The value is constrained to be within these inclusive bounds\&.
The initial value of this resource is the larger of 0 (zero) and \fBXmNminimum\fP\&.
.IP "\fBXmNvalueChangedCallback\fP" 10
Specifies the list of callbacks that is called when the slider is
released after being dragged\&.
These callbacks are also called in place of \fBXmNincrementCallback\fP,
\fBXmNdecrementCallback\fP, \fBXmNpageIncrementCallback\fP,
\fBXmNpageDecrementCallback\fP, \fBXmNtoTopCallback\fP, or
\fBXmNtoBottomCallback\fP when one of these callback lists would
normally be called but the value of the corresponding resource is NULL\&.
The reason passed to the callback is \fBXmCR_VALUE_CHANGED\fP\&.
.SS "Inherited Resources"
.PP
ScrollBar inherits behavior and resources from the
superclasses described in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmPrimitive Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNconvertCallbackXmCCallbackXtCallbackListNULLC
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightOnEnterXmCHighlightOnEnterBooleanFalseCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimensiondynamicCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmSTICKY_TAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleandynamicCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
        int \fIvalue\fP;
        int \fIpixel\fP;
} XmScrollBarCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
.IP "\fIvalue\fP" 10
Contains the new slider location value\&.
.IP "\fIpixel\fP" 10
Is used only for \fBXmNtoTopCallback\fP and \fBXmNtoBottomCallback\fP\&.
For horizontal ScrollBars, it contains the \fIx\fP coordinate of where
the mouse button selection occurred\&. For vertical ScrollBars, it
contains the \fIy\fP coordinate\&.
.SS "Translations"
.PP
\fBXmScrollBar\fP includes translations from Primitive\&.
The \fBXmScrollBar\fP translations are described in the following
list\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fB\(aps \(apc \(apm \(apa\fP \fB<Btn1Down>\fP:" 10
Select()
.IP "\fB\(aps \(apc \(apm \(apa\fP \fB<Btn1Up>\fP:" 10
Release()
.IP "\fB\(aps \(apc \(apm \(apa Button1\fP\fB<PtrMoved>\fP:" 10
Moved()
.IP "\fB\(aps \(apc \(apm \(apa\fP \fB<Btn2Down>\fP:" 10
Select()
.IP "\fB\(aps \(apc \(apm \(apa\fP \fB<Btn2Up>\fP:" 10
Release()
.IP "\fB\(aps \(apc \(apm \(apa Button2\fP\fB<PtrMoved>\fP:" 10
Moved()
.IP "\fB\(aps c \(apm \(apa\fP \fB<Btn1Down>\fP:" 10
TopOrBottom()
.IP "\fB\(aps c \(apm \(apa\fP \fB<Btn1Up>\fP:" 10
Release()
.IP "\fB:\fP\fB<Key>\fP\fB<osfActivate>\fP:" 10
PrimitiveParentActivate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCancel>\fP:" 10
CancelDrag()
.IP "\fB:\fP\fB<Key>\fP\fB<osfBeginLine>\fP:" 10
TopOrBottom()
.IP "\fB:\fP\fB<Key>\fP\fB<osfEndLine>\fP:" 10
TopOrBottom()
.IP "\fB:\fP\fB<Key>\fP\fB<osfPageLeft>\fP:" 10
PageUpOrLeft(\fBLeft\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfPageUp>\fP:" 10
PageUpOrLeft(\fBLeft\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfPageUp>\fP:" 10
PageUpOrLeft(\fBUp\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfPageRight>\fP:" 10
PageDownOrRight(\fBRight\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfPageDown>\fP:" 10
PageDownOrRight(\fBRight\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfPageDown>\fP:" 10
PageDownOrRight(\fBDown\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfHelp>\fP:" 10
PrimitiveHelp()
.IP "\fB:c\fP \fB<Key>\fP\fB<osfUp>\fP:" 10
PageUpOrLeft(\fBUp\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfUp>\fP:" 10
IncrementUpOrLeft(\fBUp\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfDown>\fP:" 10
PageDownOrRight(\fBDown\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfDown>\fP:" 10
IncrementDownOrRight(\fBDown\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfLeft>\fP:" 10
PageUpOrLeft(\fBLeft\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfLeft>\fP:" 10
IncrementUpOrLeft(\fBLeft\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfRight>\fP:" 10
PageDownOrRight(\fBRight\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfRight>\fP:" 10
IncrementDownOrRight(\fBRight\fP)
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBReturn\fP:" 10
PrimitiveParentActivate()
.IP "\fBs \(apm \(apa\fP \fB<Key>\fP\fBTab\fP:" 10
PrimitivePrevTabGroup()
.IP "\fB\(apm \(apa\fP \fB<Key>\fP\fBTab\fP:" 10
PrimitiveNextTabGroup()
.SS "Action Routines"
.PP
The ScrollBar action routines are
.IP "CancelDrag():" 10
If the key press occurs during scrolling, cancels the
scroll and returns the slider to its previous location in the scrollbar,
otherwise, and if the parent is a manager, it passes the event to
the parent\&.
.IP "IncrementDownOrRight(\fBDown|Right\fP):" 10
With an argument of \fBDown\fP, or 0 (zero) for compatibility, moves
the slider down by one increment\&.
With an argument of \fBRight\fP, or 1 for compatibility, it moves the
slider right by one increment\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_RIGHT\fP or
\fBXmMAX_ON_BOTTOM\fP, movement toward the right or
bottom calls the callbacks for \fBXmNincrementCallback\fP\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_LEFT\fP or
\fBXmMAX_ON_TOP\fP, movement toward the right or
bottom calls the callbacks for \fBXmNdecrementCallback\fP\&.
The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNincrementCallback\fP or \fBXmNdecrementCallback\fP is NULL\&.
.IP "IncrementUpOrLeft(\fBUp|Left\fP):" 10
With an argument of \fBUp\fP, or 0 (zero) for compatibility, moves the
slider up by one increment\&.
With an argument of \fBLeft\fP, or 1 for compatibility, it moves the
slider left by one increment\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_RIGHT\fP or
\fBXmMAX_ON_BOTTOM\fP,
movement to the left or top calls the callbacks for
\fBXmNdecrementCallback\fP\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_LEFT\fP or
\fBXmMAX_ON_TOP\fP,
movement to the left or top calls the callbacks for
\fBXmNincrementCallback\fP\&.
The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNincrementCallback\fP or \fBXmNdecrementCallback\fP is NULL\&.
.IP "Moved():" 10
If the button press occurs within the slider, the subsequent motion
events move the slider to the position of the pointer and call the
callbacks for \fBXmNdragCallback\fP\&.
.IP "PageDownOrRight(\fBDown|Right\fP):" 10
With an argument of \fBDown\fP, or 0 (zero) for compatibility, moves
the slider down by one page increment\&.
With an argument of \fBRight\fP, or 1 for compatibility, moves the
slider right by one page increment\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_RIGHT\fP or
\fBXmMAX_ON_BOTTOM\fP, movement toward the right or
bottom calls the callbacks for \fBXmNpageIncrementCallback\fP\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_LEFT\fP or
\fBXmMAX_ON_TOP\fP, movement toward the right or
bottom calls the \fBXmNpageDecrementCallback\fP
callbacks\&. The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNpageIncrementCallback\fP or \fBXmNpageDecrementCallback\fP is NULL\&.
.IP "PageUpOrLeft(\fBUp|Left\fP):" 10
With an argument of \fBUp\fP, or 0 (zero) for compatibility, moves the
slider up by one page increment\&.
With an argument of \fBLeft\fP, or 1 for compatibility, it moves the
slider left by one page increment\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_RIGHT\fP or
\fBXmMAX_ON_BOTTOM\fP,
movement to the left or top calls the callbacks for
\fBXmNpageDecrementCallback\fP\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_LEFT\fP or
\fBXmMAX_ON_TOP\fP,
movement to the left or top calls the
\fBXmNpageIncrementCallback\fP
callbacks\&. The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNpageIncrementCallback\fP or \fBXmNpageDecrementCallback\fP is NULL\&.
.IP "PrimitiveHelp():" 10
Calls the callbacks for \fBXmNhelpCallback\fP if any exist\&. If there are no help
callbacks for this widget, this action calls the help callbacks
for the nearest ancestor that has them\&.
.IP "PrimitiveNextTabGroup():" 10
Traverses to the first item in the next tab group\&. If
the current tab group is the last entry in the tab group list, it
wraps to the beginning of the tab group list\&.
.IP "PrimitiveParentActivate():" 10
If the parent is a manager,
passes the event to the parent\&.
.IP "PrimitivePrevTabGroup():" 10
Traverses to the first item in the previous tab group\&.
If the beginning of the tab group list is reached, it wraps to the end
of the tab group list\&.
.IP "Release():" 10
If the button press occurs within the slider and the slider position
is changed, the callbacks for \fBXmNvalueChangedCallback\fP are called\&.
.IP "Select():" 10
\fBIn arrow\fP:
Moves the slider by one increment in the direction
of the arrow\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_RIGHT\fP or
\fBXmMAX_ON_BOTTOM\fP, movement toward the right or
bottom calls the callbacks for \fBXmNincrementCallback\fP,
and movement to the left or top calls the callbacks for
\fBXmNdecrementCallback\fP\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_LEFT\fP or
\fBXmMAX_ON_TOP\fP, movement toward the right or
bottom calls the callbacks for \fBXmNdecrementCallback\fP,
and movement to the left or top calls the callbacks for
\fBXmNincrementCallback\fP\&.
The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNincrementCallback\fP or \fBXmNdecrementCallback\fP is NULL\&.
.IP "" 10
\fBIn scroll region between an arrow and the slider\fP:
Moves the slider by one page increment in the direction of the arrow\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_RIGHT\fP or
\fBXmMAX_ON_BOTTOM\fP, movement toward the right or
bottom calls the callbacks for \fBXmNpageIncrementCallback\fP,
and movement to the left or top calls the callbacks for
\fBXmNpageDecrementCallback\fP\&.
If \fBXmNprocessingDirection\fP is \fBXmMAX_ON_LEFT\fP or
\fBXmMAX_ON_TOP\fP, movement toward the right or
bottom calls the callbacks for \fBXmNpageDecrementCallback\fP,
and movement to the left or top calls the callbacks for
\fBXmNpageIncrementCallback\fP\&.
The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNpageIncrementCallback\fP or \fBXmNpageDecrementCallback\fP is
NULL\&.
.IP "" 10
\fBIn slider\fP:
Activates the interactive dragging of the slider\&.
.IP "" 10
If the button is held down in either the arrows or the scroll region
longer than the \fBXmNinitialDelay\fP resource, the slider is
moved again by the same increment and the same callbacks are called\&.
After the initial delay has been used, the time delay changes to the
time defined by the resource \fBXmNrepeatDelay\fP\&.
.IP "TopOrBottom():" 10
\fB<Ctrl>\fP\fB<Btn1Down>\fP in an arrow or in the scroll region between
an arrow and the slider moves the slider as far as possible in the
direction of the arrow\&. If \fBXmNprocessingDirection\fP is
\fBXmMAX_ON_RIGHT\fP or \fBXmMAX_ON_BOTTOM\fP, movement toward the
right or bottom calls the callbacks for \fBXmNtoBottomCallback\fP, and
movement to the left or top calls the callbacks for
\fBXmNtoTopCallback\fP\&. If \fBXmNprocessingDirection\fP is
\fBXmMAX_ON_LEFT\fP or \fBXmMAX_ON_TOP\fP, movement toward the right
or bottom calls the callbacks for \fBXmNtoTopCallback\fP, and movement
to the left or top calls the callbacks for \fBXmNtoBottomCallback\fP\&.
The \fBXmNvalueChangedCallback\fP is called if the
\fBXmNtoTopCallback\fP or \fBXmNtoBottomCallback\fP is NULL\&.
Pressing
\fB<Key>\fP\fB<osfBeginLine>\fP or \fB<Key>\fP\fB<osfBeginData>\fP moves the slider to
the minimum value and invokes the \fBXmNtoTopCallback\fP\&. Pressing
\fB<Key>\fP\fB<osfEndLine>\fP or \fB<Key>\fP\fB<osfEndData>\fP moves the slider to the
maximum value and invokes the \fBXmNtoBottomCallback\fP\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBCore\fP(3), \fBXmCreateScrollBar\fP(3), \fBXmPrimitive\fP(3),
\fBXmScrollBarGetValues\fP(3), and
\fBXmScrollBarSetValues\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
