'\" t
...\" ScrollB.sgm /main/8 1996/09/08 21:00:33 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmScrolledWindowSetAreas" "library call"
.SH "NAME"
\fBXmScrolledWindowSetAreas\fP \(em A ScrolledWindow function that adds or changes a window work region and a horizontal or vertical ScrollBar widget to the ScrolledWindow widget
.iX "XmScrolledWindowSetAreas"
.iX "ScrolledWindow functions" "XmScrolledWindowSetAreas"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ScrolledW\&.h>
\fBvoid \fBXmScrolledWindowSetAreas\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBWidget \fBhorizontal_scrollbar\fR\fR,
\fBWidget \fBvertical_scrollbar\fR\fR,
\fBWidget \fBwork_region\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmScrolledWindowSetAreas\fP adds or changes a window work region and
a horizontal or vertical ScrollBar widget to the ScrolledWindow widget for
the application\&. Each widget is optional and may be passed as NULL\&.
This function is obsolete and exists for compatibility with
other releases\&. Use the \fBXmNscrolledWindowChildType\fP resource
of \fBXmScrolledWindow\fP instead\&.
.IP "\fIwidget\fP" 10
Specifies the ScrolledWindow widget ID\&.
.IP "\fIhorizontal_scrollbar\fP" 10
Specifies the ScrollBar widget ID for the
horizontal ScrollBar to be associated
with the ScrolledWindow widget\&. Set this ID only after creating an instance
of the ScrolledWindow widget\&. The resource name associated with this
argument is \fBXmNhorizontalScrollBar\fP\&.
.IP "\fIvertical_scrollbar\fP" 10
Specifies the ScrollBar widget ID for the
vertical ScrollBar to be associated
with the ScrolledWindow widget\&. Set this ID only after creating an instance
of the ScrolledWindow widget\&. The resource name associated with this
argument is \fBXmNverticalScrollBar\fP\&.
.IP "\fIwork_region\fP" 10
Specifies the widget ID for the work window to be associated with the
ScrolledWindow widget\&. Set this ID only after creating an instance of the
ScrolledWindow widget\&. The attribute name associated with this argument is
\fBXmNworkWindow\fP\&.
.PP
For a complete definition of ScrolledWindow and its associated resources, see
\fBXmScrolledWindow\fP(3)\&.
.SH "RELATED"
.PP
\fBXmScrolledWindow\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
