'\" t
...\" SelectA.sgm /main/12 1996/09/26 14:54:17 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmSelectionBox" "library call"
.SH "NAME"
\fBXmSelectionBox\fP \(em The SelectionBox widget class
.iX "XmSelectionBox"
.iX "widget class" "SelectionBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/SelectioB\&.h>
.fi
.SH "DESCRIPTION"
.PP
SelectionBox is a general dialog widget that allows the user to
select one item from a list\&.
By default, a SelectionBox includes the following:
.IP "   \(bu" 6
A scrolling list of alternatives
.IP "   \(bu" 6
An editable text field for the selected alternative
.IP "   \(bu" 6
Labels for the list and text field
.IP "   \(bu" 6
Three or four buttons
.PP
The default button labels are \fBOK\fP, \fBCancel\fP, and \fBHelp\fP\&.
By default an \fBApply\fP button is also created; if the parent of the
SelectionBox is a DialogShell, it is managed; otherwise it is unmanaged\&.
Additional children may be added to the SelectionBox after
creation\&.
The first child is used as a work area\&. The value of
\fBXmNchildPlacement\fP determines if the work area is placed above
or below the Text area, or above or below the List area\&. Additional
children are laid out in the following manner:
.IP "Menubar" 10
The first menu bar child is placed at the top of the window\&.
The \fBXmQTmenuSystem\fP trait is used to check that it is the first
MenuBar child\&.
.IP "Buttons" 10
All \fBXmPushButton\fP
widgets or gadgets, and their subclasses are
placed after the \fBOK\fP button in the order of their
creation (this order is checked using the \fBXmQTactivatable\fP trait)\&.
The layout direction of the buttons depends on the
\fBXmNlayoutDirection\fP resource\&.
.PP
The layout of additional children that are not in the above categories
is undefined\&.
.PP
The user can select an item in two ways:
by scrolling through the list and selecting the desired
item or by entering the item name directly into the text edit area\&.
Selecting an item from
the list causes that item name to appear in the selection text edit
area\&.
.PP
The user may select a new item
as many times as desired\&. The item is not actually selected until
the user presses the \fBOK\fP PushButton\&.
.PP
The default value for the \fBXmBulletinBoard\fP resource
\fBXmNcancelButton\fP is the Cancel button, unless \fBXmNdialogType\fP is
\fBXmDIALOG_COMMAND\fP, when the default is NULL\&.
The default value for the \fBXmBulletinBoard\fP
\fBXmNdefaultButton\fP resource is the OK button, unless \fBXmNdialogType\fP is
\fBXmDIALOG_COMMAND\fP, when the default is NULL\&.
.PP
For SelectionBox and its subclasses, the default value for
\fBXmNinitialFocus\fP is the text edit area\&.
.PP
The user can specify resources in a resource file for the automatically
created widgets and gadgets of SelectionBox\&. The following list
identifies the names of these widgets (or gadgets) and the associated
SelectionBox areas:
.IP "List Items Label" 10
\fBItems\fP
.IP "List Items" 10
\fBItemsList\fP
.IP "Selection Label" 10
\fBSelection\fP
.IP "Selection Text" 10
\fBText\fP or \fBTextField\fP
.IP "Selection Separator" 10
\fBSeparator\fP
.PP
SelectionBox uses the \fBXmQTaccessTextual\fP, \fBXmQTactivatable\fP,
and \fBXmQTmenuSystem\fP traits\&.
.SS "Descendants"
.PP
SelectionBox automatically creates the descendants shown in the
following table\&.
An application can use \fBXtNameToWidget\fP to gain access
to the named descendant\&. In addition, a user or an application
can use the named descendant when specifying resource values\&.
.TS
tab() box;
l| l| l.
\fBNamed Descendant\fP\fBClass\fP\fBIdentity\fP
___
=
___
\fBApply\fP\fBXmPushButtonGadget\fPApply button
___
\fBCancel\fP\fBXmPushButtonGadget\fPCancel button
___
\fBHelp\fP\fBXmPushButtonGadget\fPHelp button
___
\fBItems\fP\fBXmLabelGadget\fPtitle above the list of items
___
\fBItemsList\fP\fBXmList\fPT{
list of items from which the user will select
T}
___
\fBItemsListSW\fP\fBXmScrolledWindow\fPScrolledWindow parent of \fBItemsList\fP
___
\fBOK\fP\fBXmPushButtonGadget\fPOK button
___
\fBSelection\fP\fBXmLabelGadget\fPtitle above the selection box
___
\fBSeparator\fP\fBXmSeparatorGadget\fPT{
dividing line between selection box and buttons
T}
___
\fBText\fP\fBXmTextField\fPT{
selection box containing text of selected item
T}
___
.TE
.SS "Classes"
.PP
SelectionBox inherits behavior, resources, and traits from \fBCore\fP,
\fBComposite\fP, \fBConstraint\fP, \fBXmManager\fP,
and \fBXmBulletinBoard\fP\&.
.PP
The class pointer is \fBxmSelectionBoxWidgetClass\fP\&.
.PP
The class name is \fBXmSelectionBox\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lowercase or uppercase, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G), or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmSelectionBox Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNapplyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNapplyLabelStringXmCApplyLabelStringXmStringdynamicCSG
_____
XmNcancelCallbackXmCCallbackXtCallbackListNULLC
_____
XmNcancelLabelStringXmCCancelLabelStringXmStringdynamicCSG
_____
XmNchildPlacementXmCChildPlacementunsigned charXmPLACE_ABOVE_SELECTIONCSG
_____
XmNdialogTypeXmCDialogTypeunsigned chardynamicCG
_____
XmNhelpLabelStringXmCHelpLabelStringXmStringdynamicCSG
_____
XmNlistItemCountXmCItemCountint0CSG
_____
XmNlistItemsXmCItemsXmStringTableNULLCSG
_____
XmNlistLabelStringXmCListLabelStringXmStringdynamicCSG
_____
XmNlistVisibleItemCountXmCVisibleItemCountintdynamicCSG
_____
XmNminimizeButtonsXmCMinimizeButtonsBooleanFalseCSG
_____
XmNmustMatchXmCMustMatchBooleanFalseCSG
_____
XmNnoMatchCallbackXmCCallbackXtCallbackListNULLC
_____
XmNokCallbackXmCCallbackXtCallbackListNULLC
_____
XmNokLabelStringXmCOkLabelStringXmStringdynamicCSG
_____
XmNselectionLabelStringXmCSelectionLabelStringXmStringdynamicCSG
_____
XmNtextAcceleratorsXmCTextAcceleratorsXtAcceleratorsdefaultC
_____
XmNtextColumnsXmCColumnsshortdynamicCSG
_____
XmNtextStringXmCTextStringXmString""CSG
_____
.TE
.IP "\fBXmNapplyCallback\fP" 10
Specifies the list of callbacks called
when the user activates the \fBApply\fP
button\&. The callback reason is \fBXmCR_APPLY\fP\&.
.IP "\fBXmNapplyLabelString\fP" 10
Specifies the string label for the \fBApply\fP button\&.
The default for this resource depends on the locale\&.
In the C locale the default is \fBApply\fP\&.
.IP "" 10
Now that some default localized label strings are provided through
message catalogs for the children of composite widgets, the
\fBlabelString\fP resources
cannot be set on the child through default resource files\&.
Instead, the resource provided at the parent level must be used\&.
.IP "\fBXmNcancelCallback\fP" 10
Specifies the list of callbacks called
when the user activates
the \fBCancel\fP button\&. The callback reason is \fBXmCR_CANCEL\fP\&.
.IP "\fBXmNcancelLabelString\fP" 10
Specifies the string label for the \fBCancel\fP button\&.
The default for this resource depends on the locale\&.
In the C locale the default is \fBCancel\fP\&.
.IP "" 10
Now that some default localized label strings are provided through
message catalogs for the children of composite widgets, the
\fBlabelString\fP resources
cannot be set on the child through default resource files\&.
Instead, the resource provided at the parent level must be used\&.
.IP "\fBXmNchildPlacement\fP" 10
Specifies the placement of the work area child\&. The
possible values are
.RS
.IP "\fBXmPLACE_ABOVE_SELECTION\fP" 10
Places the work area child above the Text area
.IP "\fBXmPLACE_BELOW_SELECTION\fP" 10
Places the work area child below the Text area
.IP "\fBXmPLACE_TOP\fP" 10
Places the work area child above the List area,
and below a MenuBar, if one is present
.RE
.IP "\fBXmNdialogType\fP" 10
Determines the set of SelectionBox children widgets that are created
and managed at initialization\&. The possible values are
.RS
.IP "\fBXmDIALOG_PROMPT\fP" 10
All standard children except the list and
list label are created, and all except the \fBApply\fP button are
managed
.IP "\fBXmDIALOG_COMMAND\fP" 10
Only the list, the selection label, and the
text field are created and managed
.IP "\fBXmDIALOG_SELECTION\fP" 10
All standard children are created and
managed
.IP "\fBXmDIALOG_FILE_SELECTION\fP" 10
All standard children are created and
managed
.IP "\fBXmDIALOG_WORK_AREA\fP" 10
All standard children are created, and all
except the \fBApply\fP button are managed
.RE
.IP "" 10
If the parent of the SelectionBox is a DialogShell, the default is
\fBXmDIALOG_SELECTION\fP; otherwise, the default is \fBXmDIALOG_WORK_AREA\fP\&.
\fBXmCreatePromptDialog\fP and \fBXmCreateSelectionDialog\fP set and append
this resource to the creation \fIarglist\fP supplied by the application\&.
This resource cannot be modified after creation\&.
.IP "\fBXmNhelpLabelString\fP" 10
Specifies the string label for the \fBHelp\fP button\&.
The default for this resource depends on the locale\&.
In the C locale the default is \fBHelp\fP\&.
.IP "" 10
Now that some default localized label strings are provided through
message catalogs for the children of composite widgets, the
\fBlabelString\fP resources
cannot be set on the child through default resource files\&.
Instead, the resource provided at the parent level must be used\&.
.IP "\fBXmNlistItems\fP" 10
Specifies the items in the SelectionBox list\&.
\fBXtGetValues\fP for this resource returns the list items themselves,
not a copy of the list items\&.
The application must not free the returned items\&.
.IP "\fBXmNlistItemCount\fP" 10
Specifies the number of items in the SelectionBox
list\&.
The value must not be negative\&.
.IP "\fBXmNlistLabelString\fP" 10
Specifies the string label to appear above the SelectionBox list
containing the selection items\&.
The default for this resource depends on the locale\&.
In the C locale the default is \fBItems\fP
unless \fBXmNdialogType\fP is
\fBXmDIALOG_PROMPT\fP; in this case the default is NULL\&.
.IP "" 10
Now that some default localized label strings are provided through
message catalogs for the children of composite widgets, the
\fBlabelString\fP resources
cannot be set on the child through default resource files\&.
Instead, the resource provided at the parent level must be used\&.
.IP "\fBXmNlistVisibleItemCount\fP" 10
Specifies the number of items displayed in the SelectionBox
list\&.
The value must be greater than 0 (zero) unless \fBXmNdialogType\fP is
\fBXmDIALOG_PROMPT\fP; in this case, the value is always 0\&.
The default is dynamic based on the height of the list\&.
.IP "\fBXmNminimizeButtons\fP" 10
Sets the buttons to the width of the widest button and height of the
tallest button if False\&. If True, button width and height are not
modified\&.
.IP "\fBXmNmustMatch\fP" 10
Specifies whether the selection widget should check if the
user\&'s selection in the text edit field has an exact match in
the SelectionBox list when the \fBOK\fP button is activated\&.
If the selection does not have an exact match, and
\fBXmNmustMatch\fP is True, the \fBXmNnoMatchCallback\fP callbacks are
called\&.
If the selection does have an exact match or if \fBXmNmustMatch\fP is
False, \fBXmNokCallback\fP callbacks are called\&.
.IP "\fBXmNnoMatchCallback\fP" 10
Specifies the list of callbacks called
when the user makes a selection
from the text edit field that does not have an exact match with
any of the items in the list box\&.
The callback reason is \fBXmCR_NO_MATCH\fP\&.
Callbacks in this list are called only if \fBXmNmustMatch\fP
is true\&.
.IP "\fBXmNokCallback\fP" 10
Specifies the list of callbacks called
when the user activates the \fBOK\fP button\&.
The callback reason is \fBXmCR_OK\fP\&.
If the selection text does not match a list item, and
\fBXmNmustMatch\fP is True, the \fBXmNnoMatchCallback\fP callbacks are
called instead\&.
.IP "\fBXmNokLabelString\fP" 10
Specifies the string label for the \fBOK\fP button\&.
The default for this resource depends on the locale\&.
In the C locale the default is \fBOK\fP\&.
.IP "" 10
Now that some default localized label strings are provided through
message catalogs for the children of composite widgets, the
\fBlabelString\fP resources
cannot be set on the child through default resource files\&.
Instead, the resource provided at the parent level must be used\&.
.IP "\fBXmNselectionLabelString\fP" 10
Specifies the string label for the selection text edit field\&.
The default for this resource depends on the locale\&.
In the C locale the default is \fBSelection\fP\&.
.IP "" 10
Now that some default localized label strings are provided through
message catalogs for the children of composite widgets, the
\fBlabelString\fP resources
cannot be set on the child through default resource files\&.
Instead, the resource provided at the parent level must be used\&.
.IP "\fBXmNtextAccelerators\fP" 10
Specifies translations added to the Text widget child of the
SelectionBox\&.
The default includes bindings for the up and down keys
for auto selection of list items\&.
This resource is ignored if \fBXmNaccelerators\fP is initialized to a
nondefault value\&.
.IP "\fBXmNtextColumns\fP" 10
Specifies the number of columns in the Text widget\&.
The value must be greater than 0 (zero)\&.
.IP "\fBXmNtextString\fP" 10
Specifies the text in the text edit selection field\&.
.SS "Inherited Resources"
.PP
SelectionBox inherits behavior and resources from the
superclasses in the following tables\&.
For a complete description of each resource, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmBulletinBoard Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNallowOverlapXmCAllowOverlapBooleanTrueCSG
_____
XmNautoUnmanageXmCAutoUnmanageBooleanTrueCG
_____
XmNbuttonFontListXmCButtonFontListXmFontListdynamicCSG
_____
XmNbuttonRenderTableXmCButtonRenderTableXmRenderTabledynamicCSG
_____
XmNcancelButtonXmCWidgetWidgetdynamicSG
_____
XmNdefaultButtonXmCWidgetWidgetdynamicSG
_____
XmNdefaultPositionXmCDefaultPositionBooleanTrueCSG
_____
XmNdialogStyleXmCDialogStyleunsigned chardynamicCSG
_____
XmNdialogTitleXmCDialogTitleXmStringNULLCSG
_____
XmNfocusCallbackXmCCallbackXtCallbackListNULLC
_____
XmNlabelFontListXmCLabelFontListXmFontListdynamicCSG
_____
XmNlabelRenderTableXmCLabelRenderTableXmRenderTabledynamicCSG
_____
XmNmapCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmarginHeightXmCMarginHeightDimension10CSG
_____
XmNmarginWidthXmCMarginWidthDimension10CSG
_____
XmNnoResizeXmCNoResizeBooleanFalseCSG
_____
XmNresizePolicyXmCResizePolicyunsigned charXmRESIZE_ANYCSG
_____
XmNshadowTypeXmCShadowTypeunsigned charXmSHADOW_OUTCSG
_____
XmNtextFontListXmCTextFontListXmFontListdynamicCSG
_____
XmNtextRenderTableXmCTextRenderTableXmRenderTabledynamicCSG
_____
XmNtextTranslationsXmCTranslationsXtTranslationsNULLC
_____
XmNunmapCallbackXmCCallbackXtCallbackListNULLC
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmManager Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNinitialFocusXmCInitialFocusWidgetdynamicCSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmTAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimensiondynamicCSG
_____
XmNstringDirectionXmCStringDirectionXmStringDirectiondynamicCG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBComposite Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNchildrenXmCReadOnlyWidgetListNULLG
_____
XmNinsertPositionXmCInsertPositionXtOrderProcNULLCSG
_____
XmNnumChildrenXmCReadOnlyCardinal0G
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicN/A
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
        XmString \fIvalue\fP;
        int \fIlength\fP;
} XmSelectionBoxCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback
.IP "\fIvalue\fP" 10
Indicates the \fBXmString\fR value selected by the user from the
SelectionBox list or entered into the SelectionBox text field
.IP "\fIlength\fP" 10
Indicates the size in bytes of the \fBXmString\fR value
This member is obsolete and exists for compatibility with
earlier releases\&.
.SS "Translations"
.PP
\fBXmSelectionBox\fP inherits translations from \fBXmBulletinBoard\fP\&.
.SS "Accelerators"
.PP
The \fBXmNtextAccelerators\fP are added to the Text descendant of
\fBXmSelectionBox\fP\&.
The default accelerators are described in the following list\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fB:\fP\fB<Key>\fP\fB<osfUp>\fP:" 10
SelectionBoxUpOrDown(\fBPrevious\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfDown>\fP:" 10
SelectionBoxUpOrDown(\fBNext\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfBeginLine>\fP:" 10
SelectionBoxUpOrDown(\fBFirst\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfEndLine>\fP:" 10
SelectionBoxUpOrDown(\fBLast\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfRestore>\fP:" 10
SelectionBoxRestore()
.IP "\fBs c \(apm \(apa\fP \fB<Key>\fP\fBspace\fP:" 10
SelectionBoxRestore()
.SS "Action Routines"
.PP
The XmSelectionBox action routines are
.IP "SelectionBoxUpOrDown(\fBPrevious|Next|First|Last\fP):" 10
When called with an argument of \fBPrevious\fP, or 0 (zero) for
compatibility, selects the previous
item in the
list and replaces the text with that item\&.
.IP "" 10
When called with an argument of \fBNext\fP, or 1 for
compatibility, selects the next item in the
list and replaces the text with that item\&.
.IP "" 10
When called with an argument of \fBFirst\fP, or 2 for
compatibility, selects the first item in the
list and replaces the text with that item\&.
.IP "" 10
When called with an argument of \fBLast\fP, or 3 for
compatibility, selects the last item in the
list and replaces the text with that item\&.
.IP "SelectionBoxRestore():" 10
Replaces the text value with the list selection\&.
If no item in the list is selected, clears the text\&.
.SS "Additional Behavior"
.PP
The SelectionBox widget has the following additional behavior:
.IP "\fB<Key>\fP\fB<osfCancel>\fP:" 10
Calls the activate callbacks for the cancel button if it is sensitive\&.
If no cancel button exists and the parent of the SelectionBox is a manager,
passes the event to the parent\&.
.IP "\fB<Key>\fP\fB<osfActivate>\fP:" 10
Calls the activate callbacks for the button with the keyboard focus\&.
If no button has the keyboard focus, calls the activate callbacks
for the default button if it is sensitive\&.
In a List widget or single-line Text widget,
the List or Text action associated with \fB<Key>\fP\fB<osfActivate>\fP
is called before the SelectionBox actions associated with
\fB<Key>\fP\fB<osfActivate>\fP\&.
In a multiline Text widget, any \fB<Key>\fP\fB<osfActivate>\fP
event except \fB<Key>\fP\fB<osfEnter>\fP calls
the Text action associated with \fB<Key>\fP\fB<osfActivate>\fP,
then the SelectionBox actions associated with \fB<Key>\fP\fB<osfActivate>\fP\&.
If no button has the focus, no default button exists, and the parent
of the SelectionBox is a manager, passes the event to the parent\&.
.IP "\fB<OK\ Button\ Activated>\fP:" 10
If \fBXmNmustMatch\fP is True and the text does not match an item in the
file list, calls the \fBXmNnoMatchCallback\fP callbacks with reason
\fBXmCR_NO_MATCH\fP\&.
Otherwise, calls the \fBXmNokCallback\fP callbacks with reason
\fBXmCR_OK\fP\&.
.IP "\fB<Apply\ Button\ Activated>\fP:" 10
Calls the \fBXmNapplyCallback\fP callbacks with reason \fBXmCR_APPLY\fP\&.
.IP "\fB<Cancel\ Button\ Activated>\fP:" 10
Calls the \fBXmNcancelCallback\fP callbacks with reason
\fBXmCR_CANCEL\fP\&.
.IP "\fB<Help\ Button\ Activated>\fP:" 10
Calls the \fBXmNhelpCallback\fP callbacks with reason \fBXmCR_HELP\fP\&.
.IP "\fB<MapWindow>\fP:" 10
Calls the callbacks for \fBXmNmapCallback\fP if the SelectionBox
is a child of a Dialog shell\&.
.IP "\fB<UnmapWindow>\fP:" 10
Calls the callbacks for \fBXmNunmapCallback\fP if the SelectionBox is
the child of a DialogShell\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys, see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBComposite\fP(3),
\fBConstraint\fP(3),
\fBCore\fP(3),
\fBXmBulletinBoard\fP(3),
\fBXmCreateSelectionBox\fP(3),
\fBXmCreateSelectionDialog\fP(3),
\fBXmCreatePromptDialog\fP(3),
\fBXmManager\fP(3), and
\fBXmSelectionBoxGetChild\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
