'\" t
...\" SSpinBoxA.sgm /main/1 1996/09/06 09:24:28 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmSimpleSpinBoxAddItem" "library call"
.SH "NAME"
\fBXmSimpleSpinBoxAddItem\fP \(em add an item to the XmSimpleSpinBox
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/SSpinB\&.h>
\fBvoid \fBXmSimpleSpinBoxAddItem\fP\fR(
\fBWidget \fBw\fR\fR,
\fBXmString \fBitem\fR\fR,
\fBint \fBpos\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
The
\fBXmSimpleSpinBoxAddItem\fP function adds the given item to the XmSimpleSpinBox at the given
position\&.
.PP
The
\fIw\fP argument specifies the widget ID\&.
.PP
The
\fIitem\fP argument specifies the
\fBXmString\fR for the new item\&.
.PP
The
\fIpos\fP argument specifies the position of the new item\&.
.SH "RETURN VALUE"
.PP
The
\fBXmSimpleSpinBoxAddItem\fP function returns no value\&.
.SH "SEE ALSO"
.PP
\fBXmSimpleSpinBox\fP(3),
.PP
\fBXmSimpleSpinBoxDeletePos\fP(3), \fBXmSimpleSpinBoxSetItem\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
