'\" t
...\" String.sgm /main/8 1996/09/08 21:08:15 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmString" "library call"
.SH "NAME"
\fBXmString\fR \(em Data type for a compound string
.iX "XmString"
.iX "data types" "XmString"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
.fi
.SH "DESCRIPTION"
.PP
\fBXmString\fR
is the data type for a compound string\&.
Compound strings consist of a sequence of components, including, but
not limited to, the following:
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_SEPARATOR\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_TAB\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_LAYOUT_POP\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_DIRECTION\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_LAYOUT_PUSH\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_CHARSET\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_FONTLIST_ELEMENT_TAG\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_LOCALE\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_LOCALE_TEXT\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_TAG\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_TEXT\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_END\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_RENDITION_BEGIN\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_RENDITION_END\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_UNKNOWN\fP
.IP "   \(bu" 6
\fBXmSTRING_COMPONENT_WIDECHAR_TEXT\fP
.PP
and also a rendition tags table, text, and text component\&.
When a
compound string is displayed, the rendition tags and the
direction are used to determine how to display the text\&.
.PP
Calling \fBXtGetValues\fP for a resource whose type is \fBXmString\fR yields a
copy of the compound string resource value\&.
The application is responsible for using \fBXmStringFree\fP to free the
memory allocated for the copy\&.
.PP
Please see the \fBXmStringComponentType\fR reference page for more
detail about compound string components, and for a description of the
order in which the components should appear in a compound string\&.
Refer to the \fBXmRenderTable\fR reference page for a description
of the algorithm that associates the rendition tags used for
displaying a compound string text component with a rendition in a
render table\&.
.SH "RELATED"
.PP
\fBXmParseMapping\fP(3),
\fBXmParseMappingCreate\fP(3),
\fBXmParseMappingFree\fP(3),
\fBXmParseMappingGetValues\fP(3),
\fBXmParseMappingSetValues\fP(3),
\fBXmParseTable\fP(3),
\fBXmParseTableFree\fP(3),
\fBXmStringBaseline\fP(3),
\fBXmStringByteCompare\fP(3),
\fBXmStringByteStreamLength\fP(3),
\fBXmStringCompare\fP(3),
\fBXmStringComponentCreate\fP(3),
\fBXmStringComponentType\fP(3),
\fBXmStringConcat\fP(3),
\fBXmStringConcatAndFree\fP(3),
\fBXmStringCopy\fP(3),
\fBXmStringCreate\fP(3),
\fBXmStringCreateLocalized\fP(3),
\fBXmStringCreateLtoR\fP(3),
\fBXmStringCreateSimple\fP(3),
\fBXmStringDirection\fP(3),
\fBXmStringDirectionCreate\fP(3),
\fBXmStringDirectionToDirection\fP(3),
\fBXmStringDraw\fP(3),
\fBXmStringDrawImage\fP(3),
\fBXmStringDrawUnderline\fP(3),
\fBXmStringEmpty\fP(3),
\fBXmStringExtent\fP(3),
\fBXmStringFree\fP(3),
\fBXmStringFreeContext\fP(3),
\fBXmStringGenerate\fP(3),
\fBXmStringGetLtoR\fP(3),
\fBXmStringGetNextComponent\fP(3),
\fBXmStringGetNextSegment\fP(3),
\fBXmStringGetNextTriple\fP(3),
\fBXmStringHasSubstring\fP(3),
\fBXmStringHeight\fP(3),
\fBXmStringInitContext\fP(3),
\fBXmStringIsVoid\fP(3),
\fBXmStringLength\fP(3),
\fBXmStringLineCount\fP(3),
\fBXmStringNConcat\fP(3),
\fBXmStringNCopy\fP(3),
\fBXmStringParseText\fP(3),
\fBXmStringPeekNextComponent\fP(3),
\fBXmStringPeekNextTriple\fP(3),
\fBXmStringPutRendition\fP(3),
\fBXmStringSegmentCreate\fP(3),
\fBXmStringSeparatorCreate\fP(3),
\fBXmStringTable\fP(3),
\fBXmStringTableParseStringArray\fP(3),
\fBXmStringTableProposeTablist\fP(3),
\fBXmStringTableToXmString\fP(3),
\fBXmStringTableUnparse\fP(3),
\fBXmStringToXmStringTable\fP(3),
\fBXmStringUnparse\fP(3),
\fBXmStringWidth\fP(3),
\fBXmCvtXmStringToByteStream\fP(3),
\fBXmCvtXmStringToCT\fP(3),
\fBXmCvtCTToXmString\fP(3), and
\fBXmCvtByteStreamToXmString\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
