'\" t
...\" StrTaB.sgm /main/9 1996/09/08 21:07:19 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmStringTableParseStringArray" "library call"
.SH "NAME"
\fBXmStringTableParseStringArray\fP \(em A convenience function that converts an array of strings to a compound string table
.iX "XmStringTableParseStringArray"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmStringTable \fBXmStringTableParseStringArray\fP\fR(
\fBXtPointer \fB*strings\fR\fR,
\fBCardinal \fBcount\fR\fR,
\fBXmStringTag \fBtag\fR\fR,
\fBXmTextType \fBtype\fR\fR,
\fBXmParseTable \fBparse\fR\fR,
\fBCardinal \fBparse_count\fR\fR,
\fBXtPointer \fBcall_data\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmStringTableParseStringArray\fP takes an array of strings,
allocates an \fBXmStringTable\fR with an equal number of slots, calls
\fBXmStringParseText\fP on each string in \fIstrings\fP, and inserts
the resulting \fBXmString\fR in the corresponding slot in the
\fBXmStringTable\fR\&.
.IP "\fIstrings\fP" 10
Specifies an array of strings of characters as determined by
\fItype\fP\&.
.IP "\fIcount\fP" 10
Specifies the number of strings in \fIstrings\fP\&.
.IP "\fItag\fP" 10
Specifies the tag to be used in creating the result\&. The type of tag
created (charset or locale) depends on the type of the text and
the value given\&. If the value specified is NULL, and \fItype\fP
indicates that a charset tag should be created, then the tag will
have the value of
\fBXmFONTLIST_DEFAULT_TAG\fP\&.
If \fItype\fP
indicates a locale tag, then the tag will have the value of
\fBXmFONTLIST_DEFAULT_TAG\fP\&.
.IP "\fItype\fP" 10
Specifies the type of text to be passed in and the type of tag\&. If
the type is either \fBXmMULTIBYTE_TEXT\fP or \fBXmWIDECHAR_TEXT\fP, a
locale tag should be created\&. If the type is \fBXmCHARSET_TEXT\fP, a
charset tag
will
be created\&.
.IP "\fIparse\fP" 10
Specifies the parse table to be used\&.
.IP "\fIparse_count\fP" 10
Specifies the number of entries in the parse table\&.
.IP "\fIcall_data\fP" 10
Specifies data to be passed to the parse procedures\&.
.SH "RETURN"
.PP
Returns a new \fBXmStringTable\fR\&.
The function allocates space to hold the \fBXmStringTable\fR\&.
When the application no longer needs the returned \fBXmStringTable\fR,
the application should call \fBXmStringFree\fP
\fIcount\fP times (that is, one time for each returned compound string)
and then call \fBXtFree\fP to deallocate the \fBXmStringTable\fR itself\&.
.SH "RELATED"
.PP
\fBXmStringFree\fP(3) and
\fBXmTabList\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
