'\" t
...\" StrGeC.sgm /main/9 1996/09/08 21:05:15 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmStringGetNextComponent" "library call"
.SH "NAME"
\fBXmStringGetNextComponent\fP \(em A compound string function that returns the type and value of the next component in a compound string
.iX "XmStringGetNextComponent"
.iX "compound string functions" "XmStringGetNextComponent"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmStringComponentType \fBXmStringGetNextComponent\fP\fR(
\fBXmStringContext \fBcontext\fR\fR,
\fBchar **\fBtext\fR\fR,
\fBXmStringTag *\fBtag\fR\fR,
\fBXmStringDirection *\fBdirection\fR\fR,
\fBXmStringComponentType *\fBunknown_tag\fR\fR,
\fBunsigned short *\fBunknown_length\fR\fR,
\fBunsigned char **\fBunknown_value\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
This function is obsolete and exists for compatibility with previous
releases\&. It is replaced by \fBXmStringGetNextTriple\fP\&.
\fBXmStringGetNextComponent\fP
returns the type and value of the next component in
the compound string identified by \fIcontext\fP\&.
Components are returned one at a time\&. On return, only
some output parameters will be valid; which ones can be determined by
examining the returned component type\&.
The following table describes the valid returns for each component
type\&.
.TS
tab() box;
lw(2.0i)| l.
\fBValid Fields\fP\fBComponent Type\fP
__
\fItag\fPT{
\fBXmSTRING_COMPONENT_LOCALE, XmSTRING_COMPONENT_TAG\fP
T}
__
\fItext\fPT{
\fBXmSTRING_COMPONENT_LOCALE_TEXT, XmSTRING_COMPONENT_TEXT,
XmSTRING_COMPONENT_WIDECHAR_TEXT\fP
T}
__
\fIdirection\fP\fBXmSTRING_COMPONENT_DIRECTION\fP
__
T{
\fIunknown_tag, unknown_length, unknown_value\fP
T}T{
\fBXmSTRING_COMPONENT_LAYOUT_POP, XmSTRING_COMPONENT_LAYOUT_PUSH,
XmSTRING_COMPONENT_TAB, XmSTRING_COMPONENT_RENDITION_BEGIN,
XmSTRING_COMPONENT_RENDITION_END\fP
T}
__
\fIno valid field\fPT{
\fBXmSTRING_COMPONENT_SEPARATOR, XmSTRING_COMPONENT_END,
XmSTRING_COMPONENT_UNKNOWN\fP
T}
__
.TE
.PP
Note that several components produce a return value of
\fBXmSTRING_COMPONENT_UNKNOWN\fP\&. The data returned by these
components is returned in the \fIunknown_tag\fP, \fIunknown_length\fP,
and \fIunknown_value\fP fields\&. This apparent inconsistency is
designed to accomodate older applications that may not be equipped to
handle the newer component types of Motif version 2\&.0 and beyond\&.
Consequently, the use of this procedure is not recommended\&. Instead,
use the \fBXmStringGetNextTriple\fP procedure, which provides all the
functionality of \fBXmStringGetNextComponent\fP, and is fully
compatible with the newer component types\&.
.PP
If the function return value is \fBXmSTRING_COMPONENT_LOCALE_TEXT\fP or
\fBXmSTRING_COMPONENT_TEXT\fP, the the function allocates space to hold
the returned \fItext\fP\&.
If the function return value is \fBXmSTRING_COMPONENT_FONTLIST_ELEMENT_TAG\fP,
or \fBXmSTRING_COMPONENT_TAG\fP, then the function allocates space to hold
the returned \fItag\fP\&.
The application is responsible for managing the allocated space\&.
The application can recover the allocated space by calling \fBXtFree\fP\&.
.IP "\fIcontext\fP" 10
Specifies the string context structure that was allocated by the
\fBXmStringInitContext\fP function\&.
.IP "\fItext\fP" 10
Specifies a pointer to a NULL terminated string\&.
.IP "\fItag\fP" 10
Specifies a pointer to the tag component associated with the
text\&. The value \fBXmFONTLIST_DEFAULT_TAG\fP identifies a locale
text segment\&.
.IP "\fIdirection\fP" 10
Specifies a pointer to the direction of the text\&.
.IP "\fIunknown_tag\fP" 10
Specifies a pointer to the tag of an unknown component\&.
.IP "\fIunknown_length\fP" 10
Specifies a pointer to the length of an unknown component\&.
.IP "\fIunknown_value\fP" 10
Specifies a pointer to the value of an unknown component\&.
.SH "RETURN"
.PP
Returns the type of component found\&.
Refer to the
\fBXmStringComponentType\fP(3) reference page for a list of component types\&.
.SH "RELATED"
.PP
\fBXmStringComponentType\fP(3),
\fBXmStringCreate\fP(3),
and \fBXmStringInitContext\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
