'\" t
...\" StrGeA.sgm /main/8 1996/09/08 21:04:59 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmStringGenerate" "library call"
.SH "NAME"
\fBXmStringGenerate\fP \(em A convenience function that generates a compound string
.iX "XmStringGenerate"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmString \fBXmStringGenerate\fP\fR(
\fBXtPointer \fBtext\fR\fR,
\fBXmStringTag \fBtag\fR\fR,
\fBXmTextType \fBtype\fR\fR,
\fBXmStringTag \fBrendition\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmStringGenerate\fP calls the \fBXmStringParseText\fP
function with a default parse table of entries
consisting of \&'\n\&', which maps to
Separator,
and \&'\t\&', which maps to Tab\&.
Matching \fBRENDITION_BEGIN\fP and
\fBRENDITION_END\fP components containing \fIrendition\fP are placed
around the resulting \fBXmString\fR\&.
.IP "\fItext\fP" 10
Specifies a NULL-terminated string containing characters of a type
determined by \fItype\fP\&.
.IP "\fItag\fP" 10
Specifies the tag to be used in creating the result\&. The type of tag
created (charset or locale) depends on the text type and the
value given\&. If specified value is NULL, and \fItype\fP indicates
that a charset tag should be created, then the tag will have the
value of
\fBXmFONTLIST_DEFAULT_TAG\fP\&.
If \fItag\fP is NULL, and \fItype\fP indicates a
locale tag, then the tag will have the value of \fB_MOTIF_DEFAULT_LOCALE\fP\&.
.IP "\fItype\fP" 10
Specifies the type of text to be passed in, and the tag type\&.
If a locale tag should be created, then \fItype\fP has a value of
either \fBXmMULTIBYTE_TEXT\fP or \fBXmWIDECHAR_TEXT\fP\&. If a
charset should be created, \fItype\fP has a value of
\fBXmCHARSET_TEXT\fP\&.
.IP "\fIrendition\fP" 10
Specifies the rendition tag to be used in an
\fBXmSTRING_COMPONENT_RENDITION_BEGIN\fP component which will begin
the returned string and in an \fBXmSTRING_COMPONENT_RENDITION_END\fP
component which will end it\&.
If \fIrendition\fP is NULL, no rendition tag is placed\&.
.SH "RETURN"
.PP
Returns a new compound string\&.
The function will allocate space to hold the returned compound string\&.
When the application no longer needs the returned compound string, the
application should call \fBXmStringFree\fP\&.
.SH "RELATED"
.PP
\fBXmString\fP(3) and
\fBXmStringFree\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
