'\" t
...\" StrHas.sgm /main/7 1996/08/30 16:11:48 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmStringHasSubstring" "library call"
.SH "NAME"
\fBXmStringHasSubstring\fP \(em A compound string function that indicates whether one compound string is contained within another
.iX "XmStringHasSubstring"
.iX "compound string functions" "XmStringHasSubstring"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBBoolean \fBXmStringHasSubstring\fP\fR(
\fBXmString \fBstring\fR\fR,
\fBXmString \fBsubstring\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmStringHasSubstring\fP
indicates whether or not one compound string is contained within
another\&.
.IP "\fIstring\fP" 10
Specifies the compound string to be searched
.IP "\fIsubstring\fP" 10
Specifies the compound string to be searched for
.SH "RETURN"
.PP
Returns True if
\fIsubstring\fP
has a single text component and if its text is completely contained within any
single text component of \fIstring\fP; otherwise, it returns False\&.
.SH "RELATED"
.PP
\fBXmStringCreate\fP(3) and
\fBXmStringCreateLocalized\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
