'\" t
...\" StrWid.sgm /main/8 1996/09/08 21:08:07 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmStringWidth" "library call"
.SH "NAME"
\fBXmStringWidth\fP \(em A compound string function that returns the width of the widest line in a compound string
.iX "XmStringWidth"
.iX "compound string functions" "XmStringWidth"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBDimension \fBXmStringWidth\fP\fR(
\fBXmRenderTable \fBrendertable\fR\fR,
\fBXmString \fBstring\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmStringWidth\fP
returns the width, in pixels, of the widest line
in the provided compound string\&.
.IP "\fIrendertable\fP" 10
Specifies the render table
.IP "\fIstring\fP" 10
Specifies the string
.SH "RETURN"
.PP
Returns the width of the compound string\&.
.SH "RELATED"
.PP
\fBXmStringCreate\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
