'\" t
...\" StrPut.sgm /main/8 1996/09/08 21:06:53 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmStringPutRendition" "library call"
.SH "NAME"
\fBXmStringPutRendition\fP \(em A convenience function that places renditions around strings
.iX "XmStringPutRendition"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBXmString \fBXmStringPutRendition\fP\fR(
\fBXmString \fBstring\fR\fR,
\fBXmStringTag \fBrendition\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmStringPutRendition\fP places matching
\fBXm_STRING_COMPONENT_RENDITION_BEGIN\fP and
\fBXmSTRING_COMPONENT_RENDITION_END\fP components containing
\fIrendition\fP around
\fIstring\fP\&. The original string is preserved\&.
.IP "\fIstring\fP" 10
Specifies the compound string to which begin and end rendition
components should be added\&.
.IP "\fIrendition\fP" 10
Specifies the rendition tag to be used in an
\fBXmSTRING_COMPONENT_RENDITION_BEGIN\fP component which will begin
the returned string and in an \fBXmSTRING_COMPONENT_RENDITION_END\fP
component which will end it\&.
.SH "RETURN"
.PP
Returns a new compound string\&.
The function allocates space to hold this returned compound string\&.
When the application no longer needs the returned compound string,
the application should call \fBXmStringFree\fP\&.
.SH "RELATED"
.PP
\fBXmString\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
