'\" t
...\" TabSetV.sgm /main/8 1996/09/08 21:09:44 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTabSetValue" "library call"
.SH "NAME"
\fBXmTabSetValue\fP \(em A convenience function that sets a tab stop
.iX "XmTabSetValue"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBvoid \fBXmTabSetValue\fP\fR(
\fBXmTab \fBtab\fR\fR,
\fBfloat \fBvalue\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmTabSetValue\fP sets the \fIvalue\fP field of the \fBXmTab\fR
structure associated with \fItab\fP\&.
.IP "\fItab\fP" 10
Specifies the tab to set the value of\&.
.IP "\fIvalue\fP" 10
Specifies the floating point number which represents the distance that
the rendering of the \fBXmString\fR segment associated with \fItab\fP
will be offset\&. The offset is from either the beginning of the
rendering or from the previous tab stop, depending on the setting for
the \fIoffset\fP model\&. The distance depends on the tab\&'s unit type\&.
Note that negative values are not permitted, and that if a tab stop
would cause text to overlap, the x position for the segment is set
immediately after the end of the previous segment\&.
.SH "RELATED"
.PP
See also the \fIMotif Programmer\&'s Guide\fP for more information about tabs
and tab lists\&.
\fBXmTab\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
