'\" t
...\" TxtFieAU.sgm /main/7 1996/08/30 16:25:31 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTextFieldPasteLink" "library call"
.SH "NAME"
\fBXmTextFieldPasteLink\fP \(em A TextField function that inserts a link to the clipboard selection
.iX "XmTextFieldPasteLink"
.iX "TextField functions" "XmTextFieldPasteLink"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/TextF\&.h>
\fBBoolean \fBXmTextFieldPasteLink\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmTextFieldPasteLink\fP inserts a link to the clipboard selection at
the insertion cursor\&.
This routine calls the widget\&'s \fBXmNdestinationCallback\fP procedures
with the \fIselection\fP member of the \fBXmDestinationCallbackStruct\fR
set to \fBCLIPBOARD\fP and with the \fIoperation\fP member set to
\fBXmLINK\fP\&.
The TextField widget itself performs no transfers; the
\fBXmNdestinationCallback\fP procedures are responsible for inserting
the link to the clipboard selection and for taking any related actions\&.
.IP "\fIwidget\fP" 10
Specifies the TextField widget ID\&.
.PP
For a complete definition of TextField and its associated resources, see
\fBXmTextField\fP(3)\&.
.SH "RETURN"
.PP
This function returns False if no transfers take place\&.
Otherwise, it returns True\&.
.SH "RELATED"
.PP
\fBXmTextField\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
