'\" t
...\" TxtGetSH.sgm /main/9 1996/09/08 21:18:08 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTextGetSubstringWcs" "library call"
.SH "NAME"
\fBXmTextGetSubstringWcs\fP \(em A Text function that retrieves
a portion of a wide character internal text buffer
.iX "XmTextGetSubstringWcs"
.iX "Text functions" "XmTextGetSubstringWcs"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Text\&.h>
\fBint \fBXmTextGetSubstringWcs\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmTextPosition \fBstart\fR\fR,
\fBint \fBnum_chars\fR\fR,
\fBint \fBbuffer_size\fR\fR,
\fBwchar_t *\fBbuffer\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmTextGetSubstringWcs\fP retrieves a copy of a portion of the internal
text buffer of a Text widget that is stored in a wide character
format\&. The function copies a specified number of characters from
a given start position in the internal text buffer into a buffer
provided by the application\&. A NULL terminator is placed at the
end of the copied data\&.
.IP "\fIwidget\fP" 10
Specifies the Text widget ID\&.
.IP "\fIstart\fP" 10
Specifies the beginning character position from which the data will be
retrieved\&. This is an integer number of characters from the beginning of
the text buffer\&. The first character position is 0 (zero)\&.
.IP "\fInum_chars\fP" 10
Specifies the number of \fBwchar_t\fR characters to be copied into
the provided buffer\&.
.IP "\fIbuffer_size\fP" 10
Specifies the size of the supplied buffer as a number of \fBwchar_t\fR
storage locations\&. The minimum size is \fInum_chars\fP + 1\&.
.IP "\fIbuffer\fP" 10
Specifies the wide character buffer into which the internal
text buffer will be copied\&.
.PP
For a complete definition of Text and its associated resources,
see \fBXmText\fP(3)\&.
.SH "RETURN"
.IP "\fBXmCOPY_SUCCEEDED\fP" 10
The function was successful\&.
.IP "\fBXmCOPY_FAILED\fP" 10
The function failed because it was unable to copy the
specified number of characters into the buffer provided\&.
The buffer size may be insufficient\&. The contents of
\fIbuffer\fP are undefined\&.
.IP "\fBXmCOPY_TRUNCATED\fP" 10
The requested number of characters extended beyond the internal
buffer\&. The function copied characters between \fIstart\fP and the
end of the widget\&'s buffer and terminated the string with a NULL
terminator; fewer than \fInum_chars\fP characters were copied\&.
.SH "RELATED"
.PP
\fBXmText\fP(3) and \fBXmTextGetSubstring\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
