'\" t
...\" TxtPosTo.sgm /main/11 1996/09/08 21:18:46 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTextPosToXY" "library call"
.SH "NAME"
\fBXmTextPosToXY\fP \(em A Text function that accesses the x and y position of a character position
.iX "XmTextPosToXY"
.iX "Text functions" "XmTextPosToXY"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Text\&.h>
\fBBoolean \fBXmTextPosToXY\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmTextPosition \fBposition\fR\fR,
\fBPosition \fB*x\fR\fR,
\fBPosition \fB*y\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmTextPosToXY\fP accesses the \fIx\fP and \fIy\fP position,
relative to the upper
left corner of the Text widget, of a given character position in the
text buffer\&.
.PP
In the case of horizontal writing, the position is the origin of the
character\&. In the case of vertical writing, the position is the vertical
origin of the character\&.
.IP "\fIwidget\fP" 10
Specifies the Text widget ID
.IP "\fIposition\fP" 10
Specifies the character position in the text for which the \fIx\fP and \fIy\fP
position is accessed\&. This is an integer number of characters
from the beginning of the buffer\&. The first character position is 0 (zero)\&.
.IP "\fIx\fP" 10
Specifies the pointer in which the \fIx\fP position is returned\&.
The returned position is the distance from the left side of the widget
to the left border of the character\&.
This value is meaningful only if the function returns True\&.
.IP "\fIy\fP" 10
Specifies the pointer in which the \fIy\fP position is returned\&.
The returned position is the distance from the top of the widget
to the character\&'s baseline\&.
This value is meaningful only if the function returns True\&.
.PP
For a complete definition of Text and its associated resources, see
\fBXmText\fP(3)\&.
.SH "RETURN"
.PP
This function returns True if the character position is displayed in the
Text widget; otherwise, it returns False, and no \fIx\fP or \fIy\fP
value is returned\&.
.SH "RELATED"
.PP
\fBXmText\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
