'\" t
...\" TxtFieAA.sgm /main/15 1996/09/25 15:57:20 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTextField" "library call"
.SH "NAME"
\fBXmTextField\fP \(em The TextField class
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
.fi
.SH "DESCRIPTION"
.PP
The TextField widget provides a single line text editor for customizing
both user and programmatic interfaces\&. It is used for single-line
string entry, and forms entry with verification procedures\&.
It provides an application with a consistent editing system for
textual data\&.
.PP
TextField provides separate callback lists to verify
movement of the insert cursor, modification of the text, and
changes in input focus\&. Each of
these callbacks provides the verification function with the
widget instance, the event that caused the callback, and a
data structure specific to the verification type\&. From this
information, the function can verify if the application considers
this to be a legitimate state change and can signal the widget
whether to continue with the action\&.
.PP
The user interface tailors a new set of actions\&.
The key bindings have been added for insert cursor movement, deletion,
insertion, and selection of text\&.
.PP
TextField allows the user to select regions of text\&.
Selection is based on the model specified in the \fIInter-Client
Communication Conventions Manual\fP (ICCCM)\&.
TextField supports primary and secondary selection\&.
.PP
TextField uses the \fBXmQTnavigator\fP, \fBXmQTspecifyRenderTable\fP, and
\fBXmQTscrollFrame\fP traits,
and holds the \fBXmQTaccessTextual\fP
\fBXmQTtransfer\fP traits\&.
.PP
If an application or widget calls the \fBsetValue\fP trait method
of \fBXmQTaccessTextual\fP, then \fBXmTextField\fP will call
\fBXmTextFieldSetString\fP to set the string value\&.
.SS "Data Transfer Behavior"
.PP
TextField supports transfer of the primary, secondary, and clipboard
selections and dragging of selected text from the widget\&.
TextField can also be the destination for the primary, secondary, and
clipboard selections, and it supports dropping of data being dragged
onto the widget\&.
.PP
When the \fBXmNconvertCallback\fP procedures are called, the
\fBlocation_data\fP member of the \fBXmConvertCallbackStruct\fR member
is NULL if the selected text is being transferred\&.
If the entire text, not the selected text, is being transferred, the
value of this member is the widget ID of the TextField widget\&.
.PP
As a source of data, TextField supports the following targets and
associated conversions of data to these targets:
.IP "\fIlocale\fP" 10
If the \fIlocale\fP target matches the widget\&'s locale, the widget
transfers the selected text in the encoding of the locale\&.
.IP "\fBCOMPOUND_TEXT\fP" 10
The widget transfers the selected text as type \fBCOMPOUND_TEXT\fP\&.
.IP "\fBSTRING\fP" 10
The widget transfers the selected text as type \fBSTRING\fP\&.
.IP "\fBTEXT\fP" 10
If the selected text is fully convertible to the encoding of the locale,
the widget transfers the selected text in the encoding of the locale\&.
Otherwise, the widget transfers the selected text as type
\fBCOMPOUND_TEXT\fP\&.
.IP "\fBDELETE\fP" 10
The widget deletes the selected text\&.
.IP "\fB_MOTIF_CLIPBOARD_TARGETS\fP" 10
The widget transfers, as type \fBATOM\fP, a list of the targets to which
the widget can convert data to be placed on the clipboard immediately\&.
These include the following targets:
.RS
.IP "   \(bu" 6
\fBCOMPOUND_TEXT\fP
.IP "   \(bu" 6
The encoding of the locale, if the selected text is fully convertible to
the encoding of the locale
.IP "   \(bu" 6
\fBSTRING\fP, if the selected text is fully convertible to \fBSTRING\fP
.RE
.IP "\fB_MOTIF_EXPORT_TARGETS\fP" 10
The widget transfers, as type \fBATOM\fP, a list of the targets to be
used as the value of the DragContext\&'s \fBXmNexportTargets\fP in a
drag-and-drop transfer\&.
These include \fBCOMPOUND_TEXT\fP, the encoding of the locale,
\fBSTRING\fP, \fBTEXT\fP, \fBBACKGROUND\fP, and \fBFOREGROUND\fP\&.
.IP "\fB_MOTIF_LOSE_SELECTION\fP" 10
The widget takes the following actions:
.RS
.IP "   \(bu" 6
When losing the \fBPRIMARY\fP selection, it unhighlights the selected
text and calls the \fBXmNlosePrimaryCallback\fP procedures\&.
.IP "   \(bu" 6
When losing the \fBSECONDARY\fP selection, it removes the secondary
selection highlight\&.
.IP "   \(bu" 6
When losing the \fB_MOTIF_DESTINATION\fP selection, if the widget does
not have focus it changes the cursor to indicate that the widget is no
longer the destination\&.
.RE
.PP
As a source of data, TextField also supports the following standard
Motif targets:
.IP "\fBBACKGROUND\fP" 10
The widget transfers \fBXmNbackground\fP as type \fBPIXEL\fP\&.
.IP "\fBCLASS\fP" 10
The widget finds the first shell in the widget hierarchy that has a
\fBWM_CLASS\fP property and transfers the contents as text in the
current locale\&.
.IP "\fBCLIENT_WINDOW\fP" 10
The widget finds the first shell in the widget hierarchy and transfers
its window as type \fBWINDOW\fP\&.
.IP "\fBCOLORMAP\fP" 10
The widget transfers \fBXmNcolormap\fP as type \fBCOLORMAP\fP\&.
.IP "\fBFOREGROUND\fP" 10
The widget transfers \fBXmNforeground\fP as type \fBPIXEL\fP\&.
.IP "\fBNAME\fP" 10
The widget finds the first shell in the widget hierarchy that has a
\fBWM_NAME\fP property and transfers the contents as text in the current
locale\&.
.IP "\fBTARGETS\fP" 10
The widget transfers, as type \fBATOM\fP, a list of the targets it
supports\&.
These include the standard targets in this list\&.
These also include \fBCOMPOUND_TEXT\fP, the encoding of the locale,
\fBSTRING\fP, and \fBTEXT\fP\&.
.IP "\fBTIMESTAMP\fP" 10
The widget transfers the timestamp used to acquire the selection as type
\fBINTEGER\fP\&.
.IP "\fB_MOTIF_RENDER_TABLE\fP" 10
The widget transfers \fBXmNrenderTable\fP if it exists, or else the
default text render table, as type \fBSTRING\fP\&.
.IP "\fB_MOTIF_ENCODING_REGISTRY\fP" 10
The widget transfers its encoding registry as type \fBSTRING\fP\&.
The value is a list of NULL separated items in the
form of tag encoding pairs\&.
This target symbolizes the transfer target for the
Motif Segment Encoding Registry\&.
Widgets and applications can use this Registry to register
text encoding formats for specified render table tags\&.
Applications access this Registry by calling
\fBXmRegisterSegmentEncoding\fP and \fBXmMapSegmentEncoding\fP\&.
.PP
As a destination for data, TextField chooses a target and requests
conversion of the selection to that target\&.
If the encoding of the locale is present in the list of available
targets, TextField chooses a requested target from the available targets
in the following order of preference:
.IP "   1." 6
\fBTEXT\fP
.IP "   2." 6
\fBCOMPOUND_TEXT\fP
.IP "   3." 6
The encoding of the locale
.IP "   4." 6
\fBSTRING\fP
.PP
If the encoding of the locale is not present in the list of available
targets, TextField chooses a requested target from the available targets
in the following order of preference:
.IP "   1." 6
\fBCOMPOUND_TEXT\fP
.IP "   2." 6
\fBSTRING\fP
.SS "Classes"
.PP
TextField widget inherits behavior, resources, and traits from \fBCore\fP
and \fIPrimitive\fP\&.
.PP
The class pointer is \fBxmTextFieldWidgetClass\fP\&.
.PP
The class name is \fBXmTextField\fP\&.
.SS "New Resources"
.PP
The following table defines a set of widget resources used by the programmer
to specify data\&. The programmer can also set the resource values for the
inherited classes to set attributes for this widget\&. To reference a
resource by name or by class in a \fB\&.Xdefaults\fP file, remove the \fBXmN\fP or
\fBXmC\fP prefix and use the remaining letters\&. To specify one of the defined
values for a resource in a \fB\&.Xdefaults\fP file, remove the \fBXm\fP prefix and use
the remaining letters (in either lower case or upper case, but include any
underscores between words)\&.
The codes in the access column indicate if the given resource can be
set at creation time (C),
set by using \fBXtSetValues\fP (S),
retrieved by using \fBXtGetValues\fP (G),
or is not applicable (N/A)\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmTextFieldResource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNactivateCallbackXmCCallbackXtCallbackListNULLC
_____
XmNblinkRateXmCBlinkRateint500CSG
_____
XmNcolumnsXmCColumnsshortdynamicCSG
_____
XmNcursorPositionXmCCursorPositionXmTextPosition0CSG
_____
XmNcursorPositionVisibleXmCCursorPositionVisibleBooleandynamicCSG
_____
XmNdestinationCallbackXmCCallbackXtCallbackListNULLC
_____
XmNeditableXmCEditableBooleanTrueCSG
_____
XmNfocusCallbackXmCCallbackXtCallbackListNULLC
_____
XmNfontListXmCFontListXmFontListdynamicCSG
_____
XmNgainPrimaryCallbackXmCCallbackXtCallbackListNULLC
_____
XmNlosePrimaryCallbackXmCCallbackXtCallbackListNULLC
_____
XmNlosingFocusCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmarginHeightXmCMarginHeightDimension5CSG
_____
XmNmarginWidthXmCMarginWidthDimension5CSG
_____
XmNmaxLengthXmCMaxLengthintlargest integerCSG
_____
XmNmodifyVerifyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNmodifyVerifyCallbackWcsXmCCallbackXtCallbackListNULLC
_____
XmNmotionVerifyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNpendingDeleteXmCPendingDeleteBooleanTrueCSG
_____
XmNrenderTableXmCRenderTableXmRenderTabledynamicCSG
_____
XmNresizeWidthXmCResizeWidthBooleanFalseCSG
_____
XmNselectionArrayXmCSelectionArrayXtPointerdefault arrayCSG
_____
XmNselectionArrayCountXmCSelectionArrayCountint3CSG
_____
XmNselectThresholdXmCSelectThresholdint5CSG
_____
XmNvalueXmCValueString""CSG
_____
XmNvalueChangedCallbackXmCCallbackXtCallbackListNULLC
_____
XmNvalueWcsXmCValueWcswchar_t *(wchar_t *)""CSG\u1\d
_____
XmNverifyBellXmCVerifyBellBooleandynamicCSG
_____
.TE
.PP
\u1\d This resource cannot be specified in a resource file\&.
.IP "\fBXmNactivateCallback\fP" 10
Specifies the list of callbacks that is called when the user invokes an
event that calls the
activate() action\&.
The type of the structure whose address is passed to this callback is
\fBXmAnyCallbackStruct\fR\&.
The reason sent by the callback is \fBXmCR_ACTIVATE\fP\&.
.IP "\fBXmNblinkRate\fP" 10
Specifies the blink rate of the text cursor in milliseconds\&.
The time indicated in the blink rate relates to the
length of time the cursor is visible and the time the
cursor is invisible (that is, the time it will take to blink
the insertion cursor on and off will be two times the blink
rate)\&. The cursor will not blink when the blink rate
is set to 0 (zero)\&.
The value must not be negative\&.
.IP "\fBXmNcolumns\fP" 10
Specifies the initial width of the text window as an integer number of
characters\&. The width equals the number of characters specified by
this resource multiplied by the width as derived from the specified
font\&. If the em-space
value is available,
it is used\&. If not, the width of the numeral "0" is used\&. If this is
not available, the maximum width is used\&.
For proportionate fonts, the actual number of characters that fit
on a given line may be greater than the value specified\&.
.IP "\fBXmNcursorPosition\fP" 10
Indicates the position in the text where the current insert cursor is to
be located\&. Position is determined by the number of characters from
the beginning of the text\&.
.IP "\fBXmNcursorPositionVisible\fP" 10
If the text widget has an \fBXmPrintShell\fP as one of its ancestors
(that is, the widget was created on a print server connection)
then the default value is
\fBFalse\fP; otherwise, it is \fBTrue\fP\&.
.IP "\fBXmNdestinationCallback\fP" 10
Specifies a list of callbacks called when the widget is the destination
of a transfer operation\&.
The type of the structure whose address is passed to these callbacks is
\fBXmDestinationCallbackStruct\fR\&.
The reason is \fBXmCR_OK\fP\&.
.IP "\fBXmNeditable\fP" 10
When set to True, indicates that the user can edit the text string\&.
A false value will prohibit the user from editing the text\&.
.IP "" 10
When \fBXmNeditable\fP is used on a widget
it sets the dropsite to \fBXmDROP_SITE_ACTIVE\fP\&.
.IP "\fBXmNfocusCallback\fP" 10
Specifies the list of callbacks called when TextField accepts
input focus\&. The type of the structure whose address is passed to this
callback is \fBXmAnyCallbackStruct\fR\&. The reason sent by the
callback is \fBXmCR_FOCUS\fP\&.
.IP "\fBXmNfontList\fP" 10
Specifies the font list to be used for TextField\&. The font list is an
obsolete structure, and is retained only for compatibility with
earlier releases of Motif\&. Use the render table (\fBXmNrenderTable\fP)
instead of font lists wherever possible\&. If both are specified, the
render table will take precedence\&. If this value is NULL at
initialization, the parent hierarchy of the widget is searched for an
ancestor that holds the \fBXmQTspecifyRenderTable\fP trait\&. If such
an ancestor is found, the font list is initialized to the
\fBXmTEXT_RENDER_TABLE\fP value of the ancestor widget\&. If no such
ancestor is found, the default is implementation dependent\&.
.IP "" 10
TextField searches the font list for the first occurrence of a font
set that has an \fBXmFONTLIST_DEFAULT_TAG\fP\&. If a default element is
not found, the first font set in the font list is used\&. If the list
contains no font sets, the first font in the font list will be used\&.
Refer to \fBXmFontList\fP(3) for more information on a font list
structure\&.
.IP "\fBXmNgainPrimaryCallback\fP" 10
Specifies the list of callbacks that are called when the user invokes
an event that causes the text widget to gain ownership of the primary
selection\&. The callback reason for this callback is \fBXmCR_GAIN_PRIMARY\fP\&.
.IP "\fBXmNlosePrimaryCallback\fP" 10
Specifies the list of callbacks that are called when the user invokes
an event that cause the text widget to lose ownership of the primary
selection\&. The callback reason for this callback is \fBXmCR_LOSE_PRIMARY\fP\&.
.IP "\fBXmNlosingFocusCallback\fP" 10
Specifies the list of callbacks that are called
before TextField widget loses input focus\&.
The type of the structure whose address is passed to this callback is
\fBXmTextVerifyCallbackStruct\fR\&.
The reason sent by the callback is \fBXmCR_LOSING_FOCUS\fP\&.
.IP "\fBXmNmarginHeight\fP" 10
Specifies the distance between the top edge of the widget
window and the text, and the bottom edge of the widget
window and the text\&.
.IP "\fBXmNmarginWidth\fP" 10
Specifies the distance between the left edge of the widget
window and the text, and the right edge of the widget
window and the text\&.
.IP "\fBXmNmaxLength\fP" 10
Specifies the maximum length of the text string that can be entered into
text from the keyboard\&.
This value must be nonnegative\&.
Strings that are entered using the \fBXmNvalue\fP resource or the
\fBXmTextFieldSetString\fP function ignore this resource\&.
.IP "\fBXmNmodifyVerifyCallback\fP" 10
Specifies the list of callbacks that is called
before text is deleted from or inserted into
TextField\&.
The type of the structure whose address is passed to this callback is
\fBXmTextVerifyCallbackStruct\fR\&.
The reason sent by the callback is \fBXmCR_MODIFYING_TEXT_VALUE\fP\&.
When multiple TextField widgets share the same
source, only the widget that initiates the source change will
generate the \fBXmNmodifyVerifyCallback\fP\&.
.IP "" 10
If both \fBXmNmodifyVerifyCallback\fP and \fBXmNmodifyVerifyCallbackWcs\fP
are registered callback lists, the procedure(s) in the
\fBXmNmodifyVerifyCallback\fP list is always executed first; and the
resulting data, which may have been modified, is passed to the
\fBXmNmodifyVerifyCallbackWcs\fP callback routines\&.
.IP "\fBXmNmodifyVerifyCallbackWcs\fP" 10
Specifies the list of callbacks called before text is deleted from
or inserted into Text\&. The type of the structure whose address is
passed to this callback is \fBXmTextVerifyCallbackStructWcs\fR\&. The
reason sent by the callback is \fBXmCR_MODIFYING_TEXT_VALUE\fP\&.
When multiple TextField widgets share the same
source, only the widget that initiates the source change will
generate the \fBXmNmodifyVerifyCallbackWcs\fP\&.
.IP "" 10
If both \fBXmNmodifyVerifyCallback\fP and \fBXmNmodifyVerifyCallbackWcs\fP
are registered callback lists, the procedure(s) in the
\fBXmNmodifyVerifyCallback\fP list is always executed first; and the
resulting data, which may have been modified, is passed to the
\fBXmNmodifyVerifyCallbackWcs\fP callback routines\&.
.IP "\fBXmNmotionVerifyCallback\fP" 10
Specifies the list of callbacks that is called
before the insert cursor is moved to a new position\&.
The type of the structure whose address is passed to this callback is
\fBXmTextVerifyCallbackStruct\fR\&.
The reason sent by the callback is \fBXmCR_MOVING_INSERT_CURSOR\fP\&.
It is possible for more than one \fBXmNmotionVerifyCallback\fPs to be
generated from a single action\&.
.IP "\fBXmNpendingDelete\fP" 10
Indicates that pending delete mode is on when the Boolean is True\&.
Pending deletion is defined as deletion
of the selected text when an insertion is made\&.
.IP "\fBXmNrenderTable\fP" 10
Specifies the render table to be used in deriving a font set or font
for displaying text\&. If both a render table and a font list are
specified, the render table will take precedence\&. If the value of
\fBXmNrenderTable\fP is NULL at initialization, the parent hierarchy
of the widget is searched for an ancestor that holds the
\fBXmQTspecifyRenderTable\fP trait\&. If such an ancestor is found, the
font list is initialized to the \fBXmTEXT_RENDER_TABLE\fP value of the
ancestor widget\&. If no such ancestor is found, the default is
implementation dependent\&.
.IP "" 10
TextField searches the render table for the first occurrence of a
rendition that has the tag \fB_MOTIF_DEFAULT_LOCALE\fP\&. If a default
element is not found, the first rendition in the table is used\&. Refer
to \fBXmRenderTable\fP(3) for more information on the render table
structure\&.
.IP "\fBXmNresizeWidth\fP" 10
Indicates that the TextField widget will attempt to resize its
width to accommodate all
the text contained in the widget when Boolean is True\&.
.IP "\fBXmNselectionArray\fP" 10
Defines the actions for multiple mouse clicks\&. Each mouse click
performed within some time of the previous mouse click will increment
the index into this array and perform the defined action for that
index\&. (This "multi-click" time is specified by the operating
environment, and varies among different systems\&. In general, it is
usually set to some fraction of a second\&.)
The possible actions are
.RS
.IP "\fBXmSELECT_POSITION\fP" 10
Resets the insert cursor position
.IP "\fBXmSELECT_WORD\fP" 10
Selects a word
.IP "\fBXmSELECT_LINE\fP" 10
Selects a line of text
.RE
.IP "\fBXmNselectionArrayCount\fP" 10
Specifies the number of actions that are defined in the
\fBXmNselectionArray\fP resource\&.
The value must not be negative\&.
.IP "\fBXmNselectThreshold\fP" 10
Specifies the number of pixels of motion that is required to select the
next character when selection is performed using the click-drag
mode of selection\&.
The value must not be negative\&.
This resource also specifies whether a drag should be started and the
number of pixels to start a drag when
\fBBtn2Down\fP and \fBBtn1Down\fP are integrated\&.
.IP "\fBXmNvalue\fP" 10
Specifies the string value of the TextField widget as a \fBchar*\fP
data value\&.
Moves the cursor to position 0 unless a value of
\fBXmNcursorPosition\fP was explicitly supplied in the argument list\&.
If \fBXmNvalue\fP and \fBXmNvalueWcs\fP are both
defined, the value of \fBXmNvalueWcs\fP supersedes that of
\fBXmNvalue\fP\&. \fBXtGetValues\fP returns a copy of the value of
the internal buffer and \fBXtSetValues\fP copies the string values
into the internal buffer\&.
.IP "\fBXmNvalueChangedCallback\fP" 10
Specifies the list of callbacks that is called
after text is deleted from or inserted into
TextField\&.
The type of the structure whose address is passed to this callback is
\fBXmAnyCallbackStruct\fR\&.
The reason sent by the callback is \fBXmCR_VALUE_CHANGED\fP\&.
The \fBXmNvalueChangedCallback\fP should occur only in pairs
with a \fBXmNmodifyVerifyCallback\fP, assuming that the \fIdoit\fP
flag in the callback structure of the \fBXmNmodifyVerifyCallback\fP is
not set to False\&.
.IP "\fBXmNvalueWcs\fP" 10
Specifies the string value of the TextField widget as a \fBwchar_t*\fP data
value\&.
Moves the cursor to position 0 unless a value of
\fBXmNcursorPosition\fP was explicitly supplied in the argument list\&.
.IP "" 10
This resource cannot be specified in a resource file\&.
.IP "" 10
If \fBXmNvalue\fP and \fBXmNvalueWcs\fP are both defined,
the value of \fBXmNvalueWcs\fP supersedes that of \fBXmNvalue\fP\&.
\fBXtGetValues\fP returns a copy of the value of the internal buffer
encoded as a wide character string\&. \fBXtSetValues\fP copies the
value of the wide character string into the internal buffer\&.
.IP "\fBXmNverifyBell\fP" 10
Specifies whether a bell will sound when an action is reversed
during a verification callback\&.
The default depends on the value of the ancestor VendorShell\&'s
\fBXmNaudibleWarning\fP resource\&.
.SS "Inherited Resources"
.PP
TextField widget inherits behavior and resources from the
superclasses in the following tables\&.
For a complete description of these resources, refer to the
reference page for that superclass\&.
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBXmPrimitive Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNbottomShadowColorXmCBottomShadowColorPixeldynamicCSG
_____
XmNbottomShadowPixmapXmCBottomShadowPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNconvertCallbackXmCCallbackXtCallbackListNULLC
_____
XmNforegroundXmCForegroundPixeldynamicCSG
_____
XmNhelpCallbackXmCCallbackXtCallbackListNULLC
_____
XmNhighlightColorXmCHighlightColorPixeldynamicCSG
_____
XmNhighlightOnEnterXmCHighlightOnEnterBooleanFalseCSG
_____
XmNhighlightPixmapXmCHighlightPixmapPixmapdynamicCSG
_____
XmNhighlightThicknessXmCHighlightThicknessDimension2CSG
_____
XmNlayoutDirectionXmCLayoutDirectionXmDirectiondynamicCG
_____
XmNnavigationTypeXmCNavigationTypeXmNavigationTypeXmTAB_GROUPCSG
_____
XmNpopupHandlerCallbackXmCCallbackXtCallbackListNULLC
_____
XmNshadowThicknessXmCShadowThicknessDimension2CSG
_____
XmNtopShadowColorXmCTopShadowColorPixeldynamicCSG
_____
XmNtopShadowPixmapXmCTopShadowPixmapPixmapdynamicCSG
_____
XmNtraversalOnXmCTraversalOnBooleanTrueCSG
_____
XmNunitTypeXmCUnitTypeunsigned chardynamicCSG
_____
XmNuserDataXmCUserDataXtPointerNULLCSG
_____
.TE
.PP
.TS
tab() box;
c s s s s
l| l| l| l| l.
\fBCore Resource Set\fP
\fBName\fP\fBClass\fP\fBType\fP\fBDefault\fP\fBAccess\fP
_____
XmNacceleratorsXmCAcceleratorsXtAcceleratorsdynamicCSG
_____
XmNancestorSensitiveXmCSensitiveBooleandynamicG
_____
XmNbackgroundXmCBackgroundPixeldynamicCSG
_____
XmNbackgroundPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderColorXmCBorderColorPixelXtDefaultForegroundCSG
_____
XmNborderPixmapXmCPixmapPixmapXmUNSPECIFIED_PIXMAPCSG
_____
XmNborderWidthXmCBorderWidthDimension0CSG
_____
XmNcolormapXmCColormapColormapdynamicCG
_____
XmNdepthXmCDepthintdynamicCG
_____
XmNdestroyCallbackXmCCallbackXtCallbackListNULLC
_____
XmNheightXmCHeightDimensiondynamicCSG
_____
XmNinitialResourcesPersistentXmCInitialResourcesPersistentBooleanTrueC
_____
XmNmappedWhenManagedXmCMappedWhenManagedBooleanTrueCSG
_____
XmNscreenXmCScreenScreen *dynamicCG
_____
XmNsensitiveXmCSensitiveBooleanTrueCSG
_____
XmNtranslationsXmCTranslationsXtTranslationsdynamicCSG
_____
XmNwidthXmCWidthDimensiondynamicCSG
_____
XmNxXmCPositionPosition0CSG
_____
XmNyXmCPositionPosition0CSG
_____
.TE
.SS "Callback Information"
.PP
A pointer to the following structure is passed to each callback:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent \fI* event\fP;
} XmAnyCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback
.PP
The TextField widget defines a new callback structure
for use with verification callbacks\&. Note that
not all of the fields are relevant for every
callback reason\&. The application must first
look at the \fIreason\fP field and use only the structure
members that are valid for the particular reason\&.
The values \fIstartPos\fP, \fIendPos\fP, and \fItext\fP in the
callback structure \fBXmTextVerifyCallbackStruct\fR may be modified upon
receiving the callback, and these changes will be reflected as the
change made to the source of the TextField widget\&. (For example, all
keystrokes can be converted to spaces or NULL characters when a
password is entered into a TextField widget\&.) The application
programmer should not overwrite the \fItext\fP field, but should
attach data to that pointer\&.
.PP
A pointer to the following structure is passed to the
callbacks for \fBXmNlosingFocusCallback\fP, \fBXmNmodifyVerifyCallback\fP,
and \fBXmNmotionVerifyCallback\fP\&.
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent *\fIevent\fP;
        Boolean \fIdoit\fP;
        XmTextPosition \fIcurrInsert, newInsert\fP;
        XmTextPosition \fIstartPos, endPos\fP;
        XmTextBlock \fItext\fP;
} XmTextVerifyCallbackStruct, *XmTextVerifyPtr;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP the triggered the callback\&.
It can be NULL\&. For example, changes made to the Text widget
programmatically do not have an event that can be
passed to the associated callback\&.
.IP "\fIdoit\fP" 10
Indicates whether the action that invoked the callback will be performed\&.
Setting \fIdoit\fP to False negates the action\&.
Note that not all actions may be negated\&. For example,
\fBXmCR_LOSING_FOCUS\fP callbacks may be beyond the control of the
widget if they are produced by mouse clicks\&.
.IP "\fIcurrInsert\fP" 10
Indicates the current position of the insert cursor\&.
.IP "\fInewInsert\fP" 10
Indicates the position at which the user attempts to position the insert
cursor\&.
.IP "\fIstartPos\fP" 10
Indicates the starting position of the text to modify\&. If the callback is
not a modify verification callback, this value is the same as \fIcurrInsert\fP\&.
.IP "\fIendPos\fP" 10
Indicates the ending position of the text to modify\&. If no text is replaced or
deleted, then the value is the same as \fIstartPos\fP\&. If the callback is not
a modify verification callback, this value is the same as \fIcurrInsert\fP\&.
.IP "\fItext\fP" 10
Points to the following structure of type
\fBXmTextBlockRec\fR\&. This structure holds
the textual information to be inserted\&.
.PP
.nf
typedef struct
{
        char *\fIptr\fP;
        int \fIlength\fP;
        XmTextFormat \fIformat\fP
} XmTextBlockRec, *XmTextBlock;
.fi
.RS
.IP "\fIptr\fP" 10
The text to be inserted\&. \fIptr\fP points to a temporary
storage space that is reused after the callback is finished\&. Therefore,
if an application needs to save the text to be inserted, it should copy
the text into its own data space\&.
.IP "\fIlength\fP" 10
Specifies the length of the text to be inserted\&.
.IP "\fIformat\fP" 10
Specifies the format of the text,
either \fBXmFMT_8_BIT\fP or \fBXmFMT_16_BIT\fP\&.
.RE
.PP
A pointer to the following structure is passed to callbacks
for \fBXmNmodifyVerifyCallbackWcs\fP\&.
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent *\fIevent\fP;
        Boolean \fIdoit\fP;
        XmTextPosition \fIcurrInsert, newInsert\fP;
        XmTextPosition \fIstartPos, endPos\fP;
        XmWcsTextBlock \fItext\fP;
} XmTextVerifyCallbackStructWcs, *XmTextVerifyPtrWcs;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
It can be NULL\&. For example, changes made to the Text widget
programmatically do not have an event that can be
passed to the associated callback\&.
.IP "\fIdoit\fP" 10
Indicates whether the action that invoked the callback is performed\&.
Setting \fIdoit\fP to False negates the action\&.
Note that not all actions may be negated\&. For example,
\fBXmCR_LOSING_FOCUS\fP callbacks may be beyond the control of the
widget if they are produced by mouse clicks\&.
.IP "\fIcurrInsert\fP" 10
Indicates the current position of the insert cursor\&.
.IP "\fInewInsert\fP" 10
Indicates the position at which the user attempts to position the insert
cursor\&.
.IP "\fIstartPos\fP" 10
Indicates the starting position of the text to modify\&. If the callback is
not a modify verification callback, this value is the same
as \fIcurrInsert\fP\&.
.IP "\fIendPos\fP" 10
Indicates the ending position of the text to modify\&. If no text is
replaced or
deleted, the value is the same as \fIstartPos\fP\&. If the callback is not
a modify verification callback, this value is the same as \fIcurrInsert\fP\&.
.IP "\fItext\fP" 10
Points to the following structure of type \fBXmTextBlockRecWcs\fR\&.
This structure holds
the textual information to be inserted\&.
.PP
.nf
typedef struct
{
        wchar_t *\fIwcsptr\fP;
        int \fIlength\fP;
} XmTextBlockRecWcs, *XmTextBlockWcs;
.fi
.RS
.IP "\fIwcsptr\fP" 10
Points to the wide character text to be inserted
.IP "\fIlength\fP" 10
Specifies the number of characters to be inserted
.RE
.PP
The following table describes the reasons for which the individual
verification callback structure fields are valid\&. Note that the
\fIevent\fP field will never be valid for \fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.TS
tab() box;
l| l.
\fBReason\fP\fBValid Fields\fP
__
XmCR_LOSING_FOCUS\fIreason, event, doit\fP
__
XmCR_MODIFYING_TEXT_VALUET{
\fIreason, event, doit, currInsert, newInsert, startPos, endPos, text\fP
T}
__
XmCR_MOVING_INSERT_CURSOR\fIreason, doit, currInsert, newInsert\fP
__
.TE
.PP
A pointer to the following callback structure is passed to the
\fBXmNdestinationCallback\fP procedures:
.PP
.nf
typedef struct
{
        int \fIreason\fP;
        XEvent *\fIevent\fP;
        Atom \fIselection\fP;
        XtEnum \fIoperation\fP;
        int \fIflags\fP;
        XtPointer \fItransfer_id\fP;
        XtPointer \fIdestination_data\fP;
        XtPointer \fIlocation_data\fP;
        Time \fItime\fP;
} XmDestinationCallbackStruct;
.fi
.IP "\fIreason\fP" 10
Indicates why the callback was invoked\&.
.IP "\fIevent\fP" 10
Points to the \fBXEvent\fP that triggered the callback\&.
It can be NULL\&.
.IP "\fIselection\fP" 10
Indicates the selection for which data transfer is being requested\&.
Possible values are \fBCLIPBOARD\fP, \fBPRIMARY\fP, \fBSECONDARY\fP, and
\fB_MOTIF_DROP\fP\&.
.IP "\fIoperation\fP" 10
Indicates the type of transfer operation requested\&.
.RS
.IP "   \(bu" 6
When the selection is \fBPRIMARY\fP or \fBSECONDARY\fP, possible
values are \fBXmMOVE\fP,
\fBXmCOPY\fP, and \fBXmLINK\fP\&.
.IP "   \(bu" 6
When the selection is \fBCLIPBOARD\fP, possible
values are \fBXmCOPY\fP and \fBXmLINK\fP\&.
.IP "   \(bu" 6
When the selection is \fB_MOTIF_DROP\fP, possible values are
\fBXmMOVE\fP, \fBXmCOPY\fP, \fBXmLINK\fP, and \fBXmOTHER\fP\&.
A value of \fBXmOTHER\fP means that the callback procedure must get
further information from the \fBXmDropProcCallbackStruct\fR in the
\fIdestination_data\fP member\&.
.RE
.IP "\fIflags\fP" 10
Indicates whether or not the destination widget is also the source of
the data to be transferred\&.
Following are the possible values:
.RS
.IP "\fBXmCONVERTING_NONE\fP" 10
The destination widget is not the source of the data to be transferred\&.
.IP "\fBXmCONVERTING_SAME\fP" 10
The destination widget is the source of the data to be transferred\&.
.RE
.IP "\fBtransfer_id\fP" 10
Serves as a unique ID to identify the transfer transaction\&.
.IP "\fIdestination_data\fP" 10
Contains information about the destination\&.
When the selection is \fB_MOTIF_DROP\fP, the callback procedures are
called by the drop site\&'s \fBXmNdropProc\fP, and \fIdestination_data\fP
is a pointer to the \fBXmDropProcCallbackStruct\fR passed to the
\fBXmNdropProc\fP procedure\&.
When the selection is \fBSECONDARY\fP,
\fIdestination_data\fP
is an Atom
representing a target recommmended by the selection owner for use in
converting the selection\&.
Otherwise, \fIdestination_data\fP is NULL\&.
.IP "\fBlocation_data\fP" 10
Contains information about the location where data is to be transferred\&.
The value is always NULL when the selection is \fBCLIPBOARD\fP\&.
If the value is NULL, the data is to be inserted at the widget\&'s cursor
position\&.
Otherwise, the value is a pointer to an \fBXPoint\fP structure
containing the x and y coordinates at the location where the data is to
be transferred\&. Once \fBXmTransferDone\fP procedures start to be called,
\fBlocation_data\fP will no longer be stable\&.
.IP "\fItime\fP" 10
Indicates the time when the transfer operation began\&.
.SS "Translations"
.PP
The \fBXmTextField\fP translations are described in the following list\&.
The actions represent the effective behavior of the associated events,
and they may differ in a right-to-left language environment\&.
.PP
The following key names are listed in the
X standard key event translation table syntax\&.
This format is the one used by Motif to
specify the widget actions corresponding to a given key\&.
A brief overview of the format is provided under
\fBVirtualBindings\fP(3)\&.
For a complete description of the format, please refer to the
X Toolkit Instrinsics Documentation\&.
.IP "\fB\(apc s \(apm \(apa\fP \fB<Btn1Down>\fP:" 10
extend-start()
.IP "\fBc \(aps \(apm \(apa\fP \fB<Btn1Down>\fP:" 10
move-destination()
.IP "\fB\(apc \(aps \(apm \(apa\fP \fB<Btn1Down>\fP:" 10
grab-focus()
.IP "\fB\(apc \(apm \(apa\fP \fB<Btn1Motion>\fP:" 10
extend-adjust()
.IP "\fB\(apc \(apm \(apa\fP \fB<Btn1Up>\fP:" 10
extend-end()
.IP "\fB<Btn2Down>\fP:" 10
process-bdrag()
.IP "\fBm \(apa\fP \fB<Btn2Motion>\fP:" 10
secondary-adjust()
.IP "\fB\(apm a\fP \fB<Btn2Motion>\fP:" 10
secondary-adjust()
.IP "\fBs c <Btn2Up>\fP:" 10
link-to()
.IP "\fB\(aps\fP \fB<Btn2Up>\fP:" 10
copy-to()
.IP "\fB\(apc\fP \fB<Btn2Up>\fP:" 10
move-to()
.IP "\fB:m\fP \fB<Key>\fP\fB<osfPrimaryPaste>\fP:" 10
cut-primary()
.IP "\fB:a\fP \fB<Key>\fP\fB<osfPrimaryPaste>\fP:" 10
cut-primary()
.IP "\fB:\fP\fB<Key>\fP\fB<osfPrimaryPaste>\fP:" 10
copy-primary()
.IP "\fB:m\fP \fB<Key>\fP\fB<osfCut>\fP:" 10
cut-primary()
.IP "\fB:a\fP \fB<Key>\fP\fB<osfCut>\fP:" 10
cut-primary()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCut>\fP:" 10
cut-clipboard()
.IP "\fB:\fP\fB<Key>\fP\fB<osfPaste>\fP:" 10
paste-clipboard()
.IP "\fB:m\fP \fB<Key>\fP\fB<osfCopy>\fP:" 10
copy-primary()
.IP "\fB:a\fP \fB<Key>\fP\fB<osfCopy>\fP:" 10
copy-primary()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCopy>\fP:" 10
copy-clipboard()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfBeginLine>\fP:" 10
beginning-of-line(\fBextend\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfBeginLine>\fP:" 10
beginning-of-line()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfEndLine>\fP:" 10
end-of-line(\fBextend\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfEndLine>\fP:" 10
end-of-line()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfPageLeft>\fP:" 10
page-left(\fBextend\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfPageLeft>\fP:" 10
page-left()
.IP "\fB:s c\fP\fB<Key>\fP\fB<osfPageUp>\fP:" 10
page-left(\fBextend\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfPageUp>\fP:" 10
page-left()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfPageRight>\fP:" 10
page-right(\fBextend\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfPageRight>\fP:" 10
page-right()
.IP "\fBs c\fP \fB<Key>\fP\fB<osfPageDown>\fP:" 10
page-right(\fBextend\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfPageDown>\fP:" 10
page-right()
.IP "\fB:\fP\fB<Key>\fP\fB<osfClear>\fP:" 10
clear-selection()
.IP "\fB:\fP\fB<Key>\fP\fB<osfBackSpace>\fP:" 10
delete-previous-character()
.IP "\fB:s m\fP \fB<Key>\fP\fB<osfDelete>\fP:" 10
cut-primary()
.IP "\fB:s a\fP \fB<Key>\fP\fB<osfDelete>\fP:" 10
cut-primary()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfDelete>\fP:" 10
cut-clipboard()
.IP "\fB:c\fP \fB<Key>\fP\fB<osfDelete>\fP:" 10
delete-to-end-of-line()
.IP "\fB:\fP\fB<Key>\fP\fB<osfDelete>\fP:" 10
delete-next-character()
.IP "\fB:c m\fP \fB<Key>\fP\fB<osfInsert>\fP:" 10
copy-primary()
.IP "\fB:c a\fP \fB<Key>\fP\fB<osfInsert>\fP:" 10
copy-primary()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfInsert>\fP:" 10
paste-clipboard()
.IP "\fB:c\fP \fB<Key>\fP\fB<osfInsert>\fP:" 10
copy-clipboard()
.IP "\fB:\fP\fB<Key>\fP\fB<osfInsert>\fP:" 10
toggle-overstrike()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfSelect>\fP:" 10
key-select()
.IP "\fB:\fP\fB<Key>\fP\fB<osfSelect>\fP:" 10
set-anchor()
.IP "\fB:\fP\fB<Key>\fP\fB<osfSelectAll>\fP:" 10
select-all()
.IP "\fB:\fP\fB<Key>\fP\fB<osfDeselectAll>\fP:" 10
deselect-all()
.IP "\fB:\fP\fB<Key>\fP\fB<osfActivate>\fP:" 10
activate()
.IP "\fB:\fP\fB<Key>\fP\fB<osfAddMode>\fP:" 10
toggle-add-mode()
.IP "\fB:\fP\fB<Key>\fP\fB<osfHelp>\fP:" 10
Help()
.IP "\fB:\fP\fB<Key>\fP\fB<osfCancel>\fP:" 10
process-cancel()
.IP "\fB:s c\fP \fB<Key>\fP\fB<osfLeft>\fP:" 10
backward-word(\fBextend\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfLeft>\fP:" 10
backward-word()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfLeft>\fP:" 10
key-select(\fBleft\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfLeft>\fP:" 10
backward-character()
.IP "\fB:s c\fP \fB<Key>\fP\fB<osfRight>\fP:" 10
forward-word(\fBextend\fP)
.IP "\fB:c\fP \fB<Key>\fP\fB<osfRight>\fP:" 10
forward-word()
.IP "\fB:s\fP \fB<Key>\fP\fB<osfRight>\fP:" 10
key-select(\fBright\fP)
.IP "\fB:\fP\fB<Key>\fP\fB<osfRight>\fP:" 10
forward-character()
.IP "\fB:\fP\fB<Key>\fP\fB<osfUp>\fP:" 10
traverse-prev()
.IP "\fB:\fP\fB<Key>\fP\fB<osfDown>\fP:" 10
traverse-next()
.IP "\fBc \(apm \(apa\fP \fB<Key>\fP\fBslash\fP:" 10
select-all()
.IP "\fBc \(apm \(apa\fP \fB<Key>\fP\fBbackslash\fP:" 10
deselect-all()
.IP "\fBs \(apm \(apa\fP \fB<Key>\fP\fBTab\fP:" 10
prev-tab-group()
.IP "\fB\(apm \(apa\fP \fB<Key>\fP\fBTab\fP:" 10
next-tab-group()
.IP "\fB\(aps \(apm \(apa\fP \fB<Key>\fP\fBReturn\fP:" 10
activate()
.IP "\fBc \(aps \(apm \(apa\fP \fB<Key>\fP\fBspace\fP:" 10
set-anchor()
.IP "\fBc s \(apm \(apa\fP \fB<Key>\fP\fBspace\fP:" 10
key-select()
.IP "\fBs \(apc \(apm \(apa\fP \fB<Key>\fP\fBspace\fP:" 10
self-insert()
.IP "\fB<Key>\fP:" 10
self-insert()
.PP
The TextField button event translations are modified when Display\&'s
\fBXmNenableBtn1Transfer\fP resource does not have a value of
\fBXmOFF\fP (in other words, it is either \fBXmBUTTON2_TRANSFER\fP or
\fBXmBUTTON2_ADJUST\fP)\&. This
option allows the
actions for selection and transfer to be integrated on \fB<Btn1>\fP\&.
The actions for \fB<Btn1>\fP that are defined above
still apply when the \fB<Btn1>\fP event occurs over text that is not
selected\&. The following actions apply when the \fB<Btn1>\fP event
occurs over text that is selected:
.IP "\fB<Btn1Down>\fP:" 10
process-bdrag()\&.
.IP "\fB<Shift>\fP\fB<Btn1Down>\fP:" 10
process-bdrag()\&.
.IP "\fB<Btn1Down>\fP\fB<Shift>\fP\fB<Btn1Up>\fP:" 10
grab-focus(), \fBextend-end\fP\&.
.IP "\fB<Shift>\fP\fB<Btn1Down>\fP\fB<Shift>\fP\fB<Btn1Up>\fP:" 10
extend-start(), extend-end()\&.
.IP "\fB<Ctrl>\fP\fB<Btn1Down>\fP\fB<Shift>\fP\fB<Btn1Up>\fP:" 10
move-destination()\&.
.IP "\fB<Ctrl>\fP\fB<Btn1Down>\fP:" 10
process-bdrag()\&.
.PP
When Display\&'s \fBXmNenableBtn1Transfer\fP resource has a value of
\fBXmBUTTON2_ADJUST\fP, the following actions apply:
.IP "\fB<Btn2Down>\fP:" 10
extend-start()\&.
.IP "\fB<Btn2Motion>\fP:" 10
extend-adjust()\&.
.IP "\fB<Btn2Up>\fP:" 10
extend-end()\&.
.SS "Action Routines"
.PP
The \fBXmTextField\fP action routines are
.IP "activate():" 10
Calls the callbacks for \fBXmNactivateCallback\fP\&.
If the parent is a manager, passes the event to the parent\&.
.IP "backward-character(\fBextend\fP):" 10
Moves the insertion cursor one character to the left\&.
This action may have different behavior in a right-to-left language
environment\&.
.IP "" 10
If called with an argument of \fIextend\fP, moves the insertion cursor as
in the case of no argument and extends the current selection\&.
.IP "" 10
The backward-character() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If called with the \fIextend\fP argument, the
backward-character() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "backward-word(\fBextend\fP):" 10
If this action is called with no argument,
moves the insertion cursor to the first non-whitespace character after the
first whitespace character to the left or after the beginning of the line\&.
If the insertion cursor is already at the beginning of a word,
moves the insertion cursor to the beginning of the previous word\&.
This action may have different behavior in a locale other than the C locale\&.
.IP "" 10
If called with an argument of \fIextend\fP, moves the insertion cursor as
in the case of no argument and extends the current selection\&.
.IP "" 10
The backward-word() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If called with the \fIextend\fP argument, the
backward-word() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "beginning-of-line(\fBextend\fP):" 10
If this action is called with no argument,
moves the insertion cursor to the beginning of the line\&.
.IP "" 10
If called with an argument of \fIextend\fP, moves the insertion cursor as
in the case of no argument and extends the current selection\&.
.IP "" 10
The beginning-of-line() action produces calls to the
\fBXmNmotionVerifyCallback\fP with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If called with the \fIextend\fP argument, the
beginning-of-line() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "clear-selection():" 10
Clears the current selection by replacing each character except
\fB<Return>\fP with a \fB<space>\fP character\&.
.IP "" 10
The clear-selection() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP and the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP\&.
.IP "copy-clipboard():" 10
If this widget owns the primary selection, this action copies the
selection to the clipboard\&.
This action calls the \fBXmNconvertCallback\fP procedures, possibly
multiple times, for the \fBCLIPBOARD\fP selection\&.
.IP "copy-primary():" 10
Copies the primary selection to just before the insertion cursor\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBPRIMARY\fP selection and the \fBXmCOPY\fP operation\&.
It calls the selection owner\&'s \fBXmNconvertCallback\fP procedures,
possibly multiple times, for the \fBPRIMARY\fP selection\&.
.IP "" 10
In addition, the copy-primary() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
The copy-primary() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "copy-to():" 10
If a secondary selection exists, this action copies the secondary
selection to the insertion position of the destination component\&.
If the primary selection is in the destination widget, it will
be deselected\&. Otherwise, there is no effect on the primary selection\&.
.IP "" 10
This action calls the destination\&'s \fBXmNdestinationCallback\fP
procedures for the \fBSECONDARY\fP selection and the
\fBXmCOPY\fP operation\&.
The destination\&'s \fBXmNdestinationCallback\fP procedures or the
destination component itself invokes the selection owner\&'s
\fBXmNconvertCallback\fP procedures, possibly multiple times, for the
\fBSECONDARY\fP selection\&.
.IP "" 10
If no secondary selection exists, this action copies the primary
selection to the pointer position\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBPRIMARY\fP selection and the \fBXmCOPY\fP operation\&.
It calls the selection owner\&'s \fBXmNconvertCallback\fP procedures,
possibly multiple times, for the \fBPRIMARY\fP selection\&.
.IP "" 10
In addition, the copy-to() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If there is no secondary selection, the
copy-to() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "cut-clipboard():" 10
If this widget owns the primary selection, this action cuts the
selection to the clipboard\&.
This action calls the \fBXmNconvertCallback\fP procedures, possibly
multiple times, for the \fBCLIPBOARD\fP selection\&.
If the transfer is successful, this action then calls the
\fBXmNconvertCallback\fP procedures for the \fBCLIPBOARD\fP selection
and the \fBDELETE\fP target\&.
.IP "" 10
In addition, the cut-clipboard() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, and the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP\&.
.IP "cut-primary():" 10
Cuts the primary selection and pastes it just before the insertion cursor\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBPRIMARY\fP selection and the \fBXmMOVE\fP operation\&.
It calls the selection owner\&'s \fBXmNconvertCallback\fP procedures,
possibly multiple times, for the \fBPRIMARY\fP selection\&.
If the transfer is successful, this action then calls the selection
owner\&'s \fBXmNconvertCallback\fP procedures for the \fBPRIMARY\fP
selection and the \fBDELETE\fP target\&.
.IP "" 10
In addition, the cut-primary() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP, the \fBXmNmodifyVerifyCallback\fP
procedures with reason value \fBXmCR_MODIFYING_TEXT_VALUE\fP, and the
\fBXmNvalueChangedCallback\fP procedures with reason value
\fBXmCR_VALUE_CHANGED\fP\&.
.IP "delete-next-character():" 10
In normal mode, if there is a nonnull selection, deletes the selection;
otherwise,
deletes the character following the insertion cursor\&.
In add mode, if there is a nonnull selection, the cursor is not disjoint
from the selection and \fBXmNpendingDelete\fP is set to True,
deletes the selection;
otherwise,
deletes the character following the insertion cursor\&.
This may impact the selection\&.
.IP "" 10
The delete-next-character() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, and the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP\&.
.IP "delete-next-word():" 10
In normal mode, if there is a nonnull selection, deletes the selection; otherwise,
deletes the characters following the insertion cursor to the next space, tab
or end-of-line character\&.
In add mode, if there is a nonnull selection, the cursor is not disjoint
from the selection and \fBXmNpendingDelete\fP is set to True,
deletes the selection; otherwise,
deletes the characters following the insertion cursor to the next space, tab
or end-of-line character\&.
This may impact the selection\&.
This action may have different behavior in a locale other than the C locale\&.
.IP "" 10
The delete-next-word() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, and the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP\&.
.IP "delete-previous-character():" 10
In normal mode, if there is a nonnull selection, deletes the selection; otherwise,
deletes the character of text immediately preceding the insertion cursor\&.
In add mode, if there is a nonnull selection, the cursor is not disjoint
from the selection and \fBXmNpendingDelete\fP is set to True,
deletes the selection; otherwise,
deletes the character of text immediately preceding the insertion cursor\&.
This may impact the selection\&.
.IP "" 10
The delete-previous-character() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "delete-previous-word():" 10
In normal mode, if there is a nonnull selection, deletes the selection; otherwise,
deletes the characters preceding the insertion cursor
to the next
space, tab or beginning-of-line character\&.
In add mode, if there is a nonnull selection, the cursor is not disjoint
from the selection and \fBXmNpendingDelete\fP is set to True,
deletes the selection; otherwise,
deletes the characters preceding the insertion cursor to the next space,
tab or beginning-of-line character\&.
This may impact the selection\&.
This action may have different behavior in a locale other than the C locale\&.
.IP "" 10
The delete-previous-word() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "delete-selection():" 10
Deletes the current selection\&.
.IP "" 10
The delete-selection() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "delete-to-end-of-line():" 10
In normal mode, if there is a nonnull selection, deletes the selection; otherwise,
deletes the characters following the insertion cursor to the next end of
line character\&.
In add mode, if there is a nonnull selection, the cursor is not disjoint
from the selection and \fBXmNpendingDelete\fP is set to True,
deletes the selection; otherwise,
deletes the characters following the insertion cursor to the next end
of line character\&.
This may impact the selection\&.
.IP "" 10
The delete-to-end-of-line() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, and the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP\&.
.IP "delete-to-start-of-line():" 10
In normal mode, if there is a nonnull selection, deletes the selection; otherwise,
deletes the characters preceding the insertion cursor to the previous
beginning-of-line character\&.
In add mode, if there is a nonnull selection, the cursor is not disjoint
from the selection and \fBXmNpendingDelete\fP is set to True,
deletes the selection; otherwise,
deletes the characters preceding the insertion cursor
to the previous beginning-of-line character\&.
This may impact the selection\&.
.IP "" 10
The delete-to-start-of-line() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "deselect-all():" 10
Deselects the current selection\&.
.IP "" 10
The deselect-all() action produces no callbacks\&.
.IP "end-of-line(\fBextend\fP):" 10
If this action is called with no argument,
moves the insertion cursor to the end of the line\&.
If called with an argument of \fIextend\fP, moves the insertion cursor as
in the case of no argument and extends the current selection\&.
.IP "" 10
The end-of-line() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If called with the \fIextend\fP argument, the
end-of-line() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "extend-adjust():" 10
Selects text from the anchor to the pointer position and deselects text
outside that range\&.
.IP "" 10
The extend-adjust() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
The extend-adjust() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "extend-end():" 10
Moves the insertion cursor to the position of the pointer\&.
The extend-end() action is used to commit the selection\&. After
this action has been done, process-cancel() will no longer
cancel the selection\&.
.IP "" 10
The extend-end() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
The extend-end() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "extend-start():" 10
Adjusts the anchor using the balance-beam method\&.
Selects text from the anchor to the pointer position and deselects text
outside that range\&.
.IP "" 10
The extend-start() action can produce no callbacks,
however, it may produce calls to the
\fBXmNgainPrimaryCallback\fP and \fBXmNmotionVerifyCallback\fP procedures\&.
See callback description for more information\&.
.IP "forward-character(\fBextend\fP):" 10
Moves the insertion cursor one character to the right\&.
This action may have different behavior in a right-to-left language
environment\&.
.IP "" 10
If called with an argument of \fIextend\fP, moves the insertion cursor as
in the case of no argument and extends the current selection\&.
.IP "" 10
The forward-character() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If called with the \fIextend\fP argument, the
forward-character() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "forward-word(\fBextend\fP):" 10
If this action is called with no argument, moves the insertion cursor to
the first whitespace character or end-of-line following the next
non-whitespace character\&.
If the insertion cursor is already at the end of a word,
moves the insertion cursor to the end of the next word\&.
This action may have different behavior in a locale other than the C locale\&.
.IP "" 10
If called with an argument of \fIextend\fP, moves the insertion cursor as
in the case of no argument and extends the current selection\&.
.IP "" 10
The forward-word() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
If called with the \fIextend\fP argument, the
forward-word() action may produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "grab-focus():" 10
This key binding performs the action defined in the
\fBXmNselectionArray\fP, depending on the number of multiple mouse
clicks\&.
The default selection array ordering is one click to move the
insertion cursor to the pointer position, two clicks to select a word,
and three
clicks to select a line of text\&.
A single click also deselects any selected text and sets the anchor at
the pointer position\&.
This action may have different behavior in a locale other than the C locale\&.
.IP "" 10
The grab-focus() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "Help():" 10
Calls the callbacks for \fBXmNhelpCallback\fP if any exist\&.
If there are no help
callbacks for this widget, this action calls the help callbacks
for the nearest ancestor that has them\&.
.IP "key-select(\fBright|left\fP):" 10
If called with an argument of \fIright\fP, moves the insertion cursor
one character to the right and extends the current selection\&.
If called with an argument of \fIleft\fP, moves the insertion cursor
one character to the left and extends the current selection\&.
If called with no argument, extends the current selection\&.
.IP "" 10
Note that after a \fBkey-select\fP action, the selection will still
begin at the original anchor, and will extend to the position
indicated in the action call\&. If this new position is on the opposite
side of the selection anchor from the previous selection boundary, the
original selection will be deselected\&.
.IP "" 10
The key-select() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
The key-select() action may also produce calls to the
\fBXmNgainPrimaryCallback\fP procedures\&.
See callback description for more information\&.
.IP "link-primary():" 10
Places a link to the primary selection just before the insertion cursor\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBPRIMARY\fP selection and the \fBXmLINK\fP operation\&.
The TextField widget itself performs no transfers; the
\fBXmNdestinationCallback\fP procedures are responsible for inserting
the link to the primary selection and for taking any related actions\&.
.IP "link-to():" 10
If a secondary selection exists, this action places a link to the
secondary selection at the insertion position of the destination
component\&.
This action calls the destination\&'s \fBXmNdestinationCallback\fP
procedures for the \fBSECONDARY\fP selection and the
\fBXmLINK\fP operation\&.
.IP "" 10
If no secondary selection exists, this action places a link to the
primary selection at the pointer position\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBPRIMARY\fP selection and the \fBXmLINK\fP operation\&.
.IP "" 10
The TextField widget itself performs no transfers; the
\fBXmNdestinationCallback\fP procedures are responsible for inserting
the link to the primary or secondary selection and for taking any
related actions\&.
.IP "move-destination():" 10
Moves the insertion cursor to the pointer position without changing any
existing current selection\&.
If there is
a
current selection, sets the widget as the destination widget\&.
This also moves the widget focus to match the insertion cursor\&.
.IP "" 10
The move-destination() action produces calls to the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "move-to():" 10
If a secondary selection exists, this action moves the secondary
selection to the insertion position of the destination component\&.
If the secondary selection is in the destination widget, and the
secondary selection and the primary selection overlap, the result
is undefined\&.
This action calls the destination\&'s \fBXmNdestinationCallback\fP
procedures for the \fBSECONDARY\fP selection and the
\fBXmCOPY\fP operation\&.
The destination\&'s \fBXmNdestinationCallback\fP procedures or the
destination component itself invokes the selection owner\&'s
\fBXmNconvertCallback\fP procedures, possibly multiple times, for the
\fBSECONDARY\fP selection\&.
If the transfer is successful, this action then calls the selection
owner\&'s \fBXmNconvertCallback\fP procedures for the \fBSECONDARY\fP
selection and the \fBDELETE\fP target\&.
.IP "" 10
If no secondary selection exists, this action moves the primary
selection to the pointer position\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBPRIMARY\fP selection and the \fBXmMOVE\fP operation\&.
It calls the selection owner\&'s \fBXmNconvertCallback\fP procedures,
possibly multiple times, for the \fBPRIMARY\fP selection\&.
If the transfer is successful, this action then calls the selection
owner\&'s \fBXmNconvertCallback\fP procedures for the \fBPRIMARY\fP
selection and the \fBDELETE\fP target\&.
.IP "" 10
In addition, the move-to() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&. This action may also produce calls
to the \fBXmNgainPrimaryCallback\fP procedures\&.
.IP "next-tab-group():" 10
Traverses to the next tab group\&.
.IP "" 10
The next-tab-group() action produces no callbacks, unless it
results in the widget losing focus, in which case, the
\fBXmNlosingFocusCallback\fP procedures are called with reason value
\fBXmCR_LOSING_FOCUS\fP\&.
.IP "page-left():" 10
Scrolls the viewing window left one page of text\&.
.IP "" 10
The page-left() action produces no callbacks\&.
.IP "page-right():" 10
Scrolls the viewing window right one page of text\&.
.IP "" 10
The page-right() action produces no callbacks\&.
.IP "paste-clipboard():" 10
Pastes the contents of the clipboard before the insertion cursor\&.
This action calls the \fBXmNdestinationCallback\fP procedures for the
\fBCLIPBOARD\fP selection and the \fBXmCOPY\fP operation\&.
.IP "" 10
The paste-clipboard() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "prev-tab-group():" 10
Traverses to the previous tab group\&.
.IP "" 10
The prev-tab-group() action produces no callbacks, unless it
results in the widget losing focus, in which case, the
\fBXmNlosingFocusCallback\fP procedures are called with reason value
\fBXmCR_LOSING_FOCUS\fP\&.
.IP "process-bdrag()" 10
If the pointer is within the selection, this action starts a drag
operation for the selection\&.
This action sets the \fBXmNconvertProc\fP of the DragContext to a
function that calls the \fBXmNconvertCallback\fP procedures, possibly
multiple times, for the \fB_MOTIF_DROP\fP selection\&.
.IP "" 10
If no selection exists or the pointer is outside the selection, this
action prepares to start a secondary selection at the pointer position\&.
.IP "process-cancel():" 10
Cancels the current extend-adjust(), secondary-adjust()
or process-bdrag()
operation and leaves the selection state as it was before the operation;
otherwise, and
if
the parent is a manager, it passes the event to the parent\&.
.IP "secondary-adjust():" 10
Extends the secondary selection to the pointer position\&.
.IP "" 10
The secondary-adjust() action produces no callbacks\&.
.IP "secondary-start():" 10
Marks the beginning of a secondary selection\&.
.IP "" 10
The secondary-start() action produces no callbacks\&.
.IP "select-all():" 10
Selects all text\&.
.IP "" 10
The select-all() action can produce no callbacks,
however, it may produce calls to the
\fBXmNgainPrimaryCallback\fP and \fBXmNmotionVerifyCallback\fP procedures\&.
See callback description for more information\&.
.IP "self-insert():" 10
If \fBXmNpendingDelete\fP is True and the cursor is not disjoint from the
current selection, deletes the entire selection\&.
Inserts the character associated with the key pressed
before the insertion cursor\&.
.IP "" 10
The self-insert() action produces calls to the
\fBXmNmodifyVerifyCallback\fP procedures with reason value
\fBXmCR_MODIFYING_TEXT_VALUE\fP, the \fBXmNvalueChangedCallback\fP
procedures with reason value \fBXmCR_VALUE_CHANGED\fP, and the
\fBXmNmotionVerifyCallback\fP procedures with reason value
\fBXmCR_MOVING_INSERT_CURSOR\fP\&.
.IP "set-anchor():" 10
Resets the anchor point for extended selections\&.
Resets the destination of secondary selection actions\&.
.IP "" 10
The set-anchor() action produces no callbacks\&.
.IP "toggle-add-mode():" 10
Toggles the state of Add Mode\&.
.IP "" 10
The toggle-add-mode() action produces no callbacks\&.
.IP "toggle-overstrike():" 10
Toggles the state of the text insertion mode\&. By default,
characters typed into the TextField widget are inserted before
the position of the insertion cursor\&. In overstrike
mode, characters entered into the TextField widget replace
the characters that directly follow the insertion cursor\&.
In overstrike mode, when the end of a line is reached,
characters are appended to the end of the line\&.
.IP "" 10
The following traversal actions generate no callbacks unless they
result in the loss of focus by the widget in question, as when
\fBXmNnavigationType\fP is \fBXmNONE\fP\&. In this case,
they produce calls to the \fBXmNlosingFocusCallback\fP procedures,
with reason value \fBXmCR_FOCUS_MOVED\fP\&.
.IP "traverse-home():" 10
Traverses to the first widget in the tab group\&.
.IP "traverse-next():" 10
Traverses to the next widget in the tab group\&.
.IP "traverse-prev():" 10
Traverses to the previous widget in the tab group\&.
.SS "Additional Behavior"
.PP
This widget has the following additional behavior:
.IP "\fB<FocusIn>\fP:" 10
Draws the insertion cursor as solid and starts blinking the cursor\&.
.IP "\fB<FocusOut>\fP:" 10
Displays the insertion cursor as a stippled I-beam unless it is the destination
widget\&.
.SS "Virtual Bindings"
.PP
The bindings for virtual keys are vendor specific\&.
For information about bindings for virtual buttons and keys,
see \fBVirtualBindings\fP(3)\&.
.SH "RELATED"
.PP
\fBCore\fP(3),
\fBXmCreateTextField\fP(3),
\fBXmFontList\fP(3),
\fBXmFontListAppendEntry\fP(3),
\fBXmPrimitive\fP(3),
\fBXmTextFieldClearSelection\fP(3),
\fBXmTextFieldCopy\fP(3),
\fBXmTextFieldCopyLink\fP(3),
\fBXmTextFieldCut\fP(3),
\fBXmTextFieldGetBaseline\fP(3),
\fBXmTextFieldGetEditable\fP(3),
\fBXmTextFieldGetInsertionPosition\fP(3),
\fBXmTextFieldGetLastPosition\fP(3),
\fBXmTextFieldGetMaxLength\fP(3),
\fBXmTextFieldGetSelection\fP(3),
\fBXmTextFieldGetSelectionPosition\fP(3),
\fBXmTextFieldGetSelectionWcs\fP(3),
\fBXmTextFieldGetString\fP(3),
\fBXmTextFieldGetStringWcs\fP(3),
\fBXmTextFieldGetSubstring\fP(3),
\fBXmTextFieldGetSubstringWcs\fP(3),
\fBXmTextFieldInsert\fP(3),
\fBXmTextFieldInsertWcs\fP(3),
\fBXmTextFieldPaste\fP(3),
\fBXmTextFieldPasteLink\fP(3),
\fBXmTextFieldPosToXY\fP(3),
\fBXmTextFieldRemove\fP(3),
\fBXmTextFieldReplace\fP(3),
\fBXmTextFieldReplaceWcs\fP(3),
\fBXmTextFieldSetAddMode\fP(3),
\fBXmTextFieldSetEditable\fP(3),
\fBXmTextFieldSetHighlight\fP(3),
\fBXmTextFieldSetInsertionPosition\fP(3),
\fBXmTextFieldSetMaxLength\fP(3),
\fBXmTextFieldSetSelection\fP(3),
\fBXmTextFieldSetString\fP(3),
\fBXmTextFieldSetStringWcs\fP(3),
\fBXmTextFieldShowPosition\fP(3), and
\fBXmTextFieldXYToPos\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
