'\" t
...\" TxtFieAM.sgm /main/8 1996/09/08 21:13:40 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTextFieldGetSelectionWcs" "library call"
.SH "NAME"
\fBXmTextFieldGetSelectionWcs\fP \(em A TextField function that retrieves the
value of a wide character encoded primary selection
.iX "XmTextFieldGetSelection\\%Wcs"
.iX "TextField functions" "XmTextFieldGetSelection\\%Wcs"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/TextF\&.h>
\fBwchar_t * \fBXmTextFieldGetSelectionWcs\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmTextFieldGetSelectionWcs\fP retrieves the value of the primary
selection, encoded in a wide character format\&. It returns a
NULL pointer if no text is selected in the widget\&. The application
is responsible for freeing the storage associated with the wide
character buffer by calling \fBXtFree\fP\&.
.IP "\fIwidget\fP" 10
Specifies the TextField widget ID
.PP
For a complete definition of TextField and its associated resources, see
\fBXmTextField\fP(3)\&.
.SH "RETURN"
.PP
Returns the wide character string that is associated with the primary
selection in the TextField widget\&.
.SH "RELATED"
.PP
\fBXmTextField\fP(3) and
\fBXmTextFieldGetSelection\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
