'\" t
...\" TrackL.sgm /main/8 1996/09/08 21:11:14 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmTrackingLocate" "library call"
.SH "NAME"
\fBXmTrackingLocate\fP \(em A Toolkit function that provides a modal interaction
.iX "XmTrackingLocate"
.iX "Toolkit functions" "XmTrackingLocate"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Xm\&.h>
\fBWidget \fBXmTrackingLocate\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBCursor \fBcursor\fR\fR,
\fBBoolean \fBconfine_to\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmTrackingLocate\fP provides a modal interface for selection of a
component\&.
It is intended to support context help\&.
This function is implemented as \fBXmTrackingEvent\fP\&.
.PP
\fBNOTE:\fP This function is obsolete and exists for compatibility with
previous releases\&. It has been replaced by \fBXmTrackingEvent\fP\&.
.IP "\fIwidget\fP" 10
Specifies the widget ID of a widget to use as the basis of the modal
interaction\&. That is, the widget within which the interaction must
occur, usually a top-level shell\&.
.IP "\fIcursor\fP" 10
Specifies the cursor to be used for the pointer during the interaction\&.
This is a standard X cursor name\&.
.IP "\fIconfine_to\fP" 10
Specifies whether or not the cursor should be confined to \fIwidget\fP
.SH "RETURN"
.PP
Returns the widget or gadget that contains the pointer when \fBBSelect\fP
is released or a key is released\&. If no widget or gadget contains the
pointer, the function returns NULL\&.
.SH "RELATED"
.PP
\fBXmTrackingEvent\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
