/* XPM */
static char * 96_2_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"96 96 12 1 0 0",
/* colors */
" 	s iconGray5	m black	c #737373737373",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray3	m white	c #adadadadadad",
"o	s iconColor1	m black	c black",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray4	m white	c #949494949494",
"$	s iconColor8	m black	c magenta",
"%	s iconColor5	m black	c blue",
"&	s iconColor2	m white	c white",
"*	s iconGray7	m black	c #424242424242",
/* pixels */
"                                                                                                ",
" ...............................................................................................",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooOooooooOooooooooOO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooOoooooOOoooooooOOO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooOOoooOoOooOoooooOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoOOOoooOOOOoOOOoooOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooOOOooOOOOOOoooooOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooOoOoooOOoooooooOOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOooooOoooooooOoooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoOOoooooOoooooo+OOooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooooooooooooooooO+ooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooooooooooOOoOo++ooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooooOOOoooOoOoOO++ooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooOOOoooOOOOOOOO+ooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.........XXX@@@@XXXXXXXXXXXXXXXXXXXXXXoooooOOOooOOOoooOOOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........X@@........XX.....X.XXX.XXXXO##ooooO#OOOooooOOOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX......o......XX@@@@XXXXXXXXXXXXXXXXXXXXXOOooOooOoooooooooOooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX......o$o......XXXXXXXXXXXXXXXXXXXXXXXXXXOooOOOoOOoooooOOoOOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXX......o$%$o......XXXXXXXXXXXXXXXXXXXXXXXXXOooOOOoooooOOOoOOOOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX......o$%$%$o......XXXXXXXXXXXXXXXXXXXXXXXXOOooOOoooooOooooOOOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXX......o$%$%$o........XXX@@@@XXXXXXXXXXXXXXXXoOOoOOooooOOooooOOOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXX......o$%$%$o..........X@@............XX....X####OOooooOOO#oooOoOO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXX......o$@&%$o............XXX@@@XXXXXXXXXXXXXXXooOOOOoOOooOOOOoooooO .",
" .XXXXXXXXXXXXXXXXXXXXXXXX......o$%&%$o....... ......XXXXXXXXXXXXXXXXXXXXoOOooooOOoooOoOoooooo .",
" .XXXXXXXXXXXXXXXXXXXXXXX......o$@&%$o....... &@......XXXXXXXXXXXXXXXXXXXOOooooooOoooooOoOOooo .",
" .XXXXXXXXXXXXXXXXXXXXXX......o$%&%$o....... &&&@......XXXXXXXXXXXXXXXXXXOOoooooOOOoooOOoOOooo .",
" .XXXXXXXXXXXXXXXXXXXXX......o$%$%$o....... &&&@........XXX@@@XXXXXXXXXXXooooOooooOooOOooOOooo .",
" .XXXXXXXXXXXXXXXXXXXX......o$%&%$o....... &&&@..........X@@........XX@@@@@@Oo###oO##OOooOOO#o .",
" .XXXXXXXXXXXXXXXXXXX......o$@&%$o....... &&&@..... ......XX@@@@XXXXXXXXXoooOOOOoooooOoooooOoo .",
" .XXXXXXXXXXXXXXXXXX......o$%&%$o....... &&&@..... &@......XXXXXXXXXXXXXXooooOOOoooOOOOOOooooo .",
" .XXXXXXXXXXXXXXXXX......o$@&%$o....... &&&@..... &&&@......XXXXXXXXXXXXXoOOoOOOOoOooOOOOooooo .",
" .XXXXXXXXXXXXXXXX......o$%&%$o....... &o&@..... &&&@........XXXXXXXXXXXXooOoooOOoOOOooOOooooo .",
" .XXXXXXXXXXXXXXX......o$%$%$o....... &o&@..... &&&@..........XXX@@@XXXXXooOOooooooOoooOOoooOO .",
" .XXXXXXXXXXXXXX......o$%&%$o....... &o&@..... &o&@..... ......X@@......XOo@@XXooo##oooOo#oOOO .",
" .XXXXXXXXXXXXX......o$@&%$o....... &&&@..... &o&@..... &@......XX@@@XXXXoOOooooOOoOoooOoooooo .",
" .XXXXXXXXXXXX......o$%&%$o....... &o&@..... &o&@..... &&&@......XXXXXXXXooOooOOoooooOoooooooo .",
" .XXXXXXXXXXX......o$%$%$o....... &o&@..... &&&@..... &&&@........XXXXXXXoOOoooOoOoooOOooooooo .",
" .XXXXXXXXXX......o$%$%$o....... &o&@..... &o&@..... &&&@..........XXXXXXoOOooooOOooooOoooOooo .",
" .XXXXXXXXX......ooo$%$o....... &o&@..... &o&@..... &&&@..... ......XXX@@oooooooOOoooOOooOOooo .",
" .XXXXXXXX......ooooo$o....... &o&@..... &o&@..... &&&@..... &@......X@@....Xooo###ooo###OOOo# .",
" .XXXXXXX......oo.&o  ....... &&&@..... &o&@..... &&&@..... &&&@......XX@@ooooooooOoooooooOOOo .",
" .XXXXXX......oo@&o  ....... &o&@..... &&&@..... &&&@..... &&&@........XXoooOooooooooooooOOooo .",
" .XXXXX......oo@.o  ....... &o&@..... &o&@..... &&&@..... &&&@..........XOOOOOooOooooooooOoooo .",
" .XXXX......oo.&o  ....... &o&@..... &o&@..... &&&@..... &&&@..... ......oOOOooooOoooOoooooooo .",
" .XXXX*......ooo  ....... &&&@..... &&&@..... &o&@..... &&&@..... &@......oooooooooooOOooooooo .",
" .XXXX *......o  ......... &@..... &o&@..... &o&@..... &o&@..... &&&@......o@.@@@XXooo###oo### .",
" .XXXX# *...... ........... ..... &o&@..... &o&@..... &o&@..... &&&@........ooooooOoooOooOOooo .",
" .XXXXX# *...................... &o&@..... &o&@..... &o&@..... &&&@..........oooooOooooooOoooo .",
" .XXXXXX# *.................... &o&@..... &o&@..... &o&@..... &&&@..... ......oooooooooooOoooo .",
" .XXXXXXX# *.................. &&&@..... &o&@..... &&&@..... &&&@..... &@......ooooOOooooOOooo .",
" .XXXXXXXX# *.................. &@..... &&&@..... &o&@..... &&&@..... &&&@......ooooOOOooOoooo .",
" .XXXXXXXXX# *.................. ..... &o&@..... &o&@..... &&&@..... &&&@........o..@@XXoO#### .",
" .XXXXXXXXXX# *...................... &o&@..... &o&@..... &o&@..... &&&@........*oooOOoooooOoo .",
" .XXXXXXXXXXX# *.................... &o&@..... &&&@..... &o&@..... &&&@........* ooooOOOoooOOo .",
" .XXXXXXXXXXXX# *.................. &&&@..... &o&@..... &o&@..... &&&@........* #oooooOOooooOo .",
" .XXXXXXXXXXXXX# *.................. &@..... &o&@..... &&&@..... &&&@........* #ooooooOoooooOO .",
" .XXXXXXXXXXXXXX# *.................. ..... &o&@..... &o&@..... &&&@........* #oooooooooOOOOoO .",
" .XXXXXXXXXXXXXXX# *...................... &o&@..... &o&@..... &&&@........* #X..@@XXoo###oo## .",
" .XXXXXXXXXXXXXXXX# *.................... &o&@..... &o&@..... &&&@........* #ooooooooooOoooooo .",
" .XXXXXXXXXXXXXXXXX# *.................. &&&@..... &o&@..... &&&@........* #ooooooooOOoooooooo .",
" .XXXXXXXXXXXXXXXXXX# *.................. &@..... &&&@..... &&&@........* #ooOooooooOooooooOoo .",
" .XXXXXXXXXXXXXXXXXXX# *.................. ..... &o&@..... &&&@........* #ooOOoooOooOooooooOoo .",
" .XXXXXXXXXXXXXXXXXXXX# *...................... &o&@..... &&&@........* #ooOOooooooOOooOOooOoo .",
" .XXXXXXXXXXXXXXXXXXXXX# *.................... &o&@..... &&&@........* #XX@@@@XXXoO###Ooo###Oo .",
" .XXXXXXXXXXXXXXXXXXXXXX# *.................. &&&@..... &&&@........* #XXooOOoOoooOOOoOooooooo .",
" .XXXXXXXXXXXXXXXXXXXXXXX# *.................. &@..... &o&@........* #XXXooOOOOoooooooOoOOoooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXX# *.................. ..... &o&@........* #XXXXoOOOOooooooooOooOOooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXX# *...................... &o&@........* #XXXXXoOoOoooooooOOoooOOooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXX# *.................... &o&@........* #XX@@@XoOoOOooooOOoooooOoooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXX# *.................. &&&@........* #X@......@@oO@@@XXoo##ooOo#oo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.................. &@........* #X@@@@@XXooOooOoooooooOOoOoooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.................. ........* #XXXXXXXXXoooOooOoooooooOooooOO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.........................* #XXXXXXXXXXoooooooooooooooOooOoO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.......................* #XXXXXXXXXXXooooooOOoooooooOooOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.....................* #XX@@@XXXXXXXooooOOOOoOOOOooOOoOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *...................* #X@........XX@@@@ooo###OooOo#oooOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.................* #XX@@@@XXXXXXXXooooooooOoooooooooooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *...............* #XXXXXXXXXXXXXXXoooooooooooooooOooooO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.............* #XXXXXXXXXXXXXXXXoooOOoOOOOooOOOoOoooO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *...........* #XXXXXXXXXXXXXXXXXooOOOOooooooOooooooOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.........* #X@@@XXXXXXXXXXXXXXooooooooooooooooooOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.......* #@.........XX...XX@@@oooo#ooooo#ooOooooOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.....* #X@@@@XXXXXXXXXXXXXXXoooooooooooooooOOOOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *...* #XXXXXXXXXXXXXXXXXXXXXOoooooooooooooOOOoooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# *.* #XXXXXXXXXXXXXXXXXXXXXXOOooooOOoooooooOooooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# * #XXXXXXXXXXXXXXXXXXXXXXXOOoooOOOOOoooooOOOooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX# #XXXXXXXXXXXXXXXXXXXXXXXXOOooooooOOOOoooo+Oooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#XXXXXXXXXXXXXXXXXXXXXXXXXoOOooooooooOoooo+OOoo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooOooooooooooooo+oOOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooooooooooooooo+ooOo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooooOOOoooooOOoo+oOO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooOOOoOOooooOOoooooO .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooOOOOoooooooOOOOoooo .",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooOooooooooOOOoOOoooo .",
" .                                                                                             .",
" ..............................................................................................."};