#!/bin/bash
#This is a simple script to clone, build, and install CDE on Debian Linux
#This is version 0.6u (9.8.2012)
#This script might build Docs, but will not install additional Locale Support
#To enable doc building, change the #Build section command.
#Tested on Ubuntu Precise 64bit

#Checking for and installing missing prerequisites

#git
prereq=$(dpkg -s git|grep installed)
 echo Checking for git: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing git..."
      sudo apt-get --yes install git
 fi

#build-essential
prereq=$(dpkg -s build-essential|grep installed)
 echo Checking for Build Tools: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing build-essential..."
      sudo apt-get --yes install build-essential
 fi

#xorg
prereq=$(dpkg -s xorg|grep installed)
 echo Checking for X: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing the X Windows System"
      sudo apt-get --yes install xorg
 fi

#ksh
prereq=$(dpkg -s ksh|grep installed)
 echo Checking for the Korn Shell: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing the Korn Shell"
      sudo apt-get --yes install ksh
 fi

#ncompress
prereq=$(dpkg -s ncompress|grep installed)
 echo Checking for compress: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing ncompress..."
      sudo apt-get --yes install ncompress
 fi

#tcl-dev
prereq=$(dpkg -s tcl-dev|grep installed)
 echo Checking for tcl: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing tcl..."
      sudo apt-get --yes install tcl-dev
 fi

#bison
prereq=$(dpkg -s bison|grep installed)
 echo Checking for bison: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing buffalumps..."
      sudo apt-get --yes install bison
 fi

#libxft-dev
prereq=$(dpkg -s libxft-dev|grep installed)
 echo Checking for libxft: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing libxft..."
      sudo apt-get --yes install libxft-dev
 fi

#libxmu-dev
prereq=$(dpkg -s libxmu-dev|grep installed)
 echo Checking for libxmu: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing libxmu..."
      sudo apt-get --yes install libxmu-dev
 fi

#libxp-dev
prereq=$(dpkg -s libxp-dev|grep installed)
 echo Checking for libxp: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing libxp..."
      sudo apt-get --yes install libxp-dev
 fi

#libfreetype6-dev
prereq=$(dpkg -s libfreetype6-dev|grep installed)
 echo Checking for libfreetype6: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing libfreetype..."
      sudo apt-get --yes install libfreetype6-dev
 fi

#libjpeg-dev
prereq=$(dpkg -s libjpeg62-dev|grep installed)
 echo Checking for libjpeg: $prereq
 if [ "" == "$prereq" ]; then
      echo "Installing libjpeg..."
      sudo apt-get --yes install libjpeg62-dev
 fi

#OpenMotif
prereq=$(dpkg -s libmotif-dev|grep installed)
 echo Checking for OpenMotif: $prereq
 if [ "" == "$prereq" ]; then#
      echo "Installing OpenMotif..."
      sudo apt-get --yes install libmotif-dev
 fi

echo "All prerequisites installed."

#Clone git master in to ./code/cde

git clone http://git.code.sf.net/p/cdesktopenv/code

#Link X11 headers
cd code/cde
mkdir -p imports/x11/include
cd imports/x11/include
ln -s /usr/include/X11 .
cd ../../..

#Build...Make World (or World.dev/World.doc)

make World.dev

#Install CDE to /usr/dt

sudo ./admin/IntegTools/dbTools/installCDE -s .

#Run post-install linux script (not sure why)

sudo ./admin/IntegTools/post_install/linux/configRun -e

#Install startCDE script.

#echo "export PATH=/usr/dt/bin:$PATH" > /tmp/startCDE.tmp
#echo "export LANG=C" >> /tmp/startCDE.tmp
#echo "startx /usr/dt/bin/Xsession" >> /tmp/startCDE.tmp

#sudo mv /tmp/startCDE.tmp /usr/local/bin/startCDE
#sudo chmod +x /usr/local/bin/startCDE

#clear
#echo "CDE built and installed, run startCDE to begin."

#fin
