'\" t
...\" Get_Loca.sgm /main/6 1996/09/08 20:14:03 rws $
...\" Get_Loca.sgm /main/6 1996/09/08 20:14:03 rws $-->
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "Get_Locale" "special file"
.SH "NAME"
\fBGet_Locale\fP \(em get a tool\&'s locale
.SH "SYNOPSIS"
.PP
.nf
Get_Locale(in string \fIcategory\fP,
        out string \fIlocale\fP
        [\&.\&.\&.]);
.fi
.SH "DESCRIPTION"
.PP
The
\fBGet_Locale\fP request
reports the
POSIX
locale of the indicated locale categories\&.
.PP
The
\fIcategory\fP argument
is the locale category to get\&.
A locale category is a
group of data types whose output formatting varies according to
locale in a similar way\&.
ISO C and X/Open locale categories are:
.PP
.nf
\f(CWLC_ALL
LC_COLLATE
LC_CTYPE
LC_MESSAGES
LC_MONETARY
LC_NUMERIC
LC_TIME\fR
.fi
.PP
.PP
The
\fIlocale\fP argument
is the name of the current locale of the indicated category\&.
The value of
\fIlocale\fP is implementation-defined\&.
.SH "ERRORS"
.PP
The ToolTalk service may return the following error
in processing the
\fBGet_Locale\fP request:
.IP "TT_DESKTOP_EINVAL" 10
The
\fIlocale\fP argument is not valid on the handler\&'s host\&.
.SH "APPLICATION USAGE"
.PP
The
\fBttdt_session_join\fP(3), function can be used to register for,
and transparently process, the
\fBGet_Locale\fP request\&.
.PP
Also,
\fBGet_Locale\fP can be sent by
\fBttdt_sender_imprint_on\fP(3), with the reply being handled transparently\&.
.SH "SEE ALSO"
.PP
\fBsetlocale\fP3C \fBttdt_sender_imprint_on\fP(3), \fBttdt_session_join\fP(3); \fBSet_Locale\fP request\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
