/* XPM */
static char * image_name[] = {
"113 88 8 1",
" 	c #57574C4C8F8F",
".	c #5C5C51519A9A",
"X	c #65655959A6A6",
"o	c #4E4E45458282",
"O	c #73736868AFAF",
"+	c #45453C3C7272",
"@	c #82827878B8B8",
"#	c #373730305A5A",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                   .                                                             ",
"                                                   X.                                                            ",
"                                                   XXo                                                           ",
"                                                   OO+o              .                                           ",
"                                                   O@++             .X                                           ",
"                                                   O@++             O. o                                         ",
"                                                   O@o#            OO o+                                         ",
"                                   X.              O@ #o          X@X #o                                         ",
"                                    @.             O@.#+         .@@.+#                                          ",
"                                    XX.            O@.##         O@Oo#+                                          ",
"                                     O..           @@.+#o       O@@X##o                                          ",
"                                     .O            @@Xo#o      .@@@+##                                           ",
"                                      O. .         @@. #+     .@@@X##+                                           ",
"                                      .O  .        @@  +#     O@@O+##o                                           ",
"                                       XX          @@  o#o   X@@@.###                                            ",
"                                        O   .      @@  o#+  .@@@Xo##+            X                               ",
"                                        XX         @@   ##  @@@O +##o         .XO.                               ",
"                                         O     .  X@@   +# O@@@. ###        .O@@.  o                             ",
"                                         .O    .. X@@ oo+# @@@. o##+      XO@@O  +#o                             ",
"                                          OX      .Xo#####oX@X  +##o   .X@@@@Oo+##o                              ",
"                          .               .O    o#o o###### o+o ###  XO@@@@@.####o                               ",
"                          X@OXX.           XX  +###oo+o     o+#o##+X@@@@@@X+###+o                                ",
"                            X@@@@OX.        O +####o           +#+O@@@@OX ####+                                  ",
"                            ++oXO@@@@@OX.   X ###+              ..@@@O. o####+                                   ",
"                             o+#o .XXO@@@@OOX ##+                O@X.  o####o                                    ",
"                               o++o    .XOO@. o+                  X   +####o                                     ",
"                                 o#+o      o#+o                   XX +####o                                      ",
"                                   o#+     ###o                    @+###+o                                       ",
"                                     +#o   ###                      +##+                                         ",
"                                      o+#o ##+                       #+                                          ",
"                                        o++##o                                                                   ",
"                                          o##        .XXXXXOOOOOO@@@@@@@@@@@@@@@@@@@@OOOOOXXX..                  ",
"                                            o.XXOO@@@@@@@@@@@@@@@@@@@@@OOOOXXXXXXXXXXXXXXXXXXXXX.                ",
"                                      XXXO@@@@@@@@@@@@@@OOOXXX  oo+########################++++oo                ",
"                                 .XO@@@@@@@@@@@OOXXX.   oo+##################+++++++++++++++++++++o              ",
"                             .XO@@@@@@@@OOXX.       o++###########++ooo                                          ",
"                           XO@@@@@@@OX.          o+#########++o                                                  ",
"                         X@@@@@@OX.            o#######++o                                                       ",
"                       .@@@@@OX              o######+o                                                           ",
"                       O@@@O.               o#####+                                                              ",
"                       @@@.                 +###+                                                                ",
"                       X@X                  o##o                                                                 ",
"                        .o                   oo                                                                  ",
"                         +#+o                 .OX.                                                               ",
"                          o###+oo              .O@@OX                                                            ",
"                            o+#####+oo           .X@@@@OXX.                                                      ",
"                               o+########+++ooo     .XO@@@@@OOXX...                                              ",
"                                   oo+###############++++o.XOOOOOOOOOXXXXX.                                      ",
"                                         oo+++##################++ooo                                            ",
"                                                   oooo+++++###########+++++oo                                   ",
"                                                                                                                 ",
"                                                                                                                 ",
"               XXX.                                                                                              ",
"            .O@@@@@@O                                                                                            ",
"           .@@.  o.OO.                                                                                           ",
"           @@.o+###+ +#o                                                                                         ",
"          X@@o##+   X+#o                                                                                         ",
"          X@@##+     o#+     .XXXX      ..   ..              X           ....         .    .     .XXX.           ",
"          X@O##       #+   X@OXXO@@O.   XO@@@OX            .@@        O@@@@O@@@O      O@@@@O.  .@OXX@@O.O@@      ",
"          X@Xo#       oo .@@.  o++ O@X    O@O  oo          X@@.o       .@@.oo O@O      .O@X  o.@O  o+XXoX@@      ",
"           @X o         .@@. +##++++ ..    .o###+          O@@o#        X ####+  o      X ####X@Xo##+oo#+o###    ",
"           XO  .X       O@Xo##+     X  o  X@ ##           .@OO #o       @O##o  X o#o    @O##+ O@.##    ## +##    ",
"            X   .OX    X@@ ##o      XX +o X@.##           XO X #+       @@##o  OOo#+    @@##o O@X#+    o#        ",
"              o   XX   O@@##+        @.o# X@.##           @X oX+#       @@##o  @@+##    @@##o X@Xoo     o        ",
"              o+    .  O@X##o        OO #+X@.##          .@ ++@ #o      @@##o X@O###    @@##o  OX .X             ",
"               o+o   + @@.##         O@ ##X@.##          OO #o@X++      @@+# O@O ##+    @@##o   .  .O            ",
"                o+o  ++@@ ##         O@.##X@.##          @OX+X@O+#      @@ooO@@ o##     @@##o    oo  X           ",
"                   . o#O@ ##         O@ ##X@.##         X@O. OO@ #o     @@##oOO #+o     @@##o     ++  oo         ",
"         .X        O.o# @ ##         @@o##X@.##         OO ##++X #+     @@###o  #o      @@##o      oo  #o        ",
"         XO        OOo#+@.+#        .@@+##X@.##        .@.o#### .o#     @@##o O o+      @@##o..      X #+        ",
"         X@ o      @@+##OX #o       O@O##+X@.##    XO  O@ #+   X@ #o    @@##o .X +o     @@##oXO      @X##        ",
"         .@X+     X@O+## O o+      X@O ##oO@.##    OX  @Oo#+    @X++    @@##o  X. +     @@##oX@ o   .@O##        ",
"          @O .. .O@@.##+    o.   .O@O +##.@@X++..XO@.o @X+#    .OOo#   X@@o#o   X  o   X@@o#o.@Xo  .O@.##        ",
"          .Xo O@@OX +##o   ++ O@@@O. o##XOOO.ooOOOOO. .OO++   .OOOoo  OOOOooo     o X.OOOOooo XX O@@O o##        ",
"            ###+o o+##o    o+##+   o+##o   o###+oooo+#o +#+      o###o   +##+o    +##+   +##+o o##o  o##o        ",
"            o+######+o       o+######o    +###########o####+    o#####+ +#####     +###o######o +#####+o         ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 ",
"                                                                                                                 "};
