'\" t
...\" dtenvvar.sgm /main/12 1996/09/30 11:29:12 cdedoc $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "dtenvvar" "file formats"
.SH "NAME"
\fBdtenvvar\fP \(em CDE environment variables
.SH "DESCRIPTION"
.PP
The CDE desktop sets up and uses a number of environment variables to
find certain files and do certain things\&. Components tied into CDE then
use these environment variables to locate specific types of files\&.
Environment variables used within the CDE desktop are:
.IP "\fICEPATH\fP" 10
Used by ToolTalk when in Classing Engine mode, where the Classing
Engine where to find the databases\&.
Refer to
\fBttsession\fP(1) and
\fBtt_type_comp\fP(1) for more information\&.
.IP "\fBCOLUMNS\fP" 10
Set by the terminal emulator\&.
Refer to
\fBdtterm\fP(1) for more information\&.
.IP "\fBDISPLAY\fP" 10
Is set to the associated display name\&.
Refer to
\fBdtlogin\fP(1) and
\fBttsession\fP(1) for more information\&.
.IP "\fBDTAPPSEARCHPATH\fP" 10
Used to search for Application Manager applications\&.
Refer
to
\fBdtappgather\fP(1) and
\fBdtsearchpath\fP(1) for more
information\&.
.IP "\fBDTDATABASESEARCHPATH\fP" 10
Used to collect filetype and action definitions, as expressed in
\fB*\&.dt\fP files\&.
Refer to
\fBdtsearchpath\fP(1), \fBdtaction\fP(1), \fBdtactionfile\fP(4), and
\fBdtdtsfile\fP(4) for
more information\&.
.IP "\fIDTHELPSEARCHPATH\fP" 10
System specified variable used to locate desktop help files\&.
Refer to
\fBdtsearchpath\fP(1) and
\fBdthelpgen\fP(1) for more information\&.
.IP "\fIDTHELPUSERSEARCHPATH\fP" 10
User specified variable used to locate desktop help files\&.
Refer to
\fBdtsearchpath\fP(1) and
\fBdthelpgen\fP(1) for more information\&.
.IP "\fBDTINFOLIBSEARCHPATH\fP" 10
Used by \fBdtinfo\fP to locate information libraries on
local and remote mounted systems\&. Refer to
\fBdtsearchpath\fP(1) and \fBdtinfogen\fP(1) for
more information\&.
.IP "\fBDTINFOLIBDEFAULT\fP" 10
Used by \fBdtinfo\fP to identify the default
information library(s) to load if the \fB-l\fP or
\fB-sect\fP option is not specified\&. Multiple information
libraries can be specified by a comma separated list\&. By default,
\fBDTINFOLIBDEFAULT\fP
is initialized to the CDE infolib cde\&.
.IP "\fIDTMOUNTPOINT\fP" 10
Used to set the name of the file system\&'s mount point, such as \&'/nfs\&'
or \&'/net\&'\&.
Refer to \fBdtspcd\fP(1m) and \fBdtsearchpath\fP(1) for more
information\&.
.IP "\fIDTPRINTCWD\fP" 10
If set to an existing, usable directory, this setting
causes
\fBdtlp\fP(1) to execute the
\fBlp\fP command pipeline from that
directory\&.
By default, this setting uses the current directory
from which
\fBdtlp\fP(1) is invoked\&.
Refer to
\fBdtlp\fP(1) for more information\&.
.IP "\fIDTPRINTFILEREMOVE\fP" 10
Remove the file after printing it\&.
This functionality is intended for temporary files generated by
components such as the Text Editor and Help system files that
don\&'t need to persist beyond the act of printing\&.
Value must be \fBTrue\fP
or \fBFalse\fP (case is ignored)\&.
Default is \fBFalse\fP\&.
Refer to
\fBdtlp\fP(1) for more information\&.
.IP "\fIDTPRINTSILENT\fP" 10
Print the file silently, without posting the PRINT dialog\&.
Value must be \fBTrue\fP
or \fBFalse\fP (case is ignored)\&.
Default is \fBFalse\fP\&.
Refer to
\fBdtlp\fP(1) for more information\&.
.IP "\fIDTPRINTUSERFILENAME\fP" 10
Use this value as the name of file as it should appear in the
PRINT dialog\&.
Default is print_file\&.
Refer to
\fBdtlp\fP(1) for more information\&.
.IP "\fIDTSCREENSAVERLIST\fP" 10
Used to set the default desktop screen saver
action list\&.
Used by
\fBdtstyle\fP(1) to determine the list
of available screen savers\&.
Refer to
\fBdtstyle\fP(1) for more information\&.
.IP "\fIDTSPSYSAPPHOSTS\fP" 10
Used by system administrators as an input to
\fBdtsearchpath\fP(1) to
create the
\fBDTAPPSEARCHPATH\fP environment variable\&.
It is the primary
environment variable and drives the remaining search paths for
filetypes and actions, for desktop icons, and for help files\&.
Refer
to
\fBdtappgather\fP(1) and
\fBdtsearchpath\fP(1) for more
information\&.
.IP "\fIDTSPSYSDATABASEHOSTS\fP" 10
Used by system administrators as an input to \fBdtsearchpath\fP to
create the
\fBDTDATABASESEARCHPATH\fP environment variable\&.
Refer to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fIDTSPSYSHELP\fP" 10
Used by system administrators as an input to \fBdtsearchpath\fP to
create the
\fIDTHELPSEARCHPATH\fP environment variable\&.
Refer to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fIDTSPSYSICON\fP" 10
Used by system administrators as an input to \fBdtsearchpath\fP to
create the
\fBXMICONSEARCHPATH\fP and
\fIXMICONBMSEARCHPATH\fP environment varables\&.
Refer to
\fBdtsearchpath\fP(1) for
more information\&.
.IP "\fIDTSPUSERAPPHOSTS\fP" 10
Used by end users as an input to
\fBdtsearchpath\fP to create the
\fBDTAPPSEARCHPATH\fP environment variable\&.
Refer to
\fBdtappgather\fP(1) and
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fIDTSPUSERDATABASEHOSTS\fP" 10
Used by end users as an input to \fBdtsearchpath\fP to
create the
\fBDTDATABASESEARCHPATH\fP environment variable\&.
Refer to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fIDTSPUSERHELP\fP" 10
Used by end users as an input to
\fBdtsearchpath\fP(1) to
create the
\fIDTHELPSEARCHPATH\fP environment variable\&.
Refer to
\fBdtsearchpath\fP for more information\&.
.IP "\fIDTSPUSERICON\fP" 10
Used by end users as an input to
\fBdtsearchpath\fP(1) to create the
\fBXMICONSEARCHPATH\fP and
\fIXMICONBMSEARCHPATH\fP environment variables\&.
Refer
to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fBDTSROCFPATH\fP" 10
Used by the \fBDtSearchInit\fP function to locate the
default API configuration \fBocf\fP file\&. If the
\fIocf_file\fP argument is NULL,
\fBDtSearchInit\fP looks for an \fBocf\fP
file with a base name of either \fBdtsearch\&.ocf\fP or
\fBaustext\&.ocf\fP in the directory specified by
\fBDTSROCFPATH\fP, in the current
working directory, or in the \fBHOME\fP directory, in that order\&.
.IP "\fBDTTAGOPT\fP" 10
Used by
\fBdthelptag\fP(1)\&. Refer
to
\fBdthelptag\fP(1) for more information\&.
.IP "\fBDTUSERSESSION\fP" 10
Used to control the location of the end user\&'s subdirectory where the
Application Manager will be rooted\&.
Also used by the Help system to
store data on a per user-session-display basis\&.
Refer to
\fBdtappgather\fP(1) or
\fBdthelpview\fP(1) for more information\&.
.IP "\fIEDITOR\fP" 10
Is set to
\fB/usr/dt/bin/dtpad\fP Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBHOME\fP" 10
Is set to the home directory of the user\&.
Refer to
\fBdtlogin\fP(1) and
\fBdtmail\fP(1) for more information\&.
.IP "\fIKBD_LANG\fP" 10
Is set to the value of
\fBLANG\fP for applicable languages\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBLANG\fP" 10
Is set to the current NLS language (if any)\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fILC_ALL\fP" 10
Is set to the current NLS language (if any)\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fILC_MESSAGES\fP" 10
Is set to the current NLS language (if any)\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBLINES\fP" 10
Set by the terminal emulator\&.
Refer to
\fBdtterm\fP(1) for more information\&.
.IP "\fBLOGNAME\fP" 10
Is set to the user name\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBLPDEST\fP" 10
Set the printer destination for the file\&.
Refer to
\fBdtlp\fP(1) for more information\&.
.IP "\fIMAIL\fP" 10
Is set to
\fB/usr/mail/$USER\fP (system dependent)\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBMAILRC\fP" 10
Used by
\fBdtmail\fP(1) as the mailer\&'s startup file\&.
Refer to
\fBdtmail\fP(1) for more information\&.
.IP "\fIMANPATH\fP" 10
The
\fBdtsearchpath\fP(1) utility appends \fB/usr/dt/man\fP to it\&.
Refer to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fBNLSPATH\fP" 10
Determine the location of message catalogues for the processing of
\fILC_MESSAGES\fP\&. Refer to
\fBdtterm\fP(1) for more information\&.
.IP "\fBPATH\fP" 10
Is set to the value of the
\fBuserPath\fP resource\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBSHELL\fP" 10
Is set to the user\&'s default shell (from
\fB/etc/passwd\fP)\&. Refer to
\fBdtlogin\fP(1) and
\fBdtterm\fP(1) for more information\&.
.IP "\fITERM\fP" 10
Is set to
\fBdtterm\fP the default CDE terminal emulator\&.
Refer to
\fBdtterm\fP(1) and
\fBdtlogin\fP(1) for more information\&.
.IP "\fITERMINAL_EMULATOR\fP" 10
Set by the terminal emulator\&.
Refer to
\fBdtterm\fP(1)) for more information\&.
.IP "\fITTPATH\fP" 10
Used by ToolTalk\&.
It tells ToolTalk where to find the ToolTalk
types database when in XDR mode\&.
Refer to
\fBttsession\fP(1) for more information\&.
.IP "\fITTSESSION_CMD\fP" 10
This specifies the shell command to be used by all ToolTalk clients
for auto-starting
\fBttsession\fP\&. Refer to \fBttsession\fP(1) for more information\&.
.IP "\fITT_ARG_TRACE_WIDTH\fP" 10
Used by ToolTalk\&.
It specifies the number of bytes of argument
and context values to write when in trace mode\&.
Refer to
\fBttsession\fP(1) for more information\&.
.IP "\fBTT_FILE\fP" 10
Set by
\fBttsession\fP when it invokes a tool to recieve a message\&.
Refer to
\fBttsession\fP(1) for more information\&.
.IP "\fBTT_SESSION\fP" 10
The
\fBttsession\fP utility uses this varible to communicate its session ID
to the tools that it starts\&.
Refer to
\fBttsession\fP(1) for more information\&.
.IP "TT_TOKEN" 10
Used to inform the ToolTalk client library that it has been invoked
by \fBttsession\fP\&.
Refer to
\fBttsession\fP(1) for more information\&.
.IP "\fITT_TRACE_SCRIPT\fP" 10
If set, tells libtt to turn on client-side tracing as specified in the
trace script
Refer to
\fBtttrace\fP(1) for more information\&.
.IP "\fBTZ\fP" 10
Is set to the value of the
\fBtimeZone\fP resource or system default\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBUSER\fP" 10
Is set to the user name\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fIWINDOWID\fP" 10
Set by the terminal emulator\&.
Refer to
\fBdtterm\fP(1) for more information\&.
.IP "\fBXAPPLRESDIR\fP" 10
Specifies the name of a directory that contains application
specific resources\&.
Refer to
\fBdtterm\fP(1) and
\fBdtwm\fP(1) for more information\&.
.IP "\fIXAUTHORITY\fP" 10
May be set to an authority file\&.
Refer to
\fBdtlogin\fP(1) for more information\&.
.IP "\fBXENVIRONMENT\fP" 10
Specifies the name of a resource file with user- or machine
specific resources\&.
Refer to
\fBdtterm\fP(1) and
\fBdtwm\fP(1) for more information\&.
.IP "\fBXFILESEARCHPATH\fP" 10
Defines a language-dependent location of app-defaults\&.
Refer to
\fBdtterm\fP(1) and
\fBdtwm\fP(1) for more information\&.
.IP "\fBXMICONSEARCHPATH\fP" 10
Used to locate desktop icons\&.
Refer to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fIXMICONBMSEARCHPATH\fP" 10
Used to locate bitmap (2 color) desktop icons\&.
Refer to
\fBdtsearchpath\fP(1) for more information\&.
.IP "\fIXMODIFIER\fP" 10
Specifies which input method to use\&.
Refer to
\fBdtterm\fP(1) for more information\&.
.SH "SEE ALSO"
.PP
\fBdtaction\fP(1), \fBdtactionfile\fP(4), \fBdtappgather\fP(1), \fBdtappintegrate\fP(1), \fBdtcm\fP(1), \fBdthelpgen\fP(1), \fBdthelptag\fP(1), \fBdthelpview\fP(1), \fBdtlogin\fP(1), \fBdtlp\fP(1), \fBdtsearchpath\fP(1), \fBdtspcd\fP(1m), \fBdtstyle\fP(1), \fBdtterm\fP(1), \fBdtdtsfile\fP(4), \fBdtwm\fP(1), \fBtt_type_comp\fP(1), \fBttsession\fP(1), \fBtttrace\fP(1)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
