'\" t
...\" DtStdApp.sgm /main/11 1996/09/08 19:59:56 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "DtStdAppFontNames" "file formats"
.SH "NAME"
\fBDtStdAppFontNames\fP \(em XCDE Standard Application Font Names
.SH "SYNOPSIS"
.PP
.nf
The XCDE Standard Application Font Names are a set of generic X Window
System font names, usable by applications as their default
fonts, for the most common categories of type designs and styles\&.
These names, for at least six sizes of 13 typefaces,
must be provided on all XCDE
systems, and they should be provided in any
X\ server product on which XCDE applications are expected to run\&.
They are typically mapped to existing fonts on the system
using the font alias mechanism, although this method is not required\&.
.fi
.SH "DESCRIPTION"
.PP
XCDE 1\&.0 does not come with a common set of fonts on all vendors\&'
systems, and both XCDE itself and XCDE applications must be able to run
on X\ servers and X terminals from non-XCDE vendors if those vendors so
desire\&.
Therefore, there are a standard set of ``generic\&'\&' font names
and sizes that each XCDE vendor makes available on their XCDE systems and
that X\ server vendors may make available on their X\ servers and
terminals\&.
The names map to existing fonts on each vendor\&'s system,
which may vary from vendor to vendor\&.
.PP
The XCDE Standard Application Font Names described here allow
applications to use a single set of default font specifications in their
\fIapp-defaults\fP files, without concern for the system
or X\ server
on which XCDE is running\&.
These
\fIapp-defaults\fP application defaults are given as XLFD font name patterns that will
match the standard XCDE font names on all XCDE systems\&.
This allows
application developers both to reduce their concern with selecting
their default fonts from a varying set of fonts on different XCDE
systems and to make use of the system default fonts\&.
.SS "Background"
.PP
Application fonts are the fonts used within an application, where a
wide variety of text designs, styles, weights and point sizes are useful\&.
These variations are used for emphasis, cross-references,
section headers, and so forth\&.
There are thousands of fonts available in the
market for use in applications, and different XCDE systems will have
different fonts\&.
The standard names attempt to provide the minimum
variety in generic designs, styles and sizes that an application might
want to use as defaults\&.
(The XCDE Standard Interface Font Names, described in
\fBDtStdInterfaceFontNames\fP(5), provide a similar mechanism for the elements of the XCDE desktop itself\&.)
.PP
Common application font names prevent applications
from needing different
\fIapp-defaults\fP files on each XCDE system\&.
The Standard Application Font Names
allow applications to use a single
\fIapp-defaults\fP file across all XCDE systems\&.
In addition, any X\ server or X
terminal vendor may ensure that XCDE applications can run on their
X\ server by mapping these standard application names to fonts of the
corresponding style on their individual X systems\&.
.SS "Rationale"
.PP
Two of the most common design variations in fonts used to display text
are the presence or absence of serifs and the choice between
proportional or regularly spaced (mono-spaced) characters\&.
Combining these two design variations yields four ``generic\&'\&' font
designs, or families:
.IP "   \(bu" 6
serif proportionally-spaced
.IP "   \(bu" 6
sans serif proportionally-spaced
.IP "   \(bu" 6
serif mono-spaced
.IP "   \(bu" 6
sans serif mono-spaced
.PP
Common examples of these four designs are:
.IP "   \(bu" 6
Times Roman
.IP "   \(bu" 6
Helvetica
.IP "   \(bu" 6
Courier
.IP "   \(bu" 6
Lucida Sans Typewriter
.PP
Each of these designs typically come, for text fonts,
in four styles (combinations of weight and slant):
.IP "   \(bu" 6
plain
.IP "   \(bu" 6
bold
.IP "   \(bu" 6
italic
.IP "   \(bu" 6
bold-italic
.PP
The four styles of each of the four design variations yield 16 generic
font variations\&.
These 16 generic fonts are among the most commonly
used in general desktop computing\&.
For example, taking the first three
real examples above (Times Roman, Helvetica, Courier), these 12 fonts,
along with the Symbol font, constitute the so-called ``Adobe 13\&'\&' that
is a de facto minimum set of fonts in the PostScript community in the
desktop computer marketplace\&.
.PP
In some cases, applications do not care about the exact font family or
name to be used, but do need to use a mono-spaced font, a sans serif
font or a serif font\&.
This XCDE mechanism allows such applications to
be freed from the need to be concerned about the exact font names that
may or may not be present on a particular XCDE system\&.
.SS "The Standard Names for the Latin-1 Character Set"
.PP
The 13 standard application font names are provided on all XCDE systems
only for the
ISO 8859
(Latin-1) character set\&.
These represent 12
generic design and style variations (serif and sans serif
proportionally-spaced, and a mono-spaced font that is either serif or
sans serif), as well as a symbol font\&.
These standard names are
provided in addition to the ``real\&'\&' names of the fonts that the
standard names are mapped to for a particular XCDE system\&.
An additional four standard font names, to allow both serif and sans serif
designs in a mono-spaced font, may also be provided by a XCDE system\&.
.SS "XLFD Field Values for the Standard Application Font Names"
.PP
The standard names are available using the X Window System XLFD font
naming scheme\&.
There are three aspects to the standard names:
.IP "   \(bu" 6
The
\fIunderlying font\fP on each system,
or X\ server platform,
to which a standard name is mapped,
typically will be different on each system\&.
.IP "   \(bu" 6
The
\fIstandard name\fP itself, a full XLFD name mapped to the underlying font,
may be different on each system in some of the XLFD fields\&.
However, most of the fields are the same from system to system,
allowing the
\fIpatterns\fP (described next) to be the same\&.
.IP "   \(bu" 6
The font resource
\fIpattern\fP containing the * wildcards, used in
\fIapp-defaults\fP files,
which will match the full XLFD name of the standard name,
is the same across all systems, for a given use in an
\fIapp-defaults\fP file\&.
.PP
Each XCDE or X\ server vendor implementing this specification
must provide full XLFD names for the standard names, mapped to
system-dependent underlying fonts,
so that the XLFD patterns used in XCDE application
\fIapp-defaults\fP files will always match one of the full XLFD names provided\&.
.PP
The Standard Application Font Names are identified by the presence of
the following XLFD field name values:
.IP "   \(bu" 6
\fBFOUNDRY\fP is
\fBdt\fP
.IP "   \(bu" 6
\fBFAMILY_NAME\fP is
\fBapplication\fP
.IP "   \(bu" 6
\fBWEIGHT_NAME\fP is
\fBmedium\fP or
\fBbold\fP
.IP "   \(bu" 6
\fBSLANT\fP is
\fBr\fP or
\fBi\fP
.IP "   \(bu" 6
\fBSETWIDTH\fP is
\fBnormal\fP
.IP "   \(bu" 6
\fBADD_STYLE\fP is
\fBsans\fP for sans serif,
\fBserif\fP for serif
.IP "   \(bu" 6
\fBSPACING\fP is
\fBp\fP or
\fBm\fP
.IP "   \(bu" 6
\fBCHARSET_REGISTRY\fP is
\fBiso8859\fP
.IP "   \(bu" 6
\fBCHARSET_ENCODING\fP is
\fB1\fP
.PP
Although
\fBsans\fP and
\fBserif\fP are not required by the XLFD font
convention, they are always part of the standard XCDE font names\&.
.SS "Point Sizes"
.PP
The complete set of point sizes available for each of the standard
application font names is determined by the set of fonts included in a
system, whether bitmapped only or both bitmapped and scalable outline\&.
The minimum set of sizes required and available on
all XCDE systems corresponds to the standard sizes of bitmapped fonts
that make up the default mapping for X11R5:
8, 10, 12, 14, 18 and 24\&.
.PP
For example, the entire set of six sizes of the plain monospaced font, on
any XCDE system, is represented by:
.PP
.nf
\f(CW-dt-application-medium-r-normal-*-*-80-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-100-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-120-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-140-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-180-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-240-*-*-m-*-iso8859-1\fR
.fi
.PP
.PP
These patterns will match the corresponding standard font name on any
XCDE system, even though the
\fBPIXEL_SIZE\fP and
\fBAVERAGE_WIDTH\fP numeric
fields may be different on various systems, and the matched fonts may
be either serif or sans serif, depending on the implementation
of the set of standard names\&.
The
\fBRESOLUTION\fP fields in the XLFD names of the underlying fonts, when
those fonts are bitmapped fonts, must match the resolution
of the monitor on which the fonts are displayed for the
point sizes to be accurate\&.
To provide expected point size
behavior for applications, systems should ensure that the
\fBRESOLUTION_X\fP and
\fBRESOLUTION_Y\fP fields of the underlying
fonts vary no more than 20% from the real monitor
resolution of the displays on which the fonts will be used\&.
.PP
Applications requesting point sizes different from the six in the minimum
set may obtain either ``scaled bitmapped\&'\&' fonts of the requested
design, or scaled outline versions of the requested design\&.
This behavior requires that the X server in question
support the scaling of fonts and that the standard names
are mapped to underlying fonts that can be scaled using
this support\&.
.SS "Example XLFD Patterns for the Standard Names"
.PP
Using the specified field values for these standard names,
subsets of the standard names can be represented with various XLFD patterns\&.
The XLFD pattern
.PP
.nf
\f(CW-dt-application-*\fR
.fi
.PP
.PP
logically matches the full set of XCDE Standard Application Font Names\&.
(Note that no specific X server behavior is implied)\&.
The pattern
.PP
.nf
\f(CW-dt-application-bold-*-*-*-*-*-*-*-p-*-*-*-\fR
.fi
.PP
.PP
matches the bold, proportionally-spaced XCDE fonts, both serif and sans
serif\&.
And the pattern
.PP
.nf
\f(CW-dt-application-*-*-*-*-*-*-*-*-m-*-*-*-\fR
.fi
.PP
.PP
matches the monospaced fonts (including both serif and sans serif)\&.
.PP
The full set of XCDE Standard Application Font Names can be represented
with the following patterns:
.PP
.nf
\f(CW-dt-application-bold-i-normal-serif-*-*-*-*-p-*-iso8859-1
-dt-application-bold-r-normal-serif-*-*-*-*-p-*-iso8859-1
-dt-application-medium-i-normal-serif-*-*-*-*-p-*-iso8859-1
-dt-application-medium-r-normal-serif-*-*-*-*-p-*-iso8859-1
-dt-application-bold-i-normal-sans-*-*-*-*-p-*-iso8859-1
-dt-application-bold-r-normal-sans-*-*-*-*-p-*-iso8859-1
-dt-application-medium-i-normal-sans-*-*-*-*-p-*-iso8859-1
-dt-application-medium-r-normal-sans-*-*-*-*-p-*-iso8859-1
-dt-application-bold-i-normal-*-*-*-*-*-m-*-iso8859-1
-dt-application-bold-r-normal-*-*-*-*-*-m-*-iso8859-1
-dt-application-medium-i-normal-*-*-*-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-*-*-*-m-*-iso8859-1
-dt-application-medium-r-normal-*-*-*-*-*-p-*-dtsymbol-1\fR
.fi
.PP
.PP
Each of these 13 standard names comes in at least six point sizes\&.
.SS "Implementation of Font Names"
.PP
Each XCDE system vendor and X\ server vendor
provides mappings of
their own fonts to XLFD names meeting this standard, so that XCDE
applications will work on their system\&.
The actual XLFD names will
vary from system to system, just as the fonts they are mapped to,
since they contain some of the same values as the XLFD name of the
underlying font\&.
What does not vary is the behavior:
the common
patterns in which only specified fields are used will match each
system\&'s standard names\&.
This is guaranteed by the field specifications given earlier\&.
.PP
The following requirements are placed on
each XCDE or X\ server vendor\&'s
implementation of the Standard Application Font Names:
.IP "   \(bu" 6
The names must be fully specified XLFD names, without wild cards\&.
.IP "   \(bu" 6
The
\fBWEIGHT_NAME\fP, \fBSLANT\fP, \fBSETWIDTH_NAME\fP, \fBSPACING\fP, \fBCHARSET_REGISTRY\fP and
\fBCHARSET_ENCODING\fP fields must contain valid values as defined previously
and must match those in the underlying font\&.
.IP "   \(bu" 6
The
\fBADD_STYLE_NAME\fP field must contain either the
\fBserif\fP or
\fBsans\fP designation, whichever matches the underlying font\&.
.SS "Default XCDE Mappings for Latin-1 Locales"
.PP
The default mapping of these standard application font names for the
ISO 8859
locales is to the following standard X11R5 bitmapped fonts
(the six minimum sizes are not shown explicitly in these patterns):
.PP
.nf
\f(CW-adobe-times-bold-i-normal--*-*-*-*-p-*-iso8859-1
-adobe-times-bold-r-normal--*-*-*-*-p-*-iso8859-1
-adobe-times-medium-i-normal--*-*-*-*-p-*-iso8859-1
-adobe-times-medium-r-normal--*-*-*-*-p-*-iso8859-1
-adobe-helvetica-bold-o-normal--*-*-*-*-p-*-iso8859-1
-adobe-helvetica-bold-r-normal--*-*-*-*-p-*-iso8859-1
-adobe-helvetica-medium-o-normal--*-*-*-*-p-*-iso8859-1
-adobe-helvetica-medium-r-normal--*-*-*-*-p-*-iso8859-1
-adobe-courier-bold-o-normal--*-*-*-*-m-*-iso8859-1
-adobe-courier-bold-r-normal--*-*-*-*-m-*-iso8859-1
-adobe-courier-medium-o-normal--*-*-*-*-m-*-iso8859-1
-adobe-courier-medium-r-normal--*-*-*-*-m-*-iso8859-1
-adobe-symbol-medium-r-normal--*-*-*-*-p-*-adobe-fontspecific\fR
.fi
.PP
.PP
A system may provide a different
mapping of these standard names as long as all 13 names map to fonts of
the appropriate design and style and the required six point sizes are
available\&.
The system documentation must document the
system-specific default mapping for the standard names\&.
.SS "Font Names in app-defaults Files"
.PP
An application can use a single
\fIapp-defaults\fP file to specify font resources and use it across all XCDE systems\&.
Since most of the fields (
\fBFOUNDRY\fP, \fBFAMILY_NAME\fP, \fBWEIGHT_NAME\fP, \fBSLANT\fP, \fBSETWIDTH_NAME\fP, \fBADD_STYLE_NAME\fP, \fBPOINT_SIZE\fP, \fBSPACING\fP, \fBCHARSET_REGISTRY\fP and
\fBCHARSET_ENCODING\fP) of the standard names are the same across different systems,
these values can be used in the resource specification in the
\fIapp-defaults\fP file\&.
However, other fields (
\fBPIXEL_SIZE\fP, \fBRESOLUTION_X\fP, \fBRESOLUTION_Y\fP and
\fBAVERAGE_WIDTH\fP) may vary across
systems, and so must be wild-carded in the resource specification\&.
For example:
.PP
.nf
\f(CWappOne*headFont: -dt-application-bold-r-normal-sans-*-140-*-*-p-*-iso8859-1
appOne*linkFont: -dt-application-bold-i-normal-sans-*-100-*-*-p-*-iso8859-1\fR
.fi
.PP
.PP
might be used to specify some of AppOne\&'s default font resource needs\&.
.SS "Other Character Sets in the Common Locales"
.PP
The standard application font names defined above can be used for locales other than the
ISO 8859 character set with the following exceptions and differences\&. For the
following locales, CDE guarantees that systems provide fonts with the following
XLFD attribute values, and that they be accessible using these names\&.
For full information on how vendors ship the fonts, and make such names
usable with the appropriate font base name lists required for correct CDE
support for internationalization, see the guidelines in the CDE
Internationalization Programming Guide document\&.
.IP "   \(bu" 6
Locales using ISO 8859-2, -3, -4, -5 (Cyrillic), -6 (Arabic), -7 (Greek), -8 (Hebrew):
.IP "" 10
The same values for
\fBFOUNDRY\fP,
\fBFAMILY_NAME\fP,
\fBWEIGHT_NAME\fP,
\fBSLANT\fP,
\fBSET_WIDTH\fP,
\fBADD_STYLE\fP and
\fBSPACING\fP as are used in this definition for the ISO 8859 locale\&.
.IP "   \(bu" 6
Japanese locales:
.IP "" 10
Two values for the
\fBFAMILY_NAME\fP
attribute (\fBGothic\fP and \fBMincho\fP) and two values for the
\fBWEIGHT_NAME\fP
attribute (\fBmedium\fP and \fBbold\fP) as well as
\fBSLANT\fP (\fBr\fP),
\fBADD_STYLE\fP (\fB*\fP) and
\fBSPACING\fP (\fBm\fP)\&.
.IP "   \(bu" 6
Chinese (Taiwan) locales:
.IP "" 10
Two values for the
\fBFAMILY_NAME\fP
attribute (\fBSung\fP and \fBKai\fP) and two values for the
\fBWEIGHT_NAME\fP
attribute (\fBmedium\fP and \fBbold\fP) as well as
\fBSLANT\fP (\fBr\fP),
\fBADD_STYLE\fP (\fB*\fP) and
\fBSPACING\fP (\fBm\fP)\&.
.IP "   \(bu" 6
Chinese (PRC) locales:
.IP "" 10
Two values for the
\fBFAMILY_NAME\fP attribute (\fBSong\fP and
\fBKai\fP) and two values for the
\fBWEIGHT_NAME\fP attribute (\fBmedium\fP and
\fBbold\fP) as well as
\fBSLANT\fP (\fBr\fP),
\fBADD_STYLE\fP (\fB*\fP) and
\fBSPACING\fP (\fBm\fP)\&.
.IP "   \(bu" 6
Korean locales:
.IP "" 10
Two values for the
\fBFAMILY_NAME\fP
attribute (\fBTotum\fP and \fBPathang\fP) and two values for the
\fBWEIGHT_NAME\fP
attribute (\fBmedium\fP and \fBbold\fP) as well as
\fBSLANT\fP (\fBr\fP),
\fBADD_STYLE\fP (\fB*\fP) and
\fBSPACING\fP (\fBm\fP)\&. Note that these names
are unofficial, tentative romanizations of the
two common font families in use in Korea; \fBTotum\fP corresponds to fonts typically
shipped as Gothic, Kodig or Dotum and \fBPathang\fP corresponds to fonts typically
shipped as Myungjo or Myeongjo\&. The official roman names for these fonts
are under review and may be changed in the future by the Korean
government, and thus may change for CDE\&.
.PP
In addition, to facilitate \fIapp-defaults\fP files that work under a variety of locales,
CDE systems must provide an additional set of Standard Application Font Names where the
\fBFAMILY_NAME\fP is \fBapplication\fP\&.
These font names are identified by the
presence of the following XLFD field values:
.IP "   \(bu" 6
\fBFOUNDRY\fP is \fBdt\fP
.IP "   \(bu" 6
\fBFAMILY_NAME\fP is \fBapplication\fP
.IP "   \(bu" 6
\fBWEIGHT_NAME\fP is \fBmedium\fP or \fBbold\fP
.IP "   \(bu" 6
\fBSLANT\fP is as appropriate (see above)
.IP "   \(bu" 6
\fBSET_WIDTH\fP is \fBnormal\fP
.IP "   \(bu" 6
\fBADD_STYLE\fP is \fB*\fP
.IP "   \(bu" 6
\fBSPACING\fP is as appropriate (see above)
.IP "   \(bu" 6
\fBCHARSET_REGISTRY\fP is as appropriate
.IP "   \(bu" 6
\fBCHARSET_ENCODING\fP is as appropriate
.PP
This set of names is mapped to an underlying font representing one of the
\fBFAMILY_NAMES\fP as listed above\&.
.PP
For example, the XLFD names
.PP
.nf
\f(CW-dt-mincho-medium-r-normal--*-*-*-*-m-*-jisx0208\&.1983-0
-dt-application-medium-r-normal--*-*-*-*-m-*-jisx0208\&.1983-0\fR
.fi
.PP
.PP
may both be mapped to
.PP
.nf
\f(CW-ibm_aix-mincho-medium-r-normal--*-*-*-*-m-*-jisx0208\&.1983-0\fR
.fi
.PP
.PP
This scheme allows application writers to create a XmFontList in a resource file as follows,
without regard for a particular locale:
.PP
.nf
\f(CW*FontList:-dt-application-medium-r-normal-*-0-14-75-75-m-0-*-*:\fR
.fi
.PP
.PP
and be assured that the font will be reasonable\&. Notice that specifying
fonts this way not only disregards the selection of the Asian
\fBFAMILY_NAME\fP,
but also the Latin \fBserif\fP or \fBsans\fP \fBADD_STYLE\fP
field\&. The font selected
will be the default\&.
.SH "SEE ALSO"
.PP
\fBdtstyle\fP(1), \fBdtterm\fP(1), \fBDtStdInterfaceFontNames\fP(5)
.SH "NOTES"
.PP
There is no requirement on a XCDE system to implement these
standard names in a particular way\&.
Several mechanisms are possible:
duplicate font files with altered naming attributes, X11R5 font
aliases, or vendor-specific mechanisms\&.
The only requirement is that
an XLFD pattern, written with attributes taken from the set that define
the standard names, can be successfully used to open a font with the
Xlib function
\fBXLoadFont\fP; and, specifically, the Xlib function
\fBXListFonts\fP need NOT return the same XLFD names for the pattern on
different XCDE systems\&.
.PP
XCDE applications should, of course, be written to behave in a
reasonable manner if these standard font names are not available on a
particular X server\&.
This is typically done in an X application by
defaulting to the
\fBfixed\fP and
\fBvariable\fP fonts\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:41
