'\" t
...\" Traits.sgm /main/10 1996/09/08 21:23:02 rws $
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "Traits" "file formats"
.SH "NAME"
\fBTraits\fP \(em Lists the traits used by the Motif Toolkit\&.
.iX "Traits"
.SH "DESCRIPTION"
.PP
A trait is a characteristic of a widget\&. A widget holding
a particular trait is announcing a particular ability to
other widgets\&.
The following table summarizes the standard Motif traits\&.
.PP
.TS
tab() box;
c s
l| l.
\fBPurpose of Each Trait\fP
\fBTrait Name\fPT{
\fBA Widget Holding This Trait Can Do The Following:\fP
T}
__
\fBXmQTaccessTextual\fPDisplay one primary text parcel\&.
__
\fBXmQTactivatable\fPT{
Become a command button in a dialog box\&.
T}
__
\fBXmQTcareParentVisual\fPT{
Borrow its parent\&'s visual information\&.
T}
__
\fBXmQTcontainer\fPManage container item children\&.
__
\fBXmQTcontainerItem\fPT{
Become a child of a container widget\&.
T}
__
\fBXmQTdialogShellSavvy\fPBecome a child of a DialogShell\&.
__
\fBXmQTjoinSide\fPT{
Attach itself to one side of a suitable parent\&.
T}
__
\fBXmQTmenuSavvy\fPBecome a menu child\&.
__
\fBXmQTmenuSystem\fPManage a menu system\&.
__
\fBXmQTnavigator\fPT{
Act as a navigator to a scrollable widget\&.
T}
__
\fBXmQTscrollFrame\fPT{
Handle one or more navigator widgets\&.
T}
__
\fBXmQTspecifyRenderTable\fPT{
Supply the names of its default render tables\&.
T}
__
\fBXmQTtakesDefault\fPT{
Change its appearance to show that it is the default button\&.
T}
__
\fBXmQTtransfer\fPT{
Transfer data to other widgets and/or receive data from other
widgets
T}
__
.TE
.PP
Traits are not often used in Motif application programs\&.
However, traits are very important to widget writers\&.
For complete details on traits, see the
\fIMotif Widget Writer\&'s Guide\fP\&.
.PP
The following table lists the names of all widgets and gadgets
in the standard Motif widget set that hold a particular trait\&.
For example, the following table shows that the
\fBXmQTcontainerItem\fP trait is held by the
\fBXmIconGadget\fR\&.
As the table suggests, some traits are held by many of the
standard Motif widgets\&.
.PP
.TS
tab() box;
c s
l| l.
T{
\fBTrait Installation in
Standard Widget Set\fP
T}
\fBTrait Name\fPT{
\fBIs Installed on The Following Widgets:\fP
T}
__
\fBXmQTaccessTextual\fPT{
\fBXmLabel\fP and all its subclasses; \fBXmLabelGadget\fP
and all its subclasses; \fBXmText; XmTextField\fP
T}
__
\fBXmQTactivatable\fPT{
\fBXmArrowButton; XmArrowButtonGadget; XmDrawnButton; XmPushButton;
XmPushButtonGadget\fP
T}
__
\fBXmQTcareParentVisual\fPT{
All the subclasses of \fBXmGadget\fP (but not
\fBXmGadget\fP itself);
\fBXmPrimitive\fP and all its subclasses
T}
__
\fBXmQTcontainer\fP\fBXmContainer\fP
__
\fBXmQTcontainerItem\fP\fBXmIconGadget\fR
__
\fBXmQTdialogShellSavvy\fP\fBXmBulletinBoard\fP
__
\fBXmQTjoinSide\fPNo widgets install this trait
__
\fBXmQTmenuSavvy\fPT{
\fBXmLabel; XmDrawnButton; XmCascadeButton; XmPushButton;
XmToggleButton; XmLabelGadget; XmCascadeButtonGadget;
XmPushButtonGadget; XmToggleButtonGadget\fP
T}
__
\fBXmQTmenuSystem\fP\fBXmRowColumn\fP
__
\fBXmQTnavigator\fP\fBXmScrollBar; XmSpinBox\fP
__
\fBXmQTscrollFrame\fP\fBXmNotebook; XmScrolledWindow\fP
__
\fBXmQTspecifyRenderTable\fPT{
\fBXmBulletinBoard\fP and all its subclasses;
\fBXmMenuShell; XmVendorShell\fP
T}
__
\fBXmQTtakesDefault\fP\fBXmPushButton; XmPushButtonGadget\fP
__
\fBXmQTtransfer\fPT{
\fBXmContainer; XmLabel\fP and all its subclasses;
\fBXmLabelGadget\fP and all its subclasses;
\fBXmList; XmScale; XmText; XmTextField\fP
T}
__
.TE
.PP
The following table lists the traits installed on each widget\&.
For example, the following table indicates that the
\fBXmArrowButton\fP widget holds both the
\fBXmQTactivatable\fP
and \fBXmQTcareParentVisual\fP traits\&.
.TS
tab() box;
c s
l| l.
\fBTrait Use by
Widget\fP
\fBWidget Name\fP\fBInstalls These Traits\fP
__
\fB=\fP
__
\fBXmArrowButton\fPT{
\fBXmQTactivatable, XmQTcareParentVisual\fP
T}
__
\fBXmArrowButtonGadget\fPT{
\fBXmQTactivatable, XmQTcareParentVisual\fP
T}
__
\fBXmBulletinBoard\fPT{
\fBXmQTdialogShellSavvy, XmQTspecifyRenderTable\fP
T}
__
\fBXmCascadeButton\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual, XmQTmenuSavvy,
XmQTtransfer\fP
T}
__
\fBXmCascadeButtonGadget\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual, XmQTmenuSavvy,
XmQTtransfer
XmComboBox\fP
T}
__
\fBXmCommand\fP\fBXmQTspecifyRenderTable\fP
__
\fBXmContainer\fP\fBXmQTcontainer, XmQTtransfer\fP
__
\fBXmDialogShell\fPNone
__
\fBXmDisplay\fPNone
__
\fBXmDragContext\fPNone
__
\fBXmDragIcon\fPNone
__
\fBXmDrawingArea\fPNone
__
\fBXmDrawnButton\fPT{
\fBXmQTaccessTextual, XmQTactivatable, XmQTcareParentVisual,
XmQTmenuSavvy, XmQTtransfer\fP
T}
__
\fBXmDropTransfer\fPNone
__
\fBXmFileSelectionBox\fP\fBXmQTspecifyRenderTable\fP
__
\fBXmForm\fP\fBXmQTspecifyRenderTable\fP
__
\fBXmFrame\fPNone
__
\fBXmGadget\fPNone
__
\fBXmIconGadget\fRT{
\fBXmQTcareParentVisual, XmQTcontainerItem\fP
T}
__
\fBXmLabel\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual, XmQTmenuSavvy,
XmQTtransfer\fP
T}
__
\fBXmLabelGadget\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual, XmQTmenuSavvy,
XmQTtransfer\fP
T}
__
\fBXmList\fP\fBXmQTcareParentVisual, XmQTtransfer\fP
__
\fBXmMainWindow\fP
__
\fBXmManager\fP
__
\fBXmMenuShell\fP\fBXmQTspecifyRenderTable\fP
__
\fBXmMessageBox\fP\fBXmQTspecifyRenderTable\fP
__
\fBXmNotebook\fP\fBXmQTscrollFrame\fP
__
\fBXmPanedWindow\fP
__
\fBXmPrimitive\fP\fBXmQTcareParentVisual\fP
__
\fBXmPushButton\fPT{
\fBXmQTaccessTextual, XmQTactivatable, XmQTcareParentVisual,
XmQTmenuSavvy, XmQTtakesDefault, XmQTtransfer\fP
T}
__
\fBXmPushButtonGadget\fPT{
\fBXmQTaccessTextual, XmQTactivatable, XmQTcareParentVisual,
XmQTmenuSavvy, XmQTtakesDefault, XmQTtransfer\fP
T}
__
\fBXmRowColumn\fP\fBXmQTmenuSystem\fP
__
\fBXmScale\fP\fBXmQTtransfer\fP
__
\fBXmScreen\fP
__
\fBXmScrollbar\fP\fBXmQTcareParentVisual, XmQTnavigator\fP
__
\fBXmScrolledWindow\fP\fBXmQTscrollFrame\fP
__
\fBXmSelectionBox\fP\fBXmQTspecifyRenderTable\fP
__
\fBXmSeparator\fP\fBXmQTcareParentVisual\fP
__
\fBXmSeparatorGadget\fP\fBXmQTcareParentVisual\fP
__
\fBXmSpinBox\fP\fBXmQTnavigator\fP
__
\fBXmText\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual, XmQTtransfer\fP
T}
__
\fBXmTextField\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual,
XmQTtransfer\fP
T}
__
\fBXmToggleButton\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual,
XmQTtransfer\fP
T}
__
\fBXmToggleButtonGadget\fPT{
\fBXmQTaccessTextual, XmQTcareParentVisual, XmQTtransfer\fP
T}
__
\fBVendorShell\fP\fBXmQTspecifyRenderTable\fP
__
.TE
.PP
The following table summarizes how the standard Motif widgets
access traits\&. There are two general ways for a widget to
access the traits of another widget\&.
.PP
One way is for a widget to ask another widget if it holds
a particular trait\&.
For example, \fBXmBulletinBoard\fP asks each of its children widgets
if they hold the \fBXmQTtakesDefault\fP trait\&.
\fBXmBulletinBoard\fP calls none of the trait methods
of \fBXmQTtakesDefault\fP\&.
.PP
Another kind of access is when one widget calls another widget\&'s
trait method(s)\&.
For example, \fBXmBulletinBoard\fP calls the
\fBgetRenderTable\fP
trait method of the \fBXmQTspecifyRenderTable\fP
trait\&.
.TS
tab() box;
c s s
l| l| l.
\fBTrait Access By
Widget\fP
\fBWidget\fP\fBAccesses These Traits:\fP\fBCalls These Trait Methods:\fP
___
\fBXmArrowButton\fPNoneNone
___
\fBXmArrowButtonGadget\fPNoneNone
___
\fBXmBulletinBoard\fP\fBXmQTtakesDefault\fPNone
___
\fBXmBulletinBoard\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmCascadeButton\fP\fBXmQTmenuSystem\fPMany
___
\fBXmCascadeButton\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmCascadeButtonGadget\fP\fBXmQTmenuSystem\fPMany
___
\fBXmCascadeButtonGadget\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmComboBox\fP\fBXmQTaccessTextual\fP\fBgetValue, setValue\fP
___
\fBXmCommand\fPNoneNone
___
\fBXmContainer\fP\fBXmQTcontainerItem\fP\fBgetValues, setValues\fP
___
\fBXmContainer\fP\fBXmQTscrollFrame\fP\fBgetInfo\fP
___
\fBXmDialogShell\fP\fBXmQTdialogShellSavvy\fP\fBcallMapUnmapCB\fP
___
\fBXmDisplay\fPNoneNone
___
\fBXmDragContext\fPNoneNone
___
\fBXmDragIcon\fPNoneNone
___
\fBXmDrawingArea\fPNoneNone
___
\fBXmDrawnButton\fP\fBXmQTmenuSystem\fPMany
___
\fBXmDrawnButton\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmDropTransfer\fPNoneNone
___
\fBXmFileSelectionBox\fP\fBXmQTactivatable\fPNone
___
\fBXmForm\fPNoneNone
___
\fBXmFrame\fPNoneNone
___
\fBXmGadget\fPNoneNone
___
\fBXmIconGadget\fR\fBXmQTcontainer\fP\fBgetValues\fP
___
\fBXmIconGadget\fR\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmLabel\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmLabel\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmLabelGadget\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmLabelGadget\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmList\fP\fBXmQTnavigator\fP\fBgetValues\fP
___
\fBXmList\fP\fBXmQTscrollFrame\fP\fBgetInfo, init\fP
___
\fBXmList\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmMainWindow\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmManager\fPNoneNone
___
\fBXmMenuShell\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmMenuShell\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmMessageBox\fP\fBXmQTactivatable\fPNone
___
\fBXmNotebook\fP\fBXmQTscrollFrame\fP\fBinit, addNavigator, removeNavigator\fP
___
\fBXmNotebook\fP\fBXmQTnavigator\fP\fBgetValue\fP
___
\fBXmNotebook\fP\fBXmQTactivatable\fP\fBchangeCB\fP
___
\fBXmNotebook\fP\fBXmQTaccessTextual\fPNone
___
\fBXmPanedWindow\fPNoneNone
___
\fBXmPrimitive\fPNoneNone
___
\fBXmPushButton\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmPushButton\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmPushButtonGadget\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmPushButtonGadget\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmRowColumn\fP\fBXmQTmenuSavvy\fPT{
\fBgetAccelerator, getMnemonic, getActivateCBName\fP
T}
___
\fBXmRowColumn\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmScale\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmScreen\fPNoneNone
___
\fBXmScrollbar\fPNoneNone
___
\fBXmScrolledWindow\fP\fBXmQTnavigator\fP\fBgetValue\fP
___
\fBXmScrolledWindow\fP\fBXmQTscrollFrame\fP\fBinit, addNavigator\fP
___
\fBXmSelectionBox\fP\fBXmQTaccessTextual\fP\fBsetValue;\fP
___
\fBXmSelectionBox\fP\fBXmQTactivatable\fPNone
___
\fBXmSeparator\fPNoneNone
___
\fBXmSeparatorGadget\fPNoneNone
___
\fBXmSpinBox\fP\fBXmQTaccessTextual\fP\fBsetValue\fP
___
\fBXmText\fP\fBXmQTaccessTextual\fP\fBgetValue, setValue\fP
___
\fBXmText\fP\fBXmQTnavigator\fP\fBgetValue\fP
___
\fBXmText\fP\fBXmQTscrollFrame\fP\fBgetInfo, init\fP
___
\fBXmText\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmTextField\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmToggleButton\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmToggleButton\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBXmToggleButtonGadget\fP\fBXmQTmenuSystem\fP\fBvarious methods\fP
___
\fBXmToggleButtonGadget\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
\fBVendorShell\fP\fBXmQTspecifyRenderTable\fP\fBgetRenderTable\fP
___
.TE
.SH "RELATED"
.PP
The following reference pages are documented in the
\fIMotif Widget Writer\&'s Guide\fP:
\fBXmeTraitSet\fP(3),
\fBXmeTraitGet\fP(3),
\fBXmQTaccessTextual\fP(3),
\fBXmQTactivatable\fP(3),
\fBXmQTcareParentVisual\fP(3),
\fBXmQTcontainer\fP(3),
\fBXmQTcontainerItem\fP(3),
\fBXmQTdialogShellSavvy\fP(3),
\fBXmQTjoinSide\fP(3),
\fBXmQTmenuSavvy\fP(3),
\fBXmQTmenuSystem\fP(3),
\fBXmQTnavigator\fP(3),
\fBXmQTscrollFrame\fP(3),
\fBXmQTspecifyRenderTable\fP(3),
and
\fBXmQTtakesDefault\fP(3)\&.
...\" created by instant / docbook-to-man, Sun 02 Sep 2012, 09:42
